package contract

import (
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestParseContract_Simple(t *testing.T) {
	cf, err := ParseContract("testdata/simple/contract.go")
	if err != nil {
		t.Fatalf("ParseContract() error = %v", err)
	}

	if cf.Package != "simple" {
		t.Errorf("Package = %q, want %q", cf.Package, "simple")
	}

	if len(cf.Interfaces) != 1 {
		t.Fatalf("len(Interfaces) = %d, want 1", len(cf.Interfaces))
	}

	iface := cf.Interfaces[0]
	if iface.Name != "Service" {
		t.Errorf("Interface name = %q, want %q", iface.Name, "Service")
	}
	if len(iface.Methods) != 2 {
		t.Fatalf("len(Methods) = %d, want 2", len(iface.Methods))
	}

	// Get(ctx context.Context, id string) (string, error)
	get := iface.Methods[0]
	if get.Name != "Get" {
		t.Errorf("Method[0].Name = %q, want %q", get.Name, "Get")
	}
	if len(get.Params) != 2 {
		t.Errorf("Get params = %d, want 2", len(get.Params))
	}
	if len(get.Results) != 2 {
		t.Errorf("Get results = %d, want 2", len(get.Results))
	}
	if get.Results[0].TypeExpr != "string" {
		t.Errorf("Get result[0].TypeExpr = %q, want %q", get.Results[0].TypeExpr, "string")
	}
	if get.Results[1].TypeExpr != "error" {
		t.Errorf("Get result[1].TypeExpr = %q, want %q", get.Results[1].TypeExpr, "error")
	}
}

func TestParseContract_Complex(t *testing.T) {
	cf, err := ParseContract("testdata/complex/contract.go")
	if err != nil {
		t.Fatalf("ParseContract() error = %v", err)
	}

	if len(cf.Interfaces) != 1 {
		t.Fatalf("len(Interfaces) = %d, want 1", len(cf.Interfaces))
	}

	iface := cf.Interfaces[0]
	if iface.Name != "Store" {
		t.Errorf("Interface name = %q, want %q", iface.Name, "Store")
	}
	if len(iface.Methods) != 4 {
		t.Fatalf("len(Methods) = %d, want 4", len(iface.Methods))
	}

	// Query — variadic args
	query := iface.Methods[0]
	if query.Name != "Query" {
		t.Errorf("Method[0].Name = %q, want %q", query.Name, "Query")
	}
	lastParam := query.Params[len(query.Params)-1]
	if !lastParam.Variadic {
		t.Error("Query last param should be variadic")
	}
	if !strings.Contains(lastParam.TypeExpr, "...any") {
		t.Errorf("Query last param type = %q, want contains ...any", lastParam.TypeExpr)
	}

	// Query returns *sql.Rows
	if !strings.Contains(query.Results[0].TypeExpr, "*sql.Rows") {
		t.Errorf("Query result[0] = %q, want *sql.Rows", query.Results[0].TypeExpr)
	}

	// Subscribe — channel return
	subscribe := iface.Methods[2]
	if subscribe.Name != "Subscribe" {
		t.Errorf("Method[2].Name = %q, want %q", subscribe.Name, "Subscribe")
	}
	if !strings.Contains(subscribe.Results[0].TypeExpr, "<-chan") {
		t.Errorf("Subscribe result[0] = %q, want contains <-chan", subscribe.Results[0].TypeExpr)
	}

	// Transform — func type param
	transform := iface.Methods[3]
	if transform.Name != "Transform" {
		t.Errorf("Method[3].Name = %q, want %q", transform.Name, "Transform")
	}
	fnParam := transform.Params[1]
	if !strings.Contains(fnParam.TypeExpr, "func(") {
		t.Errorf("Transform param[1] = %q, want contains func(", fnParam.TypeExpr)
	}
}

func TestParseContract_Multi(t *testing.T) {
	cf, err := ParseContract("testdata/multi/contract.go")
	if err != nil {
		t.Fatalf("ParseContract() error = %v", err)
	}

	if len(cf.Interfaces) != 2 {
		t.Fatalf("len(Interfaces) = %d, want 2", len(cf.Interfaces))
	}

	if cf.Interfaces[0].Name != "Reader" {
		t.Errorf("Interfaces[0].Name = %q, want %q", cf.Interfaces[0].Name, "Reader")
	}
	if cf.Interfaces[1].Name != "Writer" {
		t.Errorf("Interfaces[1].Name = %q, want %q", cf.Interfaces[1].Name, "Writer")
	}
	if len(cf.Interfaces[0].Methods) != 2 {
		t.Errorf("Reader methods = %d, want 2", len(cf.Interfaces[0].Methods))
	}
	if len(cf.Interfaces[1].Methods) != 2 {
		t.Errorf("Writer methods = %d, want 2", len(cf.Interfaces[1].Methods))
	}
}

func TestParseContract_Empty(t *testing.T) {
	cf, err := ParseContract("testdata/empty/contract.go")
	if err != nil {
		t.Fatalf("ParseContract() error = %v", err)
	}

	if len(cf.Interfaces) != 1 {
		t.Fatalf("len(Interfaces) = %d, want 1", len(cf.Interfaces))
	}

	if cf.Interfaces[0].Name != "Marker" {
		t.Errorf("Interface name = %q, want %q", cf.Interfaces[0].Name, "Marker")
	}
	if len(cf.Interfaces[0].Methods) != 0 {
		t.Errorf("Methods = %d, want 0", len(cf.Interfaces[0].Methods))
	}
}

func TestGenerate_Simple(t *testing.T) {
	dir := copyTestdata(t, "testdata/simple")
	contractPath := filepath.Join(dir, "contract.go")

	if err := Generate(contractPath); err != nil {
		t.Fatalf("Generate() error = %v", err)
	}

	// Verify mock_gen.go exists and is valid Go.
	mockPath := filepath.Join(dir, "mock_gen.go")
	assertFileExists(t, mockPath)
	assertValidGo(t, mockPath)
	assertContains(t, mockPath, "Code generated by forge. DO NOT EDIT.")
	assertContains(t, mockPath, "MockService")
	assertContains(t, mockPath, "GetFunc")
	assertContains(t, mockPath, "SetFunc")
	assertContains(t, mockPath, "var _ Service = (*MockService)(nil)")

	// Verify middleware_gen.go exists and is valid Go.
	mwPath := filepath.Join(dir, "middleware_gen.go")
	assertFileExists(t, mwPath)
	assertValidGo(t, mwPath)
	assertContains(t, mwPath, "Code generated by forge. DO NOT EDIT.")
	assertContains(t, mwPath, "InstrumentedService")
	assertContains(t, mwPath, "NewInstrumentedService")
	assertContains(t, mwPath, `"log/slog"`)
	assertContains(t, mwPath, `"time"`)
	assertContains(t, mwPath, "var _ Service = (*InstrumentedService)(nil)")

	// Verify tracing_gen.go exists and is valid Go.
	tracePath := filepath.Join(dir, "tracing_gen.go")
	assertFileExists(t, tracePath)
	assertValidGo(t, tracePath)
	assertContains(t, tracePath, "Code generated by forge. DO NOT EDIT.")
	assertContains(t, tracePath, "TracedService")
	assertContains(t, tracePath, "NewTracedService")
	assertContains(t, tracePath, `"go.opentelemetry.io/otel/trace"`)
	assertContains(t, tracePath, `"go.opentelemetry.io/otel/codes"`)
	assertContains(t, tracePath, "span.RecordError")
	assertContains(t, tracePath, "span.SetStatus(codes.Error")
	assertContains(t, tracePath, "var _ Service = (*TracedService)(nil)")

	// Verify metrics_gen.go exists and is valid Go.
	metricsPath := filepath.Join(dir, "metrics_gen.go")
	assertFileExists(t, metricsPath)
	assertValidGo(t, metricsPath)
	assertContains(t, metricsPath, "Code generated by forge. DO NOT EDIT.")
	assertContains(t, metricsPath, "MetricService")
	assertContains(t, metricsPath, "NewMetricService")
	assertContains(t, metricsPath, `"go.opentelemetry.io/otel/metric"`)
	assertContains(t, metricsPath, `"go.opentelemetry.io/otel/attribute"`)
	assertContains(t, metricsPath, "callCount")
	assertContains(t, metricsPath, "errCount")
	assertContains(t, metricsPath, "duration")
	assertContains(t, metricsPath, "var _ Service = (*MetricService)(nil)")
}

func TestGenerate_Complex(t *testing.T) {
	dir := copyTestdata(t, "testdata/complex")
	contractPath := filepath.Join(dir, "contract.go")

	if err := Generate(contractPath); err != nil {
		t.Fatalf("Generate() error = %v", err)
	}

	mockPath := filepath.Join(dir, "mock_gen.go")
	assertFileExists(t, mockPath)
	assertValidGo(t, mockPath)
	assertContains(t, mockPath, "MockStore")
	assertContains(t, mockPath, "QueryFunc")
	assertContains(t, mockPath, "ExecFunc")
	assertContains(t, mockPath, "SubscribeFunc")
	assertContains(t, mockPath, "TransformFunc")
	assertContains(t, mockPath, "args...")
	assertContains(t, mockPath, `"database/sql"`)

	mwPath := filepath.Join(dir, "middleware_gen.go")
	assertFileExists(t, mwPath)
	assertValidGo(t, mwPath)
	assertContains(t, mwPath, "InstrumentedStore")

	tracePath := filepath.Join(dir, "tracing_gen.go")
	assertFileExists(t, tracePath)
	assertValidGo(t, tracePath)
	assertContains(t, tracePath, "TracedStore")
	assertContains(t, tracePath, "NewTracedStore")
	assertContains(t, tracePath, "args...")
	assertContains(t, tracePath, `"database/sql"`)

	metricsPath := filepath.Join(dir, "metrics_gen.go")
	assertFileExists(t, metricsPath)
	assertValidGo(t, metricsPath)
	assertContains(t, metricsPath, "MetricStore")
	assertContains(t, metricsPath, "NewMetricStore")
	assertContains(t, metricsPath, "args...")
	assertContains(t, metricsPath, `"database/sql"`)
}

func TestGenerate_Multi(t *testing.T) {
	dir := copyTestdata(t, "testdata/multi")
	contractPath := filepath.Join(dir, "contract.go")

	if err := Generate(contractPath); err != nil {
		t.Fatalf("Generate() error = %v", err)
	}

	mockPath := filepath.Join(dir, "mock_gen.go")
	assertFileExists(t, mockPath)
	assertValidGo(t, mockPath)
	assertContains(t, mockPath, "MockReader")
	assertContains(t, mockPath, "MockWriter")
	assertContains(t, mockPath, "var _ Reader = (*MockReader)(nil)")
	assertContains(t, mockPath, "var _ Writer = (*MockWriter)(nil)")

	mwPath := filepath.Join(dir, "middleware_gen.go")
	assertFileExists(t, mwPath)
	assertValidGo(t, mwPath)
	assertContains(t, mwPath, "InstrumentedReader")
	assertContains(t, mwPath, "InstrumentedWriter")
	assertContains(t, mwPath, "NewInstrumentedReader")
	assertContains(t, mwPath, "NewInstrumentedWriter")

	tracePath := filepath.Join(dir, "tracing_gen.go")
	assertFileExists(t, tracePath)
	assertValidGo(t, tracePath)
	assertContains(t, tracePath, "TracedReader")
	assertContains(t, tracePath, "TracedWriter")
	assertContains(t, tracePath, "NewTracedReader")
	assertContains(t, tracePath, "NewTracedWriter")
	assertContains(t, tracePath, "var _ Reader = (*TracedReader)(nil)")
	assertContains(t, tracePath, "var _ Writer = (*TracedWriter)(nil)")

	metricsPath := filepath.Join(dir, "metrics_gen.go")
	assertFileExists(t, metricsPath)
	assertValidGo(t, metricsPath)
	assertContains(t, metricsPath, "MetricReader")
	assertContains(t, metricsPath, "MetricWriter")
	assertContains(t, metricsPath, "NewMetricReader")
	assertContains(t, metricsPath, "NewMetricWriter")
	assertContains(t, metricsPath, "var _ Reader = (*MetricReader)(nil)")
	assertContains(t, metricsPath, "var _ Writer = (*MetricWriter)(nil)")
}

func TestGenerate_Empty(t *testing.T) {
	dir := copyTestdata(t, "testdata/empty")
	contractPath := filepath.Join(dir, "contract.go")

	if err := Generate(contractPath); err != nil {
		t.Fatalf("Generate() error = %v", err)
	}

	mockPath := filepath.Join(dir, "mock_gen.go")
	assertFileExists(t, mockPath)
	assertValidGo(t, mockPath)
	assertContains(t, mockPath, "MockMarker")
	assertContains(t, mockPath, "var _ Marker = (*MockMarker)(nil)")

	mwPath := filepath.Join(dir, "middleware_gen.go")
	assertFileExists(t, mwPath)
	assertValidGo(t, mwPath)
	assertContains(t, mwPath, "InstrumentedMarker")

	tracePath := filepath.Join(dir, "tracing_gen.go")
	assertFileExists(t, tracePath)
	assertValidGo(t, tracePath)
	assertContains(t, tracePath, "TracedMarker")
	assertContains(t, tracePath, "var _ Marker = (*TracedMarker)(nil)")

	metricsPath := filepath.Join(dir, "metrics_gen.go")
	assertFileExists(t, metricsPath)
	assertValidGo(t, metricsPath)
	assertContains(t, metricsPath, "MetricMarker")
	assertContains(t, metricsPath, "var _ Marker = (*MetricMarker)(nil)")
}

func TestParseContract_Embedded(t *testing.T) {
	cf, err := ParseContract("testdata/embedded/contract.go")
	if err != nil {
		t.Fatalf("ParseContract() error = %v", err)
	}

	if len(cf.Interfaces) != 3 {
		t.Fatalf("len(Interfaces) = %d, want 3", len(cf.Interfaces))
	}

	// CommandPublisher has 1 method
	if cf.Interfaces[0].Name != "CommandPublisher" {
		t.Errorf("Interfaces[0].Name = %q, want %q", cf.Interfaces[0].Name, "CommandPublisher")
	}
	if len(cf.Interfaces[0].Methods) != 1 {
		t.Errorf("CommandPublisher methods = %d, want 1", len(cf.Interfaces[0].Methods))
	}

	// EventPublisher has 1 method
	if cf.Interfaces[1].Name != "EventPublisher" {
		t.Errorf("Interfaces[1].Name = %q, want %q", cf.Interfaces[1].Name, "EventPublisher")
	}
	if len(cf.Interfaces[1].Methods) != 1 {
		t.Errorf("EventPublisher methods = %d, want 1", len(cf.Interfaces[1].Methods))
	}

	// Service should have 3 methods: Close + PublishCommand + PublishEvent
	svc := cf.Interfaces[2]
	if svc.Name != "Service" {
		t.Errorf("Interfaces[2].Name = %q, want %q", svc.Name, "Service")
	}
	if len(svc.Methods) != 3 {
		t.Fatalf("Service methods = %d, want 3; got: %v", len(svc.Methods), methodNames(svc.Methods))
	}

	// Verify all expected methods are present
	names := methodNames(svc.Methods)
	for _, want := range []string{"Close", "PublishCommand", "PublishEvent"} {
		found := false
		for _, n := range names {
			if n == want {
				found = true
				break
			}
		}
		if !found {
			t.Errorf("Service missing method %q, has: %v", want, names)
		}
	}
}

func TestGenerate_Embedded(t *testing.T) {
	dir := copyTestdata(t, "testdata/embedded")
	contractPath := filepath.Join(dir, "contract.go")

	if err := Generate(contractPath); err != nil {
		t.Fatalf("Generate() error = %v", err)
	}

	// Verify mock_gen.go has all methods for Service
	mockPath := filepath.Join(dir, "mock_gen.go")
	assertFileExists(t, mockPath)
	assertValidGo(t, mockPath)
	assertContains(t, mockPath, "MockService")
	assertContains(t, mockPath, "CloseFunc")
	assertContains(t, mockPath, "PublishCommandFunc")
	assertContains(t, mockPath, "PublishEventFunc")
	assertContains(t, mockPath, "var _ Service = (*MockService)(nil)")

	// Verify middleware_gen.go has all methods for Service
	mwPath := filepath.Join(dir, "middleware_gen.go")
	assertFileExists(t, mwPath)
	assertValidGo(t, mwPath)
	assertContains(t, mwPath, "InstrumentedService")
	assertContains(t, mwPath, "var _ Service = (*InstrumentedService)(nil)")

	// Verify tracing_gen.go has all methods and compiles
	tracePath := filepath.Join(dir, "tracing_gen.go")
	assertFileExists(t, tracePath)
	assertValidGo(t, tracePath)
	assertContains(t, tracePath, "TracedService")
	assertContains(t, tracePath, "var _ Service = (*TracedService)(nil)")
	// Close() has no context param, so it should use context.Background()
	assertContains(t, tracePath, "context.Background()")

	// Verify metrics_gen.go has all methods and compiles
	metricsPath := filepath.Join(dir, "metrics_gen.go")
	assertFileExists(t, metricsPath)
	assertValidGo(t, metricsPath)
	assertContains(t, metricsPath, "MetricService")
	assertContains(t, metricsPath, "var _ Service = (*MetricService)(nil)")
	// Close() has no context param, so it should use context.Background()
	assertContains(t, metricsPath, "context.Background()")
}

func methodNames(methods []MethodDef) []string {
	names := make([]string, len(methods))
	for i, m := range methods {
		names[i] = m.Name
	}
	return names
}

func TestMethodDef_HasContext(t *testing.T) {
	withCtx := MethodDef{
		Params: []ParamDef{{Name: "ctx", TypeExpr: "context.Context"}},
	}
	if !withCtx.HasContext() {
		t.Error("HasContext() = false, want true")
	}

	withoutCtx := MethodDef{
		Params: []ParamDef{{Name: "id", TypeExpr: "string"}},
	}
	if withoutCtx.HasContext() {
		t.Error("HasContext() = true, want false")
	}

	noParams := MethodDef{}
	if noParams.HasContext() {
		t.Error("HasContext() = true for no params, want false")
	}
}

func TestMethodDef_ParamSignature(t *testing.T) {
	m := MethodDef{
		Name: "Query",
		Params: []ParamDef{
			{Name: "ctx", TypeExpr: "context.Context"},
			{Name: "query", TypeExpr: "string"},
			{Name: "args", TypeExpr: "...any", Variadic: true},
		},
	}
	got := m.ParamSignature()
	want := "ctx context.Context, query string, args ...any"
	if got != want {
		t.Errorf("ParamSignature() = %q, want %q", got, want)
	}
}

func TestMethodDef_CallArgs_Variadic(t *testing.T) {
	m := MethodDef{
		Params: []ParamDef{
			{Name: "ctx", TypeExpr: "context.Context"},
			{Name: "args", TypeExpr: "...any", Variadic: true},
		},
	}
	got := m.CallArgs()
	want := "ctx, args..."
	if got != want {
		t.Errorf("CallArgs() = %q, want %q", got, want)
	}
}

func TestMethodDef_FuncFieldType(t *testing.T) {
	m := MethodDef{
		Name: "Get",
		Params: []ParamDef{
			{Name: "ctx", TypeExpr: "context.Context"},
			{Name: "id", TypeExpr: "string"},
		},
		Results: []ParamDef{
			{TypeExpr: "string"},
			{TypeExpr: "error"},
		},
	}
	got := m.FuncFieldType()
	want := "func(context.Context, string) (string, error)"
	if got != want {
		t.Errorf("FuncFieldType() = %q, want %q", got, want)
	}
}

func TestMethodDef_ResultSignature_Single(t *testing.T) {
	m := MethodDef{
		Results: []ParamDef{{TypeExpr: "error"}},
	}
	got := m.ResultSignature()
	if got != "error" {
		t.Errorf("ResultSignature() = %q, want %q", got, "error")
	}
}

func TestMethodDef_ResultSignature_Multiple(t *testing.T) {
	m := MethodDef{
		Results: []ParamDef{
			{TypeExpr: "string"},
			{TypeExpr: "error"},
		},
	}
	got := m.ResultSignature()
	if got != "(string, error)" {
		t.Errorf("ResultSignature() = %q, want %q", got, "(string, error)")
	}
}

func TestMethodDef_ResultSignature_None(t *testing.T) {
	m := MethodDef{}
	got := m.ResultSignature()
	if got != "" {
		t.Errorf("ResultSignature() = %q, want empty", got)
	}
}

// ── helpers ──────────────────────────────────────────────────────────────────

// copyTestdata copies a testdata directory into a temp directory so generated
// files don't pollute the source tree.
func copyTestdata(t *testing.T, src string) string {
	t.Helper()
	dir := t.TempDir()

	entries, err := os.ReadDir(src)
	if err != nil {
		t.Fatalf("ReadDir(%s) error = %v", src, err)
	}
	for _, e := range entries {
		data, err := os.ReadFile(filepath.Join(src, e.Name()))
		if err != nil {
			t.Fatalf("ReadFile error = %v", err)
		}
		if err := os.WriteFile(filepath.Join(dir, e.Name()), data, 0644); err != nil {
			t.Fatalf("WriteFile error = %v", err)
		}
	}
	return dir
}

func assertFileExists(t *testing.T, path string) {
	t.Helper()
	if _, err := os.Stat(path); os.IsNotExist(err) {
		t.Fatalf("expected file %s to exist", path)
	}
}

func assertValidGo(t *testing.T, path string) {
	t.Helper()
	fset := token.NewFileSet()
	_, err := parser.ParseFile(fset, path, nil, parser.AllErrors)
	if err != nil {
		data, _ := os.ReadFile(path)
		t.Fatalf("generated file %s is not valid Go:\n%v\n\nContent:\n%s", path, err, string(data))
	}
}

func assertContains(t *testing.T, path, substr string) {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile(%s) error = %v", path, err)
	}
	if !strings.Contains(string(data), substr) {
		t.Errorf("file %s does not contain %q\n\nContent:\n%s", path, substr, string(data))
	}
}