// Code generated by forge. DO NOT EDIT.
package database

import (
	"context"
	"database/sql"
	"log/slog"
	"time"
)

// InstrumentedSchemaIntrospector wraps SchemaIntrospector with logging and duration tracking.
type InstrumentedSchemaIntrospector struct {
	inner  SchemaIntrospector
	logger *slog.Logger
}

// NewInstrumentedSchemaIntrospector creates a new instrumented wrapper.
func NewInstrumentedSchemaIntrospector(inner SchemaIntrospector, logger *slog.Logger) SchemaIntrospector {
	return &InstrumentedSchemaIntrospector{inner: inner, logger: logger}
}

func (w *InstrumentedSchemaIntrospector) ConnectDB(ctx context.Context, dsn string) (*sql.DB, error) {
	start := time.Now()
	r0, r1 := w.inner.ConnectDB(ctx, dsn)
	w.logger.Info("ConnectDB", "duration", time.Since(start), "error", r1)
	return r0, r1
}

func (w *InstrumentedSchemaIntrospector) IntrospectSchema(ctx context.Context, db *sql.DB, tableFilter string) ([]Table, error) {
	start := time.Now()
	r0, r1 := w.inner.IntrospectSchema(ctx, db, tableFilter)
	w.logger.Info("IntrospectSchema", "duration", time.Since(start), "error", r1)
	return r0, r1
}

func (w *InstrumentedSchemaIntrospector) IntrospectTable(ctx context.Context, db *sql.DB, tableName string) (*Table, error) {
	start := time.Now()
	r0, r1 := w.inner.IntrospectTable(ctx, db, tableName)
	w.logger.Info("IntrospectTable", "duration", time.Since(start), "error", r1)
	return r0, r1
}

func (w *InstrumentedSchemaIntrospector) CompareSchemaToProtos(ctx context.Context, tables []Table, protoDir string) (CheckResult, error) {
	start := time.Now()
	r0, r1 := w.inner.CompareSchemaToProtos(ctx, tables, protoDir)
	w.logger.Info("CompareSchemaToProtos", "duration", time.Since(start), "error", r1)
	return r0, r1
}

func (w *InstrumentedSchemaIntrospector) ParseProtoEntities(ctx context.Context, dir string) ([]ProtoEntity, error) {
	start := time.Now()
	r0, r1 := w.inner.ParseProtoEntities(ctx, dir)
	w.logger.Info("ParseProtoEntities", "duration", time.Since(start), "error", r1)
	return r0, r1
}

// Compile-time check.
var _ SchemaIntrospector = (*InstrumentedSchemaIntrospector)(nil)

// InstrumentedMigrationService wraps MigrationService with logging and duration tracking.
type InstrumentedMigrationService struct {
	inner  MigrationService
	logger *slog.Logger
}

// NewInstrumentedMigrationService creates a new instrumented wrapper.
func NewInstrumentedMigrationService(inner MigrationService, logger *slog.Logger) MigrationService {
	return &InstrumentedMigrationService{inner: inner, logger: logger}
}

func (w *InstrumentedMigrationService) CreateMigration(ctx context.Context, name string, dir string, opts *MigrationOptions) error {
	start := time.Now()
	r0 := w.inner.CreateMigration(ctx, name, dir, opts)
	w.logger.Info("CreateMigration", "duration", time.Since(start), "error", r0)
	return r0
}

func (w *InstrumentedMigrationService) GatherMigrationContext(ctx context.Context, name string, migDir string, opts MigrationOptions) (*MigrationContext, error) {
	start := time.Now()
	r0, r1 := w.inner.GatherMigrationContext(ctx, name, migDir, opts)
	w.logger.Info("GatherMigrationContext", "duration", time.Since(start), "error", r1)
	return r0, r1
}

func (w *InstrumentedMigrationService) GetPreviousMigration(ctx context.Context, dir string) (*PreviousMigrationInfo, error) {
	start := time.Now()
	r0, r1 := w.inner.GetPreviousMigration(ctx, dir)
	w.logger.Info("GetPreviousMigration", "duration", time.Since(start), "error", r1)
	return r0, r1
}

func (w *InstrumentedMigrationService) GetMigrationHistory(ctx context.Context, dir string) ([]string, error) {
	start := time.Now()
	r0, r1 := w.inner.GetMigrationHistory(ctx, dir)
	w.logger.Info("GetMigrationHistory", "duration", time.Since(start), "error", r1)
	return r0, r1
}

// Compile-time check.
var _ MigrationService = (*InstrumentedMigrationService)(nil)

// InstrumentedProtoGenerator wraps ProtoGenerator with logging and duration tracking.
type InstrumentedProtoGenerator struct {
	inner  ProtoGenerator
	logger *slog.Logger
}

// NewInstrumentedProtoGenerator creates a new instrumented wrapper.
func NewInstrumentedProtoGenerator(inner ProtoGenerator, logger *slog.Logger) ProtoGenerator {
	return &InstrumentedProtoGenerator{inner: inner, logger: logger}
}

func (w *InstrumentedProtoGenerator) GenerateProtoFiles(ctx context.Context, tables []Table, outputDir string, goModule string) error {
	start := time.Now()
	r0 := w.inner.GenerateProtoFiles(ctx, tables, outputDir, goModule)
	w.logger.Info("GenerateProtoFiles", "duration", time.Since(start), "error", r0)
	return r0
}

// Compile-time check.
var _ ProtoGenerator = (*InstrumentedProtoGenerator)(nil)
