// Code generated by forge. DO NOT EDIT.
// Source: contract.go in this package.
//
// To customize: edit contract.go (the interface IS the public surface) and
// re-run "forge generate". This file is regenerated unconditionally.
package database

import (
	"context"
	"database/sql"
	"github.com/reliant-labs/forge/pkg/contractkit"
)

// MockSchemaIntrospector is a test mock for the SchemaIntrospector interface.
//
// The embedded contractkit.Recorder records every call so tests can
// assert call counts and captured arguments. Set XxxFunc fields to
// override per-method behaviour; unset methods return the canonical
// "MockSchemaIntrospector.<Method>Func not set" error.
type MockSchemaIntrospector struct {
	contractkit.Recorder
	ConnectDBFunc             func(context.Context, string) (*sql.DB, error)
	IntrospectSchemaFunc      func(context.Context, *sql.DB, string) ([]Table, error)
	IntrospectTableFunc       func(context.Context, *sql.DB, string) (*Table, error)
	CompareSchemaToProtosFunc func(context.Context, []Table, string) (CheckResult, error)
	ParseProtoEntitiesFunc    func(context.Context, string) ([]ProtoEntity, error)
}

func (m *MockSchemaIntrospector) ConnectDB(ctx context.Context, dsn string) (*sql.DB, error) {
	m.Record("ConnectDB", ctx, dsn)
	if m.ConnectDBFunc != nil {
		return m.ConnectDBFunc(ctx, dsn)
	}
	return nil, contractkit.MockNotSet("MockSchemaIntrospector", "ConnectDB")
}

func (m *MockSchemaIntrospector) IntrospectSchema(ctx context.Context, db *sql.DB, tableFilter string) ([]Table, error) {
	m.Record("IntrospectSchema", ctx, db, tableFilter)
	if m.IntrospectSchemaFunc != nil {
		return m.IntrospectSchemaFunc(ctx, db, tableFilter)
	}
	return nil, contractkit.MockNotSet("MockSchemaIntrospector", "IntrospectSchema")
}

func (m *MockSchemaIntrospector) IntrospectTable(ctx context.Context, db *sql.DB, tableName string) (*Table, error) {
	m.Record("IntrospectTable", ctx, db, tableName)
	if m.IntrospectTableFunc != nil {
		return m.IntrospectTableFunc(ctx, db, tableName)
	}
	return nil, contractkit.MockNotSet("MockSchemaIntrospector", "IntrospectTable")
}

func (m *MockSchemaIntrospector) CompareSchemaToProtos(ctx context.Context, tables []Table, protoDir string) (CheckResult, error) {
	m.Record("CompareSchemaToProtos", ctx, tables, protoDir)
	if m.CompareSchemaToProtosFunc != nil {
		return m.CompareSchemaToProtosFunc(ctx, tables, protoDir)
	}
	return CheckResult{}, contractkit.MockNotSet("MockSchemaIntrospector", "CompareSchemaToProtos")
}

func (m *MockSchemaIntrospector) ParseProtoEntities(ctx context.Context, dir string) ([]ProtoEntity, error) {
	m.Record("ParseProtoEntities", ctx, dir)
	if m.ParseProtoEntitiesFunc != nil {
		return m.ParseProtoEntitiesFunc(ctx, dir)
	}
	return nil, contractkit.MockNotSet("MockSchemaIntrospector", "ParseProtoEntities")
}

// Compile-time check.
var _ SchemaIntrospector = (*MockSchemaIntrospector)(nil)

// MockMigrationService is a test mock for the MigrationService interface.
//
// The embedded contractkit.Recorder records every call so tests can
// assert call counts and captured arguments. Set XxxFunc fields to
// override per-method behaviour; unset methods return the canonical
// "MockMigrationService.<Method>Func not set" error.
type MockMigrationService struct {
	contractkit.Recorder
	CreateMigrationFunc        func(context.Context, string, string, *MigrationOptions) error
	GatherMigrationContextFunc func(context.Context, string, string, MigrationOptions) (*MigrationContext, error)
	GetPreviousMigrationFunc   func(context.Context, string) (*PreviousMigrationInfo, error)
	GetMigrationHistoryFunc    func(context.Context, string) ([]string, error)
}

func (m *MockMigrationService) CreateMigration(ctx context.Context, name string, dir string, opts *MigrationOptions) error {
	m.Record("CreateMigration", ctx, name, dir, opts)
	if m.CreateMigrationFunc != nil {
		return m.CreateMigrationFunc(ctx, name, dir, opts)
	}
	return contractkit.MockNotSet("MockMigrationService", "CreateMigration")
}

func (m *MockMigrationService) GatherMigrationContext(ctx context.Context, name string, migDir string, opts MigrationOptions) (*MigrationContext, error) {
	m.Record("GatherMigrationContext", ctx, name, migDir, opts)
	if m.GatherMigrationContextFunc != nil {
		return m.GatherMigrationContextFunc(ctx, name, migDir, opts)
	}
	return nil, contractkit.MockNotSet("MockMigrationService", "GatherMigrationContext")
}

func (m *MockMigrationService) GetPreviousMigration(ctx context.Context, dir string) (*PreviousMigrationInfo, error) {
	m.Record("GetPreviousMigration", ctx, dir)
	if m.GetPreviousMigrationFunc != nil {
		return m.GetPreviousMigrationFunc(ctx, dir)
	}
	return nil, contractkit.MockNotSet("MockMigrationService", "GetPreviousMigration")
}

func (m *MockMigrationService) GetMigrationHistory(ctx context.Context, dir string) ([]string, error) {
	m.Record("GetMigrationHistory", ctx, dir)
	if m.GetMigrationHistoryFunc != nil {
		return m.GetMigrationHistoryFunc(ctx, dir)
	}
	return nil, contractkit.MockNotSet("MockMigrationService", "GetMigrationHistory")
}

// Compile-time check.
var _ MigrationService = (*MockMigrationService)(nil)

// MockProtoGenerator is a test mock for the ProtoGenerator interface.
//
// The embedded contractkit.Recorder records every call so tests can
// assert call counts and captured arguments. Set XxxFunc fields to
// override per-method behaviour; unset methods return the canonical
// "MockProtoGenerator.<Method>Func not set" error.
type MockProtoGenerator struct {
	contractkit.Recorder
	GenerateProtoFilesFunc func(context.Context, []Table, string, string) error
}

func (m *MockProtoGenerator) GenerateProtoFiles(ctx context.Context, tables []Table, outputDir string, goModule string) error {
	m.Record("GenerateProtoFiles", ctx, tables, outputDir, goModule)
	if m.GenerateProtoFilesFunc != nil {
		return m.GenerateProtoFilesFunc(ctx, tables, outputDir, goModule)
	}
	return contractkit.MockNotSet("MockProtoGenerator", "GenerateProtoFiles")
}

// Compile-time check.
var _ ProtoGenerator = (*MockProtoGenerator)(nil)
