// Package checksums tracks sha256 digests of forge-generated files so
// `forge generate`, `forge upgrade`, and `forge audit` can distinguish
// "user-edited" files from "untouched generator output".
//
// The package is the lowest layer in the dependency stack so that both
// `internal/codegen` (the per-feature emitters) and `internal/generator`
// (the project-level scaffolder) can import it without an import cycle.
// `internal/generator` re-exports the public symbols as type aliases so
// existing call sites continue to compile unchanged.
package checksums

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"os"
	"path/filepath"
)

const checksumFile = ".forge/checksums.json"

// historyLimit caps how many prior-render checksums each file entry keeps.
// Long-running projects re-render Tier-2 files many times; without a bound
// the checksums.json file would grow unbounded. 20 is small enough to keep
// the file readable when a human peeks at it, large enough that ordinary
// usage never falls off the back of the window.
const historyLimit = 20

// SkipWrite is a per-pipeline-run opt-out set: paths in this map will
// have their `WriteGeneratedFile*` writes silently skipped (the recorded
// checksum is still kept as-is). Populated by `forge generate --accept`
// when the user has hand-edited a Tier-1 file and wants to preserve their
// fork; the codegen emitter still tries to render and write, but the
// helper short-circuits so the user's content survives.
//
// Stored as a package-level map (not on FileChecksums) because it's
// pipeline-run state, not persistent state. Reset between runs.
var SkipWrite = map[string]bool{}

// AddSkipWrite marks relPath as opt-out for the current run. Idempotent.
func AddSkipWrite(relPath string) { SkipWrite[relPath] = true }

// ResetSkipWrite clears the skip-write set. Called at the start of each
// pipeline run to avoid leaking state across forge invocations in tests
// or long-lived processes.
func ResetSkipWrite() { SkipWrite = map[string]bool{} }

// FileChecksums tracks sha256 digests of forge-generated files.
//
// Wire format is JSON. Two shapes are supported on disk:
//
//  1. Legacy ("flat"): files maps relative path -> hex sha256 string.
//  2. Current ("entry"): files maps relative path -> {hash, history[]}
//     where history is the list of every checksum forge has rendered for
//     that file (deduplicated, bounded by historyLimit). The most recent
//     entry sits at the end of history; hash always equals the last entry.
//
// On load, both shapes are accepted — a legacy hex string is promoted into
// an entry whose history is seeded with the same hash. On save, we always
// emit the entry shape. This means a one-time round-trip migrates legacy
// checksum files transparently.
//
// History is the mechanism that closes the "stale codegen vs user-modified"
// gap (FORGE_BACKLOG.md). When a template is updated and the on-disk file
// matches a *prior* render rather than the current one, forge knows the
// file is stale codegen — not a user edit — and can auto-update it cleanly
// without --force.
type FileChecksums struct {
	ForgeVersion string                       `json:"forge_version"`
	Files        map[string]FileChecksumEntry `json:"files"` // relative path -> entry
}

// FileChecksumEntry is the per-file checksum + history record.
//
// Hash is the checksum of the most recent render forge produced for this
// path. History is the deduplicated, bounded list of *every* checksum forge
// has rendered for this path, oldest first. Hash always equals the last
// element of History (when History is non-empty).
//
// Tier classifies the lifecycle of the file:
//
//   - 1 — generated every run (`// Code generated by forge ... DO NOT
//     EDIT.`). The Tier-1 stomp guard refuses to overwrite a Tier-1 file
//     that's been hand-edited unless `--force` or `--accept` is set.
//   - 2 — scaffold-once user-owned (`// forge:scaffold one-shot`). Forge
//     writes once and never overwrites. Tracked here only so audit can
//     report drift; the stomp guard ignores Tier-2.
//   - 0 — unset / legacy. Treated as Tier-1-equivalent for the stomp
//     guard, since pre-tier checksums covered exclusively Tier-1 files.
//     New writes should always specify a tier; the unset-→-1 default is
//     a backstop for migration only.
//
// On JSON load, missing History is treated as empty — backwards-compat with
// pre-history checksum files. On JSON save, the legacy flat-string shape is
// never emitted (we always write the structured form).
type FileChecksumEntry struct {
	Hash    string   `json:"hash"`
	History []string `json:"history,omitempty"`
	Tier    int      `json:"tier,omitempty"`
	// Forked records that the user ran `forge generate --accept` on this
	// path: they intentionally hand-edited a Tier-1 file and want forge to
	// stop trying to regenerate it. Future codegen passes will skip writes
	// to forked paths; the stomp guard ignores them too (no point
	// guarding a file forge no longer owns). Persists across runs.
	Forked bool `json:"forked,omitempty"`
}

// Load loads the checksum file from the project root.
//
// Accepts both the legacy flat shape (files: path -> hash string) and the
// current structured shape (files: path -> {hash, history[]}). Legacy
// entries get their hash promoted into a 1-element history on load.
func Load(root string) (*FileChecksums, error) {
	path := filepath.Join(root, checksumFile)
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return &FileChecksums{Files: make(map[string]FileChecksumEntry)}, nil
		}
		return nil, err
	}
	cs, err := unmarshalChecksums(data)
	if err != nil {
		return nil, err
	}
	if cs.Files == nil {
		cs.Files = make(map[string]FileChecksumEntry)
	}
	return cs, nil
}

// unmarshalChecksums decodes either the legacy flat shape or the current
// structured shape into a *FileChecksums. Splits decode logic out so it's
// independently testable.
func unmarshalChecksums(data []byte) (*FileChecksums, error) {
	// Try the structured shape first.
	var structured FileChecksums
	if err := json.Unmarshal(data, &structured); err == nil && structured.Files != nil {
		// If any value decoded as zero (Hash==""), it's likely the legacy
		// shape sneaking through (Go's json package will populate the
		// struct with a zero value when the source is a string). Fall
		// through to the legacy decode path.
		legacy := false
		for _, e := range structured.Files {
			if e.Hash == "" {
				legacy = true
				break
			}
		}
		if !legacy {
			// Backfill history for entries that have a hash but no history
			// (mid-migration files written by an older forge).
			for k, e := range structured.Files {
				if len(e.History) == 0 && e.Hash != "" {
					e.History = []string{e.Hash}
					structured.Files[k] = e
				}
			}
			return &structured, nil
		}
	}

	// Legacy flat shape: files: path -> hex string.
	var legacy struct {
		ForgeVersion string            `json:"forge_version"`
		Files        map[string]string `json:"files"`
	}
	if err := json.Unmarshal(data, &legacy); err != nil {
		return nil, err
	}
	cs := &FileChecksums{
		ForgeVersion: legacy.ForgeVersion,
		Files:        make(map[string]FileChecksumEntry, len(legacy.Files)),
	}
	for path, hash := range legacy.Files {
		cs.Files[path] = FileChecksumEntry{Hash: hash, History: []string{hash}}
	}
	return cs, nil
}

// Save writes the checksum file in the structured shape.
func Save(root string, cs *FileChecksums) error {
	path := filepath.Join(root, checksumFile)
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return err
	}
	data, err := json.MarshalIndent(cs, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, data, 0644)
}

// Hash returns the sha256 hex digest of content.
func Hash(content []byte) string {
	h := sha256.Sum256(content)
	return hex.EncodeToString(h[:])
}

// IsFileModified checks if a generated file has been modified by the user.
// Returns true if the file exists but its hash matches neither the stored
// current checksum nor any prior-render in history.
//
// Returns false if the file doesn't exist, was never tracked, or matches
// any checksum forge has previously rendered for this path. The "matches
// any prior render" branch is what lets stale codegen sail through upgrade
// cleanly — forge knows it generated this content, even if the template
// has since moved on.
func (cs *FileChecksums) IsFileModified(root, relPath string) bool {
	entry, ok := cs.Files[relPath]
	if !ok {
		return false // never tracked, not "modified"
	}
	content, err := os.ReadFile(filepath.Join(root, relPath))
	if err != nil {
		return false // file doesn't exist
	}
	h := Hash(content)
	if h == entry.Hash {
		return false
	}
	for _, prior := range entry.History {
		if h == prior {
			return false
		}
	}
	return true
}

// MatchesAnyKnownRender reports whether content's checksum equals the
// current Hash or any entry in History for this path. Distinct from
// IsFileModified in that it operates on raw content (not on-disk reads)
// and treats untracked paths as "not matching" rather than "not modified".
func (cs *FileChecksums) MatchesAnyKnownRender(relPath string, content []byte) bool {
	entry, ok := cs.Files[relPath]
	if !ok {
		return false
	}
	h := Hash(content)
	if h == entry.Hash {
		return true
	}
	for _, prior := range entry.History {
		if h == prior {
			return true
		}
	}
	return false
}

// RecordFile stores the checksum for a generated file and appends it to
// the file's render history.
//
// History is deduplicated (no contiguous duplicates and no resurrected
// older entries) and bounded by historyLimit. The most recent entry sits
// at the end of History; Hash always mirrors the tail.
func (cs *FileChecksums) RecordFile(relPath string, content []byte) {
	if cs.Files == nil {
		cs.Files = make(map[string]FileChecksumEntry)
	}
	h := Hash(content)
	entry := cs.Files[relPath]
	entry.Hash = h

	// Dedupe: if the new hash is already in history, drop the prior
	// occurrence and re-append at the tail. This keeps the "most recent
	// at the end" invariant and prevents history from churning when a
	// template flips back-and-forth between two shapes.
	filtered := entry.History[:0]
	for _, prior := range entry.History {
		if prior == h {
			continue
		}
		filtered = append(filtered, prior)
	}
	filtered = append(filtered, h)

	// Bound: keep the most recent historyLimit entries.
	if len(filtered) > historyLimit {
		filtered = filtered[len(filtered)-historyLimit:]
	}
	// Copy to a fresh slice to avoid aliasing the original backing array.
	entry.History = append([]string(nil), filtered...)
	cs.Files[relPath] = entry
}

// WriteGeneratedFile writes content to a file and records its checksum.
// If the file has been user-modified (checksum mismatch and no history
// match) and force is false, the write is skipped. Returns true if the
// file was written, false if skipped.
//
// A nil cs is tolerated — the file is written but no checksum is tracked.
// This keeps the helper safe to call from code paths that don't have a
// *FileChecksums in scope (e.g. legacy callers being incrementally ported).
//
// Tier defaults to 0 (legacy) — the stomp guard treats this as Tier-1
// for back-compat. Prefer the typed wrappers (WriteGeneratedFileTier1 /
// WriteGeneratedFileTier2) at new call sites so the manifest is explicit.
func WriteGeneratedFile(root, relPath string, content []byte, cs *FileChecksums, force bool) (bool, error) {
	if SkipWrite[relPath] {
		// `forge generate --accept` opted this path out for the current
		// run. The user's on-disk content survives; the just-rendered
		// content is dropped on the floor.
		return false, nil
	}
	if cs != nil {
		if entry, ok := cs.Files[relPath]; ok && entry.Forked {
			// User previously ran `--accept` on this path. Forge no
			// longer owns it. Skip even when force=true — the user's
			// intent is "stop touching this file"; --force is for
			// blowing away current-run hand-edits, not historical forks.
			return false, nil
		}
	}
	if cs != nil && !force && cs.IsFileModified(root, relPath) {
		// User has modified this file — skip
		return false, nil
	}

	fullPath := filepath.Join(root, relPath)
	if err := os.MkdirAll(filepath.Dir(fullPath), 0755); err != nil {
		return false, err
	}
	if err := os.WriteFile(fullPath, content, 0644); err != nil {
		return false, err
	}
	if cs != nil {
		cs.RecordFile(relPath, content)
	}
	return true, nil
}

// WriteGeneratedFileTier1 writes a Tier-1 (regenerated-every-run) file
// and tags the checksum entry as Tier-1. The Tier-1 tag drives the
// pre-pipeline stomp guard: a future `forge generate` run will refuse to
// overwrite a Tier-1 file that's been hand-edited unless the user passes
// `--force` (clobber) or `--accept` (refresh recorded checksum to the
// edited content).
//
// Behaviorally identical to WriteGeneratedFile when force is true — the
// Tier-1 tag is purely metadata that downstream guards consult. The
// caller is responsible for upholding the Tier-1 contract by including
// the `// Code generated by forge ... DO NOT EDIT.` banner in `content`.
func WriteGeneratedFileTier1(root, relPath string, content []byte, cs *FileChecksums, force bool) (bool, error) {
	wrote, err := WriteGeneratedFile(root, relPath, content, cs, force)
	if err != nil || !wrote || cs == nil {
		return wrote, err
	}
	entry := cs.Files[relPath]
	entry.Tier = 1
	cs.Files[relPath] = entry
	return wrote, nil
}

// WriteGeneratedFileTier2 writes a Tier-2 (scaffold-once user-owned)
// file. The stomp guard ignores Tier-2 entries — forge never auto-
// regenerates these, so a user edit is the expected steady state, not
// drift. Use this for "// forge:scaffold one-shot" templates.
func WriteGeneratedFileTier2(root, relPath string, content []byte, cs *FileChecksums, force bool) (bool, error) {
	wrote, err := WriteGeneratedFile(root, relPath, content, cs, force)
	if err != nil || !wrote || cs == nil {
		return wrote, err
	}
	entry := cs.Files[relPath]
	entry.Tier = 2
	cs.Files[relPath] = entry
	return wrote, nil
}

// Tier1Drift reports the relative paths of every Tier-1 file whose
// on-disk content does not match any recorded render (current Hash or
// any History entry). The returned slice is sorted to give callers a
// stable error message order.
//
// Files that aren't tracked, can't be read (e.g. removed by the user),
// or aren't tagged Tier-1 are skipped — only positive evidence of a
// hand-edit on a Tier-1 file is reported.
type Tier1DriftEntry struct {
	Path           string
	RecordedHash   string
	OnDiskHash     string
	HistoryDepth   int // count of prior renders we compared against
}

// CheckTier1Drift walks all Tier-1 entries in cs.Files and returns the
// list of files whose on-disk content doesn't match any recorded render.
// Used as a pre-pipeline guard so `forge generate` errors loudly instead
// of silently overwriting hand-edited Tier-1 files.
//
// Legacy entries (Tier == 0) are treated as Tier-1 for back-compat with
// pre-tier checksum files — the stomp guard predates the explicit tier
// tag and we don't want a forge upgrade to suddenly stop guarding files
// the user expects to be guarded.
func (cs *FileChecksums) CheckTier1Drift(root string) []Tier1DriftEntry {
	if cs == nil || len(cs.Files) == 0 {
		return nil
	}
	var drift []Tier1DriftEntry
	for relPath, entry := range cs.Files {
		if entry.Forked {
			continue
		}
		if entry.Tier != 0 && entry.Tier != 1 {
			continue
		}
		full := filepath.Join(root, relPath)
		content, err := os.ReadFile(full)
		if err != nil {
			continue // file gone or unreadable — not a "stomp" candidate
		}
		h := Hash(content)
		if h == entry.Hash {
			continue
		}
		matchedHistory := false
		for _, prior := range entry.History {
			if h == prior {
				matchedHistory = true
				break
			}
		}
		if matchedHistory {
			continue
		}
		drift = append(drift, Tier1DriftEntry{
			Path:         relPath,
			RecordedHash: entry.Hash,
			OnDiskHash:   h,
			HistoryDepth: len(entry.History),
		})
	}
	// Stable ordering for deterministic error messages.
	sortDrift(drift)
	return drift
}

// AcceptTier1Drift updates the recorded checksum for each entry in drift
// to the on-disk content's hash, marks the entry as Forked, and ensures
// future `WriteGeneratedFile*` calls skip the path. Used by
// `forge generate --accept` for the rare "I really did mean to fork
// this Tier-1 file" path. The Forked flag persists across runs so
// subsequent codegen passes never re-overwrite the user's content.
func (cs *FileChecksums) AcceptTier1Drift(root string, drift []Tier1DriftEntry) error {
	if cs == nil {
		return nil
	}
	for _, d := range drift {
		full := filepath.Join(root, d.Path)
		content, err := os.ReadFile(full)
		if err != nil {
			return err
		}
		cs.RecordFile(d.Path, content)
		// RecordFile clears any pre-existing tier when it overwrites the
		// entry value, so re-stamp the Tier-1 tag (so audit still
		// reports it as a Tier-1-derived file) and mark Forked.
		entry := cs.Files[d.Path]
		entry.Tier = 1
		entry.Forked = true
		cs.Files[d.Path] = entry
	}
	return nil
}

// sortDrift sorts a slice of Tier1DriftEntry by Path, ascending.
// Inlined to avoid an import of "sort" at the top of the file just for
// one stable-order pass.
func sortDrift(drift []Tier1DriftEntry) {
	for i := 1; i < len(drift); i++ {
		for j := i; j > 0 && drift[j-1].Path > drift[j].Path; j-- {
			drift[j-1], drift[j] = drift[j], drift[j-1]
		}
	}
}
