// Code generated by forge. DO NOT EDIT.
package packs

import (
	"context"
	"github.com/reliant-labs/forge/internal/config"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/metric"
	"time"
)

// MetricManager wraps a Manager implementation with OpenTelemetry metrics.
// Every method call records call count, error count, and duration.
type MetricManager struct {
	inner     Manager
	callCount metric.Int64Counter
	errCount  metric.Int64Counter
	duration  metric.Float64Histogram
}

// NewMetricManager creates a metrics wrapper around the given Manager.
func NewMetricManager(inner Manager, meter metric.Meter) Manager {
	callCount, _ := meter.Int64Counter("packs.calls", metric.WithDescription("Total method calls"))
	errCount, _ := meter.Int64Counter("packs.errors", metric.WithDescription("Total method errors"))
	duration, _ := meter.Float64Histogram("packs.duration", metric.WithDescription("Method duration in seconds"), metric.WithUnit("s"))
	return &MetricManager{inner: inner, callCount: callCount, errCount: errCount, duration: duration}
}

func (w *MetricManager) Load(ctx context.Context, name string) (*Pack, error) {
	start := time.Now()
	w.callCount.Add(ctx, 1, metric.WithAttributes(attribute.String("method", "Load")))
	r0, r1 := w.inner.Load(ctx, name)
	w.duration.Record(ctx, time.Since(start).Seconds(), metric.WithAttributes(attribute.String("method", "Load")))
	if r1 != nil {
		w.errCount.Add(ctx, 1, metric.WithAttributes(attribute.String("method", "Load")))
	}
	return r0, r1
}

func (w *MetricManager) Install(ctx context.Context, pack *Pack, projectDir string, cfg *config.ProjectConfig) error {
	start := time.Now()
	w.callCount.Add(ctx, 1, metric.WithAttributes(attribute.String("method", "Install")))
	r0 := w.inner.Install(ctx, pack, projectDir, cfg)
	w.duration.Record(ctx, time.Since(start).Seconds(), metric.WithAttributes(attribute.String("method", "Install")))
	if r0 != nil {
		w.errCount.Add(ctx, 1, metric.WithAttributes(attribute.String("method", "Install")))
	}
	return r0
}

func (w *MetricManager) Remove(ctx context.Context, pack *Pack, projectDir string, cfg *config.ProjectConfig) error {
	start := time.Now()
	w.callCount.Add(ctx, 1, metric.WithAttributes(attribute.String("method", "Remove")))
	r0 := w.inner.Remove(ctx, pack, projectDir, cfg)
	w.duration.Record(ctx, time.Since(start).Seconds(), metric.WithAttributes(attribute.String("method", "Remove")))
	if r0 != nil {
		w.errCount.Add(ctx, 1, metric.WithAttributes(attribute.String("method", "Remove")))
	}
	return r0
}

func (w *MetricManager) List(ctx context.Context) ([]Pack, error) {
	start := time.Now()
	w.callCount.Add(ctx, 1, metric.WithAttributes(attribute.String("method", "List")))
	r0, r1 := w.inner.List(ctx)
	w.duration.Record(ctx, time.Since(start).Seconds(), metric.WithAttributes(attribute.String("method", "List")))
	if r1 != nil {
		w.errCount.Add(ctx, 1, metric.WithAttributes(attribute.String("method", "List")))
	}
	return r0, r1
}

func (w *MetricManager) InstalledPacks(ctx context.Context, cfg *config.ProjectConfig) ([]*Pack, error) {
	start := time.Now()
	w.callCount.Add(ctx, 1, metric.WithAttributes(attribute.String("method", "InstalledPacks")))
	r0, r1 := w.inner.InstalledPacks(ctx, cfg)
	w.duration.Record(ctx, time.Since(start).Seconds(), metric.WithAttributes(attribute.String("method", "InstalledPacks")))
	if r1 != nil {
		w.errCount.Add(ctx, 1, metric.WithAttributes(attribute.String("method", "InstalledPacks")))
	}
	return r0, r1
}

func (w *MetricManager) IsInstalled(ctx context.Context, name string, cfg *config.ProjectConfig) bool {
	start := time.Now()
	w.callCount.Add(ctx, 1, metric.WithAttributes(attribute.String("method", "IsInstalled")))
	r0 := w.inner.IsInstalled(ctx, name, cfg)
	w.duration.Record(ctx, time.Since(start).Seconds(), metric.WithAttributes(attribute.String("method", "IsInstalled")))
	return r0
}

func (w *MetricManager) RenderGenerateFiles(ctx context.Context, pack *Pack, projectDir string, cfg *config.ProjectConfig) error {
	start := time.Now()
	w.callCount.Add(ctx, 1, metric.WithAttributes(attribute.String("method", "RenderGenerateFiles")))
	r0 := w.inner.RenderGenerateFiles(ctx, pack, projectDir, cfg)
	w.duration.Record(ctx, time.Since(start).Seconds(), metric.WithAttributes(attribute.String("method", "RenderGenerateFiles")))
	if r0 != nil {
		w.errCount.Add(ctx, 1, metric.WithAttributes(attribute.String("method", "RenderGenerateFiles")))
	}
	return r0
}

// Compile-time check.
var _ Manager = (*MetricManager)(nil)
