// Code generated by forge. DO NOT EDIT.
// Source: contract.go in this package.
//
// To customize: edit contract.go (the interface IS the public surface) and
// re-run "forge generate". This file is regenerated unconditionally.
package packs

import (
	"context"
	"github.com/reliant-labs/forge/internal/config"
	"github.com/reliant-labs/forge/pkg/contractkit"
)

// MockManager is a test mock for the Manager interface.
//
// The embedded contractkit.Recorder records every call so tests can
// assert call counts and captured arguments. Set XxxFunc fields to
// override per-method behaviour; unset methods return the canonical
// "MockManager.<Method>Func not set" error.
type MockManager struct {
	contractkit.Recorder
	LoadFunc                func(context.Context, string) (*Pack, error)
	InstallFunc             func(context.Context, *Pack, string, *config.ProjectConfig) error
	RemoveFunc              func(context.Context, *Pack, string, *config.ProjectConfig) error
	ListFunc                func(context.Context) ([]Pack, error)
	InstalledPacksFunc      func(context.Context, *config.ProjectConfig) ([]*Pack, error)
	IsInstalledFunc         func(context.Context, string, *config.ProjectConfig) bool
	RenderGenerateFilesFunc func(context.Context, *Pack, string, *config.ProjectConfig) error
}

func (m *MockManager) Load(ctx context.Context, name string) (*Pack, error) {
	m.Record("Load", ctx, name)
	if m.LoadFunc != nil {
		return m.LoadFunc(ctx, name)
	}
	return nil, contractkit.MockNotSet("MockManager", "Load")
}

func (m *MockManager) Install(ctx context.Context, pack *Pack, projectDir string, cfg *config.ProjectConfig) error {
	m.Record("Install", ctx, pack, projectDir, cfg)
	if m.InstallFunc != nil {
		return m.InstallFunc(ctx, pack, projectDir, cfg)
	}
	return contractkit.MockNotSet("MockManager", "Install")
}

func (m *MockManager) Remove(ctx context.Context, pack *Pack, projectDir string, cfg *config.ProjectConfig) error {
	m.Record("Remove", ctx, pack, projectDir, cfg)
	if m.RemoveFunc != nil {
		return m.RemoveFunc(ctx, pack, projectDir, cfg)
	}
	return contractkit.MockNotSet("MockManager", "Remove")
}

func (m *MockManager) List(ctx context.Context) ([]Pack, error) {
	m.Record("List", ctx)
	if m.ListFunc != nil {
		return m.ListFunc(ctx)
	}
	return nil, contractkit.MockNotSet("MockManager", "List")
}

func (m *MockManager) InstalledPacks(ctx context.Context, cfg *config.ProjectConfig) ([]*Pack, error) {
	m.Record("InstalledPacks", ctx, cfg)
	if m.InstalledPacksFunc != nil {
		return m.InstalledPacksFunc(ctx, cfg)
	}
	return nil, contractkit.MockNotSet("MockManager", "InstalledPacks")
}

func (m *MockManager) IsInstalled(ctx context.Context, name string, cfg *config.ProjectConfig) bool {
	m.Record("IsInstalled", ctx, name, cfg)
	if m.IsInstalledFunc != nil {
		return m.IsInstalledFunc(ctx, name, cfg)
	}
	return false
}

func (m *MockManager) RenderGenerateFiles(ctx context.Context, pack *Pack, projectDir string, cfg *config.ProjectConfig) error {
	m.Record("RenderGenerateFiles", ctx, pack, projectDir, cfg)
	if m.RenderGenerateFilesFunc != nil {
		return m.RenderGenerateFilesFunc(ctx, pack, projectDir, cfg)
	}
	return contractkit.MockNotSet("MockManager", "RenderGenerateFiles")
}

// Compile-time check.
var _ Manager = (*MockManager)(nil)
