// Package codegen — config_projection_gen.go emits the VALUE-projection
// half that pairs with the TYPE half in config_schema_gen.go.
//
// Where config_schema_gen.go projects the SHAPE (`schema AppConfig`), this
// emitter projects the BEHAVIOR: two generated KCL functions that turn a
// typed `AppConfig` value into the exact same env output the current Go
// projector (deploy_config_gen.go's renderEnvVarEntry / renderDeployConfigKCL)
// produces today —
//
//   - appConfigEnvVars(c, secretName, configMapName) -> [forge.EnvVar]
//     one entry per config field with a non-empty env_var, using the same
//     sensitive/non-sensitive branch as renderEnvVarEntry:
//       * non-sensitive -> config_map_ref / config_map_key
//       * sensitive     -> secret_ref / secret_key (lower(ENV_VAR))
//   - appConfigConfigMap(c, configMapName) -> forge.ConfigMap
//     the `data` map for the NON-sensitive fields only.
//
// The per-field metadata (env-var name, sensitive flag, value expression)
// is BAKED into the generated code from the proto — the functions are
// generated, not generic — so the emitted KCL is a straight-line list/dict
// literal with no runtime reflection.
//
// This is Phase 2 and is ADDITIVE: like Phase 1 it is a standalone emitter
// + test, NOT wired into the generate pipeline, and it does NOT touch
// deploy_config_gen.go (the current Go projector). A future migration can
// swap the Go projector for these functions with behavior parity, leaving
// the runtime Go loader (pkg/config/loader.go, which binds env by each
// field's env_var) unchanged.
//
// Phase 3 note: the sensitive branch reads the typed ConfigSecretRef off the
// AppConfig value (secret_ref = c.<field>.name, secret_key = c.<field>.key).
// The default backend (secret_ref = "<project>-secrets", secret_key =
// lower(env_var)) is supplied by the AppConfig field's SCHEMA DEFAULT (see
// config_schema_gen.go), and the per-env "${SECRET_NAME}" /
// "${SECRET_NAME#KEY}" override that renderEnvVarEntry supports flows through
// as a ConfigSecretRef the migration (config_k_gen.go) writes into config.k —
// so these functions now reach full parity with the Go projector INCLUDING
// override-using envs.
package codegen

import (
	"fmt"
	"strings"
)

// GenerateConfigProjectionKCL emits a KCL file declaring the two config
// projection functions (appConfigEnvVars / appConfigConfigMap) as top-level
// lambdas — the idiomatic forge-KCL function form (see kcl/base.k).
//
// The functions reference the `AppConfig` schema emitted by
// GenerateConfigSchemaKCL (co-located in the same KCL package) and the
// `forge.EnvVar` / `forge.ConfigMap` schemas from the forge module, so the
// file carries its own `import forge`.
//
// Fields are visited in proto order. A field with an empty env_var (a
// component config-block reference, or any field with no env binding) is
// skipped — mirroring the runtime loader, which binds env only for fields
// that declare an env_var.
func GenerateConfigProjectionKCL(fields []ConfigField) (string, error) {
	var b strings.Builder

	// 2-line generated-file header, matching the Phase-1 emitter's stamp
	// convention (see config_schema_gen.go).
	b.WriteString("# Code generated by forge. DO NOT EDIT.\n")
	b.WriteString("# Config projection functions (typed AppConfig -> [forge.EnvVar] + forge.ConfigMap) projected from proto/config/v1/config.proto — add or change fields in the PROTO, never here.\n\n")

	// The functions reference forge.EnvVar / forge.ConfigMap AND the AppConfig
	// schema from the sibling config_schema.k module. KCL does not share
	// top-level symbols across separately-imported modules, so AppConfig is
	// imported + qualified as config_schema.AppConfig (see ConfigSchemaModule).
	b.WriteString("import forge\n")
	b.WriteString(fmt.Sprintf("import %s\n\n", ConfigSchemaModule))

	b.WriteString(renderAppConfigEnvVars(fields))
	b.WriteString("\n")
	b.WriteString(renderAppConfigConfigMap(fields))

	return b.String(), nil
}

// renderAppConfigEnvVars emits the appConfigEnvVars lambda: one
// forge.EnvVar per field with a non-empty env_var, sensitive fields routed
// to secret_ref/secret_key and non-sensitive fields to
// config_map_ref/config_map_key — the same split as
// deploy_config_gen.go:renderEnvVarEntry.
func renderAppConfigEnvVars(fields []ConfigField) string {
	var entries []string
	for _, f := range fields {
		// Empty env_var == no env binding (block-reference messages and any
		// unbound field). Matches the runtime loader and renderEnvVarEntry.
		if f.EnvVar == "" {
			continue
		}
		if f.Sensitive {
			// Read the typed ConfigSecretRef off the AppConfig value: its
			// name/key ARE the secret_ref/secret_key. This supersedes the
			// Phase-2 default-backend-only form — the AppConfig field's
			// SCHEMA DEFAULT already supplies the default backend
			// (<project>-secrets / lower(env_var)), and an author who set a
			// ConfigSecretRef override (the ${NAME#KEY} case) flows through
			// here unchanged. The `secretName` parameter is retained for
			// signature stability but no longer consulted by sensitive fields.
			entries = append(entries, fmt.Sprintf(
				`    forge.EnvVar { name = %q, secret_ref = c.%s.name, secret_key = c.%s.key }`,
				f.EnvVar, f.Name, f.Name))
			continue
		}
		entries = append(entries, fmt.Sprintf(
			`    forge.EnvVar { name = %q, config_map_ref = configMapName, config_map_key = %q }`,
			f.EnvVar, f.EnvVar))
	}

	var b strings.Builder
	b.WriteString("# appConfigEnvVars projects a typed AppConfig into the deployment's\n")
	b.WriteString("# env_vars — one forge.EnvVar per field that declares an env_var.\n")
	b.WriteString(fmt.Sprintf("appConfigEnvVars = lambda c: %s.AppConfig, secretName: str, configMapName: str -> [forge.EnvVar] {\n", ConfigSchemaModule))
	if len(entries) == 0 {
		b.WriteString("    []\n")
	} else {
		b.WriteString("    [\n")
		for _, e := range entries {
			// Nest the entry lines one level deeper (inside the list literal).
			b.WriteString("    ")
			b.WriteString(e)
			b.WriteString("\n")
		}
		b.WriteString("    ]\n")
	}
	b.WriteString("}\n")
	return b.String()
}

// renderAppConfigConfigMap emits the appConfigConfigMap lambda: a
// forge.ConfigMap whose `data` map holds one entry per NON-sensitive field
// with a non-empty env_var, keyed by ENV_VAR, valued by the typed field
// converted to a string (see kclConfigValueExpr). This mirrors the
// cmEntries the Go projector accumulates in renderDeployConfigKCL.
func renderAppConfigConfigMap(fields []ConfigField) string {
	type kv struct{ key, expr string }
	var data []kv
	for _, f := range fields {
		if f.EnvVar == "" || f.Sensitive {
			continue
		}
		data = append(data, kv{key: f.EnvVar, expr: kclConfigValueExpr(f, "c")})
	}

	var b strings.Builder
	b.WriteString("# appConfigConfigMap projects the NON-sensitive fields of a typed\n")
	b.WriteString("# AppConfig into the per-env ConfigMap the EnvVars above reference.\n")
	b.WriteString(fmt.Sprintf("appConfigConfigMap = lambda c: %s.AppConfig, configMapName: str -> forge.ConfigMap {\n", ConfigSchemaModule))
	b.WriteString("    forge.ConfigMap {\n")
	b.WriteString("        name = configMapName\n")
	if len(data) == 0 {
		b.WriteString("        data = {}\n")
	} else {
		b.WriteString("        data = {\n")
		for _, d := range data {
			b.WriteString(fmt.Sprintf("            %q = %s\n", d.key, d.expr))
		}
		b.WriteString("        }\n")
	}
	b.WriteString("    }\n")
	b.WriteString("}\n")
	return b.String()
}

// kclConfigValueExpr renders the KCL expression that reads field f off the
// typed AppConfig receiver `recv` as a STRING (ConfigMap data values are
// {str: str}). String-typed fields — including durations, which forge
// carries as strings ("30s") — inline directly; int/float scalars are
// wrapped in KCL's str(...) builtin.
//
// Bools are the exception: KCL's str(True) yields "True"/"False"
// (capitalized), but the Go projector renders bools via strconv.FormatBool →
// "true"/"false" (lowercase), and the runtime Go loader parses env values with
// strconv.ParseBool (which accepts either, but the ConfigMap value must match
// the Go projector byte-for-byte for render parity). So a bool is projected as
// an explicit `"true" if c.<field> else "false"` conditional to emit the
// lowercase form, NOT str(...).
//
// This reuses kclTypeForProtoConfig so the str/non-str decision stays
// identical to the schema emitter's type mapping.
func kclConfigValueExpr(f ConfigField, recv string) string {
	ref := recv + "." + f.Name
	switch kclTypeForProtoConfig(f) {
	case "str":
		return ref
	case "bool":
		return `"true" if ` + ref + ` else "false"`
	default:
		return "str(" + ref + ")"
	}
}
