// Package codegen — config_projection_gen.go emits the VALUE-projection
// half, and assembles it with the TYPE half from config_schema_gen.go into
// the single generated module deploy/kcl/config_gen.k (GenerateConfigKCL,
// the one entrypoint the pipeline calls).
//
// Where config_schema_gen.go projects the SHAPE (`schema AppConfig`), this
// emitter projects the BEHAVIOR: one generated KCL function that turns a
// typed `AppConfig` value into the agnostic-core env model an agnostic
// `forge.Service` consumes —
//
//   - appConfigEnvMap(c) -> {str: forge.EnvSource}
//     the agnostic-core env MAP (kcl/core.k), keyed by ENV_VAR name, one
//     entry per config field with a non-empty env_var:
//   - non-sensitive -> {value = <the value read off c>}
//     (lowered INLINE — the typed field converted to a
//     string, no ConfigMap object or reference)
//   - sensitive     -> {from_secret = {name = c.<field>.name,
//     key  = c.<field>.key}}
//     (reads the typed ConfigSecretRef off the value)
//
// The env MAP is the idiomatic authoring shape: a service consumes config the
// native way —
//
//	env = appConfigEnvMap(app_config) | { <service extras> }
//
// — composing config-first with native KCL map-merge `|` (last-wins), so a
// service extra of the same env-var NAME overrides the config entry, and
// duplicate keys are structurally impossible (no `env_merge`). The k8s
// adapter then projects the map to `[EnvVar]` via `env_project` (core.k).
//
// Non-sensitive config values are lowered INLINE as `{value = ...}` rather
// than through a ConfigMap object + reference — simpler is better: it drops
// the whole ConfigMap object and its cross-reference wiring. Only sensitive
// fields still route out-of-band, through `from_secret`.
//
// The per-field metadata (env-var name, sensitive flag, value expression)
// is BAKED into the generated code from the proto — the function is
// generated, not generic — so the emitted KCL is a straight-line map/dict
// literal with no runtime reflection. The runtime Go loader
// (pkg/config/loader.go, which binds env by each field's env_var) reads the
// SAME projected env vars, so the two stay coherent by construction.
//
// The sensitive branch reads the typed ConfigSecretRef off the AppConfig value
// (from_secret.name = c.<field>.name, key = c.<field>.key). The default backend
// (name = "<project>-secrets", key = lower(env_var)) is supplied by the
// AppConfig field's SCHEMA DEFAULT (see config_schema_gen.go), and a per-env
// override flows through as a ConfigSecretRef the author writes into config.k —
// so an author who overrides the backing Secret/key gets that here unchanged.
package codegen

import (
	"fmt"
	"strings"
)

// GenerateConfigKCL emits the ONE generated config module —
// deploy/kcl/config_gen.k — carrying both halves of the projection: the
// TYPE (`schema ConfigSecretRef` + `schema AppConfig`) and the BEHAVIOR
// (`appConfigEnvMap`).
//
// They were two files (config_schema.k + config_projection.k) on the
// premise that a KCL module cannot hold a schema and a lambda together.
// It can — forge's own kcl/core.k interleaves `schema EnvSource`,
// `env_project = lambda ...`, `schema EnvFrom` in one file. Since both
// halves are projected from the same proto by the same run and are only
// ever valid as a pair, splitting them bought nothing and cost a second
// Tier-1 file, a second hash guard and a second diff entry in every
// change. Merging also removes the cross-module import: the lambda now
// names `AppConfig` directly instead of `config_schema.AppConfig`.
//
// Layout is TYPE first, then BEHAVIOR — the lambda's signature references
// AppConfig, and reading the shape before the projection over it is the
// order that explains itself.
//
// Fields are visited in proto order by both halves. A field with an empty
// env_var (a component config-block reference, or any field with no env
// binding) is skipped by the projection — mirroring the runtime loader,
// which binds env only for fields that declare an env_var.
func GenerateConfigKCL(fields []ConfigField, projectName string) (string, error) {
	var b strings.Builder

	b.WriteString("# Code generated by forge. DO NOT EDIT.\n")
	b.WriteString("# Typed config schema + env projection, both projected from proto/config/v1/config.proto — author per-env values in deploy/kcl/<env>/config.k as an `AppConfig { ... }` instance; add or change fields in the PROTO, never here.\n\n")

	// forge.EnvSource is the projection's return type; the schemas below
	// need no import (they are declared here).
	b.WriteString("import forge\n\n")

	schema, err := renderAppConfigSchema(fields, projectName)
	if err != nil {
		return "", fmt.Errorf("render config schema: %w", err)
	}
	b.WriteString(schema)
	b.WriteString("\n")
	b.WriteString(renderAppConfigEnvMap(fields))

	return b.String(), nil
}

// KCLConfigName maps a config MESSAGE name to the KCL schema and lambda it
// projects to: `AdminConfig` -> schema `AdminConfig`, lambda
// `adminConfigEnvMap`. The lambda name is the schema name lower-camelled
// with the `EnvMap` suffix, matching the existing appConfigEnvMap spelling
// so the per-binary names read as the same family.
func KCLConfigName(messageName string) (schema, lambda string) {
	if messageName == "" {
		return "AppConfig", "appConfigEnvMap"
	}
	lower := strings.ToLower(messageName[:1]) + messageName[1:]
	return messageName, lower + "EnvMap"
}

// GenerateConfigKCLPerBinary emits the config module for a project that
// declares PER-BINARY configs: one typed schema plus one env-projection
// lambda per binary, all in the single generated config_gen.k.
//
// Each pair is projected from ONLY that binary's fields, which is what makes
// the deploy story disjoint: an env authoring `AdminConfig { ... }` can set
// only fields admin reads (anything else is a KCL type error), and the
// workload env built from adminConfigEnvMap carries only admin's env vars —
// so gateway's Deployment does not carry admin's credentials.
//
// rootFields is the project-global AppConfig's field set. It is still
// emitted when non-empty, because a project mid-migration (or one that keeps
// a shared AppConfig alongside per-binary ones) has env files and main.k
// modules that reference AppConfig/appConfigEnvMap, and those are user-owned
// scaffold-once files forge does not rewrite.
func GenerateConfigKCLPerBinary(rootFields []ConfigField, perBinary []BinaryConfigFields, projectName string) (string, error) {
	var b strings.Builder

	b.WriteString("# Code generated by forge. DO NOT EDIT.\n")
	b.WriteString("# Typed config schemas + env projections, one per BINARY, projected from proto/config/v1/config.proto — author per-env values in deploy/kcl/<env>/config.k as `<Binary>Config { ... }` instances; add or change fields in the PROTO, never here.\n\n")
	b.WriteString("import forge\n\n")

	// ConfigSecretRef is declared once for the whole module, by whichever
	// schema is emitted first.
	first := true
	emit := func(fields []ConfigField, messageName string) error {
		schemaName, lambdaName := KCLConfigName(messageName)
		schema, err := renderConfigSchemaNamed(fields, projectName, schemaName, first)
		if err != nil {
			return fmt.Errorf("render %s schema: %w", schemaName, err)
		}
		first = false
		b.WriteString(schema)
		b.WriteString("\n")
		b.WriteString(renderConfigEnvMapNamed(fields, schemaName, lambdaName))
		b.WriteString("\n")
		return nil
	}

	if len(rootFields) > 0 {
		if err := emit(rootFields, "AppConfig"); err != nil {
			return "", err
		}
	}
	for _, bc := range perBinary {
		if err := emit(bc.Fields, bc.MessageName); err != nil {
			return "", err
		}
	}

	return strings.TrimRight(b.String(), "\n") + "\n", nil
}

// BinaryConfigFields is one binary's KCL projection input: the config
// message name (which names the schema and lambda) and the ConfigFields that
// binary resolves — its own leaves plus the leaves of every block it
// composes.
type BinaryConfigFields struct {
	Binary      string
	MessageName string
	Fields      []ConfigField
}

// BinaryConfigFieldsFrom resolves the per-binary KCL projection inputs from
// parsed config messages, in declaration order. Empty for a project that
// declares no per-binary configs.
func BinaryConfigFieldsFrom(messages []ConfigMessage) []BinaryConfigFields {
	var out []BinaryConfigFields
	for _, m := range messages {
		if m.Binary == "" {
			continue
		}
		out = append(out, BinaryConfigFields{
			Binary:      m.Binary,
			MessageName: m.Name,
			Fields:      ConfigFieldsForBinary(messages, m.Binary),
		})
	}
	return out
}

// renderAppConfigEnvMap emits the appConfigEnvMap lambda: the agnostic-core
// env MAP `{str: forge.EnvSource}` (kcl/core.k) keyed by ENV_VAR name, one
// entry per field with a non-empty env_var. Sensitive fields route to the
// `from_secret` channel (reading the typed ConfigSecretRef off the value);
// non-sensitive fields lower INLINE to the `value` channel — the typed field
// read off `c` and converted to a string (see kclConfigValueExpr), NOT a
// ConfigMap reference. Simpler is better: there is no ConfigMap object or
// cross-reference to maintain.
//
// A service consumes this the idiomatic way — config first, service extras
// merged/overriding via native map-merge:
//
//	env = appConfigEnvMap(app_config) | { "EXTRA" = {value = "x"} }
func renderAppConfigEnvMap(fields []ConfigField) string {
	return renderConfigEnvMapNamed(fields, "AppConfig", "appConfigEnvMap")
}

// renderConfigEnvMapNamed emits one env-projection lambda over one config
// schema. It is the per-binary generalization of renderAppConfigEnvMap: a
// project with per-binary configs emits one lambda per binary, each closing
// over ONLY that binary's fields.
//
// That is where the per-binary security payoff is actually realized. The
// lambda a workload's env is built from is generated from one binary's field
// set, so the rendered Deployment carries that binary's env vars and no
// others — a credential belonging to a different binary is not merely
// unread, it is absent from the manifest.
func renderConfigEnvMapNamed(fields []ConfigField, schemaName, lambdaName string) string {
	type kv struct{ key, expr string }
	var entries []kv
	for _, f := range fields {
		// Empty env_var == no env binding (block-reference messages and any
		// unbound field). Matches the runtime loader, which binds env only for
		// fields that declare an env_var.
		if f.EnvVar == "" {
			continue
		}
		if f.Sensitive {
			// Read the typed ConfigSecretRef off the AppConfig value: its
			// name/key ARE the from_secret name/key. The AppConfig field's
			// SCHEMA DEFAULT supplies the default backend (<project>-secrets /
			// lower(env_var)); an author who set a ConfigSecretRef override
			// (the ${NAME#KEY} case) flows through here unchanged.
			entries = append(entries, kv{
				key:  f.EnvVar,
				expr: fmt.Sprintf(`{from_secret = {name = c.%s.name, key = c.%s.key}}`, f.Name, f.Name),
			})
			continue
		}
		// Non-sensitive -> INLINE value channel. The typed field is read off
		// `c` and converted to a string via kclConfigValueExpr (the SAME
		// value-formatting that previously fed the ConfigMap data), lowered
		// directly as `{value = ...}` — no ConfigMap object, no reference.
		entries = append(entries, kv{
			key:  f.EnvVar,
			expr: fmt.Sprintf(`{value = %s}`, kclConfigValueExpr(f, "c")),
		})
	}

	var b strings.Builder
	fmt.Fprintf(&b, "# %s projects a typed %s into the agnostic-core env\n", lambdaName, schemaName)
	b.WriteString("# MAP — one forge.EnvSource per field that declares an env_var, keyed by\n")
	fmt.Fprintf(&b, "# ENV_VAR name. A service merges it with `|`: `%s(cfg) | {…}`.\n", lambdaName)
	// The schema is declared above in this same file, so the parameter type
	// is the bare name — no module qualifier.
	fmt.Fprintf(&b, "%s = lambda c: %s -> {str: forge.EnvSource} {\n", lambdaName, schemaName)
	if len(entries) == 0 {
		b.WriteString("    {}\n")
	} else {
		b.WriteString("    {\n")
		for _, e := range entries {
			b.WriteString(fmt.Sprintf("        %q = %s\n", e.key, e.expr))
		}
		b.WriteString("    }\n")
	}
	b.WriteString("}\n")
	return b.String()
}

// kclConfigValueExpr renders the KCL expression that reads field f off the
// typed AppConfig receiver `recv` as a STRING (env values are strings).
// String-typed fields — including durations, which forge carries as strings
// ("30s") — inline directly; int/float scalars are wrapped in KCL's str(...)
// builtin.
//
// Bools are the exception: KCL's str(True) yields "True"/"False"
// (capitalized), but the runtime Go loader parses env values with
// strconv.ParseBool and the canonical lowercase form is "true"/"false". So a
// bool is projected as an explicit `"true" if c.<field> else "false"`
// conditional to emit the lowercase form, NOT str(...).
//
// This reuses kclTypeForProtoConfig so the str/non-str decision stays
// identical to the schema emitter's type mapping.
func kclConfigValueExpr(f ConfigField, recv string) string {
	ref := recv + "." + f.Name
	switch kclTypeForProtoConfig(f) {
	case "str":
		return ref
	case "bool":
		return `"true" if ` + ref + ` else "false"`
	default:
		return "str(" + ref + ")"
	}
}
