package codegen

import (
	"encoding/json"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// TestGenerateConfigProjectionKCL_ExactBlock pins the full emitted output
// for the representative field set (reused from the Phase-1 test): a mix of
// non-sensitive string/int/bool/duration/float fields plus one required
// sensitive string. It asserts the exact projection functions, which
// implicitly covers every branch (from_secret vs from_config, str vs str(...)).
func TestGenerateConfigProjectionKCL_ExactBlock(t *testing.T) {
	got, err := GenerateConfigProjectionKCL(representativeConfigFields())
	if err != nil {
		t.Fatalf("GenerateConfigProjectionKCL: %v", err)
	}

	want := "# Code generated by forge. DO NOT EDIT.\n" +
		"# Config projection functions (typed AppConfig -> {str: forge.EnvSource} + forge.ConfigMap) projected from proto/config/v1/config.proto — add or change fields in the PROTO, never here.\n" +
		"\n" +
		"import forge\n" +
		"import config_schema\n" +
		"\n" +
		"# appConfigEnvMap projects a typed AppConfig into the agnostic-core env\n" +
		"# MAP — one forge.EnvSource per field that declares an env_var, keyed by\n" +
		"# ENV_VAR name. A service merges it with `|`: `appConfigEnvMap(cfg, cm) | {…}`.\n" +
		"appConfigEnvMap = lambda c: config_schema.AppConfig, configMapName: str -> {str: forge.EnvSource} {\n" +
		"    {\n" +
		"        \"LOG_LEVEL\" = {from_config = {name = configMapName, key = \"LOG_LEVEL\"}}\n" +
		"        \"PORT\" = {from_config = {name = configMapName, key = \"PORT\"}}\n" +
		"        \"CORS_ALLOW_CREDENTIALS\" = {from_config = {name = configMapName, key = \"CORS_ALLOW_CREDENTIALS\"}}\n" +
		"        \"DATABASE_URL\" = {from_secret = {name = c.database_url.name, key = c.database_url.key}}\n" +
		"        \"SHUTDOWN_TIMEOUT\" = {from_config = {name = configMapName, key = \"SHUTDOWN_TIMEOUT\"}}\n" +
		"        \"SAMPLE_RATE\" = {from_config = {name = configMapName, key = \"SAMPLE_RATE\"}}\n" +
		"    }\n" +
		"}\n" +
		"\n" +
		"# appConfigConfigMap projects the NON-sensitive fields of a typed\n" +
		"# AppConfig into the per-env ConfigMap the env map above references.\n" +
		"appConfigConfigMap = lambda c: config_schema.AppConfig, configMapName: str -> forge.ConfigMap {\n" +
		"    forge.ConfigMap {\n" +
		"        name = configMapName\n" +
		"        data = {\n" +
		"            \"LOG_LEVEL\" = c.log_level\n" +
		"            \"PORT\" = str(c.port)\n" +
		"            \"CORS_ALLOW_CREDENTIALS\" = \"true\" if c.cors_allow_credentials else \"false\"\n" +
		"            \"SHUTDOWN_TIMEOUT\" = c.shutdown_timeout\n" +
		"            \"SAMPLE_RATE\" = str(c.sample_rate)\n" +
		"        }\n" +
		"    }\n" +
		"}\n"

	if got != want {
		t.Fatalf("projection mismatch\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

// TestGenerateConfigProjectionKCL_SensitiveBranch isolates the sensitive
// path: a from_secret channel whose name/key read off the typed
// ConfigSecretRef on the AppConfig value, keyed by the env_var, and NO
// config-map entry for the field.
func TestGenerateConfigProjectionKCL_SensitiveBranch(t *testing.T) {
	fields := []ConfigField{
		{Name: "api_key", ProtoType: "string", GoType: "string", EnvVar: "API_KEY", Sensitive: true, Required: true},
	}
	got, err := GenerateConfigProjectionKCL(fields)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(got, `"API_KEY" = {from_secret = {name = c.api_key.name, key = c.api_key.key}}`) {
		t.Fatalf("sensitive field should project to a from_secret channel read off the typed ConfigSecretRef:\n%s", got)
	}
	// A sensitive field must NOT appear in the ConfigMap data.
	if strings.Contains(got, `"API_KEY" = c.`) {
		t.Fatalf("sensitive field must not land in ConfigMap data:\n%s", got)
	}
	// With no non-sensitive fields the ConfigMap data map is empty.
	if !strings.Contains(got, "data = {}") {
		t.Fatalf("all-sensitive input should emit empty ConfigMap data:\n%s", got)
	}
}

// TestGenerateConfigProjectionKCL_ValueExpr pins the str-conversion rule
// per type: str/duration inline, int/float/bool wrapped in str(...).
func TestGenerateConfigProjectionKCL_ValueExpr(t *testing.T) {
	cases := []struct {
		f    ConfigField
		want string
	}{
		{ConfigField{Name: "log_level", ProtoType: "string"}, "c.log_level"},
		{ConfigField{Name: "port", ProtoType: "int32"}, "str(c.port)"},
		{ConfigField{Name: "rate", ProtoType: "double"}, "str(c.rate)"},
		{ConfigField{Name: "enabled", ProtoType: "bool"}, `"true" if c.enabled else "false"`},
		{ConfigField{Name: "timeout", ProtoType: "google.protobuf.Duration"}, "c.timeout"},
		// Real duration-leaf shape from the descriptor extractor.
		{ConfigField{Name: "drain", ProtoType: "message", GoType: "string"}, "c.drain"},
	}
	for _, c := range cases {
		if got := kclConfigValueExpr(c.f, "c"); got != c.want {
			t.Errorf("kclConfigValueExpr(%+v) = %q, want %q", c.f, got, c.want)
		}
	}
}

// TestGenerateConfigProjectionKCL_SkipsEmptyEnvVar ensures fields with no
// env_var (component block-references, unbound fields) are omitted from
// BOTH functions — matching the runtime loader and the Go projector.
func TestGenerateConfigProjectionKCL_SkipsEmptyEnvVar(t *testing.T) {
	fields := []ConfigField{
		{Name: "port", ProtoType: "int32", EnvVar: "PORT"},
		{Name: "trader", ProtoType: "message", MessageType: "TraderConfig"}, // block ref, no env_var
		{Name: "unbound", ProtoType: "string"},                             // no env_var at all
	}
	got, err := GenerateConfigProjectionKCL(fields)
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(got, "trader") || strings.Contains(got, "unbound") {
		t.Fatalf("fields without env_var must be skipped:\n%s", got)
	}
	if !strings.Contains(got, `"PORT" = {from_config = {name = configMapName, key = "PORT"}}`) {
		t.Fatalf("the env-bound field must still be projected:\n%s", got)
	}
}

// TestGenerateConfigProjectionKCL_EmptyFields covers the degenerate input:
// no fields at all yields both functions with empty list / empty data, so
// the emitted KCL still compiles.
func TestGenerateConfigProjectionKCL_EmptyFields(t *testing.T) {
	got, err := GenerateConfigProjectionKCL(nil)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(got, "appConfigEnvMap = lambda") || !strings.Contains(got, "appConfigConfigMap = lambda") {
		t.Fatalf("both lambdas must be emitted even with no fields:\n%s", got)
	}
	if !strings.Contains(got, "    {}\n") {
		t.Fatalf("empty field set should emit an empty EnvSource map:\n%s", got)
	}
	if !strings.Contains(got, "data = {}") {
		t.Fatalf("empty field set should emit an empty ConfigMap data map:\n%s", got)
	}
}

// forgeKCLModuleRoot walks up from the test's cwd (internal/codegen) to the
// repo root and returns the in-tree kcl/ module path, so the e2e proof wires
// `forge = { path = <root> }` regardless of where `go test` is invoked from.
func forgeKCLModuleRoot(t *testing.T) string {
	t.Helper()
	wd, err := os.Getwd()
	if err != nil {
		t.Fatalf("Getwd: %v", err)
	}
	dir := wd
	for i := 0; i < 6; i++ {
		if _, err := os.Stat(filepath.Join(dir, "kcl", "kcl.mod")); err == nil {
			return filepath.Join(dir, "kcl")
		}
		dir = filepath.Dir(dir)
	}
	t.Fatalf("could not locate kcl/ module root from cwd %s", wd)
	return ""
}

// TestGenerateConfigProjectionKCL_EndToEndEnvMap is the hermetic e2e proof:
// it assembles a synthetic AppConfig (a non-sensitive string, a non-sensitive
// bool, and a required sensitive string) from the REAL schema + projection
// generators, has an agnostic `schema Svc(forge.Service)` consume the env map
// the idiomatic way — config first, service extras merged/overriding via
// native map-merge `|` — renders it through `Bundle.workloads`, and asserts
// against the rendered Deployment that:
//   - the sensitive field lowers to a secretKeyRef,
//   - a non-sensitive field lowers to a configMapKeyRef,
//   - the service's own EXTRA env var is present, and
//   - the service's override of a config key WINS (map-merge last-wins),
//     flipping that var from a configMapKeyRef to an inline value.
//
// This exercises the generator OUTPUT end-to-end through the forge kcl module,
// with no dependency on control-plane's (blocked) `forge generate`. Skips when
// kcl is not on PATH.
func TestGenerateConfigProjectionKCL_EndToEndEnvMap(t *testing.T) {
	if _, err := exec.LookPath("kcl"); err != nil {
		t.Skip("kcl not on PATH; skipping env-map e2e proof")
	}

	fields := []ConfigField{
		{Name: "log_level", ProtoType: "string", GoType: "string", EnvVar: "LOG_LEVEL", DefaultValue: "info"},
		{Name: "debug_mode", ProtoType: "bool", GoType: "bool", EnvVar: "DEBUG_MODE", DefaultValue: "false"},
		{Name: "api_key", ProtoType: "string", GoType: "string", EnvVar: "API_KEY", Sensitive: true, Required: true},
	}

	schema, err := GenerateConfigSchemaKCL(fields, "proj")
	if err != nil {
		t.Fatal(err)
	}
	proj, err := GenerateConfigProjectionKCL(fields)
	if err != nil {
		t.Fatal(err)
	}

	root := forgeKCLModuleRoot(t)
	dir := t.TempDir()
	write := func(name, body string) {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
	}

	write("kcl.mod", "[package]\nname = \"envmap_proof\"\nedition = \"v0.11.0\"\nversion = \"0.1.0\"\n\n[dependencies]\nforge = { path = \""+root+"\" }\n")
	// The schema module MUST be named config_schema.k — the projection/config
	// files `import config_schema` by that stem.
	write("config_schema.k", schema)
	write("config_projection.k", proj)
	// A per-env AppConfig instance; log_level overridden to prove the value
	// flows, api_key keeps the default-backend ConfigSecretRef.
	write("config.k", "import config_schema\n\napp_config = config_schema.AppConfig {\n    log_level = \"debug\"\n}\n")

	// The consuming service: env = config map | service extras (last-wins).
	// "EXTRA" is a service-only var; "LOG_LEVEL" collides with a config key
	// and must WIN, flipping from configMapKeyRef to an inline value.
	main := `import forge

schema Svc(forge.Service):
    name: str = "demo"
    image: str = "demo-image"
    ports: [int] = [8080]

_svc = Svc {
    env = appConfigEnvMap(app_config, "cm") | {
        "EXTRA" = {value = "extra-val"}
        "LOG_LEVEL" = {value = "override-wins"}
    }
}

_target = forge.ClusterTarget {
    cluster = "c"
    namespace = "ns"
    registry = "reg"
    platform = "amd64"
}
_bundle = forge.Bundle {
    cluster_target = _target
    workloads = [_svc]
}
manifests = forge.render_manifests(_bundle, "v1", {}, False)
_dep = [m for m in manifests if m.kind == "Deployment"][0]
_ctr = _dep.spec.template.spec.containers[0]
_env = {e.name: e for e in _ctr.env}

# sensitive config field -> secretKeyRef (reads the typed ConfigSecretRef).
assert_secret = _env["API_KEY"].valueFrom.secretKeyRef == {name = "proj-secrets", key = "api_key"}
# non-sensitive config field -> configMapKeyRef.
assert_config = _env["DEBUG_MODE"].valueFrom.configMapKeyRef == {name = "cm", key = "DEBUG_MODE"}
# the service's own EXTRA env var survives the merge.
assert_extra = _env["EXTRA"].value == "extra-val"
# the service override of a config key WINS (map-merge last-wins) ...
assert_override = _env["LOG_LEVEL"].value == "override-wins"
# ... flipping it from a configMapKeyRef to an inline value channel.
assert_override_channel = "valueFrom" not in _env["LOG_LEVEL"]
`
	write("main.k", main)

	cmd := exec.CommandContext(t.Context(), "kcl", "run", ".", "--format", "json")
	cmd.Dir = dir
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("kcl run failed: %v\n%s", err, out)
	}
	var parsed map[string]any
	if err := json.Unmarshal(out, &parsed); err != nil {
		t.Fatalf("unmarshal kcl json: %v\n%s", err, out)
	}
	var sawAssert bool
	for k, v := range parsed {
		if !strings.HasPrefix(k, "assert_") {
			continue
		}
		sawAssert = true
		b, ok := v.(bool)
		if !ok {
			t.Errorf("identifier %q not a bool: %v", k, v)
			continue
		}
		if !b {
			t.Errorf("assertion %q is false", k)
		}
	}
	if !sawAssert {
		t.Fatalf("no assert_* identifiers found in kcl output:\n%s", out)
	}
}
