package codegen

import (
	"strings"
	"testing"
)

// TestGenerateConfigProjectionKCL_ExactBlock pins the full emitted output
// for the representative field set (reused from the Phase-1 test): a mix of
// non-sensitive string/int/bool/duration/float fields plus one required
// sensitive string. It asserts the exact projection functions, which
// implicitly covers every branch (secret vs config_map, str vs str(...)).
func TestGenerateConfigProjectionKCL_ExactBlock(t *testing.T) {
	got, err := GenerateConfigProjectionKCL(representativeConfigFields())
	if err != nil {
		t.Fatalf("GenerateConfigProjectionKCL: %v", err)
	}

	want := "# Code generated by forge. DO NOT EDIT.\n" +
		"# Config projection functions (typed AppConfig -> [forge.EnvVar] + forge.ConfigMap) projected from proto/config/v1/config.proto — add or change fields in the PROTO, never here.\n" +
		"\n" +
		"import forge\n" +
		"import config_schema\n" +
		"\n" +
		"# appConfigEnvVars projects a typed AppConfig into the deployment's\n" +
		"# env_vars — one forge.EnvVar per field that declares an env_var.\n" +
		"appConfigEnvVars = lambda c: config_schema.AppConfig, secretName: str, configMapName: str -> [forge.EnvVar] {\n" +
		"    [\n" +
		"        forge.EnvVar { name = \"LOG_LEVEL\", config_map_ref = configMapName, config_map_key = \"LOG_LEVEL\" }\n" +
		"        forge.EnvVar { name = \"PORT\", config_map_ref = configMapName, config_map_key = \"PORT\" }\n" +
		"        forge.EnvVar { name = \"CORS_ALLOW_CREDENTIALS\", config_map_ref = configMapName, config_map_key = \"CORS_ALLOW_CREDENTIALS\" }\n" +
		"        forge.EnvVar { name = \"DATABASE_URL\", secret_ref = c.database_url.name, secret_key = c.database_url.key }\n" +
		"        forge.EnvVar { name = \"SHUTDOWN_TIMEOUT\", config_map_ref = configMapName, config_map_key = \"SHUTDOWN_TIMEOUT\" }\n" +
		"        forge.EnvVar { name = \"SAMPLE_RATE\", config_map_ref = configMapName, config_map_key = \"SAMPLE_RATE\" }\n" +
		"    ]\n" +
		"}\n" +
		"\n" +
		"# appConfigConfigMap projects the NON-sensitive fields of a typed\n" +
		"# AppConfig into the per-env ConfigMap the EnvVars above reference.\n" +
		"appConfigConfigMap = lambda c: config_schema.AppConfig, configMapName: str -> forge.ConfigMap {\n" +
		"    forge.ConfigMap {\n" +
		"        name = configMapName\n" +
		"        data = {\n" +
		"            \"LOG_LEVEL\" = c.log_level\n" +
		"            \"PORT\" = str(c.port)\n" +
		"            \"CORS_ALLOW_CREDENTIALS\" = \"true\" if c.cors_allow_credentials else \"false\"\n" +
		"            \"SHUTDOWN_TIMEOUT\" = c.shutdown_timeout\n" +
		"            \"SAMPLE_RATE\" = str(c.sample_rate)\n" +
		"        }\n" +
		"    }\n" +
		"}\n"

	if got != want {
		t.Fatalf("projection mismatch\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

// TestGenerateConfigProjectionKCL_SensitiveBranch isolates the sensitive
// path: secret_ref bound to the secretName parameter, secret_key = the
// LOWERCASED env_var — matching deploy_config_gen.go:renderEnvVarEntry, and
// NO config_map entry for the field.
func TestGenerateConfigProjectionKCL_SensitiveBranch(t *testing.T) {
	fields := []ConfigField{
		{Name: "api_key", ProtoType: "string", GoType: "string", EnvVar: "API_KEY", Sensitive: true, Required: true},
	}
	got, err := GenerateConfigProjectionKCL(fields)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(got, `forge.EnvVar { name = "API_KEY", secret_ref = c.api_key.name, secret_key = c.api_key.key }`) {
		t.Fatalf("sensitive field should project to secret_ref/secret_key read off the typed ConfigSecretRef:\n%s", got)
	}
	// A sensitive field must NOT appear in the ConfigMap data.
	if strings.Contains(got, `"API_KEY" =`) {
		t.Fatalf("sensitive field must not land in ConfigMap data:\n%s", got)
	}
	// With no non-sensitive fields the ConfigMap data map is empty.
	if !strings.Contains(got, "data = {}") {
		t.Fatalf("all-sensitive input should emit empty ConfigMap data:\n%s", got)
	}
}

// TestGenerateConfigProjectionKCL_ValueExpr pins the str-conversion rule
// per type: str/duration inline, int/float/bool wrapped in str(...).
func TestGenerateConfigProjectionKCL_ValueExpr(t *testing.T) {
	cases := []struct {
		f    ConfigField
		want string
	}{
		{ConfigField{Name: "log_level", ProtoType: "string"}, "c.log_level"},
		{ConfigField{Name: "port", ProtoType: "int32"}, "str(c.port)"},
		{ConfigField{Name: "rate", ProtoType: "double"}, "str(c.rate)"},
		{ConfigField{Name: "enabled", ProtoType: "bool"}, `"true" if c.enabled else "false"`},
		{ConfigField{Name: "timeout", ProtoType: "google.protobuf.Duration"}, "c.timeout"},
		// Real duration-leaf shape from the descriptor extractor.
		{ConfigField{Name: "drain", ProtoType: "message", GoType: "string"}, "c.drain"},
	}
	for _, c := range cases {
		if got := kclConfigValueExpr(c.f, "c"); got != c.want {
			t.Errorf("kclConfigValueExpr(%+v) = %q, want %q", c.f, got, c.want)
		}
	}
}

// TestGenerateConfigProjectionKCL_SkipsEmptyEnvVar ensures fields with no
// env_var (component block-references, unbound fields) are omitted from
// BOTH functions — matching the runtime loader and the Go projector.
func TestGenerateConfigProjectionKCL_SkipsEmptyEnvVar(t *testing.T) {
	fields := []ConfigField{
		{Name: "port", ProtoType: "int32", EnvVar: "PORT"},
		{Name: "trader", ProtoType: "message", MessageType: "TraderConfig"}, // block ref, no env_var
		{Name: "unbound", ProtoType: "string"},                             // no env_var at all
	}
	got, err := GenerateConfigProjectionKCL(fields)
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(got, "trader") || strings.Contains(got, "unbound") {
		t.Fatalf("fields without env_var must be skipped:\n%s", got)
	}
	if !strings.Contains(got, `name = "PORT"`) {
		t.Fatalf("the env-bound field must still be projected:\n%s", got)
	}
}

// TestGenerateConfigProjectionKCL_EmptyFields covers the degenerate input:
// no fields at all yields both functions with empty list / empty data, so
// the emitted KCL still compiles.
func TestGenerateConfigProjectionKCL_EmptyFields(t *testing.T) {
	got, err := GenerateConfigProjectionKCL(nil)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(got, "appConfigEnvVars = lambda") || !strings.Contains(got, "appConfigConfigMap = lambda") {
		t.Fatalf("both lambdas must be emitted even with no fields:\n%s", got)
	}
	if !strings.Contains(got, "    []\n") {
		t.Fatalf("empty field set should emit an empty EnvVar list:\n%s", got)
	}
	if !strings.Contains(got, "data = {}") {
		t.Fatalf("empty field set should emit an empty ConfigMap data map:\n%s", got)
	}
}
