package codegen

import (
	"encoding/json"
	"strings"
	"testing"

	apiext "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// fixtureCRD builds a CRD exercising every construct the KCL lowering has to
// get right: nested objects, arrays of objects, arrays of scalars, enums,
// patterns with backslashes, numeric bounds, required lists, and the
// hyphenated x-kubernetes-* keys that MUST come out quoted.
func fixtureCRD() CRDDoc {
	str := func(extra func(*apiext.JSONSchemaProps)) apiext.JSONSchemaProps {
		p := apiext.JSONSchemaProps{Type: "string"}
		if extra != nil {
			extra(&p)
		}
		return p
	}
	i64 := func(min *float64) apiext.JSONSchemaProps {
		return apiext.JSONSchemaProps{Type: "integer", Format: "int64", Minimum: min}
	}
	one := 1.0

	return CRDDoc{
		Kind:   "Widget",
		Lambda: "widget_crd",
		CRD: apiext.CustomResourceDefinition{
			ObjectMeta: metav1.ObjectMeta{Name: "widgets.example.com"},
			Spec: apiext.CustomResourceDefinitionSpec{
				Group: "example.com",
				Names: apiext.CustomResourceDefinitionNames{
					Kind:       "Widget",
					ListKind:   "WidgetList",
					Plural:     "widgets",
					Singular:   "widget",
					ShortNames: []string{"wg"},
					Categories: []string{"example"},
				},
				Scope: apiext.NamespaceScoped,
				Versions: []apiext.CustomResourceDefinitionVersion{{
					Name:         "v1alpha1",
					Served:       true,
					Storage:      true,
					Subresources: &apiext.CustomResourceSubresources{Status: &apiext.CustomResourceSubresourceStatus{}},
					AdditionalPrinterColumns: []apiext.CustomResourceColumnDefinition{
						{Name: "Phase", Type: "string", JSONPath: ".status.phase"},
					},
					Schema: &apiext.CustomResourceValidation{
						OpenAPIV3Schema: &apiext.JSONSchemaProps{
							Type:     "object",
							Required: []string{"spec"},
							Properties: map[string]apiext.JSONSchemaProps{
								"apiVersion": str(nil),
								"kind":       str(nil),
								"metadata":   {Type: "object"},
								"spec": {
									Type:     "object",
									Required: []string{"name", "network"},
									Properties: map[string]apiext.JSONSchemaProps{
										"name": str(func(p *apiext.JSONSchemaProps) {
											p.MinLength = ptr(int64(1))
											p.MaxLength = ptr(int64(63))
											// A backslash-dense pattern: the
											// case that breaks naive quoting.
											p.Pattern = `^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]+)*$`
										}),
										"network": str(func(p *apiext.JSONSchemaProps) {
											p.Enum = []apiext.JSON{
												{Raw: []byte(`"public"`)},
												{Raw: []byte(`"private"`)},
											}
										}),
										"replicas": i64(&one),
										"ports": {
											Type:  "array",
											Items: &apiext.JSONSchemaPropsOrArray{Schema: &apiext.JSONSchemaProps{Type: "integer", Format: "int32"}},
										},
										"resources": {
											Type:     "object",
											Required: []string{"cpu"},
											Properties: map[string]apiext.JSONSchemaProps{
												"cpu": i64(&one),
											},
										},
									},
								},
								"status": {
									Type: "object",
									Properties: map[string]apiext.JSONSchemaProps{
										"conditions": {
											Type:         "array",
											XListType:    ptr("map"),
											XListMapKeys: []string{"type"},
											Items: &apiext.JSONSchemaPropsOrArray{Schema: &apiext.JSONSchemaProps{
												Type:     "object",
												Required: []string{"status", "type"},
												Properties: map[string]apiext.JSONSchemaProps{
													"type":   str(nil),
													"status": str(nil),
												},
											}},
										},
									},
								},
							},
						},
					},
				}},
			},
		},
	}
}

// TestGenerateCRDKCL_RendersValidStructure pins the generated module's shape:
// the DO-NOT-EDIT banner, one lambda per CRD with the expected name, and the
// quoting rules that a hand-rolled renderer gets wrong.
func TestGenerateCRDKCL_RendersValidStructure(t *testing.T) {
	out, err := GenerateCRDKCL([]CRDDoc{fixtureCRD()}, "v0.20.1")
	if err != nil {
		t.Fatalf("GenerateCRDKCL: %v", err)
	}

	for _, want := range []string{
		"# Code generated by forge. DO NOT EDIT.",
		"widget_crd = lambda -> any {",
		`apiVersion = "apiextensions.k8s.io/v1"`,
		`kind = "CustomResourceDefinition"`,
		`"controller-gen.kubebuilder.io/version" = "v0.20.1"`,
		// Hyphenated keys MUST be quoted or the module is a syntax error.
		`"x-kubernetes-list-type" = "map"`,
		`"x-kubernetes-list-map-keys" = [`,
		// KCL booleans are capitalised.
		"served = True",
		"storage = True",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("generated module missing %q\n--- output ---\n%s", want, out)
		}
	}

	// Integral numbers must not acquire a decimal point.
	if strings.Contains(out, "minimum = 1.0") {
		t.Errorf("integral minimum rendered as a float:\n%s", out)
	}
	if !strings.Contains(out, "minimum = 1") {
		t.Errorf("expected `minimum = 1` in output:\n%s", out)
	}

	// Server-owned fields must not appear in a manifest.
	if strings.Contains(out, "acceptedNames") || strings.Contains(out, "storedVersions") {
		t.Errorf("generated module leaked CRD .status (server-owned):\n%s", out)
	}
	if strings.Contains(out, "creationTimestamp = None") {
		t.Errorf("generated module leaked a null creationTimestamp:\n%s", out)
	}
}

// TestGenerateCRDKCL_PreservesRegexBackslashes is the case most likely to be
// silently wrong. A pattern that loses a backslash still renders, still
// installs, and then accepts or rejects the WRONG set of values — so it is
// pinned explicitly rather than left to the structural test above.
func TestGenerateCRDKCL_PreservesRegexBackslashes(t *testing.T) {
	out, err := GenerateCRDKCL([]CRDDoc{fixtureCRD()}, "v0.20.1")
	if err != nil {
		t.Fatalf("GenerateCRDKCL: %v", err)
	}

	// In the generated KCL source the backslash is escaped for the string
	// literal, so the bytes on disk are `\\.` and a KCL parse yields `\.`.
	const wantLiteral = `pattern = "^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]+)*$"`
	if !strings.Contains(out, wantLiteral) {
		t.Errorf("regex pattern not escaped as expected.\nwant literal: %s\n--- output ---\n%s", wantLiteral, out)
	}
}

// TestGenerateCRDKCL_Idempotent guards the property that makes a
// checksum-tracked generated file usable: the same input must produce
// byte-identical output every time. Map iteration order is the hazard, so the
// assertion is repeated enough times to make an unsorted walk essentially
// certain to show up.
func TestGenerateCRDKCL_Idempotent(t *testing.T) {
	first, err := GenerateCRDKCL([]CRDDoc{fixtureCRD()}, "v0.20.1")
	if err != nil {
		t.Fatalf("GenerateCRDKCL: %v", err)
	}
	for i := 0; i < 25; i++ {
		again, err := GenerateCRDKCL([]CRDDoc{fixtureCRD()}, "v0.20.1")
		if err != nil {
			t.Fatalf("GenerateCRDKCL (run %d): %v", i, err)
		}
		if again != first {
			t.Fatalf("output is not deterministic (run %d differs)", i)
		}
	}
}

// TestGenerateCRDKCL_OrdersCRDsDeterministically pins that the ORDER of
// lambdas does not depend on the caller's slice order — the loader's kind
// iteration comes off a map upstream.
func TestGenerateCRDKCL_OrdersCRDsDeterministically(t *testing.T) {
	a := fixtureCRD()
	b := fixtureCRD()
	b.Kind, b.Lambda = "Alpha", "alpha_crd"
	b.CRD.Spec.Names.Kind = "Alpha"

	forward, err := GenerateCRDKCL([]CRDDoc{a, b}, "v0.20.1")
	if err != nil {
		t.Fatalf("GenerateCRDKCL: %v", err)
	}
	reversed, err := GenerateCRDKCL([]CRDDoc{b, a}, "v0.20.1")
	if err != nil {
		t.Fatalf("GenerateCRDKCL: %v", err)
	}
	if forward != reversed {
		t.Error("lambda order depends on input order; output must be sorted by kind")
	}
	if strings.Index(forward, "alpha_crd") > strings.Index(forward, "widget_crd") {
		t.Error("CRDs are not sorted by kind")
	}
}

// TestGenerateCRDKCL_EmptyInputIsAnError: emitting an empty module would
// silently uninstall every CRD in a project's render. Callers must skip the
// step instead, so an empty slice is a programming error and says so.
func TestGenerateCRDKCL_EmptyInputIsAnError(t *testing.T) {
	if _, err := GenerateCRDKCL(nil, "v0.20.1"); err == nil {
		t.Fatal("expected an error for an empty CRD set, got nil")
	}
}

func TestCRDLambdaName(t *testing.T) {
	for kind, want := range map[string]string{
		"SimpleBackend":   "simplebackend_crd",
		"ManagedDatabase": "manageddatabase_crd",
		"Workspace":       "workspace_crd",
		"ImageBuild":      "imagebuild_crd",
		"StaticSite":      "staticsite_crd",
	} {
		if got := CRDLambdaName(kind); got != want {
			t.Errorf("CRDLambdaName(%q) = %q, want %q", kind, got, want)
		}
	}
}

// TestRenderKCLValue_Scalars pins the scalar spellings that differ from JSON.
func TestRenderKCLValue_Scalars(t *testing.T) {
	cases := []struct {
		in   any
		want string
	}{
		{true, "True"},
		{false, "False"},
		{nil, "None"},
		{float64(3), "3"},
		{float64(65535), "65535"},
		{"plain", `"plain"`},
		{map[string]any{}, "{}"},
		{[]any{}, "[]"},
	}
	for _, c := range cases {
		if got := renderKCLValue(c.in, 0); got != c.want {
			t.Errorf("renderKCLValue(%#v) = %q, want %q", c.in, got, c.want)
		}
	}
}

// TestKCLKey_QuotesNonIdentifiers pins the rule whose failure is a syntax
// error rather than a subtle wrong value — worth its own test because every
// x-kubernetes-* key depends on it.
func TestKCLKey_QuotesNonIdentifiers(t *testing.T) {
	bare := []string{"type", "metadata", "x_underscored", "a1"}
	quoted := []string{"x-kubernetes-list-type", "controller-gen.kubebuilder.io/version", "1leading"}

	for _, k := range bare {
		if got := kclKey(k); got != k {
			t.Errorf("kclKey(%q) = %q, want it unquoted", k, got)
		}
	}
	for _, k := range quoted {
		if got := kclKey(k); !strings.HasPrefix(got, `"`) {
			t.Errorf("kclKey(%q) = %q, want it quoted", k, got)
		}
	}
}

// TestCrdToKCLValue_JSONRoundTripIsFaithful verifies the generic tree the
// renderer walks still carries the schema keywords, i.e. that dropping .status
// and creationTimestamp did not take anything else with it.
func TestCrdToKCLValue_JSONRoundTripIsFaithful(t *testing.T) {
	obj, err := crdToKCLValue(fixtureCRD(), "v0.20.1")
	if err != nil {
		t.Fatalf("crdToKCLValue: %v", err)
	}
	b, err := json.Marshal(obj)
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	s := string(b)
	for _, want := range []string{
		`"minLength":1`, `"maxLength":63`, `"enum":["public","private"]`,
		`"x-kubernetes-list-type":"map"`, `"required":["name","network"]`,
	} {
		if !strings.Contains(s, want) {
			t.Errorf("round-tripped CRD lost %s\n%s", want, s)
		}
	}
	if strings.Contains(s, `"status"`) && strings.Contains(s, "acceptedNames") {
		t.Errorf("CRD .status survived the projection:\n%s", s)
	}
}
