package codegen

import (
	"strings"
	"testing"
)

func TestGenerateFrontendConfigTS_Shape(t *testing.T) {
	out, err := GenerateFrontendConfigTS(sampleFrontendConfig(), "demo", "nextjs")
	if err != nil {
		t.Fatalf("generate: %v", err)
	}

	for _, want := range []string{
		"Code generated by forge. DO NOT EDIT.",
		`import { z } from "zod";`,
		"export const configSchema = z.object({",
		"export type WebConfig = z.infer<typeof configSchema>;",
		"export function loadConfig(): WebConfig {",
		"export function resetConfigForTests(): void {",
		// Keyed by env_var, so one spelling spans proto/KCL/JS/TS.
		`API_URL: z.string().default("http://localhost:8080")`,
		// Required with no default must reject the empty string a KCL
		// type-zero would otherwise supply.
		`OIDC_ISSUER: z.string().min(1, "required but empty")`,
		`OTEL_ENDPOINT: z.string().default("")`,
		"window.__FORGE_CONFIG__",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("generated TS missing %q:\n%s", want, out)
		}
	}

	// The module must steer readers away from the mechanism it replaces.
	if !strings.Contains(out, "process.env") || !strings.Contains(out, "Do not reach for") {
		t.Errorf("generated TS should warn against process.env:\n%s", out)
	}
	// And it must never mention a dotenv file as a source.
	for _, forbidden := range []string{".env.local", ".env.dev", "dotenv"} {
		if strings.Contains(out, forbidden) {
			t.Errorf("generated TS must not reference %q:\n%s", forbidden, out)
		}
	}
}

// A number field has to survive both transports: a JSON number from
// config.js and a string from a server-side process.env read.
func TestGenerateFrontendConfigTS_NumericFieldCoerces(t *testing.T) {
	fc := FrontendConfig{
		Frontend: "web", MessageName: "WebConfig",
		Fields: []ConfigField{{
			Name: "poll_interval_ms", GoName: "PollIntervalMs", GoType: "int32",
			ProtoType: "int32", EnvVar: "POLL_INTERVAL_MS", DefaultValue: "5000",
		}},
	}
	out, err := GenerateFrontendConfigTS(fc, "demo", "nextjs")
	if err != nil {
		t.Fatalf("generate: %v", err)
	}
	if !strings.Contains(out, "POLL_INTERVAL_MS: z.coerce.number().default(5000)") {
		t.Errorf("numeric field should coerce and carry its default:\n%s", out)
	}
}

// React Native has no server-render path, so the non-window branch must not
// emit process.env plumbing it would never use.
func TestGenerateFrontendConfigTS_ReactNativeHasNoServerBranch(t *testing.T) {
	out, err := GenerateFrontendConfigTS(sampleFrontendConfig(), "demo", "react-native")
	if err != nil {
		t.Fatalf("generate: %v", err)
	}
	if strings.Contains(out, "process.env[") {
		t.Errorf("react-native module should not read process.env:\n%s", out)
	}
}

func TestGenerateFrontendConfigJS_Shape(t *testing.T) {
	out := GenerateFrontendConfigJS("web", "prod", `{"API_URL":"https://api.example.com"}`)
	for _, want := range []string{
		"Code generated by forge. DO NOT EDIT.",
		`window.__FORGE_CONFIG__ = {"API_URL":"https://api.example.com"};`,
		"promoted between environments",
		"PUBLIC",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("generated config.js missing %q:\n%s", want, out)
		}
	}
}

// A proto description is prose written by a human, and prose about URLs
// routinely contains a glob: forge's OWN scaffolded config.proto describes the
// OIDC redirect URI with "http://localhost:*/auth/callback". Interpolated raw
// into a /** ... */ block, the `*/` in that URL CLOSES the comment and the rest
// of the sentence is parsed as TypeScript — 30 syntax errors in a file no user
// may edit, and `forge lint` failing its own freshly-scaffolded project on both
// the frontend lint and typecheck lanes.
//
// The comment delimiter has to be escaped, and the test names the real string
// that broke it rather than a synthetic one.
func TestGenerateFrontendConfigTS_EscapesCommentTerminatorInDescription(t *testing.T) {
	fc := FrontendConfig{
		Frontend: "web", MessageName: "WebConfig",
		Fields: []ConfigField{{
			Name: "oidc_redirect_uri", GoName: "OidcRedirectUri",
			GoType: "string", ProtoType: "string", EnvVar: "OIDC_REDIRECT_URI",
			Description: "forge registers http://localhost:*/auth/callback with the dev IdP. Never carry a wildcard to a real issuer.",
		}},
	}

	out, err := GenerateFrontendConfigTS(fc, "demo", "nextjs")
	if err != nil {
		t.Fatalf("generate: %v", err)
	}

	// The JSDoc block must contain no raw `*/` before its own terminator:
	// find the doc comment and assert it closes exactly once.
	start := strings.Index(out, "/** forge registers")
	if start < 0 {
		t.Fatalf("description was not emitted as a doc comment:\n%s", out)
	}
	body := out[start+len("/**") : start+len("/**")+strings.Index(out[start+len("/**"):], "\n")]
	if n := strings.Count(body, "*/"); n != 1 {
		t.Errorf("doc comment closes %d times, want exactly 1 (an inner %q terminates it early):\n%s", n, "*/", body)
	}

	// The text must survive readably — escaping may not eat the URL.
	if !strings.Contains(out, "localhost:*") || !strings.Contains(out, "auth/callback") {
		t.Errorf("escaping destroyed the described URL:\n%s", out)
	}
}
