package codegen

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestGenerateK3dPorts_Empty_NoFile asserts that an empty listener
// slice writes nothing — the pipeline gate is responsible for
// removing stale files, not this function.
func TestGenerateK3dPorts_Empty_NoFile(t *testing.T) {
	tmp := t.TempDir()
	if err := GenerateK3dPorts(K3dPortsGenInput{GenContext: GenContext{ProjectDir: tmp}}); err != nil {
		t.Fatalf("Generate: %v", err)
	}
	if _, err := os.Stat(filepath.Join(tmp, "deploy", "k3d-ports.yaml")); !os.IsNotExist(err) {
		t.Fatalf("expected no file written for empty input, got err=%v", err)
	}
}

// TestGenerateK3dPorts_RendersSorted asserts:
//   - one ports entry per listener
//   - sorted by port number ascending
//   - each entry has nodeFilters: loadbalancer
//   - a comment line ties each entry back to gateway/listener name
func TestGenerateK3dPorts_RendersSorted(t *testing.T) {
	tmp := t.TempDir()
	in := K3dPortsGenInput{
		GenContext: GenContext{ProjectDir: tmp},
		Listeners: []K3dListener{
			{GatewayName: "public", ListenerName: "grpc", Port: 19190},
			{GatewayName: "public", ListenerName: "http", Port: 18080},
			{GatewayName: "internal", ListenerName: "http", Port: 18180},
		},
	}
	if err := GenerateK3dPorts(in); err != nil {
		t.Fatalf("Generate: %v", err)
	}
	raw, err := os.ReadFile(filepath.Join(tmp, "deploy", "k3d-ports.yaml"))
	if err != nil {
		t.Fatalf("read: %v", err)
	}
	got := string(raw)

	wantContains := []string{
		"# Generated by `forge generate`",
		"  # public/http\n  - port: 18080:18080\n    nodeFilters:\n      - loadbalancer\n",
		"  # internal/http\n  - port: 18180:18180\n",
		"  # public/grpc\n  - port: 19190:19190\n",
	}
	for _, s := range wantContains {
		if !strings.Contains(got, s) {
			t.Errorf("output missing expected fragment %q\nfull output:\n%s", s, got)
		}
	}

	// Sort order: 18080 must appear before 18180 before 19190.
	pos := func(needle string) int { return strings.Index(got, needle) }
	if pos("18080:18080") > pos("18180:18180") || pos("18180:18180") > pos("19190:19190") {
		t.Errorf("ports not sorted ascending:\n%s", got)
	}
}

// TestGenerateK3dPorts_DedupSamePort covers the edge case where two
// listeners declare the same host port. The fragment must emit only
// one mapping (the first by sort order) and a comment flagging the
// skipped duplicate so the user knows why their second listener
// isn't exposed.
func TestGenerateK3dPorts_DedupSamePort(t *testing.T) {
	tmp := t.TempDir()
	in := K3dPortsGenInput{
		GenContext: GenContext{ProjectDir: tmp},
		Listeners: []K3dListener{
			{GatewayName: "public", ListenerName: "http", Port: 18080},
			{GatewayName: "internal", ListenerName: "http", Port: 18080},
		},
	}
	if err := GenerateK3dPorts(in); err != nil {
		t.Fatalf("Generate: %v", err)
	}
	raw, _ := os.ReadFile(filepath.Join(tmp, "deploy", "k3d-ports.yaml"))
	got := string(raw)
	if strings.Count(got, "- port: 18080:18080") != 1 {
		t.Errorf("expected exactly one port-18080 entry, got:\n%s", got)
	}
	if !strings.Contains(got, "port 18080 declared by multiple listeners") {
		t.Errorf("expected duplicate-port comment, got:\n%s", got)
	}
}

// TestGenerateK3dPorts_Determinism pins the byte-stable contract —
// running twice with the same input produces identical output. The
// pipeline's `--check` mode depends on this.
func TestGenerateK3dPorts_Determinism(t *testing.T) {
	tmp1, tmp2 := t.TempDir(), t.TempDir()
	in := []K3dListener{
		{GatewayName: "public", ListenerName: "http", Port: 18080},
		{GatewayName: "public", ListenerName: "grpc", Port: 19190},
	}
	if err := GenerateK3dPorts(K3dPortsGenInput{GenContext: GenContext{ProjectDir: tmp1}, Listeners: in}); err != nil {
		t.Fatalf("first: %v", err)
	}
	if err := GenerateK3dPorts(K3dPortsGenInput{GenContext: GenContext{ProjectDir: tmp2}, Listeners: in}); err != nil {
		t.Fatalf("second: %v", err)
	}
	a, _ := os.ReadFile(filepath.Join(tmp1, "deploy", "k3d-ports.yaml"))
	b, _ := os.ReadFile(filepath.Join(tmp2, "deploy", "k3d-ports.yaml"))
	if string(a) != string(b) {
		t.Errorf("byte mismatch:\n--- a ---\n%s\n--- b ---\n%s", a, b)
	}
}

// TestGenerateK3dPorts_DerivationCompleteness is the load-bearing
// invariant: the host-port SET the fragment maps must equal the host-port
// SET of the rendered Gateway listeners fed in — EVERY listener port gets a
// mapping, and the fragment invents none. This is what guarantees there is
// "nothing to check": if a Gateway listener renders a port (here, a dev
// `controller` listener on 28090 alongside http 28080 / grpc 29190), the
// k3d host-port mapping is derived from the SAME set, so it can never be
// silently dropped the way a hand-maintained static port list can.
func TestGenerateK3dPorts_DerivationCompleteness(t *testing.T) {
	tmp := t.TempDir()
	listeners := []K3dListener{
		{GatewayName: "public", ListenerName: "http", Port: 28080},
		{GatewayName: "public", ListenerName: "grpc", Port: 29190},
		// The transform-added controller listener — the exact one that
		// used to be missing from the fragment, leaving :28090 unmapped.
		{GatewayName: "public", ListenerName: "controller", Port: 28090},
	}
	if err := GenerateK3dPorts(K3dPortsGenInput{
		GenContext: GenContext{ProjectDir: tmp},
		Listeners:  listeners,
	}); err != nil {
		t.Fatalf("Generate: %v", err)
	}
	raw, err := os.ReadFile(filepath.Join(tmp, "deploy", "k3d-ports.yaml"))
	if err != nil {
		t.Fatalf("read: %v", err)
	}

	// The set of host ports the listeners declare...
	want := map[int]bool{}
	for _, l := range listeners {
		want[l.Port] = true
	}
	// ...must EQUAL the set of host ports the fragment maps.
	got := parseFragmentHostPorts(t, string(raw))

	for p := range want {
		if !got[p] {
			t.Errorf("listener port %d rendered but NOT mapped in k3d-ports.yaml — derivation is incomplete:\n%s", p, raw)
		}
	}
	for p := range got {
		if !want[p] {
			t.Errorf("k3d-ports.yaml maps host port %d that no listener declares — derivation invented a port:\n%s", p, raw)
		}
	}
	if len(want) != len(got) {
		t.Errorf("derived host-port set (%d) != rendered listener port set (%d)\nwant=%v got=%v\n%s",
			len(got), len(want), want, got, raw)
	}
}

// parseFragmentHostPorts pulls every `- port: <host>:<cluster>` host port
// out of a rendered k3d-ports.yaml fragment.
func parseFragmentHostPorts(t *testing.T, body string) map[int]bool {
	t.Helper()
	ports := map[int]bool{}
	for _, line := range strings.Split(body, "\n") {
		line = strings.TrimSpace(line)
		const prefix = "- port:"
		if !strings.HasPrefix(line, prefix) {
			continue
		}
		spec := strings.TrimSpace(strings.TrimPrefix(line, prefix))
		hostStr, _, ok := strings.Cut(spec, ":")
		if !ok {
			continue
		}
		var host int
		if _, err := fmt.Sscanf(hostStr, "%d", &host); err != nil {
			t.Fatalf("unparseable host port %q in line %q", hostStr, line)
		}
		ports[host] = true
	}
	return ports
}

// TestRemoveK3dPorts covers the stale-file cleanup path used by the
// pipeline gate when ingress is on but the dev env has no gateways
// (e.g. user disabled all routes).
func TestRemoveK3dPorts(t *testing.T) {
	tmp := t.TempDir()
	path := filepath.Join(tmp, "deploy", "k3d-ports.yaml")
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte("stale"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := RemoveK3dPorts(tmp); err != nil {
		t.Fatalf("Remove: %v", err)
	}
	if _, err := os.Stat(path); !os.IsNotExist(err) {
		t.Errorf("file not removed: %v", err)
	}
	// Idempotent: calling on an absent file is fine.
	if err := RemoveK3dPorts(tmp); err != nil {
		t.Errorf("second remove (no file): %v", err)
	}
}
