// Package codegen — ingress_k3d_gen.go writes deploy/k3d-ports.yaml,
// a small YAML fragment carrying the host→cluster port mappings the
// k3d loadbalancer needs to expose each Gateway listener.
//
// The fragment is derived from the dev environment's KCL ingress
// topology, NOT hand-written. `forge cluster up` merges this
// fragment into the user-owned deploy/k3d.yaml at create time so
// k3d's ports block reflects the current gateway listeners. Keeping
// the merge at cluster-up time (rather than baking ports into
// k3d.yaml directly) lets the user edit `deploy/k3d.yaml` freely
// without forge clobbering it, while still keeping the listener
// ports in lockstep with whatever the project's Gateway resources
// declare.
//
// Shape (one entry per listener across all dev-env gateways):
//
//	# Generated by `forge generate`. Do not edit — regenerated from
//	# deploy/kcl/dev/ingress.k.
//	ports:
//	  - port: 18080:18080
//	    nodeFilters: [loadbalancer]
//	  - port: 19190:19190
//	    nodeFilters: [loadbalancer]
//
// Empty gateway list → no file written. Stale file from a previous
// generate (e.g. ingress feature was just disabled) is cleaned up by
// the caller, not here.
package codegen

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// K3dListener is the minimal slice of a Gateway listener that the
// k3d-ports fragment needs. Callers project from
// internal/cli.GatewayEntity.Listeners → []K3dListener so this
// package stays free of the cli dependency.
type K3dListener struct {
	GatewayName  string // for de-dup logs and comment lines
	ListenerName string
	Port         int
}

// K3dPortsGenInput is the per-project input for [GenerateK3dPorts].
// Embeds GenContext for ProjectDir + Checksums (ModulePath is unused —
// this fragment carries no Go imports).
type K3dPortsGenInput struct {
	GenContext

	Listeners []K3dListener // every dev-env listener, in any order

	// MaxStacks is the parallel-dev-stack ceiling
	// (config.DevStackConfig.EffectiveMaxStacks). The fragment maps the
	// listener ports for EVERY reachable stack, not just the default one:
	// stack N binds listener port P at P + N*BlockSize, and k3d can only
	// forward a host port it mapped at cluster-CREATE time.
	//
	// Why this belongs here. The block-0 ports were derived from the render
	// while blocks 1..N-1 were a hand-maintained ports: list in the user's
	// k3d.yaml, under a comment that had to be updated by hand whenever the
	// ceiling moved. That is the same fact written in two places, and the two
	// silently disagreed: nothing checked the hand-written range against the
	// allocator, so a worktree past the last hand-mapped block allocated
	// cleanly and then failed as "gateway unreachable", nowhere near the
	// cause. Deriving the whole range from the ceiling makes the pre-map and
	// the allocator two views of ONE number.
	//
	// Zero or one means only the default stack — emit block 0 alone, which is
	// exactly the historical output.
	MaxStacks int

	// BlockSize is the port-number distance between adjacent stacks
	// (config.DevStackConfig.EffectiveBlockSize). Zero falls back to 100, the
	// value this arithmetic was hardcoded to before it was configurable.
	BlockSize int
}

// GenerateK3dPorts writes deploy/k3d-ports.yaml. Returns nil when
// there are no listeners — the caller is expected to ensure a stale
// file is removed in that case (handled in the pipeline gate, not
// here).
//
// The function is idempotent: same input → byte-identical output.
// Listeners are sorted by (port, gateway, name) so a hand-rearranged
// ingress.k doesn't produce a no-op diff.
func GenerateK3dPorts(in K3dPortsGenInput) error {
	if in.ProjectDir == "" {
		return fmt.Errorf("k3d ports gen: ProjectDir required")
	}
	if len(in.Listeners) == 0 {
		return nil
	}

	// Stable sort: by port primarily, then by gateway+listener name as
	// a tiebreaker. Ports must be unique within a single gateway by
	// schema check, but two gateways might use distinct ports — the
	// sort keeps output deterministic regardless of input order.
	sorted := make([]K3dListener, len(in.Listeners))
	copy(sorted, in.Listeners)
	sort.SliceStable(sorted, func(i, j int) bool {
		if sorted[i].Port != sorted[j].Port {
			return sorted[i].Port < sorted[j].Port
		}
		if sorted[i].GatewayName != sorted[j].GatewayName {
			return sorted[i].GatewayName < sorted[j].GatewayName
		}
		return sorted[i].ListenerName < sorted[j].ListenerName
	})

	// Dedup by port. Two gateways binding the same host port is a
	// k3d-side error (port already mapped) — log via comment and pick
	// the first.
	blockSize := in.BlockSize
	if blockSize <= 0 {
		blockSize = 100
	}
	stacks := in.MaxStacks
	if stacks <= 0 {
		stacks = 1
	}

	seen := map[int]bool{}
	var body strings.Builder
	body.WriteString("# Generated by `forge generate`. Do not edit — regenerated from\n")
	body.WriteString("# deploy/kcl/dev/ingress.k. `forge cluster up` merges this into\n")
	body.WriteString("# deploy/k3d.yaml's `ports:` block at cluster-create time.\n")
	body.WriteString("#\n")
	if stacks > 1 {
		body.WriteString(fmt.Sprintf("# Covers all %d parallel dev stacks (dev_stack.max_stacks in forge.yaml):\n", stacks))
		body.WriteString(fmt.Sprintf("# stack N binds each listener at port + N*%d, and k3d only forwards host\n", blockSize))
		body.WriteString("# ports mapped at cluster-CREATE time, so every reachable stack's ports are\n")
		body.WriteString("# pre-mapped here — a new worktree needs no cluster recreate. Raising the\n")
		body.WriteString("# ceiling regenerates this file; do NOT hand-maintain the range.\n")
	} else {
		body.WriteString("# Only the default stack is mapped (dev_stack.max_stacks is 1).\n")
	}
	body.WriteString("ports:\n")
	for stack := 0; stack < stacks; stack++ {
		offset := stack * blockSize
		if stacks > 1 {
			body.WriteString(fmt.Sprintf("  # ── stack %d (offset +%d) ──\n", stack, offset))
		}
		for _, l := range sorted {
			port := l.Port + offset
			if seen[port] {
				body.WriteString(fmt.Sprintf("  # port %d declared by multiple listeners — skipped duplicate (gateway=%s listener=%s)\n",
					port, l.GatewayName, l.ListenerName))
				continue
			}
			seen[port] = true
			body.WriteString(fmt.Sprintf("  # %s/%s\n", l.GatewayName, l.ListenerName))
			body.WriteString(fmt.Sprintf("  - port: %d:%d\n", port, port))
			body.WriteString("    nodeFilters:\n")
			body.WriteString("      - loadbalancer\n")
		}
	}

	outPath := filepath.Join(in.ProjectDir, "deploy", "k3d-ports.yaml")
	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		return fmt.Errorf("create deploy dir: %w", err)
	}

	rel := filepath.Join("deploy", "k3d-ports.yaml")
	if in.Checksums != nil {
		if err := writeForgeOwned(in.ProjectDir, rel, []byte(body.String()), in.Checksums); err != nil {
			return fmt.Errorf("write %s: %w", rel, err)
		}
		return nil
	}
	return writeUserScaffold(outPath, []byte(body.String()))
}

// RemoveK3dPorts deletes deploy/k3d-ports.yaml when present. Used by
// the generator gate when the ingress feature is off, or when the
// dev env has no gateways — the previous-generate's file would
// otherwise become a stale port-mapping the user might forget about.
func RemoveK3dPorts(projectDir string) error {
	outPath := filepath.Join(projectDir, "deploy", "k3d-ports.yaml")
	if err := os.Remove(outPath); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("remove %s: %w", outPath, err)
	}
	return nil
}
