// Code generated by forge. DO NOT EDIT.
package codegen

import (
	"context"
	"github.com/reliant-labs/forge/internal/config"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/metric"
	"time"
)

// MetricParser wraps a Parser implementation with OpenTelemetry metrics.
// Every method call records call count, error count, and duration.
type MetricParser struct {
	inner     Parser
	callCount metric.Int64Counter
	errCount  metric.Int64Counter
	duration  metric.Float64Histogram
}

// NewMetricParser creates a metrics wrapper around the given Parser.
func NewMetricParser(inner Parser, meter metric.Meter) Parser {
	callCount, _ := meter.Int64Counter("codegen.calls", metric.WithDescription("Total method calls"))
	errCount, _ := meter.Int64Counter("codegen.errors", metric.WithDescription("Total method errors"))
	duration, _ := meter.Float64Histogram("codegen.duration", metric.WithDescription("Method duration in seconds"), metric.WithUnit("s"))
	return &MetricParser{inner: inner, callCount: callCount, errCount: errCount, duration: duration}
}

func (w *MetricParser) ParseServicesFromProtos(dir string, projectDir string) ([]ServiceDef, error) {
	start := time.Now()
	w.callCount.Add(context.Background(), 1, metric.WithAttributes(attribute.String("method", "ParseServicesFromProtos")))
	r0, r1 := w.inner.ParseServicesFromProtos(dir, projectDir)
	w.duration.Record(context.Background(), time.Since(start).Seconds(), metric.WithAttributes(attribute.String("method", "ParseServicesFromProtos")))
	if r1 != nil {
		w.errCount.Add(context.Background(), 1, metric.WithAttributes(attribute.String("method", "ParseServicesFromProtos")))
	}
	return r0, r1
}

func (w *MetricParser) GetModulePath(dir string) (string, error) {
	start := time.Now()
	w.callCount.Add(context.Background(), 1, metric.WithAttributes(attribute.String("method", "GetModulePath")))
	r0, r1 := w.inner.GetModulePath(dir)
	w.duration.Record(context.Background(), time.Since(start).Seconds(), metric.WithAttributes(attribute.String("method", "GetModulePath")))
	if r1 != nil {
		w.errCount.Add(context.Background(), 1, metric.WithAttributes(attribute.String("method", "GetModulePath")))
	}
	return r0, r1
}

func (w *MetricParser) ParseEntityProtos(projectDir string) ([]EntityDef, error) {
	start := time.Now()
	w.callCount.Add(context.Background(), 1, metric.WithAttributes(attribute.String("method", "ParseEntityProtos")))
	r0, r1 := w.inner.ParseEntityProtos(projectDir)
	w.duration.Record(context.Background(), time.Since(start).Seconds(), metric.WithAttributes(attribute.String("method", "ParseEntityProtos")))
	if r1 != nil {
		w.errCount.Add(context.Background(), 1, metric.WithAttributes(attribute.String("method", "ParseEntityProtos")))
	}
	return r0, r1
}

func (w *MetricParser) ParseConfigProto(protoPath string) ([]ConfigMessage, error) {
	start := time.Now()
	w.callCount.Add(context.Background(), 1, metric.WithAttributes(attribute.String("method", "ParseConfigProto")))
	r0, r1 := w.inner.ParseConfigProto(protoPath)
	w.duration.Record(context.Background(), time.Since(start).Seconds(), metric.WithAttributes(attribute.String("method", "ParseConfigProto")))
	if r1 != nil {
		w.errCount.Add(context.Background(), 1, metric.WithAttributes(attribute.String("method", "ParseConfigProto")))
	}
	return r0, r1
}

func (w *MetricParser) ParseConfigProtosFromDir(dir string) ([]ConfigMessage, error) {
	start := time.Now()
	w.callCount.Add(context.Background(), 1, metric.WithAttributes(attribute.String("method", "ParseConfigProtosFromDir")))
	r0, r1 := w.inner.ParseConfigProtosFromDir(dir)
	w.duration.Record(context.Background(), time.Since(start).Seconds(), metric.WithAttributes(attribute.String("method", "ParseConfigProtosFromDir")))
	if r1 != nil {
		w.errCount.Add(context.Background(), 1, metric.WithAttributes(attribute.String("method", "ParseConfigProtosFromDir")))
	}
	return r0, r1
}

func (w *MetricParser) DetectFallibleConstructor(dir string) (bool, error) {
	start := time.Now()
	w.callCount.Add(context.Background(), 1, metric.WithAttributes(attribute.String("method", "DetectFallibleConstructor")))
	r0, r1 := w.inner.DetectFallibleConstructor(dir)
	w.duration.Record(context.Background(), time.Since(start).Seconds(), metric.WithAttributes(attribute.String("method", "DetectFallibleConstructor")))
	if r1 != nil {
		w.errCount.Add(context.Background(), 1, metric.WithAttributes(attribute.String("method", "DetectFallibleConstructor")))
	}
	return r0, r1
}

// Compile-time check.
var _ Parser = (*MetricParser)(nil)

// MetricGenerator wraps a Generator implementation with OpenTelemetry metrics.
// Every method call records call count, error count, and duration.
type MetricGenerator struct {
	inner     Generator
	callCount metric.Int64Counter
	errCount  metric.Int64Counter
	duration  metric.Float64Histogram
}

// NewMetricGenerator creates a metrics wrapper around the given Generator.
func NewMetricGenerator(inner Generator, meter metric.Meter) Generator {
	callCount, _ := meter.Int64Counter("codegen.calls", metric.WithDescription("Total method calls"))
	errCount, _ := meter.Int64Counter("codegen.errors", metric.WithDescription("Total method errors"))
	duration, _ := meter.Float64Histogram("codegen.duration", metric.WithDescription("Method duration in seconds"), metric.WithUnit("s"))
	return &MetricGenerator{inner: inner, callCount: callCount, errCount: errCount, duration: duration}
}

func (w *MetricGenerator) GenerateServiceStub(svc ServiceDef, targetDir string) error {
	start := time.Now()
	w.callCount.Add(context.Background(), 1, metric.WithAttributes(attribute.String("method", "GenerateServiceStub")))
	r0 := w.inner.GenerateServiceStub(svc, targetDir)
	w.duration.Record(context.Background(), time.Since(start).Seconds(), metric.WithAttributes(attribute.String("method", "GenerateServiceStub")))
	if r0 != nil {
		w.errCount.Add(context.Background(), 1, metric.WithAttributes(attribute.String("method", "GenerateServiceStub")))
	}
	return r0
}

func (w *MetricGenerator) RegenerateServiceFile(svc ServiceDef, targetDir string) error {
	start := time.Now()
	w.callCount.Add(context.Background(), 1, metric.WithAttributes(attribute.String("method", "RegenerateServiceFile")))
	r0 := w.inner.RegenerateServiceFile(svc, targetDir)
	w.duration.Record(context.Background(), time.Since(start).Seconds(), metric.WithAttributes(attribute.String("method", "RegenerateServiceFile")))
	if r0 != nil {
		w.errCount.Add(context.Background(), 1, metric.WithAttributes(attribute.String("method", "RegenerateServiceFile")))
	}
	return r0
}

func (w *MetricGenerator) GenerateMock(svc ServiceDef, mockDir string) (written bool, err error) {
	start := time.Now()
	w.callCount.Add(context.Background(), 1, metric.WithAttributes(attribute.String("method", "GenerateMock")))
	r0, r1 := w.inner.GenerateMock(svc, mockDir)
	w.duration.Record(context.Background(), time.Since(start).Seconds(), metric.WithAttributes(attribute.String("method", "GenerateMock")))
	if r1 != nil {
		w.errCount.Add(context.Background(), 1, metric.WithAttributes(attribute.String("method", "GenerateMock")))
	}
	return r0, r1
}

func (w *MetricGenerator) GenerateBootstrap(services []ServiceDef, packages []BootstrapPackageData, workers []BootstrapWorkerData, operators []BootstrapOperatorData, modulePath string, hasDatabase bool, ormEnabled bool, projectDir string) error {
	start := time.Now()
	w.callCount.Add(context.Background(), 1, metric.WithAttributes(attribute.String("method", "GenerateBootstrap")))
	r0 := w.inner.GenerateBootstrap(services, packages, workers, operators, modulePath, hasDatabase, ormEnabled, projectDir)
	w.duration.Record(context.Background(), time.Since(start).Seconds(), metric.WithAttributes(attribute.String("method", "GenerateBootstrap")))
	if r0 != nil {
		w.errCount.Add(context.Background(), 1, metric.WithAttributes(attribute.String("method", "GenerateBootstrap")))
	}
	return r0
}

func (w *MetricGenerator) GenerateBootstrapTesting(services []ServiceDef, packages []BootstrapPackageData, workers []BootstrapWorkerData, operators []BootstrapOperatorData, modulePath string, multiTenantEnabled bool, projectDir string) error {
	start := time.Now()
	w.callCount.Add(context.Background(), 1, metric.WithAttributes(attribute.String("method", "GenerateBootstrapTesting")))
	r0 := w.inner.GenerateBootstrapTesting(services, packages, workers, operators, modulePath, multiTenantEnabled, projectDir)
	w.duration.Record(context.Background(), time.Since(start).Seconds(), metric.WithAttributes(attribute.String("method", "GenerateBootstrapTesting")))
	if r0 != nil {
		w.errCount.Add(context.Background(), 1, metric.WithAttributes(attribute.String("method", "GenerateBootstrapTesting")))
	}
	return r0
}

func (w *MetricGenerator) GenerateMigrate(targetDir string, modulePath string, hasMigrations bool) error {
	start := time.Now()
	w.callCount.Add(context.Background(), 1, metric.WithAttributes(attribute.String("method", "GenerateMigrate")))
	r0 := w.inner.GenerateMigrate(targetDir, modulePath, hasMigrations)
	w.duration.Record(context.Background(), time.Since(start).Seconds(), metric.WithAttributes(attribute.String("method", "GenerateMigrate")))
	if r0 != nil {
		w.errCount.Add(context.Background(), 1, metric.WithAttributes(attribute.String("method", "GenerateMigrate")))
	}
	return r0
}

func (w *MetricGenerator) GenerateMissingHandlerStubs(svc ServiceDef, targetDir string) (*MissingHandlerResult, error) {
	start := time.Now()
	w.callCount.Add(context.Background(), 1, metric.WithAttributes(attribute.String("method", "GenerateMissingHandlerStubs")))
	r0, r1 := w.inner.GenerateMissingHandlerStubs(svc, targetDir)
	w.duration.Record(context.Background(), time.Since(start).Seconds(), metric.WithAttributes(attribute.String("method", "GenerateMissingHandlerStubs")))
	if r1 != nil {
		w.errCount.Add(context.Background(), 1, metric.WithAttributes(attribute.String("method", "GenerateMissingHandlerStubs")))
	}
	return r0, r1
}

func (w *MetricGenerator) GenerateSetup(modulePath string, databaseDriver string, ormEnabled bool, targetDir string) error {
	start := time.Now()
	w.callCount.Add(context.Background(), 1, metric.WithAttributes(attribute.String("method", "GenerateSetup")))
	r0 := w.inner.GenerateSetup(modulePath, databaseDriver, ormEnabled, targetDir)
	w.duration.Record(context.Background(), time.Since(start).Seconds(), metric.WithAttributes(attribute.String("method", "GenerateSetup")))
	if r0 != nil {
		w.errCount.Add(context.Background(), 1, metric.WithAttributes(attribute.String("method", "GenerateSetup")))
	}
	return r0
}

func (w *MetricGenerator) GenerateConfigLoader(messages []ConfigMessage, targetDir string) error {
	start := time.Now()
	w.callCount.Add(context.Background(), 1, metric.WithAttributes(attribute.String("method", "GenerateConfigLoader")))
	r0 := w.inner.GenerateConfigLoader(messages, targetDir)
	w.duration.Record(context.Background(), time.Since(start).Seconds(), metric.WithAttributes(attribute.String("method", "GenerateConfigLoader")))
	if r0 != nil {
		w.errCount.Add(context.Background(), 1, metric.WithAttributes(attribute.String("method", "GenerateConfigLoader")))
	}
	return r0
}

func (w *MetricGenerator) GenerateAuthMiddleware(cfg *config.AuthConfig, modulePath string, skipMethods []string, targetDir string) error {
	start := time.Now()
	w.callCount.Add(context.Background(), 1, metric.WithAttributes(attribute.String("method", "GenerateAuthMiddleware")))
	r0 := w.inner.GenerateAuthMiddleware(cfg, modulePath, skipMethods, targetDir)
	w.duration.Record(context.Background(), time.Since(start).Seconds(), metric.WithAttributes(attribute.String("method", "GenerateAuthMiddleware")))
	if r0 != nil {
		w.errCount.Add(context.Background(), 1, metric.WithAttributes(attribute.String("method", "GenerateAuthMiddleware")))
	}
	return r0
}

func (w *MetricGenerator) GenerateTenantMiddleware(mt *config.MultiTenantConfig, targetDir string) error {
	start := time.Now()
	w.callCount.Add(context.Background(), 1, metric.WithAttributes(attribute.String("method", "GenerateTenantMiddleware")))
	r0 := w.inner.GenerateTenantMiddleware(mt, targetDir)
	w.duration.Record(context.Background(), time.Since(start).Seconds(), metric.WithAttributes(attribute.String("method", "GenerateTenantMiddleware")))
	if r0 != nil {
		w.errCount.Add(context.Background(), 1, metric.WithAttributes(attribute.String("method", "GenerateTenantMiddleware")))
	}
	return r0
}

func (w *MetricGenerator) GenerateCRUDHandlers(svc ServiceDef, crudMethods []CRUDMethod, modulePath string, projectDir string) error {
	start := time.Now()
	w.callCount.Add(context.Background(), 1, metric.WithAttributes(attribute.String("method", "GenerateCRUDHandlers")))
	r0 := w.inner.GenerateCRUDHandlers(svc, crudMethods, modulePath, projectDir)
	w.duration.Record(context.Background(), time.Since(start).Seconds(), metric.WithAttributes(attribute.String("method", "GenerateCRUDHandlers")))
	if r0 != nil {
		w.errCount.Add(context.Background(), 1, metric.WithAttributes(attribute.String("method", "GenerateCRUDHandlers")))
	}
	return r0
}

func (w *MetricGenerator) GenerateCRUDTests(svc ServiceDef, crudMethods []CRUDMethod, modulePath string, projectDir string) error {
	start := time.Now()
	w.callCount.Add(context.Background(), 1, metric.WithAttributes(attribute.String("method", "GenerateCRUDTests")))
	r0 := w.inner.GenerateCRUDTests(svc, crudMethods, modulePath, projectDir)
	w.duration.Record(context.Background(), time.Since(start).Seconds(), metric.WithAttributes(attribute.String("method", "GenerateCRUDTests")))
	if r0 != nil {
		w.errCount.Add(context.Background(), 1, metric.WithAttributes(attribute.String("method", "GenerateCRUDTests")))
	}
	return r0
}

// Compile-time check.
var _ Generator = (*MetricGenerator)(nil)
