package codegen

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/reliant-labs/forge/internal/checksums"
)

// TestRemoveRetiredBootstrapTesting_ReclaimsPreMarkerForgeOutput pins the
// case that wedged a real project: a pkg/app/testing.go written by a forge
// that predated the forge:hash marker. It self-identifies ("Code generated by
// forge") but has no marker, so checksums.Verify reports NoMarker, not
// Pristine — and the retire step used to skip it.
//
// The skip is harmless only while every service the stale file imports still
// exists. The moment a proto service is deleted, the leftover file imports a
// package that is gone, generate's own build validation fails on it, the run
// rolls back, and the file is never retired: `forge generate` cannot converge.
func TestRemoveRetiredBootstrapTesting_ReclaimsPreMarkerForgeOutput(t *testing.T) {
	dir := t.TempDir()
	rel := filepath.Join("pkg", "app", "testing.go")
	abs := filepath.Join(dir, rel)
	if err := os.MkdirAll(filepath.Dir(abs), 0o755); err != nil {
		t.Fatal(err)
	}
	body := "// Code generated by forge. DO NOT EDIT.\n// forge-owned: regenerated every run\npackage app\n"
	if err := os.WriteFile(abs, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}

	if err := removeRetiredBootstrapTesting(dir, &checksums.FileChecksums{}); err != nil {
		t.Fatalf("removeRetiredBootstrapTesting: %v", err)
	}
	if _, err := os.Stat(abs); !os.IsNotExist(err) {
		t.Fatalf("pre-marker forge-generated %s survived retirement (stat err=%v); a deleted "+
			"service would leave it importing a missing package and wedge generate", rel, err)
	}
}

// TestRemoveRetiredBootstrapTesting_KeepsUserFile: a file that does not
// self-identify as forge output is the user's, and is never deleted.
func TestRemoveRetiredBootstrapTesting_KeepsUserFile(t *testing.T) {
	dir := t.TempDir()
	abs := filepath.Join(dir, "pkg", "app", "testing.go")
	if err := os.MkdirAll(filepath.Dir(abs), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(abs, []byte("package app\n\n// mine\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := removeRetiredBootstrapTesting(dir, &checksums.FileChecksums{}); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(abs); err != nil {
		t.Fatalf("a user-authored pkg/app/testing.go was deleted: %v", err)
	}
}
