package lint

import (
	"context"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
	"testing"

	"github.com/reliant-labs/forge/internal/checksums"
	"github.com/reliant-labs/forge/internal/config"
)

// TestFormatFrontendTrees_FormatsOwnedSourcesOnly pins the scope of the
// frontend half of `forge lint`'s auto-fix pre-pass.
//
// The defect it guards: a scaffold-once file forge emitted
// (control-plane's git-credential-internal-service-hooks.test.tsx) failed the
// project's CI prettier check, and `forge lint` — whose help promises that
// "mechanical formatting never surfaces as a gating error" — left it as it
// was, because the only frontend fixer was eslint --fix and the scaffolded
// eslint config carries no formatting rules.
//
// The stub prettier on node_modules/.bin records the files it was handed and
// lists them as rewritten, so the test sees exactly the set forge chose. That
// set must include every user-owned src/ file and EXCLUDE what forge owns,
// which a formatter rewrite would only make the next `forge generate` fight:
// *_gen.* modules, src/gen/, banner-marked generated files, a pristine
// scaffold-until-touched file, and everything outside src/.
func TestFormatFrontendTrees_FormatsOwnedSourcesOnly(t *testing.T) {
	if testing.Short() {
		t.Skip("drives a fake prettier through shell subprocesses; runs in task test")
	}
	if runtime.GOOS == "windows" {
		t.Skip("stub prettier is a POSIX shell script")
	}
	root := t.TempDir()
	writeFixture(t, filepath.Join(root, "forge.yaml"), "name: x\nmodule_path: example.com/x\n")
	fe := filepath.Join(root, "frontends", "web")

	owned := []string{
		"src/hooks/orders-service-hooks.test.tsx", // the reported file
		"src/components/ui/button.tsx",
		"src/app/globals.css",
		"src/lib/format-utils.ts",
	}
	notOwned := []string{
		"src/hooks/orders-service-hooks_gen.ts", // Tier-1 generated module
		"src/lib/thing_gen.test.ts",             // generated test
		"src/gen/services/orders/v1/orders_pb.ts",
		"src/hooks/index.ts",      // banner-marked generated barrel
		"src/components/nav.tsx",  // pristine scaffold-until-touched
		"tsconfig.json",           // forge/npm edit it in place
		"eslint.config.mjs",       // outside src/
		"src/components/logo.svg", // not a prettier source
		"node_modules/x/src/a.ts", // dependencies
	}
	for _, rel := range append(append([]string{}, owned...), notOwned...) {
		body := "export const x = 1;\n"
		if rel == "src/hooks/index.ts" {
			body = "// Code generated by forge. DO NOT EDIT.\nexport * from \"./a_gen\";\n"
		}
		writeFixture(t, filepath.Join(fe, rel), body)
	}
	// nav.tsx is pristine: the ledger records exactly the bytes on disk.
	navRel := filepath.Join("frontends", "web", "src", "components", "nav.tsx")
	navBytes, err := os.ReadFile(filepath.Join(root, navRel))
	if err != nil {
		t.Fatal(err)
	}
	checksums.RecordScaffoldWithHash(root, navRel, navBytes)

	argvLog := filepath.Join(root, "prettier-argv")
	// The stub behaves like prettier where it matters: --log-level warn (or
	// quieter) suppresses the --list-different output, which is how the
	// pre-pass once formatted files while reporting none.
	stub := "#!/bin/sh\n" +
		"case \" $* \" in *\" --log-level \"*) exit 0;; esac\n" +
		"for a in \"$@\"; do case \"$a\" in --*) ;; *) echo \"$a\" >> '" + argvLog + "'; echo \"$a\";; esac; done\n"
	writeFixture(t, filepath.Join(fe, "node_modules", ".bin", "prettier"), stub)
	if err := os.Chmod(filepath.Join(fe, "node_modules", ".bin", "prettier"), 0o755); err != nil {
		t.Fatal(err)
	}

	cfg := &config.ProjectConfig{Frontends: []config.FrontendConfig{{Name: "web"}}}
	changed, err := formatFrontendTrees(context.Background(), root, cfg)
	if err != nil {
		t.Fatalf("formatFrontendTrees: %v", err)
	}

	got := map[string]bool{}
	for _, c := range changed {
		got[strings.TrimPrefix(c, "frontends/web/")] = true
	}
	for _, rel := range owned {
		if !got[rel] {
			t.Errorf("user-owned %s was not handed to prettier", rel)
		}
	}
	for _, rel := range notOwned {
		if got[rel] {
			t.Errorf("%s is not the user's to format, but prettier was run on it", rel)
		}
	}
	if t.Failed() {
		keys := make([]string, 0, len(got))
		for k := range got {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		t.Logf("prettier was handed: %v", keys)
	}
}

// Once the user edits a scaffold-until-touched file it is theirs, and the
// formatter treats it like any other owned file.
func TestFormatFrontendTrees_EditedScaffoldIsOwned(t *testing.T) {
	if testing.Short() {
		t.Skip("drives a fake prettier through shell subprocesses; runs in task test")
	}
	if runtime.GOOS == "windows" {
		t.Skip("stub prettier is a POSIX shell script")
	}
	root := t.TempDir()
	writeFixture(t, filepath.Join(root, "forge.yaml"), "name: x\nmodule_path: example.com/x\n")
	fe := filepath.Join(root, "frontends", "web")
	navRel := filepath.Join("frontends", "web", "src", "components", "nav.tsx")
	checksums.RecordScaffoldWithHash(root, navRel, []byte("as forge wrote it\n"))
	writeFixture(t, filepath.Join(root, navRel), "edited by the user\n")
	writeFixture(t, filepath.Join(fe, "node_modules", ".bin", "prettier"),
		"#!/bin/sh\nfor a in \"$@\"; do case \"$a\" in --*) ;; *) echo \"$a\";; esac; done\n")
	if err := os.Chmod(filepath.Join(fe, "node_modules", ".bin", "prettier"), 0o755); err != nil {
		t.Fatal(err)
	}

	cfg := &config.ProjectConfig{Frontends: []config.FrontendConfig{{Name: "web"}}}
	changed, err := formatFrontendTrees(context.Background(), root, cfg)
	if err != nil {
		t.Fatalf("formatFrontendTrees: %v", err)
	}
	if len(changed) != 1 || changed[0] != "frontends/web/src/components/nav.tsx" {
		t.Errorf("an edited nav.tsx is the user's and should be formatted, got %v", changed)
	}
}

// No installed prettier (deps not installed yet) is a silent no-op: this is a
// fixer, and the eslint/typecheck lanes already report the missing install.
// Above all it must not fall back to npx, which downloads.
func TestFormatFrontendTrees_NoInstalledPrettierIsNoOp(t *testing.T) {
	root := t.TempDir()
	writeFixture(t, filepath.Join(root, "frontends", "web", "src", "a.ts"), "export const a = 1;\n")
	cfg := &config.ProjectConfig{Frontends: []config.FrontendConfig{{Name: "web"}}}
	changed, err := formatFrontendTrees(context.Background(), root, cfg)
	if err != nil || len(changed) != 0 {
		t.Errorf("want a silent no-op, got changed=%v err=%v", changed, err)
	}
}

// writeFixture is mustWrite plus the parent directories a nested fixture needs.
func writeFixture(t *testing.T, path, content string) {
	t.Helper()
	mustMkdirAll(t, filepath.Dir(path))
	mustWrite(t, path, content)
}
