//go:build ignore

// Package middleware is YOUR auth policy surface — forge scaffolded it
// once and will not rewrite it.
//
// The middleware MECHANISMS (auth interceptor modes + refusal-to-start,
// authz interceptor, CORS, security headers, request-id, rate limiting,
// idempotency, the HTTP stack, recovery/logging) live in the forge
// libraries — github.com/reliant-labs/forge/pkg/{authn,authz,middleware,
// observe} — versioned with forge so they keep receiving fixes. This
// file wires the POLICY: the four things projects actually customize.
//
//  1. Token validator  — passed EXPLICITLY into NewAuthInterceptor via
//     AuthDeps.Validate (no package-global slot). The composition root
//     (internal/app/providers.go OpenInfra, or the generated auth_gen.go)
//     builds the validator and the cmd serve.go threads it in.
//  2. Identity enricher — enrichClaims (hydrate roles/org/flags onto
//     validated claims before handlers see them).
//  3. Allow-list        — unauthenticatedProcedures (exact procedure
//     strings that skip auth).
//  4. Dev claims        — devClaims (the synthetic principal attached
//     while running with auth off in dev / AUTH_MODE=none).
//
// It also owns the Claims type + context key (generated handlers and
// authorizers reference middleware.Claims / ClaimsFromContext — keep
// these here so generated code's public surface never churns) and the
// Authorizer policy window (Authorizer interface, DevAuthorizer,
// action constants) that per-service authorizers implement.
//
// The codegen siblings in this package (auth_gen.go, tenant_gen.go —
// regenerated by `forge generate` from forge.yaml) plug into the same
// hooks: InstallGeneratedAuth (called by the generated cmd serve.go)
// builds the forge.yaml provider's validator and HANDS IT to
// NewAuthInterceptor via AuthDeps (or reports ExternalAuth for a
// header-carried provider) and uses ContextWithClaims; the tenant
// interceptor calls ClaimsFromContext.
package middleware

import (
	"context"
	"fmt"

	"connectrpc.com/connect"

	"github.com/reliant-labs/forge/pkg/auth"
	"github.com/reliant-labs/forge/pkg/authn"
	"github.com/reliant-labs/forge/pkg/authz"
)

// ─── Claims ownership ───────────────────────────────────────────────

// Claims is the canonical claims type used throughout the application.
// It is a type alias for auth.Claims so library code (the generated
// auth interceptor in auth_gen.go, pkg/authn, pkg/authz, the tenant
// interceptor) and project code share the same type.
//
// To extend Claims with project-specific fields, prefer enriching the
// existing fields via enrichClaims below. If you truly need a custom
// struct, replace this alias with a type that embeds auth.Claims and
// update the callbacks this file passes to the forge libraries.
type Claims = auth.Claims

type claimsContextKey struct{}

// ClaimsFromContext retrieves user claims from the context. Returns
// nil, false if no claims are present (e.g. unauthenticated request).
func ClaimsFromContext(ctx context.Context) (*Claims, bool) {
	claims, ok := ctx.Value(claimsContextKey{}).(*Claims)
	return claims, ok
}

// ContextWithClaims returns a new context with the given claims attached.
func ContextWithClaims(ctx context.Context, claims *Claims) context.Context {
	return context.WithValue(ctx, claimsContextKey{}, claims)
}

// ─── Policy hook 3: the unauthenticated allow-list ──────────────────
//
// unauthenticatedProcedures is an explicit allow-list of RPC procedures
// that bypass the auth interceptor. Entries must be FULL procedure
// strings of the form "/package.Service/Method" — matching is exact,
// never by substring, so a user-defined "HealthReport" RPC can't ride
// along with the health checks.
//
// Extend this set to expose additional unauthenticated endpoints (e.g.
// public version or readiness RPCs).
var unauthenticatedProcedures = map[string]struct{}{
	"/grpc.health.v1.Health/Check": {},
	"/grpc.health.v1.Health/Watch": {},
}

// ─── Policy hook 1: the token validator (explicit, no global) ─────────

// AuthDeps carries the EXPLICIT authentication policy into the
// interceptor. It replaces the retired package-global state
// (SetTokenValidator / MarkExternalAuth): the composition root builds an
// AuthDeps once and threads it into NewAuthInterceptor, so there is no
// process-wide mutable slot the per-request hot path reads.
type AuthDeps struct {
	// DevMode is INJECTED from the project's typed config
	// (config.DevAuthBypass(cfg)). This package never re-derives dev mode
	// from the environment.
	DevMode bool

	// ExternalAuth reports that another interceptor in the chain owns auth
	// (a pack, or a header-carried provider). The interceptor then becomes
	// a pure passthrough so the external interceptor is the source of truth.
	ExternalAuth bool

	// Validate validates a raw bearer token and returns the claims. Non-nil
	// switches the interceptor into validate mode; nil leaves it to the
	// other signals (ExternalAuth / DevMode / AUTH_MODE=none) and otherwise
	// refuses to start (a production server with no auth provider is a bug).
	Validate func(token string) (*Claims, error)
}

// ─── Policy hook 2: identity enrichment ──────────────────────────────
//
// enrichClaims runs after token validation and before the claims are
// stashed on the context. Hydrate identity here — roles from the user
// table, org membership, feature flags. Returning an error rejects the
// request (CodeUnauthenticated unless you return a *connect.Error).
//
// The default is the identity function.
func enrichClaims(_ context.Context, claims *Claims) (*Claims, error) {
	return claims, nil
}

// ─── Policy hook 4: dev claims ───────────────────────────────────────
//
// devClaims supplies the synthetic principal attached to every request
// while the server runs with auth off — and ONLY then: pkg/authn
// consults DevClaims solely in passthrough mode (dev mode or
// AUTH_MODE=none) and ignores it in Validate mode and when an external
// auth provider is registered, so this principal can never leak into a
// real-auth deployment.
//
// The default below makes the generated CRUD handlers — which demand
// claims via GetUser — callable in dev with zero auth config. It
// carries no OrgID: multi-tenant projects whose tenant interceptor
// scopes rows by an org claim should set OrgID to a fixture tenant
// here, or tenant-scoped queries will see no rows. Return nil to keep
// dev passthrough claim-free (every CRUD call then 401s until a real
// validator is installed).
func devClaims() *Claims {
	return &Claims{
		UserID: "dev-user",
		Email:  "dev@localhost",
		Role:   "admin",
	}
}

// ─── Interceptor construction ────────────────────────────────────────

// NewAuthInterceptor resolves this file's policy into the forge authn
// interceptor from an EXPLICIT AuthDeps (no package globals). deps.DevMode
// is INJECTED from the project's typed config (config.DevAuthBypass(cfg)) —
// the single dev-mode source of truth.
//
// Mode resolution (see forge/pkg/authn for details): a server with NO
// validator (deps.Validate == nil), NO external auth, AUTH_MODE != none,
// and deps.DevMode == false REFUSES TO START — cmd serve.go returns the
// error before the listener binds. A production server with no auth
// provider is always a bug; refusing to start is safer than silently
// accepting (or silently rejecting) every request.
func NewAuthInterceptor(deps AuthDeps) (connect.Interceptor, error) {
	return authn.NewInterceptor(authn.Policy{
		DevMode:             deps.DevMode,
		ValidatorConfigured: deps.Validate != nil,
		ExternalAuth:        deps.ExternalAuth,
		Validate:            deps.Validate,
		Unauthenticated:     unauthenticatedProcedures,
		Enrich:              enrichClaims,
		DevClaims:           devClaims,
		ContextWithClaims:   ContextWithClaims,
	})
}

// ─── Authorization policy window ─────────────────────────────────────

// GetUser extracts the authenticated user's claims from the context.
// Returns a connect CodeUnauthenticated error if no claims are present.
// Use this in handlers to get the current user before calling
// Authorizer.Can.
func GetUser(ctx context.Context) (*Claims, error) {
	claims, ok := ClaimsFromContext(ctx)
	if !ok {
		return nil, connect.NewError(connect.CodeUnauthenticated, fmt.Errorf("no authenticated user"))
	}
	return claims, nil
}

// Standard CRUD action constants for use with Authorizer.Can.
const (
	ActionCreate = "create"
	ActionRead   = "read"
	ActionUpdate = "update"
	ActionDelete = "delete"
	ActionList   = "list"
)

// Authorizer determines whether the current request is authorized to
// access a given RPC procedure. Per-service authorizers (the generated
// handlers/<svc>/authorizer_gen.go shims over forge/pkg/authz)
// implement it. Return nil to allow access, or a connect.Error to deny.
type Authorizer interface {
	// CanAccess checks whether the authenticated user in ctx is authorized
	// to call the given procedure. The procedure string is the full RPC
	// method name (e.g. "/proto.services.users.v1.UsersService/Create").
	CanAccess(ctx context.Context, procedure string) error

	// Can checks if the user has permission to perform the action on the
	// resource. action is one of the Action* constants; resource is the
	// entity name in lowercase (e.g. "patient", "invoice").
	Can(ctx context.Context, claims *Claims, action string, resource string) error
}

// AuthzInterceptor returns a Connect interceptor that checks
// authorization on every RPC call using the provided Authorizer. Thin
// shim over forge/pkg/authz — the project keeps the call site so the
// Authorizer interface above stays the only policy boundary.
func AuthzInterceptor(a Authorizer) connect.Interceptor {
	return authz.Interceptor(a)
}

// DevAuthorizer is an allow-all Authorizer intended for use in local
// development only. Production authorizers deny by default
// (fail-closed); DevAuthorizer is the opt-in dev-ergonomics counterpart
// selected when cfg.Environment == "development".
//
// DO NOT use this in production. Bootstrap guards its use behind an
// explicit config value and logs a WARN at startup when it is active.
type DevAuthorizer struct{}

// CanAccess implements Authorizer.CanAccess. Always returns nil (allow).
func (DevAuthorizer) CanAccess(context.Context, string) error { return nil }

// Can implements Authorizer.Can. Always returns nil (allow).
func (DevAuthorizer) Can(context.Context, *Claims, string, string) error { return nil }

// VerifyAuth checks if the user has the required roles. It checks both
// the single Role field and the Roles slice for a match.
func VerifyAuth(ctx context.Context, requiredRoles ...string) error {
	claims, ok := ClaimsFromContext(ctx)
	if !ok {
		return connect.NewError(connect.CodeUnauthenticated, fmt.Errorf("no authentication claims found"))
	}

	if len(requiredRoles) == 0 {
		return nil
	}

	for _, requiredRole := range requiredRoles {
		if claims.Role == requiredRole {
			return nil
		}
		for _, userRole := range claims.Roles {
			if userRole == requiredRole {
				return nil
			}
		}
	}

	return connect.NewError(connect.CodePermissionDenied, fmt.Errorf("insufficient permissions"))
}
