// Package authz provides the runtime helper used by the per-service
// handlers/<svc>/authorizer_gen.go file forge generates.
//
// # Shape
//
// The library exposes an interface-driven authorizer. Generated forge
// projects emit a thin shim that constructs an [Authorizer] wrapping a
// project-supplied [Decider]. The shim conforms to the project's
// pkg/middleware.Authorizer interface (Can / CanAccess) so the rest of
// the handler layer needs no changes when policy logic moves around.
//
// The boundary of responsibility:
//
//   - The library owns the wiring (CanAccess procedure → method lookup,
//     Can action+resource → method lookup, panic recovery, deny-by-default
//     fall-through, error envelope).
//   - The user owns policy via a [Decider] implementation. The default
//     stub deciders ([DenyAll], [AllowAll]) cover dev/test paths; a real
//     project ships its decider in handlers/<svc>/authz.go.
//
// # Usage from a handler package
//
//	// handlers/users/authz.go (user-owned)
//	package users
//
//	import (
//	    "context"
//
//	    "github.com/reliant-labs/forge/pkg/auth"
//	    "github.com/reliant-labs/forge/pkg/authz"
//	)
//
//	type decider struct{}
//
//	func (decider) Decide(ctx context.Context, method string, claims *auth.Claims) error {
//	    if claims == nil {
//	        return authz.Deny("authentication required")
//	    }
//	    if claims.Role == "admin" {
//	        return nil
//	    }
//	    return authz.Deny("admin role required for %s", method)
//	}
//
//	func newDecider() authz.Decider { return decider{} }
//
// The companion handlers/<svc>/authorizer_gen.go (regenerated by forge)
// is a thin shim that calls authz.New(newDecider()) and is wired into
// pkg/app/bootstrap.go automatically.
//
// # Why interface-driven over data-driven
//
// An earlier sketch in CODEGEN_AUDIT.md proposed a data-shim where the
// generated file populated a methodRoles map and the library carried the
// matching logic. That approach forced the library to know about role
// semantics and to bake in a single matching strategy. The interface
// approach lets each service ship arbitrary policy (RBAC, ABAC, OPA
// callouts, …) without changing the library or the generated shim. A
// roles-table decider is one helper among many — see [RolesDecider].
package authz

import (
	"context"
	"errors"
	"fmt"
	"log/slog"

	"connectrpc.com/connect"

	"github.com/reliant-labs/forge/pkg/auth"
)

// Decider makes a single authorization decision for one method invocation.
//
// Implementations receive the canonical method identifier (the Connect
// procedure for [Authorizer.CanAccess], or the synthesised "<action>:<resource>"
// string for [Authorizer.Can]) and the authenticated claims (nil when no
// authentication ran). They return nil to allow, or a non-nil error to deny.
//
// Returned errors flow back to the handler verbatim; if the implementation
// returns a [*connect.Error] the code is preserved, otherwise the
// [Authorizer] wraps it as connect.CodePermissionDenied. Implementations
// MAY panic; the [Authorizer] recovers and converts a panic into a
// PermissionDenied error so a misbehaving policy never tears down a service.
type Decider interface {
	// Decide returns nil to allow the call, or an error to deny it.
	Decide(ctx context.Context, method string, claims *auth.Claims) error
}

// DeciderFunc adapts an ordinary function to the [Decider] interface.
type DeciderFunc func(ctx context.Context, method string, claims *auth.Claims) error

// Decide implements [Decider].
func (f DeciderFunc) Decide(ctx context.Context, method string, claims *auth.Claims) error {
	return f(ctx, method, claims)
}

// Authorizer is the boundary type used by generated handlers.
//
// It implements both halves of the project's pkg/middleware.Authorizer
// interface (Can / CanAccess) by delegating to a user-supplied [Decider].
// Construct with [New]; the zero value is not usable.
type Authorizer struct {
	decider Decider
}

// New returns an [Authorizer] backed by d.
//
// d must be non-nil; passing nil is an obvious construction bug and would
// produce nil-panics on every request. New panics in that case so the
// failure surfaces at boot rather than under load. Tests that want a
// no-policy authorizer should pass [DenyAll] (production-safe default)
// or [AllowAll] (only for local-dev / unit-test fixtures).
func New(d Decider) *Authorizer {
	if d == nil {
		panic("authz.New: decider must not be nil; use authz.DenyAll{} or authz.AllowAll{} for stubs")
	}
	return &Authorizer{decider: d}
}

// CanAccess implements pkg/middleware.Authorizer.CanAccess.
//
// Given a Connect procedure path (e.g. "/users.v1.UsersService/Get"), it
// pulls authenticated claims out of ctx (using [auth.Claims] via
// [ClaimsFromContext], which is a project-supplied callback wired by the
// generated shim) and asks the decider whether the call is allowed.
//
// An empty procedure is denied unconditionally — Connect always passes a
// real procedure name, so an empty value is a defensive bug check.
func (a *Authorizer) CanAccess(ctx context.Context, procedure string) error {
	if procedure == "" {
		return connect.NewError(connect.CodePermissionDenied,
			fmt.Errorf("empty procedure name is denied by default"))
	}
	claims, _ := ClaimsFromContext(ctx)
	return a.invoke(ctx, procedure, claims)
}

// Can implements pkg/middleware.Authorizer.Can.
//
// It synthesises a method identifier of the form "<action>:<resource>"
// (e.g. "create:patient", "list:invoice") and forwards to the decider
// alongside the supplied claims. Generated CRUD handlers call Can after
// they've already extracted claims from the context, so callers pass them
// through directly.
//
// When claims is nil and the decider returns a plain error (or a
// PermissionDenied connect.Error from the default wrapping), the result is
// re-cast as CodeUnauthenticated so callers can distinguish "you must
// sign in" from "you can't do that". A decider that explicitly chooses
// a different connect code (e.g. CodeFailedPrecondition) keeps that code
// verbatim.
func (a *Authorizer) Can(ctx context.Context, claims *auth.Claims, action, resource string) error {
	method := action + ":" + resource
	err := a.invoke(ctx, method, claims)
	if err == nil || claims != nil {
		return err
	}
	// claims == nil → re-cast PermissionDenied (which is what invoke
	// produces by default) as Unauthenticated. A decider that picked a
	// different code keeps it.
	var ce *connect.Error
	if errors.As(err, &ce) && ce.Code() == connect.CodePermissionDenied {
		return connect.NewError(connect.CodeUnauthenticated, errors.New(ce.Message()))
	}
	return err
}

// invoke is the shared core of CanAccess and Can: panic recovery, error
// envelope normalisation, and the actual Decider call. Keeping the wiring
// here means new boundary methods (a future Stream variant, say) can be
// added without re-deriving the recovery contract.
func (a *Authorizer) invoke(ctx context.Context, method string, claims *auth.Claims) (err error) {
	defer func() {
		if r := recover(); r != nil {
			// A panic in user policy must not take down the request: convert
			// it to PermissionDenied so the request fails closed and the
			// failure shows up in logs.
			err = connect.NewError(connect.CodePermissionDenied,
				fmt.Errorf("authorizer panic: %v", r))
		}
	}()
	if err := a.decider.Decide(ctx, method, claims); err != nil {
		// If the decider already wrapped a connect.Error, pass it through.
		var ce *connect.Error
		if errors.As(err, &ce) {
			return err
		}
		return connect.NewError(connect.CodePermissionDenied, err)
	}
	return nil
}

// Deny is a small helper for Decider implementations that want a plain
// "denied" error without importing connect. The returned error is plain;
// [Authorizer.invoke] wraps it as CodePermissionDenied at the boundary.
func Deny(format string, args ...any) error {
	return fmt.Errorf(format, args...)
}

// DenyAll is the production-safe default decider: every call is denied.
//
// New services scaffold with a stub decider; until a real policy lands,
// fail-closed semantics mean an unsecured handler returns 403 rather
// than silently allowing every caller through. Use for tests that want
// to assert deny behaviour without rolling a one-off Decider type.
type DenyAll struct{}

// Decide implements [Decider]; always returns CodePermissionDenied.
func (DenyAll) Decide(ctx context.Context, method string, claims *auth.Claims) error {
	return connect.NewError(connect.CodePermissionDenied,
		fmt.Errorf("authorization not configured for %s", method))
}

// AllowAll is the dev/test counterpart to [DenyAll]: every call is allowed.
//
// Suitable for local development (where the [DevAuthorizer] in pkg/middleware
// uses it under the hood) and for tests whose subject of interest is not
// the authorization layer. NOT for production use.
type AllowAll struct{}

// Decide implements [Decider]; always returns nil.
func (AllowAll) Decide(ctx context.Context, method string, claims *auth.Claims) error {
	return nil
}

// claimsLookup is the project-supplied claims-from-context helper. The
// generated shim calls [SetClaimsLookup] at package init so library code
// (CanAccess) can read claims without importing pkg/middleware (which
// would create a cycle: middleware imports authz, authz can't import
// middleware back).
var claimsLookup func(context.Context) (*auth.Claims, bool)

// SetClaimsLookup wires the project's claims-from-context helper. It is
// called by the generated handlers/<svc>/authorizer_gen.go shim's
// init() before any handler runs.
//
// Idempotent on identical lookups; setting it twice with different
// functions panics so a stray re-init in tests surfaces immediately.
func SetClaimsLookup(lookup func(context.Context) (*auth.Claims, bool)) {
	if lookup == nil {
		claimsLookup = nil
		return
	}
	claimsLookup = lookup
}

// ClaimsFromContext returns the authenticated claims (or nil + false) by
// dispatching to the lookup wired via [SetClaimsLookup]. When no lookup is
// wired (library used standalone in tests, say), it returns nil + false.
func ClaimsFromContext(ctx context.Context) (*auth.Claims, bool) {
	if claimsLookup == nil {
		return nil, false
	}
	return claimsLookup(ctx)
}

// FailMode controls what [RolesDecider] does when an RPC reaches the
// authorizer with no entry in either MethodRoles or MethodAuthRequired
// (the "unknown method" case). The zero value is [FailOpen] — the safe
// default for fresh scaffolds whose proto hasn't grown annotations yet,
// since pure fail-closed would 403 every RPC in staging/prod the moment
// dev mode is turned off. The accompanying [RolesDecider.warnUnknownMethod]
// still fires under FailOpen so the missing annotation surfaces in logs.
//
// Projects that want explicit deny-by-default (e.g. multi-tenant SaaS
// that treats unannotated as an audit-class bug) opt in via FailClosed.
type FailMode int

const (
	// FailOpen allows the call but emits the [RolesDecider.warnUnknownMethod]
	// signal so the missing annotation can be tracked. This is the zero
	// value because the alternative — fail-closed on uninitialised maps —
	// reliably bricks a freshly-scaffolded staging deploy the first time
	// it boots without the dev-mode authorizer swap.
	FailOpen FailMode = 0

	// FailClosed denies the call (legacy 1.x behaviour). The original
	// rationale was "an unannotated procedure is a bug", which holds for
	// mature services but blows up new ones. Opt in explicitly when the
	// project's policy is "no policy means no access".
	FailClosed FailMode = 1
)

// RolesDecider is a convenience [Decider] implementation that allows a
// call when the authenticated user has at least one of the configured
// roles for the requested method.
//
// MethodRoles maps the canonical method identifier (Connect procedure or
// "<action>:<resource>") to the slice of allowed roles. An entry whose
// value is an empty slice grants access to any authenticated user.
//
// MethodAuthRequired (optional) records which methods require authentication.
// When set, a method with MethodAuthRequired[method] == false is allowed
// unconditionally — no claims required. This is the data shape the forge
// authorizer_gen.go shim feeds in from proto annotations
// (auth_required + required_roles per RPC).
//
// When MethodRoles has no entry for the method, behaviour is governed by
// the combination of FailMode + Default. See [FailMode] for the rationale
// behind the open-by-default choice. Default still applies under FailOpen
// — set Default to e.g. []string{"admin"} to require admin for unknown
// procedures while still permitting the warn-then-allow shape for known
// procedures whose required-roles slice happens to be empty.
//
// This is offered as a building block, not a mandate: the design stays
// interface-driven so projects can swap in OPA, Casbin, or hand-rolled
// matchers without touching the generated shim.
type RolesDecider struct {
	// MethodRoles is the per-method allow-list.
	MethodRoles map[string][]string

	// MethodAuthRequired flips per-method auth on or off. Optional; when
	// nil, every method is treated as authenticated (matches Default).
	MethodAuthRequired map[string]bool

	// Default is consulted when MethodRoles has no entry for the method.
	// nil → fall through to FailMode (open allows, closed denies);
	// empty slice → allow any authenticated user (overrides FailMode).
	// A non-empty slice forces role membership even under FailOpen, which
	// lets a project bias toward open-for-known but admin-only for
	// unknown-but-callable procedures.
	Default []string

	// FailMode governs the unknown-method branch. Defaults to FailOpen so
	// uninitialised scaffolds don't 403 every RPC in staging — see the
	// [FailMode] doc for the longer rationale.
	FailMode FailMode

	// OnUnknownMethod is called once per unknown-method event (allow or
	// deny, depending on FailMode) so the foot-gun shows up in server logs
	// alongside the response. nil (the default) emits a slog.Default().Warn
	// line; pass a no-op to silence (e.g. under attack traffic that hammers
	// random procedure names) or wire a project-specific log shape.
	// Unknown here covers BOTH the MethodAuthRequired-missing and the
	// MethodRoles-missing-with-nil-Default branches — they share the
	// same operator-visible symptom ("regenerate or check the proto")
	// so they share the same signal.
	OnUnknownMethod func(method string)
}

// Decide implements [Decider] for [RolesDecider].
func (r RolesDecider) Decide(ctx context.Context, method string, claims *auth.Claims) error {
	if r.MethodAuthRequired != nil {
		authReq, known := r.MethodAuthRequired[method]
		if !known {
			// Unknown procedure: warn so the missing annotation surfaces,
			// then dispatch on FailMode. FailOpen (the zero value) allows
			// the call so a fresh scaffold's empty-map authorizer doesn't
			// 403 every RPC; FailClosed preserves the legacy 1.x deny.
			r.warnUnknownMethod(method)
			if r.FailMode == FailClosed {
				return Deny("unknown method %q is denied by default", method)
			}
			return nil
		}
		if !authReq {
			return nil // method opted out of auth via proto annotation
		}
	}
	roles, ok := r.MethodRoles[method]
	if !ok {
		if r.Default == nil {
			// Same FailMode dispatch as the MethodAuthRequired-miss branch.
			r.warnUnknownMethod(method)
			if r.FailMode == FailClosed {
				return Deny("unknown method %q is denied by default", method)
			}
			return nil
		}
		roles = r.Default
	}
	if claims == nil {
		return connect.NewError(connect.CodeUnauthenticated, fmt.Errorf("authentication required"))
	}
	if len(roles) == 0 {
		return nil // any authenticated user is allowed
	}
	for _, want := range roles {
		if claims.Role == want {
			return nil
		}
		for _, have := range claims.Roles {
			if have == want {
				return nil
			}
		}
	}
	return Deny("requires one of roles %v", roles)
}

// warnUnknownMethod surfaces the foot-gun: a procedure reached the
// authorizer with no entry in the codegen'd tables, which usually means
// the proto has drifted from the running binary (forgotten regen, new
// RPC not yet in `forge generate` output, hand-mounted endpoint outside
// the proto). The default uses slog.Default() so projects that have
// configured a logger get structured output for free; projects that
// haven't still see something on stderr. Override via OnUnknownMethod
// to plug into a project-specific log shape or to rate-limit / silence
// under attack-traffic shaped at random procedure names.
func (r RolesDecider) warnUnknownMethod(method string) {
	if r.OnUnknownMethod != nil {
		r.OnUnknownMethod(method)
		return
	}
	slog.Default().Warn("authz: unknown method — regenerate proto bindings (`forge generate`) or check that this procedure exists in the .proto (FailOpen allows by default; set RolesDecider.FailMode=FailClosed to deny)",
		"method", method,
	)
}
