package cli

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/reliant-labs/forge/internal/checksums"
	"github.com/reliant-labs/forge/internal/codegen"
	"github.com/reliant-labs/forge/internal/config"
)

// refreshFrontendRuntimeConfigs re-renders every frontend's runtime config
// document (config.js) from the environment's CURRENT KCL, and reports how
// many it actually changed.
//
// # The bug this closes
//
// One value in that document cannot be declared: an OIDC client's
// `client_id` is generated by the IdP when the application is registered.
// The idp-provision job registers it and publishes the result into
// deploy/kcl/dev/idp_identity_gen.k, which the env's config.k imports — so
// after the job, the declared value is right.
//
// But config.js is rendered by `forge generate`, and the job runs during
// `forge run`. On a FRESH project those happen in that order exactly once,
// with the wrong result: generate renders the document while the client id
// is still the empty stub, the job then publishes the real one, and nothing
// re-reads it. The browser gets `"OIDC_CLIENT_ID": ""` — which the frontend
// correctly interprets as the no-auth posture — and a first sign-in is
// impossible until the developer runs `forge generate` a second time, for
// a reason nothing on screen names.
//
// A second `forge generate` did fix it, which is what makes this the worst
// kind of bug: everything works for anyone who happens to regenerate, and
// nothing works for someone following the documented path.
//
// # Why re-render here rather than reorder generate
//
// The ordering cannot be fixed by moving generate. The client id does not
// exist until a running IdP has been asked for it, so no amount of
// rearranging generate-time steps can produce it — the value is only
// knowable AFTER the job, and the job needs a stack that is already up.
// This is a converge-then-publish dependency, and the honest shape for one
// is to re-read the published value once it exists.
//
// It re-renders the whole document rather than patching the one field on
// purpose: the document is a projection of the env's KCL, and rendering it
// through the same evaluator generate uses is what keeps this from becoming
// a second, subtly different opinion about what config.js should contain.
// Any other value the jobs converged rides along for free.
//
// It is a NO-OP when nothing changed, which is the normal case from the
// second run on — the identity is already published and the rendered bytes
// are identical, so the file is not rewritten and nothing is reported.
//
// Best-effort by design: this improves a document that already exists, so a
// render failure is reported and the dev loop continues. Blocking a `forge
// run` on it would trade a working stack with a stale client id for no
// stack at all.
func refreshFrontendRuntimeConfigs(cfg *config.ProjectConfig, projectDir, envName string) (int, error) {
	if cfg == nil || len(cfg.Frontends) == 0 {
		return 0, nil
	}
	docs, err := renderFrontendRuntimeDocs(projectDir, envName)
	if err != nil {
		return 0, fmt.Errorf("render frontend runtime config: %w", err)
	}
	return writeFrontendRuntimeDocs(cfg, projectDir, docs)
}

// writeFrontendRuntimeDocs writes each rendered document to the path its
// frontend actually serves it from, and reports how many CHANGED.
//
// Split from the render so the two halves are testable apart: rendering
// needs a project with a compiled proto descriptor, while the behaviour
// that was broken — a freshly published value not reaching the served file
// — is entirely in the writing. The render half's own property (that it
// reads whatever idp-provision last published) is covered by
// TestScaffoldedIdentityConfigKRenders.
func writeFrontendRuntimeDocs(cfg *config.ProjectConfig, projectDir string, docs map[string]string) (int, error) {
	if cfg == nil || len(cfg.Frontends) == 0 || len(docs) == 0 {
		return 0, nil
	}

	// The checksum ledger is loaded and saved around the writes so a file
	// forge owns stays stamped the way `forge generate` stamps it. Skipping
	// that would make the next generate see a Tier-1 file whose content it
	// did not record — i.e. report drift for a file forge itself wrote.
	cs, err := checksums.Load(projectDir)
	if err != nil {
		return 0, fmt.Errorf("load checksums: %w", err)
	}

	changed := 0
	for _, fe := range cfg.Frontends {
		body, ok := docs[fe.Name]
		if !ok {
			continue
		}
		staticDir := frontendStaticDir(fe.Type)
		if staticDir == "" {
			continue // react-native serves no static asset root
		}
		feDir, ok := fe.Dir(projectDir)
		if !ok {
			// No directory in this repository — a cross-repo
			// source pin, or a path outside the project root.
			continue
		}
		rel := filepath.Join(feDir, staticDir, codegen.FrontendConfigJSFile)
		// Unchanged is the common case; comparing first keeps a no-op run
		// from touching the file's mtime, which a watching dev server would
		// otherwise treat as a reason to reload.
		//
		// Compared by BODY HASH, not by raw bytes. The file on disk carries
		// a `forge:hash=` stamp that the writer adds and this render does
		// not, so a byte comparison never matches and every single run
		// reports a change it did not make.
		if existing, rerr := os.ReadFile(filepath.Join(projectDir, rel)); rerr == nil &&
			checksums.BodyHash(existing) == checksums.BodyHash([]byte(body)) {
			continue
		}
		if err := os.MkdirAll(filepath.Join(projectDir, feDir, staticDir), 0o755); err != nil {
			return changed, fmt.Errorf("create static dir for %s: %w", fe.Name, err)
		}
		if _, err := checksums.WriteGeneratedFileTier1(projectDir, rel, []byte(body), cs, true); err != nil {
			return changed, fmt.Errorf("write config.js for %s: %w", fe.Name, err)
		}
		changed++
	}
	if changed > 0 {
		if err := checksums.Save(projectDir, cs); err != nil {
			return changed, fmt.Errorf("save checksums: %w", err)
		}
	}
	return changed, nil
}
