package cli

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/reliant-labs/forge/internal/checksums"
	"github.com/reliant-labs/forge/internal/config"
)

// TestGenerateFrontendNav_EmitsBasePathGen asserts that the per-frontend
// codegen pass emits `src/lib/basepath_gen.ts` as a Tier-1 (tracked,
// always-regenerated) file, baking forge.yaml's `frontends[].base_path`
// as the fallback for the single canonical env var NEXT_PUBLIC_BASE_PATH.
//
// The helper is the browser-side half of basePath support: Next.js's
// <Link>/router prepend the prefix automatically, but hand-built URLs
// (window.location-based payment redirects, share links) need
// joinBasePath() — and that helper must track forge.yaml, not a
// hand-baked string literal.
func TestGenerateFrontendNav_EmitsBasePathGen(t *testing.T) {
	projectDir := t.TempDir()
	cfg := &config.ProjectConfig{
		Name: "demo",
		Frontends: []config.FrontendConfig{
			{Name: "admin", Type: "nextjs", BasePath: "/admin"},
		},
	}
	cs := &checksums.FileChecksums{Files: make(map[string]checksums.FileChecksumEntry)}

	if err := generateFrontendNav(cfg, nil, projectDir, nil, cs); err != nil {
		t.Fatalf("generateFrontendNav: %v", err)
	}

	rel := filepath.Join("frontends", "admin", "src", "lib", "basepath_gen.ts")
	body, err := os.ReadFile(filepath.Join(projectDir, rel))
	if err != nil {
		t.Fatalf("expected basepath_gen.ts after generate, got: %v", err)
	}
	s := string(body)

	for _, want := range []string{
		"// Code generated by forge. DO NOT EDIT.",
		`process.env.NEXT_PUBLIC_BASE_PATH ?? "/admin"`,
		"export const BASE_PATH",
		"export function joinBasePath(path: string): string {",
	} {
		if !strings.Contains(s, want) {
			t.Errorf("basepath_gen.ts missing %q; got:\n%s", want, s)
		}
	}

	// Tier-1 tracked: the checksums manifest must carry the entry with
	// Tier == 1 so (a) hand-edits trip the stomp guard and (b) the
	// stale-cleanup sweep sees the file as live codegen.
	entry, ok := cs.Files[rel]
	if !ok {
		t.Fatalf("basepath_gen.ts not recorded in checksums manifest; have: %v", cs.Files)
	}
	if entry.Tier != 1 {
		t.Errorf("basepath_gen.ts recorded with Tier=%d, want Tier=1", entry.Tier)
	}
}

// TestGenerateFrontendNav_BasePathGen_RegenIdempotent pins regen
// idempotency: a second `forge generate` over an unchanged forge.yaml
// must reproduce basepath_gen.ts byte-identically (no churn in diffs,
// no checksum drift), and editing base_path in forge.yaml must
// propagate on the next run without re-scaffolding the frontend.
func TestGenerateFrontendNav_BasePathGen_RegenIdempotent(t *testing.T) {
	projectDir := t.TempDir()
	cfg := &config.ProjectConfig{
		Name: "demo",
		Frontends: []config.FrontendConfig{
			{Name: "admin", Type: "nextjs", BasePath: "/admin"},
		},
	}
	cs := &checksums.FileChecksums{Files: make(map[string]checksums.FileChecksumEntry)}

	if err := generateFrontendNav(cfg, nil, projectDir, nil, cs); err != nil {
		t.Fatalf("first generateFrontendNav: %v", err)
	}
	path := filepath.Join(projectDir, "frontends", "admin", "src", "lib", "basepath_gen.ts")
	first, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read after first run: %v", err)
	}

	if err := generateFrontendNav(cfg, nil, projectDir, nil, cs); err != nil {
		t.Fatalf("second generateFrontendNav: %v", err)
	}
	second, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read after second run: %v", err)
	}
	if string(first) != string(second) {
		t.Errorf("basepath_gen.ts is not regen-idempotent.\nfirst:\n%s\nsecond:\n%s", first, second)
	}

	// Changing base_path in forge.yaml must flow through on the next run.
	cfg.Frontends[0].BasePath = "/console"
	if err := generateFrontendNav(cfg, nil, projectDir, nil, cs); err != nil {
		t.Fatalf("third generateFrontendNav (base_path changed): %v", err)
	}
	third, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read after third run: %v", err)
	}
	if !strings.Contains(string(third), `process.env.NEXT_PUBLIC_BASE_PATH ?? "/console"`) {
		t.Errorf("basepath_gen.ts did not pick up the edited base_path; got:\n%s", third)
	}
}

// TestGenerateFrontendNav_BasePathGen_EmptyBasePath asserts the
// no-base_path shape: the helper is still emitted (so call sites can
// import joinBasePath unconditionally) with an empty baked fallback —
// NEXT_PUBLIC_BASE_PATH remains the only way to set a prefix.
func TestGenerateFrontendNav_BasePathGen_EmptyBasePath(t *testing.T) {
	projectDir := t.TempDir()
	cfg := &config.ProjectConfig{
		Name: "demo",
		Frontends: []config.FrontendConfig{
			{Name: "web", Type: "nextjs"},
		},
	}
	cs := &checksums.FileChecksums{Files: make(map[string]checksums.FileChecksumEntry)}

	if err := generateFrontendNav(cfg, nil, projectDir, nil, cs); err != nil {
		t.Fatalf("generateFrontendNav: %v", err)
	}
	body, err := os.ReadFile(filepath.Join(projectDir, "frontends", "web", "src", "lib", "basepath_gen.ts"))
	if err != nil {
		t.Fatalf("expected basepath_gen.ts even without base_path, got: %v", err)
	}
	if !strings.Contains(string(body), `process.env.NEXT_PUBLIC_BASE_PATH ?? ""`) {
		t.Errorf("basepath_gen.ts (no base_path) must bake an empty fallback; got:\n%s", body)
	}
}
