// File: internal/cli/generate_validate_tests_test.go
//
// The validate step's second half: generated _test.go files must be
// typechecked. `go build ./...` does not compile test files, which is
// how `forge generate` printed "✅ Code generation complete — 36
// file(s) written" over a tree whose generated helpers_gen_test.go was
// not valid Go. The user found out later, from a contract-linter
// "packages failed to load" and a "[build failed]" test run, neither of
// which named the real cause.

package cli

import (
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// writeValidateFixture lays down a minimal module. Every file in extra
// is written verbatim, so a test can add a broken _test.go.
func writeValidateFixture(t *testing.T, extra map[string]string) string {
	t.Helper()
	dir := t.TempDir()
	files := map[string]string{
		"go.mod": "module example.com/validateapp\n\ngo 1.22\n",
		"lib.go": "package validateapp\n\nfunc F() int { return 1 }\n",
	}
	for k, v := range extra {
		files[k] = v
	}
	for rel, content := range files {
		full := filepath.Join(dir, filepath.FromSlash(rel))
		if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
			t.Fatalf("mkdir: %v", err)
		}
		if err := os.WriteFile(full, []byte(content), 0o644); err != nil {
			t.Fatalf("write %s: %v", rel, err)
		}
	}
	return dir
}

// TestRunGoBuildValidate_RejectsUncompilableTestFile is the regression
// for the shipped-broken-tree bug. The non-test code compiles cleanly,
// so `go build ./...` is green; only the _test.go is broken. Validation
// must fail anyway.
func TestRunGoBuildValidate_RejectsUncompilableTestFile(t *testing.T) {
	if testing.Short() {
		t.Skip("spawns a real typecheck over a temp module; full mode only")
	}
	dir := writeValidateFixture(t, map[string]string{
		// The generated-helper shape: a stub method returning a
		// composite literal for an interface. This is precisely what
		// zeroValueForResultType now prevents, kept here as the
		// end-to-end proof that the GATE catches it even if a future
		// generator regresses.
		// The forge:hash marker is REQUIRED for this fixture to exercise the
		// fail path: validateTestFilesTypecheck splits diagnostics by
		// ownership, and only a forge-OWNED test file fails the run. A
		// user-owned one warns, deliberately — failing generate over a file
		// the user can fix would deadlock the command they would reach for to
		// refresh what it compiles against. Without the marker this fixture
		// asserted the wrong half of that contract.
		"helpers_gen_test.go": "// Code generated by forge. DO NOT EDIT.\n" +
			// ASSEMBLED, never written out literally. A contiguous
			// `forge:hash=<64 hex>` in this source lands in the file's own
			// scanned head, and `forge ci verify-generated` then reads it as
			// THIS file's marker and reports the test file as a hand-edited
			// generated file. The fixture needs the marker; the repository
			// must not appear to carry one.
			"// forge:hash=" + strings.Repeat("0", 64) + "\n" + `package validateapp

type Store interface{ WithTx() Store }

type stubStore struct{}

func (stubStore) WithTx() Store { return Store{} }
`,
	})

	_, restore := captureStderr(t)
	err := runGoBuildValidate(dir)
	restore()

	if err == nil {
		t.Fatal("validation must fail when a _test.go file does not compile — " +
			"`go build ./...` alone skips test files, which is how a broken tree shipped as '✅ complete'")
	}
	if !strings.Contains(err.Error(), "helpers_gen_test.go") &&
		!strings.Contains(errOutputOf(err), "helpers_gen_test.go") {
		t.Errorf("the failure must name the offending test file so the user isn't left guessing; got: %v\n%s",
			err, errOutputOf(err))
	}
}

// TestRunGoBuildValidate_IgnoresVetStyleFindings is the guard that
// rules out plain `go vet ./...` as the implementation. Vet's analyzer
// suite reports real-but-non-fatal lint findings in HAND-WRITTEN code
// (measured: a fmt.Printf arity bug exits 1 while go build exits 0).
// Failing `forge generate` on those would break generation for projects
// that are entirely valid, so the check must be a pure TYPECHECK.
func TestRunGoBuildValidate_IgnoresVetStyleFindings(t *testing.T) {
	if testing.Short() {
		t.Skip("spawns a real typecheck over a temp module; full mode only")
	}
	dir := writeValidateFixture(t, map[string]string{
		"printf.go": `package validateapp

import "fmt"

// A genuine vet finding (format arity), but valid Go that compiles.
func G() { fmt.Printf("%d\n") }
`,
		"ok_test.go": "package validateapp\n\nfunc use() int { return F() }\n",
	})

	_, restore := captureStderr(t)
	err := runGoBuildValidate(dir)
	restore()

	if err != nil {
		t.Fatalf("a vet-style lint finding in hand-written code must NOT fail generation "+
			"(the tree compiles); got: %v\n%s", err, errOutputOf(err))
	}
}

// errOutputOf digs the captured compiler/typecheck text out of a
// validateBuildError so assertions can read it.
func errOutputOf(err error) string {
	var ve *validateBuildError
	if errors.As(err, &ve) {
		return ve.Output
	}
	return ""
}

// TestRunGoBuildValidate_WarnsOnUserOwnedTestFile is the complement, and the
// reason the fixture above needs an ownership marker at all.
//
// A USER-owned _test.go that does not compile must NOT fail the run. Failing
// it would deadlock the user: `forge generate` is exactly what they would
// reach for to refresh the generated code their half-written test compiles
// against, and forge will never rewrite their file for them. So it warns.
func TestRunGoBuildValidate_WarnsOnUserOwnedTestFile(t *testing.T) {
	if testing.Short() {
		t.Skip("spawns a real typecheck over a temp module; full mode only")
	}
	dir := writeValidateFixture(t, map[string]string{
		// Same defect as above, no forge marker — the user's own file.
		"mine_test.go": `package validateapp

type Store interface{ WithTx() Store }

type stubStore struct{}

func (stubStore) WithTx() Store { return Store{} }
`,
	})

	_, restore := captureStderr(t)
	err := runGoBuildValidate(dir)
	restore()

	if err != nil {
		t.Fatalf("a user-owned uncompilable _test.go must not fail generate — that deadlocks the "+
			"command that would refresh what it compiles against. got: %v", err)
	}
}

// TestRunGoBuildValidate_LoneMainPackageInSubdir is the F3 regression. With
// exactly one main package, bare `go build ./...` WRITES a binary named
// after its directory; for a main at ./echo that collides with the
// directory itself ("build output "echo" already exists and is a
// directory") and generate refused a valid project. Validation must be a
// pure compile check that writes nothing into the project.
func TestRunGoBuildValidate_LoneMainPackageInSubdir(t *testing.T) {
	if testing.Short() {
		t.Skip("spawns a real go build over a temp module; full mode only")
	}
	// ./echo must be the ONLY package: go writes a binary only when the
	// pattern matches exactly one, so writeValidateFixture's root lib.go
	// would mask the bug.
	dir := t.TempDir()
	for rel, body := range map[string]string{
		"go.mod":       "module example.com/e2eh\n\ngo 1.22\n",
		"echo/main.go": "package main\n\nfunc main() {}\n",
	} {
		full := filepath.Join(dir, filepath.FromSlash(rel))
		if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(full, []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	before, _ := os.ReadDir(dir)

	_, restore := captureStderr(t)
	err := runGoBuildValidate(dir)
	restore()

	if err != nil {
		t.Fatalf("a project whose only main package is ./echo must validate; got: %v\n%s", err, errOutputOf(err))
	}
	after, _ := os.ReadDir(dir)
	if len(after) != len(before) {
		t.Errorf("validation wrote into the project: %d entries before, %d after", len(before), len(after))
	}
}
