package cli

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/reliant-labs/forge/internal/checksums"
)

// newSkillsPipelineCtx builds a minimal pipelineContext for exercising
// stepAgentSkills against a temp project root.
func newSkillsPipelineCtx(t *testing.T) *pipelineContext {
	t.Helper()
	root := t.TempDir()
	return &pipelineContext{
		ProjectDir: root,
		AbsPath:    root,
		Checksums:  &checksums.FileChecksums{Files: map[string]checksums.FileChecksumEntry{}},
	}
}

// TestStepAgentSkillsWritesTier1 verifies the core delivery contract:
// every forge-shipped skill lands under .claude/skills/<flat>/SKILL.md,
// tracked as Tier-1, with frontmatter at byte 0 and the generated-by
// banner immediately after it.
func TestStepAgentSkillsWritesTier1(t *testing.T) {
	ctx := newSkillsPipelineCtx(t)
	if err := stepAgentSkills(ctx); err != nil {
		t.Fatalf("stepAgentSkills: %v", err)
	}

	skills, err := listForgeShippedSkills()
	if err != nil {
		t.Fatalf("listForgeShippedSkills: %v", err)
	}
	if len(skills) == 0 {
		t.Fatal("no forge-shipped skills found")
	}

	for _, s := range skills {
		rel := agentSkillRelPath(s.Path)
		if s.Relevance == SkillRelevanceMigration {
			// One-time migration skills are not delivered to projects.
			if _, err := os.Stat(filepath.Join(ctx.AbsPath, rel)); !os.IsNotExist(err) {
				t.Errorf("migration skill %q was delivered to %s; want skipped", s.Path, rel)
			}
			if _, tracked := ctx.Checksums.Files[rel]; tracked {
				t.Errorf("migration skill %q has a checksum entry; want untracked", s.Path)
			}
			continue
		}
		body, err := os.ReadFile(filepath.Join(ctx.AbsPath, rel))
		if err != nil {
			t.Fatalf("skill %q not written to %s: %v", s.Path, rel, err)
		}
		if !bytes.HasPrefix(body, []byte("---\n")) {
			t.Errorf("%s: frontmatter must stay at byte 0", rel)
		}
		if !bytes.Contains(body, []byte("Code generated by forge")) {
			t.Errorf("%s: missing generated-by banner", rel)
		}
		entry, ok := ctx.Checksums.Files[rel]
		if !ok {
			t.Errorf("%s: no checksum entry recorded", rel)
		} else if entry.Tier != 1 {
			t.Errorf("%s: Tier = %d, want 1", rel, entry.Tier)
		}
	}
}

// TestStepAgentSkillsBannerAfterFrontmatter pins the banner placement:
// the line directly after the frontmatter close must be the banner.
func TestStepAgentSkillsBannerAfterFrontmatter(t *testing.T) {
	ctx := newSkillsPipelineCtx(t)
	if err := stepAgentSkills(ctx); err != nil {
		t.Fatalf("stepAgentSkills: %v", err)
	}
	body, err := os.ReadFile(filepath.Join(ctx.AbsPath, agentSkillRelPath("db")))
	if err != nil {
		t.Fatalf("read db skill: %v", err)
	}
	s := string(body)
	end := strings.Index(s[4:], "\n---")
	if end < 0 {
		t.Fatal("db skill has no frontmatter close")
	}
	after := s[4+end+1:]
	// Skip the closing "---" line itself.
	nl := strings.IndexByte(after, '\n')
	bannerLine := after[nl+1:]
	if !strings.HasPrefix(bannerLine, "<!-- Code generated by forge ") {
		t.Errorf("line after frontmatter close is not the banner: %q", bannerLine[:min(len(bannerLine), 80)])
	}
}

// TestStepAgentSkillsRefreshesStaleScaffoldCopy verifies the tier
// transition: a pre-existing, untracked (scaffold-era) skill file whose
// content differs from the fresh render is overwritten — NOT preserved
// as a precious user edit.
func TestStepAgentSkillsRefreshesStaleScaffoldCopy(t *testing.T) {
	ctx := newSkillsPipelineCtx(t)
	rel := agentSkillRelPath("db")
	full := filepath.Join(ctx.AbsPath, rel)
	if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
		t.Fatal(err)
	}
	stale := []byte("---\nname: db\n---\n# Ancient scaffold-era guidance\n")
	if err := os.WriteFile(full, stale, 0o644); err != nil {
		t.Fatal(err)
	}

	if err := stepAgentSkills(ctx); err != nil {
		t.Fatalf("stepAgentSkills: %v", err)
	}

	got, err := os.ReadFile(full)
	if err != nil {
		t.Fatal(err)
	}
	if bytes.Contains(got, []byte("Ancient scaffold-era guidance")) {
		t.Error("stale scaffold copy was preserved; want overwrite")
	}
	if entry := ctx.Checksums.Files[rel]; entry.Tier != 1 {
		t.Errorf("Tier = %d after migration, want 1", entry.Tier)
	}
}

// TestStepAgentSkillsMigratesTier2Entry verifies that an entry previously
// tracked as Tier-2 (scaffold-once) migrates to Tier-1 and gets the fresh
// render even though its on-disk content matches the old recorded hash.
func TestStepAgentSkillsMigratesTier2Entry(t *testing.T) {
	ctx := newSkillsPipelineCtx(t)
	rel := agentSkillRelPath("testing")
	full := filepath.Join(ctx.AbsPath, rel)
	if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
		t.Fatal(err)
	}
	old := []byte("---\nname: testing\n---\nold tier-2 body\n")
	if err := os.WriteFile(full, old, 0o644); err != nil {
		t.Fatal(err)
	}
	ctx.Checksums.RecordFile(rel, old)
	entry := ctx.Checksums.Files[rel]
	entry.Tier = 2
	ctx.Checksums.Files[rel] = entry

	if err := stepAgentSkills(ctx); err != nil {
		t.Fatalf("stepAgentSkills: %v", err)
	}

	got, err := os.ReadFile(full)
	if err != nil {
		t.Fatal(err)
	}
	if bytes.Contains(got, []byte("old tier-2 body")) {
		t.Error("Tier-2 era content survived; want fresh render")
	}
	if e := ctx.Checksums.Files[rel]; e.Tier != 1 {
		t.Errorf("Tier = %d after migration, want 1", e.Tier)
	}
}

// TestStepAgentSkillsNeverTouchesUserSkillDirs pins the scoping contract:
// directories under .claude/skills/ that are not forge-shipped skills are
// left alone.
func TestStepAgentSkillsNeverTouchesUserSkillDirs(t *testing.T) {
	ctx := newSkillsPipelineCtx(t)
	userSkill := filepath.Join(ctx.AbsPath, ".claude", "skills", "my-own-skill", "SKILL.md")
	if err := os.MkdirAll(filepath.Dir(userSkill), 0o755); err != nil {
		t.Fatal(err)
	}
	userBody := []byte("---\nname: my-own-skill\n---\nmine\n")
	if err := os.WriteFile(userSkill, userBody, 0o644); err != nil {
		t.Fatal(err)
	}

	if err := stepAgentSkills(ctx); err != nil {
		t.Fatalf("stepAgentSkills: %v", err)
	}

	got, err := os.ReadFile(userSkill)
	if err != nil {
		t.Fatalf("user skill removed: %v", err)
	}
	if !bytes.Equal(got, userBody) {
		t.Error("user-created skill content was modified")
	}
	if _, tracked := ctx.Checksums.Files[filepath.Join(".claude", "skills", "my-own-skill", "SKILL.md")]; tracked {
		t.Error("user-created skill must not be checksum-tracked")
	}
}

// TestStepAgentSkillsIdempotent verifies a second run rewrites the same
// bytes (no churn).
func TestStepAgentSkillsIdempotent(t *testing.T) {
	ctx := newSkillsPipelineCtx(t)
	if err := stepAgentSkills(ctx); err != nil {
		t.Fatal(err)
	}
	rel := agentSkillRelPath("db")
	first, err := os.ReadFile(filepath.Join(ctx.AbsPath, rel))
	if err != nil {
		t.Fatal(err)
	}
	if err := stepAgentSkills(ctx); err != nil {
		t.Fatal(err)
	}
	second, err := os.ReadFile(filepath.Join(ctx.AbsPath, rel))
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(first, second) {
		t.Error("second run produced different bytes — skill render is not deterministic")
	}
}

// TestStepAgentSkillsGCsRetiredSkill verifies the transition contract:
// a skill forge previously delivered as Tier-1 (here: a migration skill
// from before migration skills were excluded from delivery, or any
// renamed/retired skill) is removed from disk and from the manifest on
// the next regen.
func TestStepAgentSkillsGCsRetiredSkill(t *testing.T) {
	ctx := newSkillsPipelineCtx(t)

	for _, retired := range []string{"migrations/v0.x-to-contractkit", "api-handlers"} {
		rel := agentSkillRelPath(retired)
		full := filepath.Join(ctx.AbsPath, rel)
		if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
			t.Fatal(err)
		}
		// Simulate the previous regen's render: frontmatter + forge banner.
		body := []byte("---\nname: " + retired + "\n---\n<!-- Code generated by forge v0.0.1. DO NOT EDIT -->\nold guidance\n")
		if err := os.WriteFile(full, body, 0o644); err != nil {
			t.Fatal(err)
		}
		ctx.Checksums.RecordFile(rel, body)
		entry := ctx.Checksums.Files[rel]
		entry.Tier = 1
		ctx.Checksums.Files[rel] = entry
	}

	if err := stepAgentSkills(ctx); err != nil {
		t.Fatalf("stepAgentSkills: %v", err)
	}

	for _, retired := range []string{"migrations/v0.x-to-contractkit", "api-handlers"} {
		rel := agentSkillRelPath(retired)
		full := filepath.Join(ctx.AbsPath, rel)
		if _, err := os.Stat(full); !os.IsNotExist(err) {
			t.Errorf("retired skill %s still on disk; want removed", rel)
		}
		if _, err := os.Stat(filepath.Dir(full)); !os.IsNotExist(err) {
			t.Errorf("retired skill dir %s still on disk; want pruned", filepath.Dir(full))
		}
		if _, tracked := ctx.Checksums.Files[rel]; tracked {
			t.Errorf("retired skill %s still checksum-tracked; want manifest entry dropped", rel)
		}
	}
}

// TestStepAgentSkillsGCKeepsUserReplacedFile pins the banner backstop:
// a tracked-but-retired path whose content the user replaced (no forge
// banner) keeps its file — only the manifest entry is dropped.
func TestStepAgentSkillsGCKeepsUserReplacedFile(t *testing.T) {
	ctx := newSkillsPipelineCtx(t)
	rel := agentSkillRelPath("migrations/v0.1-to-v0.2")
	full := filepath.Join(ctx.AbsPath, rel)
	if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
		t.Fatal(err)
	}
	userBody := []byte("---\nname: mine\n---\nhand-written replacement, no banner\n")
	if err := os.WriteFile(full, userBody, 0o644); err != nil {
		t.Fatal(err)
	}
	ctx.Checksums.RecordFile(rel, []byte("what forge originally wrote"))
	entry := ctx.Checksums.Files[rel]
	entry.Tier = 1
	ctx.Checksums.Files[rel] = entry

	if err := stepAgentSkills(ctx); err != nil {
		t.Fatalf("stepAgentSkills: %v", err)
	}

	got, err := os.ReadFile(full)
	if err != nil {
		t.Fatalf("user-replaced file was removed: %v", err)
	}
	if !bytes.Equal(got, userBody) {
		t.Error("user-replaced file content changed")
	}
	if _, tracked := ctx.Checksums.Files[rel]; tracked {
		t.Error("manifest entry for user-replaced retired skill should be dropped")
	}
}

// TestStepAgentSkillsGCDropsMissingEntry verifies that a tracked retired
// skill whose file is already gone from disk just loses its manifest entry.
func TestStepAgentSkillsGCDropsMissingEntry(t *testing.T) {
	ctx := newSkillsPipelineCtx(t)
	rel := agentSkillRelPath("migrations/v0.x-to-testkit")
	ctx.Checksums.RecordFile(rel, []byte("recorded but never on disk"))
	entry := ctx.Checksums.Files[rel]
	entry.Tier = 1
	ctx.Checksums.Files[rel] = entry

	if err := stepAgentSkills(ctx); err != nil {
		t.Fatalf("stepAgentSkills: %v", err)
	}
	if _, tracked := ctx.Checksums.Files[rel]; tracked {
		t.Error("manifest entry for already-deleted retired skill should be dropped")
	}
}
