package cli

import (
	"bytes"
	"strings"
	"testing"
)

// TestRenderAgentSkillInjectsPreamble pins that every forge-generated
// skill carries the shared agent-operation preamble, placed after the
// generated-by banner and before the skill body. The preamble is defined
// once (agentOperationPreamble) and injected by renderAgentSkill, so this
// guards against a future refactor dropping or duplicating it.
func TestRenderAgentSkillInjectsPreamble(t *testing.T) {
	body := []byte("# Some skill\n\nbody text\n")
	out := renderAgentSkill(skillMeta{Path: "db", Name: "db"}, body)
	s := string(out)

	marker := "Operating forge as an agent."
	if !strings.Contains(s, marker) {
		t.Fatalf("rendered skill missing preamble marker %q\n---\n%s", marker, s)
	}

	bannerIdx := strings.Index(s, "Code generated by forge")
	preambleIdx := strings.Index(s, marker)
	bodyIdx := strings.Index(s, "# Some skill")
	if bannerIdx < 0 || bodyIdx < 0 {
		t.Fatalf("missing banner or body in render:\n%s", s)
	}
	if !(bannerIdx < preambleIdx && preambleIdx < bodyIdx) {
		t.Errorf("preamble out of order: banner=%d preamble=%d body=%d", bannerIdx, preambleIdx, bodyIdx)
	}

	// The preamble must be a single shared definition — assert the body
	// of the constant appears exactly once so a render never duplicates it.
	if n := bytes.Count(out, []byte(marker)); n != 1 {
		t.Errorf("preamble marker appears %d times, want exactly 1", n)
	}

	// Spot-check the load-bearing operating instructions are present.
	for _, want := range []string{
		"non-interactive without a TTY",
		"runbook",
		"Background long-running commands",
		"gcloud auth login",
		"project's own skills directory",
	} {
		if !strings.Contains(s, want) {
			t.Errorf("preamble missing expected guidance %q", want)
		}
	}
}
