package cli

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/jinzhu/inflection"
	"github.com/reliant-labs/forge/internal/codegen"
	"github.com/reliant-labs/forge/internal/config"
	"github.com/reliant-labs/forge/internal/templates"
)

// generateFrontendMocks generates TypeScript mock data files and a mock
// transport for each Next.js frontend. Mock data files contain typed arrays
// derived from entity definitions using the same deterministic values as
// db/fixtures. The mock transport intercepts ConnectRPC calls and returns
// fixture data, enabled via NEXT_PUBLIC_MOCK_API=true.
func generateFrontendMocks(cfg *config.ProjectConfig, services []codegen.ServiceDef, entities []codegen.EntityDef, projectDir string) error {
	if len(entities) == 0 || len(services) == 0 {
		return nil
	}

	// Load templates
	mockDataTmplContent, err := templates.FrontendTemplates.Get(filepath.Join("mocks", "mock-data.ts.tmpl"))
	if err != nil {
		return fmt.Errorf("read mock-data template: %w", err)
	}
	mockDataTmpl, err := template.New("mock-data.ts.tmpl").Funcs(templates.FuncMap()).Parse(string(mockDataTmplContent))
	if err != nil {
		return fmt.Errorf("parse mock-data template: %w", err)
	}

	mockTransportTmplContent, err := templates.FrontendTemplates.Get(filepath.Join("mocks", "mock-transport.ts.tmpl"))
	if err != nil {
		return fmt.Errorf("read mock-transport template: %w", err)
	}
	mockTransportTmpl, err := template.New("mock-transport.ts.tmpl").Funcs(templates.FuncMap()).Parse(string(mockTransportTmplContent))
	if err != nil {
		return fmt.Errorf("parse mock-transport template: %w", err)
	}

	// Build entity→service mapping: match entity names to the service that owns them
	entityToService := buildEntityServiceMap(services, entities)

	// Build mock transport entities for the transport template
	transportEntities := codegen.ExtractMockTransportEntities(services, entities)

	for _, fe := range cfg.Frontends {
		if !strings.EqualFold(fe.Type, "nextjs") {
			continue
		}

		feDir := fe.Path
		if feDir == "" {
			feDir = filepath.Join("frontends", fe.Name)
		}

		mocksDir := filepath.Join(projectDir, feDir, "src", "mocks")
		if err := os.MkdirAll(mocksDir, 0o755); err != nil {
			return fmt.Errorf("create mocks directory: %w", err)
		}

		var mockFileCount int
		var generatedSlugs []string

		// Generate per-entity mock data files
		for _, entity := range entities {
			svc, ok := entityToService[entity.Name]
			if !ok {
				continue
			}

			data := codegen.EntityDefToMockData(entity, svc)

			var buf bytes.Buffer
			if err := mockDataTmpl.Execute(&buf, data); err != nil {
				return fmt.Errorf("render mock data for %s: %w", entity.Name, err)
			}

			slug := codegen.PascalToKebab(inflection.Plural(entity.Name))
			outPath := filepath.Join(mocksDir, slug+".ts")
			if err := os.WriteFile(outPath, buf.Bytes(), 0o644); err != nil {
				return fmt.Errorf("write mock data file %s: %w", outPath, err)
			}
			generatedSlugs = append(generatedSlugs, slug)
			mockFileCount++
		}

		// Generate mock transport
		if len(transportEntities) > 0 {
			transportData := codegen.MockTransportTemplateData{
				Entities: transportEntities,
			}

			var buf bytes.Buffer
			if err := mockTransportTmpl.Execute(&buf, transportData); err != nil {
				return fmt.Errorf("render mock transport: %w", err)
			}

			libDir := filepath.Join(projectDir, feDir, "src", "lib")
			if err := os.MkdirAll(libDir, 0o755); err != nil {
				return fmt.Errorf("create lib directory: %w", err)
			}

			outPath := filepath.Join(libDir, "mock-transport.ts")
			if err := os.WriteFile(outPath, buf.Bytes(), 0o644); err != nil {
				return fmt.Errorf("write mock transport: %w", err)
			}
		}

		// Generate barrel index.ts for mocks
		if mockFileCount > 0 {
			if err := writeMocksIndex(mocksDir, generatedSlugs); err != nil {
				return fmt.Errorf("write mocks index: %w", err)
			}
		}

		fmt.Printf("  ✅ Generated %d mock data file(s) + transport for frontend %s\n", mockFileCount, fe.Name)
	}

	return nil
}

// buildEntityServiceMap creates a mapping from entity name to the service
// that owns the CRUD RPCs for that entity.
func buildEntityServiceMap(services []codegen.ServiceDef, entities []codegen.EntityDef) map[string]codegen.ServiceDef {
	result := make(map[string]codegen.ServiceDef, len(entities))
	for _, svc := range services {
		pages := codegen.ExtractCRUDEntities(svc)
		for _, page := range pages {
			for _, entity := range entities {
				if entity.Name == page.EntityName {
					result[entity.Name] = svc
				}
			}
		}
	}
	return result
}

// writeMocksIndex writes a barrel index.ts that re-exports all mock data files.
func writeMocksIndex(mocksDir string, slugs []string) error {
	var buf bytes.Buffer
	buf.WriteString("// AUTO-GENERATED — DO NOT EDIT\n")
	buf.WriteString("// Generated by forge generate\n\n")

	for _, slug := range slugs {
		buf.WriteString(fmt.Sprintf("export * from \"./%s\";\n", slug))
	}

	return os.WriteFile(filepath.Join(mocksDir, "index.ts"), buf.Bytes(), 0o644)
}