// Manifest-driven stale-artifact cleanup.
//
// Forge's pre-2026-06-05 cleanup walked generated-artifact directories
// (gen/services/, handlers/<svc>/, handlers/mocks/, frontends/<fe>/src/
// hooks/) and removed anything whose name didn't match a re-derived
// "expected" set computed from forge.yaml via serviceNameToPackage. The
// re-derivation produced a compact, separator-free identifier ("admin
// server" → "adminserver") that disagreed with the on-disk reality of
// projects whose proto layout used snake_case directories
// ("admin_server"). cleanup helpfully deleted the user's
// handlers/admin_server/*.go.
//
// The new model deletes only paths that forge itself recorded in
// `.forge/checksums.json`. The manifest is the authoritative record of
// "files forge wrote" — paths NOT in the manifest are user content and
// forge doesn't get to delete them. For each manifest entry, the
// pipeline-run `WrittenThisRun` set tells us whether THIS run touched
// the path; entries we tracked but didn't re-write are stale-candidates.
//
// Two additional guardrails apply before a candidate is actually deleted:
//
//   - Owner-step gate. The tier1OwnerRegistry in generate_tier1_scope.go
//     maps each generated path back to the step that emits it. A path
//     whose owning step is gated off this run (e.g. handlers/.../*_gen.go
//     when codegen is disabled) is left in place; that step wouldn't
//     touch the file regardless of whether the service was renamed, so
//     a missing-from-WrittenThisRun signal is uninformative.
//   - Banner backstop. Even with a manifest entry and an active owner
//     step, we only remove files whose first line declares "Code
//     generated by forge". This catches the unlikely-but-possible race
//     where a manifest entry's content was replaced by user-owned code
//     in the same path between runs.
//
// Paths in the manifest whose on-disk file is missing entirely are
// surfaced (not auto-recreated) so `forge audit` can flag them — the
// inverse of the orphan-gen check. The user may have removed the file
// deliberately or it may be a symptom of a botched lane sync.
package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/reliant-labs/forge/internal/checksums"
	"github.com/reliant-labs/forge/internal/generator"
)

// upgradeManagedPaths is a single-load cache of the upgrade-managed
// path set. The set is constant for the binary's lifetime (it's
// derived from compiled-in upgrade.go file lists), so loading it once
// avoids re-walking the kind/binary matrix every cleanup pass. Tests
// that need to swap it (e.g. to simulate a project shape that doesn't
// have a particular managed file) can do so by reassigning before
// invoking cleanupStaleArtifacts.
var upgradeManagedPaths = generator.UpgradeManagedPaths()

// cleanupStaleArtifacts walks manifest-recorded paths that the current
// pipeline run did not re-emit and returns them as deletion candidates,
// plus the list of manifest-tracked-but-on-disk-missing paths (the
// inverse finding). Both slices are sorted for deterministic test
// output.
//
// Deletion is gated on ctx.ForceCleanup: when true the function deletes
// each candidate (and prunes the manifest entry) as it walks; when false
// it returns the candidate list without touching the filesystem so the
// caller can format a "would delete" warning. See the ForceCleanup field
// doc on pipelineContext for the rationale (cp-forge surprise-delete).
//
// Inputs are read from the pipeline context:
//   - ctx.Checksums.Files is the manifest (path -> entry).
//   - checksums.WrittenThisRun is the "this run touched it" set, populated
//     as a side effect of every WriteGeneratedFile*/RecordFile call.
//   - tier1OwnerRegistry (in generate_tier1_scope.go) provides the
//     per-path owner-step gate.
//
// Calling cleanupStaleArtifacts with a nil ctx.Checksums or empty Files
// map is a no-op — there's no manifest to consult, so by construction
// there are no forge-owned paths to delete.
func cleanupStaleArtifacts(ctx *pipelineContext) (candidates []string, missing []string, err error) {
	if ctx == nil || ctx.Checksums == nil || len(ctx.Checksums.Files) == 0 {
		return nil, nil, nil
	}

	cs := ctx.Checksums

	// Snapshot keys for stable iteration order + so we can mutate
	// cs.Files mid-loop (we delete entries we've removed from disk).
	paths := make([]string, 0, len(cs.Files))
	for rel := range cs.Files {
		paths = append(paths, rel)
	}
	sort.Strings(paths)

	for _, rel := range paths {
		// Honor `forge generate --accept`: forked paths are user-owned
		// forks, forge no longer wants to manage them. Don't delete.
		if cs.Files[rel].Forked {
			continue
		}

		// This run wrote this path — definitely not stale.
		if checksums.WrittenThisRun[rel] {
			continue
		}

		// Deliberately-skipped-but-alive: `forge generate --accept`
		// populated SkipWrite for this path, so the emitter rendered
		// but the write was intentionally short-circuited to preserve
		// the user's on-disk content. The file is alive by user intent
		// — never a deletion candidate. (Forked entries — the persistent
		// cousin of this per-run state — are skipped above.)
		if checksums.SkipWrite[rel] {
			continue
		}

		// Upgrade-managed paths: tracked in the manifest, but `forge
		// generate` is not the emitter. `forge upgrade` writes these on
		// version bumps; `forge generate` deliberately leaves them
		// alone. Without this guard the stale sweep flags every
		// upgrade-only file (cmd/main.go, .golangci.yml,
		// .github/CODEOWNERS, …) as a "stale" candidate, terrifies the
		// user, and the user reaches for the only workaround they can
		// find: hand-flipping `forked: true`, which silences the
		// warning but also breaks `forge upgrade`'s ability to re-emit
		// the file on the next version bump.
		if upgradeManagedPaths[rel] {
			continue
		}

		// Owner-step gate. If the owning emitter step is gated off this
		// run, we can't conclude the path is stale — the step wasn't
		// going to write it regardless. Leave it alone.
		if gate := tier1OwnerGate(rel); gate != nil && !gate(ctx) {
			continue
		}

		full := filepath.Join(ctx.ProjectDir, rel)
		info, statErr := os.Stat(full)
		if statErr != nil {
			if os.IsNotExist(statErr) {
				// Inverse finding: forge tracks this path but it's gone
				// from disk. Surface it (don't auto-recreate) so audit
				// can prompt the user. Silent here — file-already-gone
				// is the EXPECTED state for a recently-renamed service,
				// and the missing slice gets reported in aggregate by
				// the caller.
				missing = append(missing, rel)
				continue
			}
			// Other stat errors (typically permission-denied or transient
			// I/O glitches) are noteworthy: we can't tell whether the
			// file is stale or live, so we leave it tracked and warn
			// loudly with the full path. The sweep continues so one
			// permission-denied entry doesn't tank cleanup for the rest
			// of the manifest.
			fmt.Fprintf(os.Stderr, "⚠️  Warning: cleanup: could not stat tracked file %s: %v\n", full, statErr)
			continue
		}
		if info.IsDir() {
			// Manifest entries are individual files. A directory at the
			// recorded path is anomalous; skip rather than RemoveAll.
			continue
		}

		// Banner backstop. The manifest entry says forge wrote this
		// path, but the on-disk content may have been replaced by the
		// user. Skip Go files that don't carry the forge banner — they
		// may be the user's hand-rolled replacement.
		if shouldRequireBanner(rel) && !isForgeGeneratedBanner(full) {
			continue
		}

		// Always record the candidate so callers (stepCleanupStale) can
		// report it. Actual deletion is gated on ctx.ForceCleanup — the
		// default-deny posture protects users who run `forge generate`
		// mid-rename from losing files they hadn't realized were stale.
		candidates = append(candidates, full)
		if !ctx.ForceCleanup {
			continue
		}

		if removeErr := os.Remove(full); removeErr != nil {
			if os.IsNotExist(removeErr) {
				// Race with concurrent cleanup — file gone between stat
				// and remove. Drop the manifest entry and continue.
				delete(cs.Files, rel)
				continue
			}
			// Other remove errors (typically permission-denied) are
			// surfaced as a warning rather than a fatal — the file
			// remains tracked, the sweep continues, and the user gets a
			// clear signal pointing at the problem path. PROMOTED from
			// fatal-return so a single locked file doesn't abort the
			// whole sweep mid-way (which previously left the manifest in
			// an inconsistent state: half-pruned, half-not).
			fmt.Fprintf(os.Stderr, "⚠️  cleanup partial: could not remove %s (%v) — file remains tracked\n", full, removeErr)
			continue
		}
		// Drop the entry from the manifest so subsequent steps (rehash,
		// audit) don't keep tracking a path forge no longer owns.
		delete(cs.Files, rel)

		// Best-effort: prune the now-empty parent directory if the
		// manifest entry was the only file in it. Don't recurse — a
		// single os.Remove on the dir succeeds only if it's empty.
		// Empty-dir cleanup failing is typically expected (sibling files
		// keep the dir alive), so we log at info level rather than warn.
		if rmDirErr := os.Remove(filepath.Dir(full)); rmDirErr != nil && !os.IsNotExist(rmDirErr) {
			// "Directory not empty" is the dominant case — sibling files
			// in the same dir keep it alive. Surface only for diagnostic
			// users (the ctx.Verbose path) so we don't spam every
			// pipeline run with "directory not empty" lines.
			if ctx.Verbose {
				fmt.Fprintf(os.Stderr, "  ℹ️  cleanup: empty-dir prune failed for %s (%v) — usually expected (sibling files present)\n", filepath.Dir(full), rmDirErr)
			}
		}
	}

	sort.Strings(candidates)
	sort.Strings(missing)
	return candidates, missing, nil
}

// shouldRequireBanner reports whether the banner backstop applies to
// relPath. The banner check only makes sense for source files where
// forge actually emits the "Code generated by forge ... DO NOT EDIT."
// header — Go and TypeScript files. Other manifest entries (e.g.
// proto-derived JSON descriptors, generated YAML fragments) don't carry
// the banner and would always fail the check, so we don't apply it.
func shouldRequireBanner(relPath string) bool {
	switch strings.ToLower(filepath.Ext(relPath)) {
	case ".go", ".ts", ".tsx":
		return true
	}
	return false
}

// isForgeGeneratedBanner returns true when the file's first line declares
// it as "Code generated by forge". This is the standard forge marker,
// used across bootstrap/testing/etc. templates. Kept here (rather than
// in audit.go) because cleanup is the primary consumer; audit imports
// it via package-internal visibility.
func isForgeGeneratedBanner(path string) bool {
	f, err := os.Open(path)
	if err != nil {
		return false
	}
	defer f.Close()
	buf := make([]byte, 256)
	n, _ := f.Read(buf)
	head := string(buf[:n])
	if i := strings.IndexByte(head, '\n'); i >= 0 {
		head = head[:i]
	}
	return strings.Contains(head, "Code generated by forge")
}

// trackedMissingFiles returns the sorted list of manifest entries whose
// on-disk file does not exist. Used by `forge audit` to surface the
// inverse-of-orphan finding ("forge tracked this, but the file is
// gone — did you delete it by hand?") without going through the full
// cleanupStaleArtifacts pass.
//
// Forked entries are excluded — a forked path is user-owned by intent,
// so its removal is a deliberate "stop tracking me" signal rather than
// drift worth reporting.
//
// Upgrade-managed paths are also excluded for the same reason
// cleanupStaleArtifacts skips them: `forge generate` is not the
// emitter, so absence (e.g. a CLI-kind project that doesn't ship
// .github/workflows/e2e.yml) is the expected state, not drift.
func trackedMissingFiles(projectDir string, cs *generator.FileChecksums) []string {
	if cs == nil || len(cs.Files) == 0 {
		return nil
	}
	var missing []string
	for rel, entry := range cs.Files {
		if entry.Forked {
			continue
		}
		if upgradeManagedPaths[rel] {
			continue
		}
		full := filepath.Join(projectDir, rel)
		if _, err := os.Stat(full); err != nil && os.IsNotExist(err) {
			missing = append(missing, rel)
		}
	}
	sort.Strings(missing)
	return missing
}
