// Per-file extension-point hints for Tier-1 drift.
//
// When the stomp guard catches a hand-edited Tier-1 file, the worst
// thing the error can do is lead with --accept: agents take the path
// of least resistance, fork the file, and permanently lose
// regeneration (the failure chain this whole subsystem exists to
// prevent). The right answer is almost always "your customization has
// a designated user-owned home" — these hints name that home, per
// file shape, so the error message teaches the extension point first
// and the fork escape hatch last.
//
// The same mapping feeds `forge unfork --merge`'s post-merge guidance:
// a cleanly merged file is about to be re-rendered by the next
// generate, so surviving customizations need to move to the same
// destinations.
package cli

import (
	"fmt"
	"path"
	"strings"

	"github.com/reliant-labs/forge/internal/checksums"
)

// tier1ExtensionPointHint returns the designated user-owned extension
// point for a Tier-1 path, or "" when the path has no specific
// mapping. relPath is project-relative with forward slashes.
func tier1ExtensionPointHint(relPath string) string {
	rel := strings.TrimPrefix(relPath, "./")
	base := path.Base(rel)
	dir := path.Dir(rel)

	// pkg/app wiring set: custom wiring has three designated homes the
	// bootstrap codegen already cooperates with.
	if dir == "pkg/app" {
		switch base {
		case "bootstrap.go", "app_gen.go", "wire_gen.go":
			return "custom wiring belongs in pkg/app/setup.go / post_bootstrap.go / app_extras.go (user-owned)"
		}
	}

	// handlers/<svc>/: per-service generated files each have a
	// user-owned counterpart or an upstream source of truth.
	if strings.HasPrefix(dir, "handlers/") {
		switch {
		case base == "authorizer_gen.go":
			svc := path.Base(dir)
			return "override in handlers/" + svc + "/authorizer.go (user-owned), which wire_gen already calls via NewAuthorizer()"
		case base == "handlers_gen.go" || base == "mock_gen.go":
			return "regenerate from contract.go / proto instead of editing — this file is derived output"
		}
	}

	return ""
}

// formatTier1DriftReport renders the batched stomp-guard error body.
// Extracted from stepCheckTier1Drift so (a) the explain-drift path can
// reuse the identical report and (b) the message can be pinned by unit
// tests without spinning up a pipeline context.
//
// Message design: the extension point leads, the fork trails. The old
// ordering taught --accept as the path of least resistance, and agents
// dutifully took it — permanently losing regeneration for the file
// (.forge/backlog.md 2026-06-03/05). --accept stays documented, but as
// what it is: adopting permanent ownership.
func formatTier1DriftReport(drift []checksums.Tier1DriftEntry) string {
	var b strings.Builder
	fmt.Fprintf(&b, "%d Tier-1 file(s) modified after last `forge generate`:\n\n", len(drift))
	for _, d := range drift {
		fmt.Fprintf(&b, "  • %s\n", d.Path)
		fmt.Fprintf(&b, "      recorded: %s\n", short(d.RecordedHash))
		fmt.Fprintf(&b, "      current:  %s (no match in %d prior render(s))\n", short(d.OnDiskHash), d.HistoryDepth)
		if hint := tier1ExtensionPointHint(d.Path); hint != "" {
			fmt.Fprintf(&b, "      ↪ %s\n", hint)
		}
	}
	fmt.Fprintf(&b, "\nTier-1 files carry the `// Code generated by forge ... DO NOT EDIT.` banner — forge owns them and regenerates them every run. Options, in order of preference:\n")
	fmt.Fprintf(&b, "  1. Move the customization to the designated extension point named above (user-owned; survives every regenerate) — or any Tier-2 file — then revert the generated file (`git checkout -- <path>`) and re-run.\n")
	fmt.Fprintf(&b, "  2. Re-run with `--explain-drift` to see a diff of each drifted file against a fresh render of the current templates before deciding.\n")
	fmt.Fprintf(&b, "  3. Re-run with `--force` to discard your edits and regenerate from the current templates.\n")
	fmt.Fprintf(&b, "  4. Re-run with `--accept` to fork the file — you adopt PERMANENT ownership and forge will never update this file again (reverse with `forge unfork`, reconcile later with `forge unfork --merge`).\n")
	return b.String()
}
