package cli

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/reliant-labs/forge/internal/codegen"
	"github.com/reliant-labs/forge/internal/config"
	"github.com/reliant-labs/forge/internal/naming"
	"github.com/reliant-labs/forge/internal/templates"
)

// generateFrontendHooks generates TypeScript React Query hook files for each
// service in every Next.js frontend. It writes one <service>-hooks.ts per
// service and an index.ts barrel file.
func generateFrontendHooks(cfg *config.ProjectConfig, services []codegen.ServiceDef, projectDir string) error {
	if len(services) == 0 {
		return nil
	}

	tmplContent, err := templates.FrontendTemplates().Get("hooks.ts.tmpl")
	if err != nil {
		return fmt.Errorf("read hooks template: %w", err)
	}

	tmpl, err := template.New("hooks.ts.tmpl").Funcs(templates.FuncMap()).Parse(string(tmplContent))
	if err != nil {
		return fmt.Errorf("parse hooks template: %w", err)
	}

	for _, fe := range cfg.Frontends {
		if !strings.EqualFold(fe.Type, "nextjs") && !strings.EqualFold(fe.Type, "react-native") {
			continue
		}

		feDir := fe.Path
		if feDir == "" {
			feDir = filepath.Join("frontends", fe.Name)
		}

		hooksDir := filepath.Join(projectDir, feDir, "src", "hooks")
		if err := os.MkdirAll(hooksDir, 0o755); err != nil {
			return fmt.Errorf("create hooks directory: %w", err)
		}

		var hookFiles []string

		for _, svc := range services {
			data := codegen.ServiceDefToHookData(svc)
			if len(data.Methods) == 0 {
				continue
			}

			var buf bytes.Buffer
			if err := tmpl.Execute(&buf, data); err != nil {
				return fmt.Errorf("render hooks for %s: %w", svc.Name, err)
			}

			fileName := serviceNameToHookFile(svc.Name)
			hookFiles = append(hookFiles, fileName)

			outPath := filepath.Join(hooksDir, fileName)
			if err := os.WriteFile(outPath, buf.Bytes(), 0o644); err != nil {
				return fmt.Errorf("write hooks file %s: %w", outPath, err)
			}
		}

		// Generate barrel index.ts
		if len(hookFiles) > 0 {
			indexPath := filepath.Join(hooksDir, "index.ts")
			if err := writeHooksIndex(indexPath, hookFiles); err != nil {
				return fmt.Errorf("write hooks index: %w", err)
			}
		}

		fmt.Printf("  ✅ Generated %d hook file(s) for frontend %s\n", len(hookFiles), fe.Name)
	}

	return nil
}

// serviceNameToHookFile converts a service name to a hook file name.
// "UserService" → "user-service-hooks.ts", "EchoService" → "echo-service-hooks.ts",
// "LLMGatewayService" → "llm-gateway-service-hooks.ts" (NOT
// "l-l-m-gateway-service-hooks.ts" — see naming.ToKebabCase for the
// initialism table that keeps acronyms glued).
//
// All file-emitter sites and the re-export indexer below MUST go through
// this single function. If a future caller needs kebab-casing for any
// service-name-derived path, route, or import specifier, use
// `naming.ToKebabCase` directly rather than re-implementing the rule —
// the index.ts re-export stays in lockstep with the on-disk filenames
// only because both go through the same canonical splitter.
func serviceNameToHookFile(name string) string {
	return naming.ToKebabCase(name) + "-hooks.ts"
}

// writeHooksIndex writes a barrel index.ts that re-exports all hook files.
func writeHooksIndex(path string, hookFiles []string) error {
	var buf bytes.Buffer
	buf.WriteString("// AUTO-GENERATED — DO NOT EDIT\n")
	buf.WriteString("// Generated by forge generate\n\n")

	for _, f := range hookFiles {
		module := strings.TrimSuffix(f, ".ts")
		buf.WriteString(fmt.Sprintf("export * from \"./%s\";\n", module))
	}

	return os.WriteFile(path, buf.Bytes(), 0o644)
}