// A failed `forge generate` must not claim "your tree is back to its pre-run
// state" over files it left changed.
//
// The observed defect (control-plane, prod triage): validation failed, forge
// printed "reverted 328 file(s) … your tree is back to its pre-run state",
// and 32 buf-generated files were still modified — gen/**/*.pb.go carrying
// the local protoc-gen-go's version header instead of the committed one, and
// stubs regenerated from another agent's uncommitted proto. The journal only
// recorded forge's own writers; buf's output was outside it, and the report
// asserted a whole-tree fact it had never checked.
//
// Pinned contract:
//
//   - A step that runs an external tool declares what the tool writes
//     (GenStep.Writes); the pipeline captures it before the step runs; a
//     failed run restores it — modified outputs, created outputs, deleted
//     outputs alike.
//   - The "pre-run state" sentence is printed only when a post-revert
//     comparison against the pre-run tree finds nothing else changed. A
//     write nobody declared is NAMED, never papered over.
package cli

import (
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
	"testing"

	"github.com/reliant-labs/forge/internal/checksums"
)

// writeTreeFileT writes body to path, creating parent directories.
func writeTreeFileT(t *testing.T, path, body string) {
	t.Helper()
	mustMkdirAllT(t, filepath.Dir(path))
	mustWrite(t, path, body)
}

// withPipelineSteps runs the real pipeline driver over steps.
func withPipelineSteps(t *testing.T, steps []GenStep) {
	t.Helper()
	prev := pipelineSteps
	pipelineSteps = func() []GenStep { return steps }
	t.Cleanup(func() { pipelineSteps = prev })
	t.Cleanup(checksums.ResetPerRunState)
	t.Cleanup(checksums.CommitRollback)
}

// productionStep returns the real step plan's entry by name, so a test
// exercises the declaration production runs with, not a copy of it.
func productionStep(t *testing.T, name string) GenStep {
	t.Helper()
	for _, s := range generateSteps() {
		if s.Name == name {
			return s
		}
	}
	t.Fatalf("no generate step named %q", name)
	return GenStep{}
}

// failingValidate stands in for "go build (validate generated code)".
func failingValidate() GenStep {
	return GenStep{
		Name: "go build (validate generated code)",
		Gate: always,
		Run:  func(*pipelineContext) error { return errors.New("validation failed: generated code does not compile") },
		Tag:  "validate",
	}
}

func runPipelineCapturingOutput(t *testing.T, dir string) (string, error) {
	t.Helper()
	stderr, restore := captureStderr(t)
	var runErr error
	stdout := captureStdout(t, func() {
		runErr = runGeneratePipelineFlags(dir, pipelineFlags{})
	})
	restore()
	return stdout + stderr.String(), runErr
}

// TestGenerate_FailedRunRestoresBufOutput is the control-plane repro, with
// the REAL buf step: committed stubs that the local plugin renders
// differently, plus a proto with no committed stub (another agent's
// uncommitted file). buf rewrites the one and creates the other; validation
// then fails. Every buf output must be back, and the claim must be true.
func TestGenerate_FailedRunRestoresBufOutput(t *testing.T) {
	if testing.Short() {
		t.Skip("-short: runs real `buf generate`; runs in task test")
	}
	for _, tool := range []string{"buf", "protoc-gen-go"} {
		if _, err := exec.LookPath(tool); err != nil {
			t.Skipf("%s not on PATH", tool)
		}
	}
	dir := t.TempDir()
	writeTreeFileT(t, filepath.Join(dir, "buf.yaml"), "version: v2\nmodules:\n  - path: proto\n")
	writeTreeFileT(t, filepath.Join(dir, "buf.gen.yaml"), "version: v2\ninputs:\n  - directory: proto\nplugins:\n"+
		"  - local: protoc-gen-go\n    out: gen\n    opt:\n      - paths=source_relative\n")
	mustMkdirAllT(t, filepath.Join(dir, "proto", "widget", "v1"))
	writeTreeFileT(t, filepath.Join(dir, "proto", "widget", "v1", "widget.proto"),
		"syntax = \"proto3\";\npackage widget.v1;\noption go_package = \"example.com/app/gen/widget/v1;widgetv1\";\nmessage Widget { string id = 1; }\n")
	writeTreeFileT(t, filepath.Join(dir, "proto", "widget", "v1", "gadget.proto"),
		"syntax = \"proto3\";\npackage widget.v1;\noption go_package = \"example.com/app/gen/widget/v1;widgetv1\";\nmessage Gadget { string id = 1; }\n")
	// The committed stub, as a different protoc-gen-go rendered it.
	mustMkdirAllT(t, filepath.Join(dir, "gen", "widget", "v1"))
	writeTreeFileT(t, filepath.Join(dir, "gen", "widget", "v1", "widget.pb.go"),
		"// Code generated by protoc-gen-go. DO NOT EDIT.\n// versions:\n// \tprotoc-gen-go v0.0.0-committed\n\npackage widgetv1\n")
	before := snapshotTree(t, dir)

	withPipelineSteps(t, []GenStep{productionStep(t, "buf generate (Go stubs)"), failingValidate()})
	out, runErr := runPipelineCapturingOutput(t, dir)
	if runErr == nil || !strings.Contains(runErr.Error(), "validation failed") {
		t.Fatalf("expected the validate step to fail the run, got %v\n%s", runErr, out)
	}
	if !strings.Contains(out, "Running buf generate") {
		t.Fatalf("precondition: buf must have run before validation failed:\n%s", out)
	}

	if diffs := diffTrees(before, snapshotTree(t, dir)); len(diffs) > 0 {
		t.Errorf("a failed generate must restore buf's output, still changed:\n  %s\n%s", strings.Join(diffs, "\n  "), out)
	}
	if !strings.Contains(out, "your tree is back to its pre-run state") {
		t.Errorf("a restore verified complete must say so:\n%s", out)
	}
	for _, want := range []string{"gen/widget/v1/widget.pb.go", "gen/widget/v1/gadget.pb.go"} {
		if !strings.Contains(out, want) {
			t.Errorf("the reverted list must name %s:\n%s", want, out)
		}
	}
}

// TestGenerate_FailedRunNeverClaimsAnUnverifiedRestore pins the invariant
// that makes the sentence trustworthy whatever the next undeclared writer
// is: a step that writes WITHOUT declaring it leaves the file changed, and
// the report must say so and name it — not claim the tree is restored.
func TestGenerate_FailedRunNeverClaimsAnUnverifiedRestore(t *testing.T) {
	dir := t.TempDir()
	writeTreeFileT(t, filepath.Join(dir, "gen", "a.pb.go"), "package a // committed\n")
	writeTreeFileT(t, filepath.Join(dir, "internal", "x.go"), "package internal\n")

	undeclared := GenStep{
		Name: "external tool that declares nothing",
		Gate: always,
		Tag:  "proto",
		Run: func(ctx *pipelineContext) error {
			return os.WriteFile(filepath.Join(ctx.AbsPath, "gen", "a.pb.go"), []byte("package a // regenerated\n"), 0o644)
		},
	}
	forgeWriter := GenStep{
		Name: "forge writer",
		Gate: always,
		Tag:  "codegen",
		Run: func(ctx *pipelineContext) error {
			_, err := checksums.WriteGeneratedFile(ctx.AbsPath, "internal/x_gen.go", []byte("package internal\n"), &checksums.FileChecksums{}, false)
			return err
		},
	}
	withPipelineSteps(t, []GenStep{undeclared, forgeWriter, failingValidate()})
	out, runErr := runPipelineCapturingOutput(t, dir)
	if runErr == nil {
		t.Fatalf("expected the run to fail:\n%s", out)
	}

	if strings.Contains(out, "your tree is back to its pre-run state") {
		t.Errorf("must not claim the tree is back to its pre-run state while gen/a.pb.go is still changed:\n%s", out)
	}
	if !strings.Contains(out, "NOT fully back to its pre-run state") {
		t.Errorf("the report must say the restore is incomplete:\n%s", out)
	}
	if !strings.Contains(out, "! gen/a.pb.go") {
		t.Errorf("the report must name the file it did not restore:\n%s", out)
	}
	// forge's own write is still reverted.
	if _, err := os.Stat(filepath.Join(dir, "internal", "x_gen.go")); !os.IsNotExist(err) {
		t.Errorf("forge's own write must be reverted, stat err = %v", err)
	}
	// And the undeclared change is left alone: it may be someone else's.
	if got, _ := os.ReadFile(filepath.Join(dir, "gen", "a.pb.go")); string(got) != "package a // regenerated\n" {
		t.Errorf("forge must not revert a path it never journaled, got %q", got)
	}
}

// TestGenerate_DeclaredWritesRestoredAndVerified is the same shape with the
// write DECLARED: the path is restored and the claim is made. Runs under
// -short (no tools), so the contract has a fast-tier guard.
func TestGenerate_DeclaredWritesRestoredAndVerified(t *testing.T) {
	dir := t.TempDir()
	writeTreeFileT(t, filepath.Join(dir, "gen", "a.pb.go"), "package a // committed\n")
	writeTreeFileT(t, filepath.Join(dir, "gen", "stale.pb.go"), "package a // removed by the tool\n")
	before := snapshotTree(t, dir)

	tool := GenStep{
		Name:   "external tool",
		Gate:   always,
		Tag:    "proto",
		Writes: func(*pipelineContext) []string { return []string{"gen", "openapi"} },
		Run: func(ctx *pipelineContext) error {
			for rel, body := range map[string]string{
				"gen/a.pb.go":      "package a // regenerated\n",
				"gen/new/b.pb.go":  "package b\n",
				"openapi/svc.yaml": "openapi: 3.1.0\n",
			} {
				full := filepath.Join(ctx.AbsPath, rel)
				if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
					return err
				}
				if err := os.WriteFile(full, []byte(body), 0o644); err != nil {
					return err
				}
			}
			return os.Remove(filepath.Join(ctx.AbsPath, "gen", "stale.pb.go"))
		},
	}
	withPipelineSteps(t, []GenStep{tool, failingValidate()})
	out, runErr := runPipelineCapturingOutput(t, dir)
	if runErr == nil {
		t.Fatalf("expected the run to fail:\n%s", out)
	}
	if diffs := diffTrees(before, snapshotTree(t, dir)); len(diffs) > 0 {
		t.Errorf("declared tool output must be restored, still changed:\n  %s\n%s", strings.Join(diffs, "\n  "), out)
	}
	if _, err := os.Stat(filepath.Join(dir, "openapi")); !os.IsNotExist(err) {
		t.Errorf("a directory the tool created must be removed, stat err = %v", err)
	}
	if !strings.Contains(out, "your tree is back to its pre-run state (checked against the pre-run tree") {
		t.Errorf("a verified restore must make the claim:\n%s", out)
	}
}

// TestRestoreVerification_IgnoresGitIgnoredChurn: in a git work tree the
// comparison is over what git shows, so a build cache or dev-server log that
// changes during the run is not reported as a change the run made.
func TestRestoreVerification_IgnoresGitIgnoredChurn(t *testing.T) {
	if _, err := exec.LookPath("git"); err != nil {
		t.Skip("git not on PATH")
	}
	dir := t.TempDir()
	if out, err := exec.Command("git", "-C", dir, "init", "-q").CombinedOutput(); err != nil {
		t.Fatalf("git init: %v\n%s", err, out)
	}
	writeTreeFileT(t, filepath.Join(dir, ".gitignore"), "tmp/\n")
	writeTreeFileT(t, filepath.Join(dir, "tmp", "cache.bin"), "a")
	writeTreeFileT(t, filepath.Join(dir, "tracked.go"), "package x\n")

	pre := snapshotWorkTree(dir)
	writeTreeFileT(t, filepath.Join(dir, "tmp", "cache.bin"), "bb")
	if res := verifyRestoredTree(dir, pre, nil, nil); !res.Clean() {
		t.Errorf("git-ignored churn must not be reported, got %+v", res)
	}
	writeTreeFileT(t, filepath.Join(dir, "tracked.go"), "package y\n")
	writeTreeFileT(t, filepath.Join(dir, "untracked.go"), "package x\n")
	res := verifyRestoredTree(dir, pre, nil, nil)
	if want := []string{"tracked.go", "untracked.go"}; !reflect.DeepEqual(res.Changed, want) {
		t.Errorf("Changed = %v, want %v", res.Changed, want)
	}
}

// TestRestoreVerification_SameBytesRewriteIsNotAChange: a tool that rewrites
// every output with identical bytes (new mtime) has changed nothing.
func TestRestoreVerification_SameBytesRewriteIsNotAChange(t *testing.T) {
	dir := t.TempDir()
	writeTreeFileT(t, filepath.Join(dir, "gen", "a.pb.go"), "package a\n")
	pre := snapshotWorkTree(dir)
	path := filepath.Join(dir, "gen", "a.pb.go")
	info, _ := os.Stat(path)
	writeTreeFileT(t, path, "package a\n")
	_ = os.Chtimes(path, info.ModTime().Add(1e9), info.ModTime().Add(1e9))
	if res := verifyRestoredTree(dir, pre, nil, nil); !res.Clean() {
		t.Errorf("an identical rewrite is not a change, got %+v", res)
	}
}

// Every step that runs a tool writing into the project must declare it.
// Adding a step that shells buf, go mod tidy, sqlc, an npm install, or any
// other writer without declaring Writes is exactly how the control-plane
// report came to lie; this set is reviewed like the ReadOnly one.
func TestGenerateStepsDeclareExternalToolOutputs(t *testing.T) {
	want := []string{
		"migrate env registries onto images",
		"ensure gen/go.mod",
		"buf generate (Go stubs)",
		"descriptor extraction",
		"OpenAPI specs (protoc-gen-connect-openapi)",
		"TypeScript stubs (frontends)",
		"go mod tidy (pre-wiring)",
		"sqlc generate",
		"go mod tidy (gen/)",
		"go mod tidy (root)",
	}
	var got []string
	for _, s := range generateSteps() {
		if s.Writes != nil {
			got = append(got, s.Name)
		}
	}
	sort.Strings(want)
	sort.Strings(got)
	if !reflect.DeepEqual(got, want) {
		t.Errorf("steps declaring external writes = %v\nwant %v", got, want)
	}
}

func TestBufTemplateOutDirs(t *testing.T) {
	dir := t.TempDir()
	tmpl := filepath.Join(dir, "buf.gen.yaml")
	writeTreeFileT(t, tmpl, "version: v2\nplugins:\n  - local: protoc-gen-go\n    out: gen\n  - local: protoc-gen-connect-go\n    out: gen\n"+
		"  - local: ./web/node_modules/.bin/protoc-gen-es\n    out: web/src/gen\n  - local: x\n    out: ../escape\n  - local: y\n    out: /abs\n")
	if got, want := bufTemplateOutDirs(tmpl), []string{"gen", "web/src/gen"}; !reflect.DeepEqual(got, want) {
		t.Errorf("bufTemplateOutDirs = %v, want %v", got, want)
	}
	if got := bufTemplateOutDirs(filepath.Join(dir, "missing.yaml")); got != nil {
		t.Errorf("missing template: got %v", got)
	}
}

func TestSqlcOutDirs(t *testing.T) {
	v2 := "version: \"2\"\nsql:\n  - engine: postgresql\n    queries: q\n    schema: s\n    gen:\n      go:\n        package: db\n        out: internal/db/sqlc\n"
	if got, want := sqlcOutDirs([]byte(v2)), []string{"internal/db/sqlc"}; !reflect.DeepEqual(got, want) {
		t.Errorf("v2: got %v, want %v", got, want)
	}
	v1 := "version: \"1\"\npackages:\n  - name: db\n    path: internal/db\n"
	if got, want := sqlcOutDirs([]byte(v1)), []string{"internal/db"}; !reflect.DeepEqual(got, want) {
		t.Errorf("v1: got %v, want %v", got, want)
	}
}

// TestBirthContractTest_IsJournaled is the undeclared write the post-revert
// verification found in the cp-forge e2e fixture: the scaffold-once
// contract_test.go was written with a raw os.WriteFile, so a refused generate
// left it behind (and its scaffold-ledger birth with it, so it would never be
// scaffolded again). It is now journaled: the restore removes the file and
// forgets the birth.
func TestBirthContractTest_IsJournaled(t *testing.T) {
	dir := t.TempDir()
	writeTreeFileT(t, filepath.Join(dir, "go.mod"), "module example.com/app\n\ngo 1.22\n")
	writeTreeFileT(t, filepath.Join(dir, "forge.yaml"), "name: app\n")
	pkgDir := filepath.Join(dir, "internal", "pgstore")
	writeTreeFileT(t, filepath.Join(pkgDir, "contract.go"), "package pgstore\n\n// Service is the boundary.\ntype Service interface{ Ping() error }\n")
	writeTreeFileT(t, filepath.Join(pkgDir, "service.go"), "package pgstore\n\n// Deps holds dependencies.\ntype Deps struct{}\n\nfunc New(deps Deps) (Service, error) { return nil, nil }\n")
	before := snapshotTree(t, dir)

	checksums.ResetPerRunState()
	t.Cleanup(checksums.ResetPerRunState)
	checksums.BeginRollbackJournal(dir)
	t.Cleanup(checksums.CommitRollback)

	testPath := filepath.Join(pkgDir, "contract_test.go")
	root, rel, ledger := checksums.SplitScaffoldPath(testPath)
	captureStdout(t, func() {
		if err := birthContractTest(contractTestBirth{
			ProjectDir: dir, PkgDir: pkgDir, Rel: "internal/pgstore", ContractPath: filepath.Join(pkgDir, "contract.go"),
			TestPath: testPath, TestRoot: root, TestRel: rel, TestLedger: ledger,
		}, &contractTestDeclines{}); err != nil {
			t.Fatalf("birthContractTest: %v", err)
		}
	})
	if _, err := os.Stat(testPath); err != nil {
		t.Fatalf("precondition: contract_test.go should have been scaffolded: %v", err)
	}

	checksums.RestoreRollback(dir)
	if diffs := diffTrees(before, snapshotTree(t, dir)); len(diffs) > 0 {
		t.Errorf("a failed run must remove the contract_test.go it scaffolded:\n  %s", strings.Join(diffs, "\n  "))
	}
	if ledger && checksums.ScaffoldRecorded(root, rel) {
		t.Errorf("the restore must forget the birth, or the next run will never scaffold %s", rel)
	}
}
