package cli

import (
	"fmt"
	"strings"

	"github.com/reliant-labs/forge/internal/buildinfo"
)

// toolchainDiagnosis renders the "which forge is this?" block attached to a
// failure that a toolchain mismatch would explain.
//
// The motivating incident: an unattended agent scaffolded a project with the
// standalone `forge` binary, then ran the project's gate, which invokes
// `reliant forge`. The two were different builds — reliant embeds forge via
// a local replace and only picks up forge changes when RELIANT is rebuilt —
// and the second one refused at the forge/pkg compatibility handshake. The
// error named a missing symbol and suggested bumping forge/pkg, which was
// not the problem. The agent concluded the project was unfixable, saved its
// protos, and rebuilt the entire tree under the other toolchain.
//
// Everything that failure needed to say is mechanically available: the
// running build's identity, the forge/pkg it resolved, and (when recorded)
// the build that actually generated the tree. Forge's convention is that a
// refusal is a runbook — expected vs found vs the command to fix it — so
// this block states all three.
func toolchainDiagnosis(projectDir string) string {
	var sb strings.Builder

	sb.WriteString("Toolchain in use:\n")
	sb.WriteString(buildinfo.Describe())

	// What generated the tree, when we recorded it. This is the line that
	// turns "confusing failure" into "obvious mismatch".
	running := buildinfo.Identity()
	if recorded := readGeneratingBuild(projectDir); recorded != "" {
		fmt.Fprintf(&sb, "  generated by:   %s\n", recorded)
		if recorded != running {
			sb.WriteString("\n")
			sb.WriteString("MISMATCH: this tree was generated by a DIFFERENT forge build than the one\n")
			sb.WriteString("you just ran. That alone explains this failure — the pinned forge/pkg may\n")
			sb.WriteString("be perfectly correct for the build that generated the tree.\n")
		}
	} else {
		sb.WriteString("  generated by:   (not recorded — tree predates build stamping)\n")
	}

	sb.WriteString("\n")
	sb.WriteString(twoToolchainNote())
	return sb.String()
}

// twoToolchainNote explains that two forge builds can share one PATH, and
// gives the literal commands to compare and reconcile them. It is phrased
// from the perspective of whichever build is running, so the "other" one is
// always the one the reader has not just used.
func twoToolchainNote() string {
	var sb strings.Builder
	sb.WriteString("Note: forge can be installed TWICE on one machine, as two different builds:\n")
	sb.WriteString("  * `forge`         — standalone binary (go install ./cmd/forge)\n")
	sb.WriteString("  * `reliant forge` — forge compiled INTO reliant; it changes only when\n")
	sb.WriteString("                      RELIANT is rebuilt, even though it uses your local\n")
	sb.WriteString("                      forge checkout via a replace directive.\n")
	sb.WriteString("A tree generated by one can fail this handshake under the other.\n\n")
	sb.WriteString("Compare them:\n")
	sb.WriteString("  forge version\n")
	sb.WriteString("  reliant forge version\n\n")
	sb.WriteString("Reinstall whichever is stale so both report the same build:\n")
	sb.WriteString("  (cd /path/to/forge    && go install ./cmd/forge)\n")
	sb.WriteString("  (cd /path/to/reliant  && go install ./cmd/reliant)\n")
	return sb.String()
}
