package cli

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/reliant-labs/forge/internal/doctor"
	"github.com/reliant-labs/forge/internal/kclplugin"
)

// A KCL module's generated file (fp.write_file) is written by the commands
// that LAUNCH the env and by nothing that only reads it.
//
// Incident: control-plane's dev KCL generates the TRACKED deploy/nats/nats.conf
// — one NATS account per running dev stack — as a side effect of rendering.
// `forge ci validate-kcl` (and so `task test`, which reaches the same render)
// evaluated dev without the dev-stack roster and rewrote the committed file
// with the default account only, deleting every other worktree's account. A
// check must not mutate the tree it checks.

// withGeneratedConf appends a generated-file line to a fixture main.k, the
// shape control-plane's lib/nats.k uses (the result is bound so the call is
// evaluated).
func withGeneratedConf(mainK string) string {
	return mainK + "\n_generated = fp.write_file(\"deploy/nats/nats.conf\", \"generated by a render\\n\")\n"
}

const committedConf = "committed accounts for every worktree\n"

// seedCommittedConf writes the file as it stands in version control and
// returns a func reporting whether a render has since changed it.
func seedCommittedConf(t *testing.T, projectDir string) func() bool {
	t.Helper()
	path := filepath.Join(projectDir, "deploy", "nats", "nats.conf")
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(committedConf), 0o644); err != nil {
		t.Fatal(err)
	}
	return func() bool {
		got, _ := os.ReadFile(path)
		return string(got) != committedConf
	}
}

// renderAs runs the render sequence a command runs, and returns whether the
// generated file changed.
func renderAs(t *testing.T, projectDir, env string, sequence func(ctx context.Context)) bool {
	t.Helper()
	resetDevStackGlobals(t)
	changed := seedCommittedConf(t, projectDir)
	t.Chdir(projectDir)
	sequence(t.Context())
	if _, err := RenderKCL(t.Context(), projectDir, env); err != nil {
		t.Fatalf("render %s: %v", env, err)
	}
	return changed()
}

func TestGeneratedFilesAreWrittenOnlyByCommandsThatLaunch(t *testing.T) {
	kclplugin.Register()

	type command struct {
		name      string
		sequence  func(ctx context.Context, projectDir, env string)
		wantWrite bool
	}
	up := command{"env up", func(ctx context.Context, dir, env string) {
		activateDevStack(ctx, dir, env, renderToLaunch)
		armMaterializer(dir)
	}, true}
	deployApply := command{"env deploy", func(ctx context.Context, dir, env string) {
		activateDevStack(ctx, dir, env, renderDeclaration)
		armMaterializer(dir)
	}, true}
	deployDryRun := command{"env deploy --dry-run", func(ctx context.Context, dir, env string) {
		activateDevStack(ctx, dir, env, renderDeclaration)
	}, false}
	statusOnly := command{"env status / cluster lifecycle", func(ctx context.Context, dir, env string) {
		activateDevStack(ctx, dir, env, renderToLaunch)
	}, false}
	bare := command{"ci / doctor / generate (no activation)", func(context.Context, string, string) {}, false}

	for _, tc := range []struct {
		env, mainK string
		cmds       []command
	}{
		{"dev", localDevMainK, []command{up, deployApply, deployDryRun, statusOnly, bare}},
		// A cloud env's deploy launches nothing here, so a file generated
		// for a LOCAL consumer has no business being written.
		{"prod", cloudProdMainK, []command{
			up,
			{deployApply.name, deployApply.sequence, false},
			deployDryRun, bare,
		}},
	} {
		for _, c := range tc.cmds {
			t.Run(tc.env+"/"+c.name, func(t *testing.T) {
				dir := t.TempDir()
				writePortblockProject(t, dir, tc.env, withGeneratedConf(tc.mainK))
				got := renderAs(t, dir, tc.env, func(ctx context.Context) { c.sequence(ctx, dir, tc.env) })
				switch {
				case got && !c.wantWrite:
					t.Errorf("%s wrote the generated file; only a command that materializes a local env may", c.name)
				case !got && c.wantWrite:
					t.Errorf("%s did not write the generated file; the command that launches the env must", c.name)
				}
			})
		}
	}
}

// TestCIValidateKCLLeavesGeneratedFilesAlone drives the exact render
// `forge ci validate-kcl` performs (doctor.CheckDeployManifests over every
// env) against a project that generates a tracked file, and requires the
// tree to come out as it went in.
func TestCIValidateKCLLeavesGeneratedFilesAlone(t *testing.T) {
	kclplugin.Register()
	resetDevStackGlobals(t)
	dir := t.TempDir()
	writePortblockProject(t, dir, "dev", withGeneratedConf(localDevMainK))
	changed := seedCommittedConf(t, dir)
	t.Chdir(dir)

	res := doctor.CheckDeployManifests(t.Context(), &doctor.Environment{ProjectDir: dir})
	if res.Status == doctor.StatusFail {
		t.Fatalf("validate-kcl render failed: %s\n%s", res.Message, res.Evidence)
	}
	if changed() {
		t.Error("`forge ci validate-kcl` rewrote a tracked file the dev KCL generates")
	}
}

// TestEnvRenderReportsTheWriteItDeclined: `forge env render` is where a user
// asks "what would this env do", so a generated file it did NOT write is
// named, rather than silently absent.
func TestEnvRenderReportsTheWriteItDeclined(t *testing.T) {
	kclplugin.Register()
	resetDevStackGlobals(t)
	dir := t.TempDir()
	writePortblockProject(t, dir, "dev", withGeneratedConf(localDevMainK))
	changed := seedCommittedConf(t, dir)

	_, stderr, err := runRenderCapturingProcessStdout(t, dir, "dev")
	if err != nil {
		t.Fatalf("forge env render dev: %v\nstderr:\n%s", err, stderr)
	}
	if changed() {
		t.Error("`forge env render` wrote a generated file")
	}
	if !strings.Contains(stderr, "deploy/nats/nats.conf") {
		t.Errorf("env render did not name the generated file it declined to write; stderr:\n%s", stderr)
	}
}
