// Package cli — `forge map` command.
//
// Map is a tree-shaped view of the project with ownership annotations on
// every leaf. The annotations come from cross-referencing:
//
//   - The .forge/checksums.json file (forge-tracked = forge-space).
//   - File-name conventions (*_gen.go = forge-regenerated).
//   - Forge banner check (`Code generated by forge` first line).
//   - FORGE_SCAFFOLD marker presence (scaffolded but not finalized).
//   - Health flags: hand-edits to forge-space files (drift), proto/db
//     entities not represented in migrations, etc.
//
// Filtering and depth control mirror the spec: --depth N, --filter
// <subtree>, --json. The non-JSON output is plain-text indented tree
// (no box-drawing chars in the source — we render them at print time so
// the file stays grep-friendly).
package cli

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/spf13/cobra"

	"github.com/reliant-labs/forge/internal/codegen"
	"github.com/reliant-labs/forge/internal/generator"
)

// MapNode is one entry in the project tree. Children is empty for files;
// for directories it is sorted alphabetically (dirs first, then files,
// each group ordered by name).
type MapNode struct {
	Path        string    `json:"path"`
	Name        string    `json:"name"`
	IsDir       bool      `json:"is_dir"`
	Ownership   string    `json:"ownership,omitempty"`
	Flags       []string  `json:"flags,omitempty"`
	Children    []*MapNode `json:"children,omitempty"`
}

// Ownership classes used in the output. We pick a narrow set so a
// downstream agent can switch on them.
const (
	OwnershipUser           = "user-owned"
	OwnershipForgeSpace     = "forge-space, regenerated"
	OwnershipForgeDrifted   = "forge-space, hand-edited (drift from regen)"
	OwnershipScaffold       = "scaffold, FORGE_SCAFFOLD markers present"
	OwnershipScaffoldOnce   = "user-owned, scaffolded once"
	OwnershipUnknown        = ""
)

// mapWalkSkip names directories that pollute the map without adding
// signal: vendor/, node_modules/, .git/, etc.
var mapWalkSkip = map[string]struct{}{
	"vendor": {}, "node_modules": {}, ".git": {}, ".forge": {},
	".idea": {}, ".vscode": {}, "dist": {}, "build": {},
	".next": {}, ".turbo": {}, ".task": {}, "tmp": {},
}

func newMapCmd() *cobra.Command {
	var (
		depth   int
		filter  string
		jsonOut bool
	)
	cmd := &cobra.Command{
		Use:   "map",
		Short: "Print project tree with ownership annotations",
		Long: `Print project tree with ownership annotations.

Each path is annotated as user-owned, forge-space (regenerated), scaffold
(FORGE_SCAFFOLD markers), or drifted (forge-space file with hand-edits).
Use --depth to truncate, --filter to focus on a subtree, --json for
machine-readable output.

Examples:
  forge map                    # full tree
  forge map --depth 2          # shallow
  forge map --filter handlers  # subtree
  forge map --json             # machine-readable`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runMap(depth, filter, jsonOut)
		},
	}
	cmd.Flags().IntVar(&depth, "depth", 0, "Max depth (0 = unlimited)")
	cmd.Flags().StringVar(&filter, "filter", "", "Subtree path filter (e.g. handlers/)")
	cmd.Flags().BoolVar(&jsonOut, "json", false, "Output as JSON")
	return cmd
}

func runMap(maxDepth int, filter string, jsonOut bool) error {
	cfg, cfgErr := loadProjectConfig()
	if cfgErr != nil && !errors.Is(cfgErr, ErrProjectConfigNotFound) {
		return fmt.Errorf("load project config: %w", cfgErr)
	}
	projectDir := "."
	if cfg != nil {
		// Walk up from cwd; we already know forge.yaml exists somewhere.
		if path, err := findProjectConfigFile(); err == nil {
			projectDir = filepath.Dir(path)
		}
	}

	cs, err := generator.LoadChecksums(projectDir)
	if err != nil {
		return fmt.Errorf("load checksums: %w", err)
	}

	// Collect entity tables for health flags (proto/db/ vs migrations).
	migTables := tablesFromMigrations(filepath.Join(projectDir, "db", "migrations"))
	entityTables := map[string]struct{}{}
	if dirExists(filepath.Join(projectDir, "proto")) {
		if defs, err := codegen.ParseEntityProtos(projectDir); err == nil {
			for _, e := range defs {
				entityTables[e.TableName] = struct{}{}
			}
		}
	}

	root, err := buildMapTree(projectDir, cs, filter, maxDepth, migTables, entityTables)
	if err != nil {
		return err
	}

	if jsonOut {
		enc := json.NewEncoder(os.Stdout)
		enc.SetIndent("", "  ")
		return enc.Encode(root)
	}
	printMapTree(os.Stdout, root, "")
	return nil
}

// buildMapTree walks projectDir and produces a MapNode tree with
// ownership/flags computed at each leaf. The root MapNode's name is the
// project's basename so the printed output says e.g. `my-project/` at the
// top.
func buildMapTree(projectDir string, cs *generator.FileChecksums, filter string, maxDepth int,
	migTables map[string]struct{}, entityTables map[string]struct{},
) (*MapNode, error) {
	abs, err := filepath.Abs(projectDir)
	if err != nil {
		return nil, err
	}
	root := &MapNode{
		Path:  ".",
		Name:  filepath.Base(abs) + "/",
		IsDir: true,
	}

	// Walk with explicit recursion so we can apply filter + depth + skip
	// uniformly. filepath.WalkDir works too but its skip semantics get
	// gnarly with our depth limit.
	if err := walkForMap(projectDir, ".", root, cs, filter, maxDepth, 0, migTables, entityTables); err != nil {
		return nil, err
	}
	return root, nil
}

func walkForMap(projectDir, rel string, parent *MapNode, cs *generator.FileChecksums,
	filter string, maxDepth, curDepth int,
	migTables, entityTables map[string]struct{},
) error {
	if maxDepth > 0 && curDepth >= maxDepth {
		return nil
	}
	full := filepath.Join(projectDir, rel)
	entries, err := os.ReadDir(full)
	if err != nil {
		return nil // tolerate read errors silently — partial tree is fine
	}
	// Sort directories first, then files; alphabetical within each group.
	sort.Slice(entries, func(i, j int) bool {
		di, dj := entries[i].IsDir(), entries[j].IsDir()
		if di != dj {
			return di // dirs first
		}
		return entries[i].Name() < entries[j].Name()
	})

	for _, e := range entries {
		name := e.Name()
		// Skip noise dirs and dotfiles outside .forge.
		if e.IsDir() {
			if _, skip := mapWalkSkip[name]; skip {
				continue
			}
		}
		// Skip top-level dotfiles by convention (kept terse).
		if strings.HasPrefix(name, ".") && name != ".github" {
			continue
		}

		childRel := filepath.Join(rel, name)
		// Filter early: include only paths under filter (or above on the
		// way down — we traverse directories that are prefixes of filter).
		if filter != "" {
			if !pathMatchesFilter(childRel, filter) {
				if e.IsDir() && filterStartsWith(filter, childRel) {
					// keep traversing into prefixes of the filter path
				} else {
					continue
				}
			}
		}

		node := &MapNode{
			Path:  filepath.ToSlash(childRel),
			Name:  name,
			IsDir: e.IsDir(),
		}
		if e.IsDir() {
			node.Name = name + "/"
			parent.Children = append(parent.Children, node)
			if err := walkForMap(projectDir, childRel, node, cs, filter, maxDepth, curDepth+1, migTables, entityTables); err != nil {
				return err
			}
			continue
		}
		// File node: compute ownership + flags.
		annotateFileNode(projectDir, childRel, node, cs, migTables, entityTables)
		parent.Children = append(parent.Children, node)
	}
	return nil
}

// pathMatchesFilter is true when rel is at or below filter.
// Both inputs are forward-slash relative paths (or filepath-native; we
// normalise here).
func pathMatchesFilter(rel, filter string) bool {
	r := filepath.ToSlash(rel)
	f := strings.TrimSuffix(filepath.ToSlash(filter), "/")
	return r == f || strings.HasPrefix(r, f+"/")
}

// filterStartsWith reports whether the filter path is itself prefixed by
// rel, which is how we know to continue descending into a parent of the
// filter target. Example: filter="handlers/billing", rel="handlers".
func filterStartsWith(filter, rel string) bool {
	r := filepath.ToSlash(rel)
	f := strings.TrimSuffix(filepath.ToSlash(filter), "/")
	return strings.HasPrefix(f, r+"/") || f == r
}

// annotateFileNode determines ownership + health flags for a single file.
// The decision tree:
//
//  1. Tracked in checksums and unmodified  → forge-space, regenerated.
//  2. Tracked in checksums and modified    → forge-space, drifted.
//  3. Has forge banner but not in checksums → forge-space (legacy untracked).
//  4. Contains FORGE_SCAFFOLD               → scaffold.
//  5. Filename ends in _gen.go              → forge-space (heuristic).
//  6. Otherwise                              → user-owned.
func annotateFileNode(projectDir, rel string, node *MapNode, cs *generator.FileChecksums,
	migTables, entityTables map[string]struct{},
) {
	relSlash := filepath.ToSlash(rel)
	if _, tracked := cs.Files[relSlash]; tracked {
		if cs.IsFileModified(projectDir, relSlash) {
			node.Ownership = OwnershipForgeDrifted
			node.Flags = append(node.Flags, "drift")
		} else {
			node.Ownership = OwnershipForgeSpace
		}
		return
	}

	full := filepath.Join(projectDir, rel)
	hasMarker := containsScaffoldMarker(full)
	if hasMarker {
		node.Ownership = OwnershipScaffold
		node.Flags = append(node.Flags, "FORGE_SCAFFOLD")
		return
	}

	name := filepath.Base(rel)
	if strings.HasSuffix(name, "_gen.go") || strings.HasSuffix(name, "_gen_test.go") || isForgeGeneratedBanner(full) {
		node.Ownership = OwnershipForgeSpace
		return
	}

	node.Ownership = OwnershipUser

	// Health flag: proto/db/ entity that doesn't appear in migrations.
	if strings.HasPrefix(relSlash, "proto/db/") && strings.HasSuffix(relSlash, ".proto") {
		// crude: look for `option (forge.v1.entity) = { table_name: "x" };`
		// and warn if x not present in migTables.
		if missing := protoEntityMissingFromMigrations(full, migTables); len(missing) > 0 {
			node.Flags = append(node.Flags, "diverged-from-migrations")
		}
	}

	_ = entityTables // reserved
}

// containsScaffoldMarker reports whether the file has a real scaffold
// placeholder (a line-start comment marker of the canonical form, e.g.
// the comment-form scaffold-marker shipped by forge templates). It
// deliberately ignores literal-string references to the marker name
// (forge's own linter source, docs that explain marker syntax) so
// `forge map` doesn't paint every file that mentions the marker as a
// scaffold.
//
// The semantics match `forge lint --scaffolds` and `forge audit`'s
// scaffold check; keeping the three views consistent avoids the "lint
// is green but map / audit are yellow" surprise.
func containsScaffoldMarker(path string) bool {
	// Markdown / JSON intentionally cite the marker syntax for
	// documentation; only treat source-shape files as scaffold
	// candidates, mirroring isMarkerScannable in audit.go.
	if !isMarkerScannable(filepath.Base(path)) {
		return false
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	return countLineStartScaffoldMarkers(data) > 0
}

// protoEntityMissingFromMigrations returns the list of `table_name` values
// in a proto file that do not appear in migTables. The parse is regex-only
// — no protoc import — to keep `forge map` cheap.
func protoEntityMissingFromMigrations(path string, migTables map[string]struct{}) []string {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil
	}
	var missing []string
	// rough: match `table_name: "<name>"`
	src := string(data)
	for _, line := range strings.Split(src, "\n") {
		idx := strings.Index(line, "table_name:")
		if idx < 0 {
			continue
		}
		rest := line[idx+len("table_name:"):]
		rest = strings.TrimSpace(rest)
		rest = strings.TrimLeft(rest, "\"")
		end := strings.Index(rest, "\"")
		if end < 0 {
			continue
		}
		name := strings.ToLower(rest[:end])
		if _, ok := migTables[name]; !ok {
			missing = append(missing, name)
		}
	}
	return missing
}

// printMapTree renders the human-readable tree with box-drawing chars.
// indent is the prefix accumulated for child lines (e.g. "│   ").
func printMapTree(w *os.File, n *MapNode, indent string) {
	// Print self.
	if indent == "" {
		fmt.Fprintln(w, n.Name)
	}
	for i, child := range n.Children {
		isLast := i == len(n.Children)-1
		branch := "├── "
		nextIndent := indent + "│   "
		if isLast {
			branch = "└── "
			nextIndent = indent + "    "
		}
		annot := ""
		if child.Ownership != "" || len(child.Flags) > 0 {
			parts := []string{}
			if child.Ownership != "" {
				parts = append(parts, child.Ownership)
			}
			for _, f := range child.Flags {
				parts = append(parts, "⚠ "+f)
			}
			annot = "    [" + strings.Join(parts, ", ") + "]"
		}
		fmt.Fprintf(w, "%s%s%s%s\n", indent, branch, child.Name, annot)
		if child.IsDir {
			printMapTree(w, child, nextIndent)
		}
	}
}
