package cli

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"github.com/reliant-labs/forge/internal/generator"
)

// TestBuildMapTree_Basic exercises the map tree builder against a tiny
// fixture: one tracked forge-space file, one user-owned file, one
// scaffold file. We assert that each file gets the right ownership label.
func TestBuildMapTree_Basic(t *testing.T) {
	dir := t.TempDir()

	// Write three files under different ownership classes.
	mustWriteFile(t, filepath.Join(dir, "internal", "billing", "service.go"), "package billing\n")
	mustWriteFile(t, filepath.Join(dir, "internal", "billing", "mock_gen.go"), "// Code generated by forge\npackage billing\n")
	mustWriteFile(t, filepath.Join(dir, "internal", "billing", "scaffold.go"), "package billing\n// FORGE_SCAFFOLD: replace me\n")

	// Track the forge-space file in the checksums file. Use the actual
	// content's hash so IsFileModified returns false and we get the
	// "regenerated" label rather than "drifted".
	cs := &generator.FileChecksums{
		ForgeVersion: "test",
		Files:        map[string]generator.FileChecksumEntry{},
	}
	rel := "internal/billing/mock_gen.go"
	full := filepath.Join(dir, rel)
	data, err := os.ReadFile(full)
	if err != nil {
		t.Fatal(err)
	}
	cs.Files[rel] = generator.FileChecksumEntry{Hash: generator.HashContent(data)}

	root, err := buildMapTree(dir, cs, "", 0, nil, nil)
	if err != nil {
		t.Fatalf("buildMapTree: %v", err)
	}

	// Walk down to the three leaves and assert ownership.
	got := map[string]string{}
	collectLeaves(root, got)
	wantOwnership := map[string]string{
		"internal/billing/service.go":   OwnershipUser,
		"internal/billing/mock_gen.go":  OwnershipForgeSpace,
		"internal/billing/scaffold.go":  OwnershipScaffold,
	}
	for path, want := range wantOwnership {
		if got[path] != want {
			t.Errorf("path %s: got ownership %q, want %q", path, got[path], want)
		}
	}

	// JSON round-trip.
	b, err := json.Marshal(root)
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	var decoded MapNode
	if err := json.Unmarshal(b, &decoded); err != nil {
		t.Fatalf("unmarshal: %v", err)
	}
}

func collectLeaves(n *MapNode, out map[string]string) {
	if !n.IsDir {
		out[n.Path] = n.Ownership
		return
	}
	for _, c := range n.Children {
		collectLeaves(c, out)
	}
}

func mustWriteFile(t *testing.T, path, body string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
}
