// Code generated by refactor extraction from main.go. Types and parsing
// for the protoc-gen-forge plugin.
//
// Forge ORM is annotation-driven: a message becomes a database entity ONLY
// when it carries an explicit `option (forge.v1.entity) = { ... }` and has
// at least one field marked `(forge.v1.field) = { pk: true }`. There is no
// auto-detection by field name (`id`, `created_at`, `tenant_id`, `email`,
// `*_id`, etc.) — every semantic must be declared. Auto-detection was
// removed in forge v0.6 because it conflicted with the explicit annotation
// system: name-based heuristics silently picked up unintended messages
// (e.g. service Request/Response wrappers with an `id` field) and
// shadow-applied semantics that the user never asked for.
package cli

import (
	"fmt"
	"strings"
	"unicode"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"

	forgev1 "github.com/reliant-labs/forge/internal/gen/forge/v1"
)

// entityInfo holds parsed entity metadata for a single annotated message.
type entityInfo struct {
	msg         *protogen.Message
	tableName   string
	softDelete  bool
	timestamps  bool
	middleware  []string
	fields      []fieldInfo
	pkField     *fieldInfo
	tenantField *fieldInfo // non-nil when exactly one field is marked as tenant_key
}

// fieldInfo holds parsed column metadata for a single field.
type fieldInfo struct {
	field         *protogen.Field
	columnName    string
	isPK          bool
	notNull       bool
	isTimestamp   bool
	unique        bool
	autoIncrement bool
	references    string          // FK reference in "table.column" format
	isTenantKey   bool            // true when marked as tenant_key for row-level isolation
	store         forgev1.StoreAs // how to persist complex types
	index         bool            // create a single-column index
	skip          bool            // skip this field in code generation
	immutable     bool            // field cannot be updated after creation
}

// parseEntity parses a proto message annotated with (forge.v1.entity) into
// an entityInfo. Returns (entityInfo{}, false, nil) for messages that have
// no entity annotation — those are not entities and the caller should skip.
// Returns a non-nil error when the message IS annotated as an entity but
// is malformed (e.g. missing a (forge.v1.field) = { pk: true } marker on
// any field): forge has no auto-detection fallback, so unannotated entities
// must produce a clear actionable error rather than silently generating
// broken ORM code.
func parseEntity(msg *protogen.Message) (entityInfo, bool, error) {
	opts := msg.Desc.Options()
	if opts == nil {
		return entityInfo{}, false, nil
	}
	ext := proto.GetExtension(opts, forgev1.E_Entity)
	if ext == nil {
		return entityInfo{}, false, nil
	}
	eo, ok := ext.(*forgev1.EntityOptions)
	if !ok || eo == nil {
		return entityInfo{}, false, nil
	}

	tableName := eo.GetTable()
	if tableName == "" {
		tableName = inferTableName(string(msg.Desc.Name()))
	}

	ent := entityInfo{
		msg:        msg,
		tableName:  tableName,
		softDelete: eo.GetSoftDelete(),
		timestamps: eo.GetTimestamps(),
		middleware: eo.GetMiddleware(),
	}

	for _, f := range msg.Fields {
		fi := parseField(f)
		if fi.skip {
			continue
		}
		ent.fields = append(ent.fields, fi)
		if fi.isPK {
			pk := fi
			ent.pkField = &pk
		}
		if fi.isTenantKey {
			tf := fi
			ent.tenantField = &tf
		}
	}

	// Annotation-only: the entity must declare its primary key explicitly via
	// (forge.v1.field) = { pk: true }. Auto-detection by field name (`id`)
	// was removed because it silently shadowed the explicit annotation
	// system. Surface a precise, actionable error instead.
	if ent.pkField == nil {
		return entityInfo{}, true, fmt.Errorf(
			"entity %q (in %s) is missing a primary key annotation: "+
				"mark the PK field with `[(forge.v1.field) = { pk: true }]`. "+
				"Auto-detection by field name was removed in forge v0.6",
			msg.Desc.Name(), msg.Desc.ParentFile().Path(),
		)
	}

	return ent, true, nil
}

func parseField(f *protogen.Field) fieldInfo {
	fi := fieldInfo{
		field:      f,
		columnName: toSnake(string(f.Desc.Name())),
	}

	if f.Desc.Message() != nil && f.Desc.Message().FullName() == "google.protobuf.Timestamp" {
		fi.isTimestamp = true
	}

	opts := f.Desc.Options()
	if opts == nil {
		return fi
	}

	ext := proto.GetExtension(opts, forgev1.E_Field)
	if ext != nil {
		if fo, ok := ext.(*forgev1.FieldOptions); ok && fo != nil {
			fi.isPK = fo.GetPk()
			fi.isTenantKey = fo.GetTenant()
			fi.unique = fo.GetUnique()
			fi.index = fo.GetIndex()
			fi.skip = fo.GetSkip()
			fi.immutable = fo.GetImmutable()
			fi.store = fo.GetStore()
			if fo.GetRef() != "" {
				fi.references = fo.GetRef()
			}
			if fi.isPK || fi.isTenantKey {
				fi.notNull = true
			}
		}
	}

	return fi
}

// isIntegerKind returns true for proto field kinds that map to integer DB types.
func isIntegerKind(k protoreflect.Kind) bool {
	switch k {
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind,
		protoreflect.Uint32Kind, protoreflect.Fixed32Kind,
		protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind,
		protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		return true
	}
	return false
}

// pluralize applies simple English pluralization rules.
func pluralize(s string) string {
	if s == "" {
		return s
	}
	if strings.HasSuffix(s, "y") {
		if len(s) >= 2 {
			prev := s[len(s)-2]
			if prev == 'a' || prev == 'e' || prev == 'i' || prev == 'o' || prev == 'u' {
				return s + "s"
			}
		}
		return s[:len(s)-1] + "ies"
	}
	if strings.HasSuffix(s, "s") || strings.HasSuffix(s, "x") ||
		strings.HasSuffix(s, "sh") || strings.HasSuffix(s, "ch") {
		return s + "es"
	}
	return s + "s"
}

// inferTableName derives a table name from a PascalCase message name by
// converting to snake_case and applying simple pluralization.
func inferTableName(messageName string) string {
	s := toSnake(messageName)
	if strings.HasSuffix(s, "y") {
		return s[:len(s)-1] + "ies"
	}
	if strings.HasSuffix(s, "s") {
		return s + "es"
	}
	return s + "s"
}

// toSnake converts a PascalCase or camelCase string to snake_case.
// This is intentionally a simple converter (no acronym handling) suitable
// for proto field/message names.
func toSnake(s string) string {
	var result []rune
	for i, r := range s {
		if i > 0 && unicode.IsUpper(r) {
			result = append(result, '_')
		}
		result = append(result, unicode.ToLower(r))
	}
	return string(result)
}

// goTypeForField returns the Go type string for a proto field.
func goTypeForField(f *protogen.Field) string {
	// Maps
	if f.Desc.IsMap() {
		keyType := scalarGoType(f.Desc.MapKey().Kind())
		valType := scalarGoType(f.Desc.MapValue().Kind())
		if f.Desc.MapValue().Kind() == protoreflect.MessageKind {
			valType = "*" + string(f.Message.Fields[1].Message.GoIdent.GoName)
		} else if f.Desc.MapValue().Kind() == protoreflect.EnumKind {
			valType = string(f.Desc.MapValue().Enum().Name())
		}
		return "map[" + keyType + "]" + valType
	}

	// Repeated (non-map)
	if f.Desc.IsList() {
		elemType := scalarGoType(f.Desc.Kind())
		if f.Desc.Kind() == protoreflect.MessageKind {
			elemType = "*" + f.Message.GoIdent.GoName
		} else if f.Desc.Kind() == protoreflect.EnumKind {
			elemType = f.Enum.GoIdent.GoName
		}
		return "[]" + elemType
	}

	// Enums
	if f.Desc.Kind() == protoreflect.EnumKind {
		return f.Enum.GoIdent.GoName
	}

	// Messages (Timestamp, wrappers, custom)
	if f.Desc.Kind() == protoreflect.MessageKind {
		fullName := f.Desc.Message().FullName()
		switch fullName {
		case "google.protobuf.Timestamp":
			return "*timestamppb.Timestamp"
		case "google.protobuf.StringValue":
			return "*string"
		case "google.protobuf.Int32Value":
			return "*int32"
		case "google.protobuf.Int64Value":
			return "*int64"
		case "google.protobuf.BoolValue":
			return "*bool"
		case "google.protobuf.FloatValue":
			return "*float32"
		case "google.protobuf.DoubleValue":
			return "*float64"
		case "google.protobuf.UInt32Value":
			return "*uint32"
		case "google.protobuf.UInt64Value":
			return "*uint64"
		case "google.protobuf.BytesValue":
			return "[]byte"
		default:
			return "*" + f.Message.GoIdent.GoName
		}
	}

	return scalarGoType(f.Desc.Kind())
}

// scalarGoType returns the Go type for a scalar proto kind.
func scalarGoType(k protoreflect.Kind) string {
	switch k {
	case protoreflect.StringKind:
		return "string"
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
		return "int32"
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		return "int64"
	case protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
		return "uint32"
	case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		return "uint64"
	case protoreflect.BoolKind:
		return "bool"
	case protoreflect.FloatKind:
		return "float32"
	case protoreflect.DoubleKind:
		return "float64"
	case protoreflect.BytesKind:
		return "[]byte"
	default:
		return "string"
	}
}

// isNullableType returns true if the proto field type maps to a Go type that
// should be scanned as a pointer when the column is nullable.
func isNullableType(f *protogen.Field) bool {
	switch f.Desc.Kind() {
	case protoreflect.StringKind,
		protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind,
		protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind,
		protoreflect.Uint32Kind, protoreflect.Fixed32Kind,
		protoreflect.Uint64Kind, protoreflect.Fixed64Kind,
		protoreflect.BoolKind,
		protoreflect.FloatKind, protoreflect.DoubleKind:
		return true
	}
	return false
}

// wrapperGoType returns the wrapperspb Go type for a well-known wrapper
// message (e.g. "wrapperspb.DoubleValue" for google.protobuf.DoubleValue)
// and the unwrapped scalar Go type stored on the wrapper's Value field
// (e.g. "float64"). Returns ("", "", false) for fields that are not
// well-known wrappers.
//
// The ORM codegen treats wrapper fields specially: the entity struct
// inherits the protoc-generated `*wrapperspb.XValue` field type, but the
// database column stores the unwrapped scalar (nullable). Without this
// distinction, generateValues would pass `*wrapperspb.XValue` to the SQL
// driver (which has no conversion) and generateScan would assign a
// `*scalar` directly to the wrapper field (type mismatch → go build fails).
// See orm_codegen.go::generateValues / generateScan for the bridge.
func wrapperGoType(f *protogen.Field) (wrapper string, scalar string, ok bool) {
	if f.Desc.Kind() != protoreflect.MessageKind || f.Desc.Message() == nil {
		return "", "", false
	}
	switch f.Desc.Message().FullName() {
	case "google.protobuf.StringValue":
		return "wrapperspb.StringValue", "string", true
	case "google.protobuf.Int32Value":
		return "wrapperspb.Int32Value", "int32", true
	case "google.protobuf.Int64Value":
		return "wrapperspb.Int64Value", "int64", true
	case "google.protobuf.UInt32Value":
		return "wrapperspb.UInt32Value", "uint32", true
	case "google.protobuf.UInt64Value":
		return "wrapperspb.UInt64Value", "uint64", true
	case "google.protobuf.BoolValue":
		return "wrapperspb.BoolValue", "bool", true
	case "google.protobuf.FloatValue":
		return "wrapperspb.FloatValue", "float32", true
	case "google.protobuf.DoubleValue":
		return "wrapperspb.DoubleValue", "float64", true
	}
	return "", "", false
}

// isWrapperField is a thin predicate over wrapperGoType used at call sites
// that don't need the type names.
func isWrapperField(f *protogen.Field) bool {
	_, _, ok := wrapperGoType(f)
	return ok
}

// protoKindToOrmType maps proto field kinds to orm.FieldType constants.
func protoKindToOrmType(f *protogen.Field, isTimestamp bool) string {
	if isTimestamp {
		return "orm.TypeTimestampTZ"
	}
	switch f.Desc.Kind() {
	case protoreflect.StringKind:
		return "orm.TypeText"
	case protoreflect.BoolKind:
		return "orm.TypeBoolean"
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind,
		protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
		return "orm.TypeInteger"
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind,
		protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		return "orm.TypeBigInt"
	case protoreflect.FloatKind:
		return "orm.TypeReal"
	case protoreflect.DoubleKind:
		return "orm.TypeDoublePrecision"
	case protoreflect.BytesKind:
		return "orm.TypeBytea"
	case protoreflect.EnumKind:
		return "orm.TypeInteger"
	case protoreflect.MessageKind:
		return "orm.TypeText" // JSON-serialized by default
	default:
		return "orm.TypeText"
	}
}
