package cli

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/reliant-labs/forge/internal/config"
	"github.com/reliant-labs/forge/internal/generator"
)

// The upgrade command writes its report straight to os.Stdout, and for a
// --check run that report IS the product — so these tests assert on it via
// captureStdout (dev_status_test.go).

func forceTestConfig() *config.ProjectConfig {
	return &config.ProjectConfig{
		Name:       "test-project",
		ModulePath: "github.com/example/test-project",
	}
}

// TestResolveForceSelection covers the flag surface: nothing armed, the
// whole-project form, and the per-path form that lets a user adopt one
// template without stomping every other file they have customized.
func TestResolveForceSelection(t *testing.T) {
	cfg := forceTestConfig()

	sel, err := resolveForceSelection(cfg, false, nil)
	if err != nil {
		t.Fatalf("no flags: %v", err)
	}
	if sel.Any() {
		t.Error("no --force must overwrite nothing")
	}

	sel, err = resolveForceSelection(cfg, true, nil)
	if err != nil {
		t.Fatalf("bare --force: %v", err)
	}
	if !sel.Allows("Dockerfile") || !sel.Allows("buf.yaml") {
		t.Error("bare --force must cover every managed file")
	}

	sel, err = resolveForceSelection(cfg, true, []string{"Dockerfile"})
	if err != nil {
		t.Fatalf("--force Dockerfile: %v", err)
	}
	if !sel.Allows("Dockerfile") {
		t.Error("--force Dockerfile must cover Dockerfile")
	}
	if sel.Allows("buf.yaml") {
		t.Error("--force Dockerfile must NOT cover buf.yaml")
	}
}

// TestResolveForceSelection_PathsNeedForce: a path list only ever narrows a
// destructive act, so it must not arm one on its own.
func TestResolveForceSelection_PathsNeedForce(t *testing.T) {
	sel, err := resolveForceSelection(forceTestConfig(), false, []string{"Dockerfile"})
	if err == nil {
		t.Fatal("expected an error for paths without --force")
	}
	if sel.Any() {
		t.Error("a rejected invocation must not arm any overwrite")
	}
	if !strings.Contains(err.Error(), "--force") {
		t.Errorf("error should point at --force: %v", err)
	}
}

// TestResolveForceSelection_UnknownPathRejected: silently ignoring a path
// upgrade does not manage would report "nothing forced" while the user
// believes the file was adopted.
func TestResolveForceSelection_UnknownPathRejected(t *testing.T) {
	_, err := resolveForceSelection(forceTestConfig(), true, []string{"internal/app/setup.go"})
	if err == nil {
		t.Fatal("expected an error for a path upgrade does not manage")
	}
	if !strings.Contains(err.Error(), "internal/app/setup.go") {
		t.Errorf("error should name the offending path: %v", err)
	}
	// The remedy lists what upgrade DOES own, so a typo is one read away
	// from the right path.
	if !strings.Contains(err.Error(), "Dockerfile") {
		t.Errorf("error should list the managed paths: %v", err)
	}
}

// TestResolveForceSelection_ManagedPathsAreProjectShaped pins that validation
// uses THIS project's managed set: the command tree is binary-name scoped, so
// a per-service project's cmd/<name>/cmd/commands.go is a legitimate --force
// argument.
func TestResolveForceSelection_ManagedPathsAreProjectShaped(t *testing.T) {
	cfg := forceTestConfig()
	rel := filepath.Join("cmd", "test-project", "cmd", "commands.go")
	sel, err := resolveForceSelection(cfg, true, []string{rel})
	if err != nil {
		t.Fatalf("--force %s: %v", rel, err)
	}
	if !sel.Allows(rel) {
		t.Errorf("%s should be covered by the selection", rel)
	}
	for _, p := range generator.ManagedPathsFor(cfg) {
		if p == rel {
			return
		}
	}
	t.Errorf("%s missing from ManagedPathsFor", rel)
}

// TestRunUpgradeCheck_DevPinnedProjectGetsATruthfulAnswer is the end-to-end
// regression test for the bug this work fixes.
//
// A project generated by a locally-built forge pins a Go pseudo-version. That
// project used to be handed a migration toward a shape that had already been
// deleted, for a release the project was never on and forge has never cut. The
// run must instead report the baseline honestly, label it as a dev build, and
// offer no migration it cannot show applies. All of that with no tag published
// anywhere.
//
// The assertion is on the migration SECTION rather than any skill name: the
// registry is pruned per release and is empty most of the time, so a test
// naming a specific migration dies with that migration while the property it
// was protecting — never offering one that doesn't apply — still needs a guard.
func TestRunUpgradeCheck_DevPinnedProjectGetsATruthfulAnswer(t *testing.T) {
	const devPin = "v0.0.4-0.20260724212501-dfb85daf8474+dirty"
	dir := newTestProjectWithVersion(t, devPin)

	var out string
	withCwd(t, dir, func() {
		out = captureStdout(t, func() {
			if err := runUpgrade(true /* check */, false, nil, ""); err != nil {
				t.Fatalf("runUpgrade --check: %v", err)
			}
		})
	})

	if strings.Contains(out, "Migrations this project still needs") {
		t.Errorf("a dev-pinned project with none of the old shapes was offered migrations anyway:\n%s", out)
	}
	if !strings.Contains(out, devPin) {
		t.Errorf("baseline should be reported exactly as pinned:\n%s", out)
	}
	if !strings.Contains(out, "(dev build)") {
		t.Errorf("a pseudo-version baseline should be labelled a dev build:\n%s", out)
	}
	// The template-drift half still runs and still reports — a truthful
	// answer is not an empty one.
	//
	// Asserted on the SECTION, not on a particular filename. The report
	// caps each group at maxRowsPerGroup, so which files are listed
	// depends on how many this fixture happens to produce; a test naming
	// one of them fails the day the cap or the fixture moves, while the
	// property it guards — that the managed lane said something — still
	// needs a guard. `--all` then proves the named file is reachable.
	if !strings.Contains(out, "would update") {
		t.Errorf("expected the managed-file report:\n%s", out)
	}

	var all string
	withCwd(t, dir, func() {
		all = captureStdout(t, func() {
			if err := runUpgradeWithView(true, false, true /* all */, nil, ""); err != nil {
				t.Fatalf("runUpgrade --check --all: %v", err)
			}
		})
	})
	if !strings.Contains(all, "Dockerfile") {
		t.Errorf("--all must name every managed file the report covers:\n%s", all)
	}
}

// TestRunUpgradeCheck_NamesBothRemedies: at the moment a user is looking at
// the diff of a file upgrade refused to touch, both ways out must be on
// screen — adopt this specific file, or claim it permanently. `disown` was
// already the durable answer; nothing said so when it mattered.
func TestRunUpgradeCheck_NamesBothRemedies(t *testing.T) {
	dir := newTestProjectWithVersion(t, "v0.0.3")
	// An unmarked, non-template Dockerfile reads as user-modified.
	if err := os.WriteFile(filepath.Join(dir, "Dockerfile"), []byte("FROM scratch\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	var out string
	withCwd(t, dir, func() {
		out = captureStdout(t, func() {
			if err := runUpgrade(true /* check */, false, nil, ""); err != nil {
				t.Fatalf("runUpgrade --check: %v", err)
			}
		})
	})

	if !strings.Contains(out, "with local edits (skipped)") {
		t.Fatalf("expected Dockerfile to report as carrying local edits:\n%s", out)
	}
	if !strings.Contains(out, "Dockerfile") {
		t.Fatalf("expected Dockerfile to be named:\n%s", out)
	}
	if !strings.Contains(out, "project upgrade --force Dockerfile") {
		t.Errorf("expected the per-path adopt remedy naming the file:\n%s", out)
	}
	if !strings.Contains(out, "project disown Dockerfile") {
		t.Errorf("expected the disown remedy naming the file:\n%s", out)
	}
	if !strings.Contains(out, "--reason") {
		t.Errorf("the disown hint must include the required --reason flag:\n%s", out)
	}
}

// TestRunUpgrade_PerPathForceLeavesOtherEditsAlone drives the CLI end to end:
// two hand-edited managed files, one named after --force. Only the named file
// may change on disk.
func TestRunUpgrade_PerPathForceLeavesOtherEditsAlone(t *testing.T) {
	dir := newTestProjectWithVersion(t, "v0.0.3")
	const forced = "Dockerfile"
	const spared = "docker-compose.yml"
	edit := []byte("# hand-edited by the user\n")
	for _, rel := range []string{forced, spared} {
		if err := os.WriteFile(filepath.Join(dir, rel), edit, 0o644); err != nil {
			t.Fatal(err)
		}
	}

	withCwd(t, dir, func() {
		_ = captureStdout(t, func() {
			if err := runUpgrade(false, true /* force */, []string{forced}, ""); err != nil {
				t.Fatalf("runUpgrade --force %s: %v", forced, err)
			}
		})
	})

	forcedNow, err := os.ReadFile(filepath.Join(dir, forced))
	if err != nil {
		t.Fatal(err)
	}
	if string(forcedNow) == string(edit) {
		t.Errorf("%s was named in --force but not adopted", forced)
	}
	sparedNow, err := os.ReadFile(filepath.Join(dir, spared))
	if err != nil {
		t.Fatal(err)
	}
	if string(sparedNow) != string(edit) {
		t.Errorf("%s was not named in --force but was rewritten:\n%s", spared, sparedNow)
	}
}
