// Code generated by forge. DO NOT EDIT.
// forge:hash=4dc229e57b6a99d2ec0f3920617efd7234c7792c86ced9322fb5c3228cc346a8
// forge-owned: regenerated every run — do not edit (forge project disown to take ownership)
// Source: contract.go in this package.
//
// To customize: edit contract.go (the interface IS the public surface) and
// re-run "forge generate". This file is regenerated unconditionally.
package docs

import (
	"github.com/reliant-labs/forge/internal/codegen"
	"github.com/reliant-labs/forge/internal/config"
	"github.com/reliant-labs/forge/internal/generator/contract"
	"github.com/reliant-labs/forge/pkg/contractkit"
)

// MockService is a test mock for the Service interface.
//
// The embedded contractkit.Recorder records every call so tests can
// assert call counts and captured arguments. Set XxxFunc fields to
// override per-method behaviour; unset methods return the canonical
// "MockService.<Method>Func not set" error.
type MockService struct {
	contractkit.Recorder
	RunFunc func(string, *config.ProjectConfig, *Overrides) error
}

// Run records the call and delegates to RunFunc when set.
func (m *MockService) Run(projectDir string, cfg *config.ProjectConfig, overrides *Overrides) error {
	m.Recorder.Record("Run", projectDir, cfg, overrides)
	if m.RunFunc != nil {
		return m.RunFunc(projectDir, cfg, overrides)
	}
	return contractkit.MockNotSet("MockService", "Run")
}

// Compile-time check.
var _ Service = (*MockService)(nil)

// MockParser is a test mock for the codegen.Parser interface.
//
// The embedded contractkit.Recorder records every call so tests can
// assert call counts and captured arguments. Set XxxFunc fields to
// override per-method behaviour; unset methods return the canonical
// "MockParser.<Method>Func not set" error.
type MockParser struct {
	contractkit.Recorder
	ParseServicesFromProtosFunc  func(string, string) ([]codegen.ServiceDef, error)
	ParseEntityProtosFunc        func(string) ([]codegen.EntityDef, error)
	ParseConfigProtoFunc         func(string) ([]codegen.ConfigMessage, error)
	ParseConfigProtosFromDirFunc func(string) ([]codegen.ConfigMessage, error)
	GetModulePathFunc            func(string) (string, error)
}

// ParseServicesFromProtos records the call and delegates to ParseServicesFromProtosFunc when set.
func (m *MockParser) ParseServicesFromProtos(dir string, projectDir string) ([]codegen.ServiceDef, error) {
	m.Recorder.Record("ParseServicesFromProtos", dir, projectDir)
	if m.ParseServicesFromProtosFunc != nil {
		return m.ParseServicesFromProtosFunc(dir, projectDir)
	}
	return nil, contractkit.MockNotSet("MockParser", "ParseServicesFromProtos")
}

// ParseEntityProtos records the call and delegates to ParseEntityProtosFunc when set.
func (m *MockParser) ParseEntityProtos(projectDir string) ([]codegen.EntityDef, error) {
	m.Recorder.Record("ParseEntityProtos", projectDir)
	if m.ParseEntityProtosFunc != nil {
		return m.ParseEntityProtosFunc(projectDir)
	}
	return nil, contractkit.MockNotSet("MockParser", "ParseEntityProtos")
}

// ParseConfigProto records the call and delegates to ParseConfigProtoFunc when set.
func (m *MockParser) ParseConfigProto(protoPath string) ([]codegen.ConfigMessage, error) {
	m.Recorder.Record("ParseConfigProto", protoPath)
	if m.ParseConfigProtoFunc != nil {
		return m.ParseConfigProtoFunc(protoPath)
	}
	return nil, contractkit.MockNotSet("MockParser", "ParseConfigProto")
}

// ParseConfigProtosFromDir records the call and delegates to ParseConfigProtosFromDirFunc when set.
func (m *MockParser) ParseConfigProtosFromDir(dir string) ([]codegen.ConfigMessage, error) {
	m.Recorder.Record("ParseConfigProtosFromDir", dir)
	if m.ParseConfigProtosFromDirFunc != nil {
		return m.ParseConfigProtosFromDirFunc(dir)
	}
	return nil, contractkit.MockNotSet("MockParser", "ParseConfigProtosFromDir")
}

// GetModulePath records the call and delegates to GetModulePathFunc when set.
func (m *MockParser) GetModulePath(dir string) (string, error) {
	m.Recorder.Record("GetModulePath", dir)
	if m.GetModulePathFunc != nil {
		return m.GetModulePathFunc(dir)
	}
	return "", contractkit.MockNotSet("MockParser", "GetModulePath")
}

// Compile-time check.
var _ codegen.Parser = (*MockParser)(nil)

// MockContractService is a test mock for the contract.Service interface.
//
// The embedded contractkit.Recorder records every call so tests can
// assert call counts and captured arguments. Set XxxFunc fields to
// override per-method behaviour; unset methods return the canonical
// "MockContractService.<Method>Func not set" error.
type MockContractService struct {
	contractkit.Recorder
	GenerateFunc      func(string) error
	ParseContractFunc func(string) (*contract.File, error)
}

// Generate records the call and delegates to GenerateFunc when set.
func (m *MockContractService) Generate(contractPath string) error {
	m.Recorder.Record("Generate", contractPath)
	if m.GenerateFunc != nil {
		return m.GenerateFunc(contractPath)
	}
	return contractkit.MockNotSet("MockContractService", "Generate")
}

// ParseContract records the call and delegates to ParseContractFunc when set.
func (m *MockContractService) ParseContract(path string) (*contract.File, error) {
	m.Recorder.Record("ParseContract", path)
	if m.ParseContractFunc != nil {
		return m.ParseContractFunc(path)
	}
	return nil, contractkit.MockNotSet("MockContractService", "ParseContract")
}

// Compile-time check.
var _ contract.Service = (*MockContractService)(nil)
