package protomethod

import (
	"go/ast"
	"go/types"
	"strings"

	"golang.org/x/tools/go/analysis"
	"golang.org/x/tools/go/analysis/passes/inspect"
	"golang.org/x/tools/go/ast/inspector"
)

var Analyzer = &analysis.Analyzer{
	Name:     "protomethod",
	Doc:      "checks that all exported functions/methods implement proto service interfaces (no exported standalone functions allowed)",
	Run:      run,
	Requires: []*analysis.Analyzer{inspect.Analyzer},
}

// protoService holds a resolved proto service handler interface.
type protoService struct {
	interfaceName string
	ifaceType     *types.Interface
	methodNames   map[string]bool
}

// scaffoldedMethods are methods generated by forge on service types
// that are part of the framework contract, not proto service methods.
var scaffoldedMethods = map[string]bool{
	"Name":         true,
	"Register":     true,
	"RegisterHTTP": true,
}

func run(pass *analysis.Pass) (interface{}, error) {
	insp := pass.ResultOf[inspect.Analyzer].(*inspector.Inspector)

	// Collect proto handler interfaces from both local .connect.go files
	// AND imported packages (the gen/ module is typically a separate module).
	protoServices := extractProtoServices(pass)
	if len(protoServices) == 0 {
		return nil, nil
	}

	// Build a map from named types to the set of proto interface method names
	// they are allowed to have, based on which proto interfaces they implement.
	typeAllowed := buildTypeAllowedMethods(pass, protoServices)

	nodeFilter := []ast.Node{
		(*ast.FuncDecl)(nil),
	}

	insp.Preorder(nodeFilter, func(n ast.Node) {
		funcDecl := n.(*ast.FuncDecl)

		// Skip test files.
		filename := pass.Fset.File(funcDecl.Pos()).Name()
		if strings.HasSuffix(filename, "_test.go") {
			return
		}

		// Skip generated files (mocks, etc.).
		if isGeneratedFile(pass, funcDecl) {
			return
		}

		if !ast.IsExported(funcDecl.Name.Name) {
			return
		}

		// Standalone exported functions (no receiver).
		if funcDecl.Recv == nil || len(funcDecl.Recv.List) == 0 {
			// Allow constructor functions (New, NewFoo) that return a
			// package-local type. These are the standard Go factory pattern.
			if isConstructor(pass, funcDecl) {
				return
			}
			// Allow functions annotated with //forge:allow.
			if hasAllowDirective(pass, funcDecl) {
				return
			}
			pass.Reportf(funcDecl.Pos(),
				"exported function %s is not allowed; all exported functions must be methods implementing proto service interfaces",
				funcDecl.Name.Name)
			return
		}

		// Resolve the receiver's named type via the type checker.
		recvType := pass.TypesInfo.TypeOf(funcDecl.Recv.List[0].Type)
		if recvType == nil {
			return
		}
		if ptr, ok := recvType.(*types.Pointer); ok {
			recvType = ptr.Elem()
		}
		named, ok := recvType.(*types.Named)
		if !ok {
			return
		}

		allowed, isProtoImpl := typeAllowed[named]
		if !isProtoImpl {
			// This type doesn't implement any proto handler interface.
			// Skip it — the linter only enforces method discipline on
			// types that embed Unimplemented*Handler.
			return
		}

		// The type implements a proto handler. Allow proto interface methods
		// and scaffolded framework methods.
		methodName := funcDecl.Name.Name
		if allowed[methodName] || scaffoldedMethods[methodName] {
			return
		}

		// Allow HTTP handler methods — these are registered via RegisterHTTP
		// and intentionally exist outside the proto contract. Detection is
		// signature-based: (http.ResponseWriter, *http.Request) is the standard
		// Go HTTP handler signature.
		if isHTTPHandler(pass, funcDecl) {
			return
		}

		// Check for escape hatch annotation: //forge:allow
		if hasAllowDirective(pass, funcDecl) {
			return
		}

		recvName := named.Obj().Name()
		pass.Reportf(funcDecl.Pos(),
			"exported method %s.%s does not implement a proto service interface; only proto service methods should be exported",
			recvName, methodName)
	})

	return nil, nil
}

func isHTTPHandler(pass *analysis.Pass, funcDecl *ast.FuncDecl) bool {
	params := funcDecl.Type.Params
	if params == nil || len(params.List) != 2 {
		return false
	}

	// Resolve types via the type checker
	firstType := pass.TypesInfo.TypeOf(params.List[0].Type)
	secondType := pass.TypesInfo.TypeOf(params.List[1].Type)
	if firstType == nil || secondType == nil {
		return false
	}

	return isHTTPResponseWriter(firstType) && isHTTPRequest(secondType)
}

func isHTTPResponseWriter(t types.Type) bool {
	// http.ResponseWriter is an interface — check the named type directly
	named, ok := t.(*types.Named)
	if !ok {
		return false
	}
	obj := named.Obj()
	return obj.Name() == "ResponseWriter" && obj.Pkg() != nil && obj.Pkg().Path() == "net/http"
}

func isHTTPRequest(t types.Type) bool {
	// http.Request is used as *http.Request — unwrap the pointer first
	ptr, ok := t.(*types.Pointer)
	if !ok {
		return false
	}
	named, ok := ptr.Elem().(*types.Named)
	if !ok {
		return false
	}
	obj := named.Obj()
	return obj.Name() == "Request" && obj.Pkg() != nil && obj.Pkg().Path() == "net/http"
}

func hasAllowDirective(pass *analysis.Pass, funcDecl *ast.FuncDecl) bool {
	funcLine := pass.Fset.Position(funcDecl.Pos()).Line

	// Find the file containing this function
	for _, file := range pass.Files {
		filePos := pass.Fset.Position(file.Pos())
		funcPos := pass.Fset.Position(funcDecl.Pos())
		if filePos.Filename != funcPos.Filename {
			continue
		}

		for _, cg := range file.Comments {
			for _, c := range cg.List {
				commentLine := pass.Fset.Position(c.Pos()).Line
				// Allow comment on same line or line immediately before
				if (commentLine == funcLine || commentLine == funcLine-1) &&
					strings.Contains(c.Text, "forge:allow") {
					return true
				}
			}
		}
	}
	return false
}

// isGeneratedFile checks if the file containing the node has a "Code generated"
// comment as specified by the Go generate convention.
func isGeneratedFile(pass *analysis.Pass, funcDecl *ast.FuncDecl) bool {
	pos := pass.Fset.Position(funcDecl.Pos())
	for _, file := range pass.Files {
		filePos := pass.Fset.Position(file.Pos())
		if filePos.Filename != pos.Filename {
			continue
		}
		for _, cg := range file.Comments {
			for _, c := range cg.List {
				if strings.Contains(c.Text, "Code generated") && strings.Contains(c.Text, "DO NOT EDIT") {
					return true
				}
			}
		}
	}
	return false
}

// isConstructor returns true for functions named "New" or "NewFoo" that return
// a pointer to a type defined in the same package. This is the standard Go
// constructor pattern used by forge for service and authorizer constructors.
func isConstructor(pass *analysis.Pass, funcDecl *ast.FuncDecl) bool {
	name := funcDecl.Name.Name
	if name != "New" && !strings.HasPrefix(name, "New") {
		return false
	}

	// Must return at least one value.
	if funcDecl.Type.Results == nil || len(funcDecl.Type.Results.List) == 0 {
		return false
	}

	// Check that the first return type is a pointer to a named type in this package.
	firstResult := funcDecl.Type.Results.List[0]
	resultType := pass.TypesInfo.TypeOf(firstResult.Type)
	if resultType == nil {
		return false
	}
	if ptr, ok := resultType.(*types.Pointer); ok {
		resultType = ptr.Elem()
	}
	named, ok := resultType.(*types.Named)
	if !ok {
		return false
	}

	return named.Obj().Pkg() == pass.Pkg
}

// buildTypeAllowedMethods maps each named type in the package to the set of
// method names it is allowed to export, based on which proto handler
// interfaces it implements (checked via types.Implements).
func buildTypeAllowedMethods(pass *analysis.Pass, services []*protoService) map[*types.Named]map[string]bool {
	result := make(map[*types.Named]map[string]bool)

	for _, obj := range pass.TypesInfo.Defs {
		tn, ok := obj.(*types.TypeName)
		if !ok || tn.IsAlias() {
			continue
		}
		named, ok := tn.Type().(*types.Named)
		if !ok {
			continue
		}

		ptrType := types.NewPointer(named)
		for _, svc := range services {
			// Skip empty interfaces — a proto service with no RPCs produces
			// an empty handler interface that every type satisfies.
			if svc.ifaceType.NumMethods() == 0 {
				continue
			}
			if !types.Implements(named, svc.ifaceType) && !types.Implements(ptrType, svc.ifaceType) {
				continue
			}
			// This type implements svc — merge allowed method names.
			if result[named] == nil {
				result[named] = make(map[string]bool)
			}
			for name := range svc.methodNames {
				result[named][name] = true
			}
		}
	}

	return result
}

// extractProtoServices finds proto handler interfaces from two sources:
// 1. Local *.connect.go files in the current package (same-package case)
// 2. Imported packages whose path ends with "connect" (cross-module case,
//
//	e.g., gen/services/api/v1/apiv1connect)
//
// This handles both single-module projects (where connect.go is in the same
// package) and multi-module projects (where gen/ is a separate module).
func extractProtoServices(pass *analysis.Pass) []*protoService {
	var services []*protoService

	// Source 1: Local .connect.go files in the package being analyzed.
	services = append(services, extractFromLocalFiles(pass)...)

	// Source 2: Imported packages that look like connect-generated packages.
	services = append(services, extractFromImports(pass)...)

	return services
}

// extractFromLocalFiles scans pass.Files for *.connect.go files and extracts
// handler interfaces from them (for single-package projects).
func extractFromLocalFiles(pass *analysis.Pass) []*protoService {
	var services []*protoService

	for _, file := range pass.Files {
		if !strings.HasSuffix(pass.Fset.File(file.Pos()).Name(), ".connect.go") {
			continue
		}

		for _, decl := range file.Decls {
			genDecl, ok := decl.(*ast.GenDecl)
			if !ok {
				continue
			}
			for _, spec := range genDecl.Specs {
				typeSpec, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}
				if _, ok := typeSpec.Type.(*ast.InterfaceType); !ok {
					continue
				}
				if !isHandlerInterface(typeSpec.Name.Name) {
					continue
				}

				obj := pass.TypesInfo.Defs[typeSpec.Name]
				if obj == nil {
					continue
				}
				tn, ok := obj.(*types.TypeName)
				if !ok {
					continue
				}
				iface, ok := tn.Type().Underlying().(*types.Interface)
				if !ok {
					continue
				}

				services = append(services, newProtoService(typeSpec.Name.Name, iface))
			}
		}
	}

	return services
}

// extractFromImports scans imported packages for handler interfaces.
// This covers the cross-module case where the connect-generated code
// is in a separate gen/ module.
func extractFromImports(pass *analysis.Pass) []*protoService {
	var services []*protoService

	for _, pkg := range pass.Pkg.Imports() {
		// Connect-generated packages have paths ending in "connect"
		// (e.g., "apiv1connect", "usersv1connect").
		// Exclude the core connect library itself (connectrpc.com/connect)
		// which is not a generated package.
		pkgPath := pkg.Path()
		if !strings.HasSuffix(pkgPath, "connect") {
			continue
		}
		if pkgPath == "connectrpc.com/connect" {
			continue
		}

		scope := pkg.Scope()
		for _, name := range scope.Names() {
			if !isHandlerInterface(name) {
				continue
			}

			obj := scope.Lookup(name)
			tn, ok := obj.(*types.TypeName)
			if !ok {
				continue
			}
			iface, ok := tn.Type().Underlying().(*types.Interface)
			if !ok {
				continue
			}

			services = append(services, newProtoService(name, iface))
		}
	}

	return services
}

// isHandlerInterface returns true for names like "APIServiceHandler" but
// false for "UnimplementedAPIServiceHandler" and "UnsafeAPIServiceHandler".
func isHandlerInterface(name string) bool {
	if !strings.HasSuffix(name, "Handler") {
		return false
	}
	if strings.HasPrefix(name, "Unimplemented") || strings.HasPrefix(name, "Unsafe") {
		return false
	}
	return true
}

// newProtoService creates a protoService from a resolved interface type.
func newProtoService(name string, iface *types.Interface) *protoService {
	methodNames := make(map[string]bool)
	for i := range iface.NumMethods() {
		methodNames[iface.Method(i).Name()] = true
	}
	return &protoService{
		interfaceName: name,
		ifaceType:     iface,
		methodNames:   methodNames,
	}
}