package controller

import (
	"context"
	"fmt"
	"log/slog"
	"reflect"
	"time"

	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/client-go/tools/record"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/builder"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/controller/controllerutil"
	"sigs.k8s.io/controller-runtime/pkg/handler"
	"sigs.k8s.io/controller-runtime/pkg/predicate"
	"sigs.k8s.io/controller-runtime/pkg/reconcile"
)

// ReconcileFunc is the user-supplied domain-logic callback invoked by
// Reconciler[T].Reconcile after the object has been fetched and
// finalizer/deletion bookkeeping has been performed. Returning a
// non-nil error causes controller-runtime to requeue with backoff.
type ReconcileFunc[T client.Object] func(ctx context.Context, obj T) (Result, error)

// FinalizeFunc is the optional user-supplied callback invoked when the
// object is being deleted and Finalizer is set. It runs BEFORE the
// finalizer is removed; if it returns an error, the finalizer is left
// in place and controller-runtime requeues.
type FinalizeFunc[T client.Object] func(ctx context.Context, obj T) error

// Reconciler is the generic base for typed controller-runtime
// reconcilers. Per-CRD shims embed it:
//
//	type WorkspaceController struct {
//	    controller.Reconciler[*v1alpha1.Workspace]
//	    DB        *sql.DB
//	    Publisher EventPublisher
//	}
//
//	func (r *WorkspaceController) ReconcileSpec(ctx context.Context, w *v1alpha1.Workspace) (controller.Result, error) {
//	    // user implements domain logic
//	    return controller.Done(), nil
//	}
//
//	func (r *WorkspaceController) FinalizeSpec(ctx context.Context, w *v1alpha1.Workspace) error {
//	    // user implements cleanup
//	    return nil
//	}
//
// The Reconcile method on the embedded Reconciler is wired by calling
// SetupWithManager + a small Reconcile entry point (typically
// generated by `forge add crd`) that delegates to ReconcileFunc /
// FinalizeFunc.
//
// The zero value is NOT ready to use: at minimum Client and Scheme
// must be populated by SetupWithManager.
type Reconciler[T client.Object] struct {
	// Client is the controller-runtime client used to fetch and
	// patch the reconciled object. Populated by SetupWithManager.
	Client client.Client

	// Scheme is the runtime scheme used by the manager. Populated
	// by SetupWithManager.
	Scheme *runtime.Scheme

	// Recorder is an optional event recorder. When non-nil,
	// Reconciler emits a "Reconciling" / "Reconciled" event around
	// each reconcile attempt.
	Recorder record.EventRecorder

	// Log is the structured logger used by the base. Defaults to
	// slog.Default() when nil.
	Log *slog.Logger

	// Finalizer is the optional finalizer string. When non-empty,
	// Reconcile auto-adds the finalizer on first reconcile and
	// invokes FinalizeFunc on deletion before removing the
	// finalizer.
	Finalizer string
}

// Run is the entry-point invoked by per-CRD shims. The shim's
// Reconcile method calls Run, passing the object's blank-T template
// and the user's ReconcileFunc / FinalizeFunc.
//
// Lifecycle:
//
//  1. Fetch the resource. NotFound → (Done(), nil).
//  2. If the object is being deleted AND r.Finalizer is set AND the
//     object carries the finalizer: invoke finalize, remove the
//     finalizer, return.
//  3. If the object is NOT being deleted AND r.Finalizer is set AND
//     the finalizer is missing: add the finalizer, re-fetch, then
//     dispatch to reconcile.
//  4. Otherwise dispatch to reconcile and return its result.
//
// blank is a freshly-allocated zero value of T (e.g. &v1alpha1.Workspace{}).
// The shim creates it because Go generics can't allocate concrete types
// from the type parameter alone (T may be an interface satisfied by a
// pointer-to-struct).
func (r *Reconciler[T]) Run(
	ctx context.Context,
	req ctrl.Request,
	blank T,
	reconcile ReconcileFunc[T],
	finalize FinalizeFunc[T],
) (Result, error) {
	logger := r.logger().With("name", req.Name, "namespace", req.Namespace)
	start := time.Now()

	// 1. Fetch.
	if err := r.Client.Get(ctx, req.NamespacedName, blank); err != nil {
		if errors.IsNotFound(err) {
			return Done(), nil
		}
		return Done(), fmt.Errorf("fetch object: %w", err)
	}

	// 2. Deletion path.
	if !blank.GetDeletionTimestamp().IsZero() {
		if r.Finalizer != "" && controllerutil.ContainsFinalizer(blank, r.Finalizer) {
			if finalize != nil {
				if err := finalize(ctx, blank); err != nil {
					logger.Error("finalize failed", "error", err)
					return Done(), err
				}
			}
			controllerutil.RemoveFinalizer(blank, r.Finalizer)
			if err := r.Client.Update(ctx, blank); err != nil {
				return Done(), fmt.Errorf("removing finalizer: %w", err)
			}
			r.recordEvent(blank, "Finalized", "object cleaned up")
		}
		return Done(), nil
	}

	// 3. Finalizer add (first reconcile).
	if r.Finalizer != "" && !controllerutil.ContainsFinalizer(blank, r.Finalizer) {
		controllerutil.AddFinalizer(blank, r.Finalizer)
		if err := r.Client.Update(ctx, blank); err != nil {
			return Done(), fmt.Errorf("adding finalizer: %w", err)
		}
		// Re-fetch after Update to avoid stale resourceVersion.
		if err := r.Client.Get(ctx, req.NamespacedName, blank); err != nil {
			if errors.IsNotFound(err) {
				return Done(), nil
			}
			return Done(), fmt.Errorf("re-fetch after finalizer: %w", err)
		}
	}

	// 4. Dispatch to user logic.
	r.recordEvent(blank, "Reconciling", "starting reconcile")
	result, err := reconcile(ctx, blank)
	dur := time.Since(start)
	if err != nil {
		logger.Error("reconcile failed", "duration", dur, "error", err)
		r.recordEvent(blank, "ReconcileFailed", err.Error())
		return result, err
	}
	logger.Info("reconciled", "duration", dur)
	r.recordEvent(blank, "Reconciled", fmt.Sprintf("reconciled in %s", dur))
	return result, nil
}

// SetupOptions configures how Reconciler[T] is wired into a manager.
type SetupOptions struct {
	// SkipDeletion, when true, filters Delete events out of the
	// watch. Use this when Finalizer is set and you want the
	// reconcile loop to handle cleanup via the deletion-timestamp
	// path rather than via Delete events.
	SkipDeletion bool

	// ExtraPredicates are AND-composed with any default predicate
	// the library applies. Empty means no extra filtering.
	ExtraPredicates []predicate.Predicate

	// Owns lists secondary resource types whose changes should
	// trigger a reconcile of the primary T. This is the standard
	// controller-runtime "Owns(&corev1.Pod{})" pattern.
	Owns []client.Object

	// Watches lets the operator declare cross-namespace or label-mapped
	// watches that don't fit the parent-owns-child controller-runtime
	// model (where owner references work). Each WatchSpec adds a
	// Watches(...) call to the controller builder with the supplied
	// EventHandler — typically handler.EnqueueRequestsFromMapFunc(...).
	//
	// Use this when secondary resources live in a different namespace
	// than the primary CR (owner references can't cross namespaces) or
	// when a label/annotation is the only link back to the parent.
	Watches []WatchSpec
}

// WatchSpec describes a secondary-resource watch to register on the
// controller builder. The Object identifies the GVK to watch and the
// Handler determines how each event maps back to one or more
// reconcile.Requests on the primary type.
type WatchSpec struct {
	// Object is a typed empty value (e.g. &corev1.Pod{}) used for
	// scheme registration of the watched GVK.
	Object client.Object

	// Handler converts secondary-resource events into reconcile
	// requests for the primary type. Typically constructed via
	// handler.EnqueueRequestsFromMapFunc.
	Handler handler.EventHandler
}

// SetupWithManager wires a per-CRD reconciler shim into the manager.
// The shim must implement reconcile.Reconciler — typically by exposing
// a Reconcile method that calls Reconciler[T].Run with its own
// ReconcileSpec / FinalizeSpec callbacks.
//
// Concrete is a freshly-allocated zero value of T (e.g.
// &v1alpha1.Workspace{}) — see Run's documentation.
func (r *Reconciler[T]) SetupWithManager(
	mgr ctrl.Manager,
	concrete T,
	rec reconcile.Reconciler,
	opts SetupOptions,
) error {
	if r.Client == nil {
		r.Client = mgr.GetClient()
	}
	if r.Scheme == nil {
		r.Scheme = mgr.GetScheme()
	}

	preds := opts.ExtraPredicates
	if opts.SkipDeletion {
		preds = append(preds, SkipDeletion())
	}

	b := ctrl.NewControllerManagedBy(mgr).
		For(concrete, builder.WithPredicates(preds...))
	for _, owned := range opts.Owns {
		b = b.Owns(owned)
	}
	for _, w := range opts.Watches {
		b = b.Watches(w.Object, w.Handler)
	}
	return b.Complete(rec)
}

func (r *Reconciler[T]) logger() *slog.Logger {
	if r.Log != nil {
		return r.Log
	}
	return slog.Default()
}

func (r *Reconciler[T]) recordEvent(obj client.Object, reason, msg string) {
	if r.Recorder == nil {
		return
	}
	// Defensive: ensure obj is non-nil and addressable. Using the
	// reflect.ValueOf().IsNil() check avoids panics if a typed-nil
	// gets through.
	if obj == nil || (reflect.ValueOf(obj).Kind() == reflect.Ptr && reflect.ValueOf(obj).IsNil()) {
		return
	}
	r.Recorder.Event(obj, "Normal", reason, msg)
}
