package templates

import (
	"strings"
	"testing"
)

func TestDeployTemplate_AllEnvironments(t *testing.T) {
	data := DeployWorkflowData{
		ProjectName: "myapp",
		Environments: []DeployEnv{
			{Name: "staging", Auto: true, Protection: false},
			{Name: "preprod", Auto: false, Protection: true, URL: "https://preprod.example.com"},
			{Name: "prod", Auto: false, Protection: true, URL: "https://example.com"},
		},
		Registry:         "ghcr",
		HasFrontends:     true,
		FrontendDeploy:   "none",
		MigrationTest:    true,
		Concurrency:      true,
		CancelInProgress: false,
	}

	out, err := CITemplates("github").Render("deploy.yml.tmpl", data)
	if err != nil {
		t.Fatalf("render error: %v", err)
	}

	s := string(out)

	// Must have all three deploy jobs
	for _, env := range []string{"deploy-staging", "deploy-preprod", "deploy-prod"} {
		if !strings.Contains(s, env+":") {
			t.Errorf("missing job %q", env)
		}
	}

	// Must have retag-release and deploy-release
	if !strings.Contains(s, "retag-release:") {
		t.Error("missing retag-release job")
	}
	if !strings.Contains(s, "deploy-release:") {
		t.Error("missing deploy-release job")
	}

	// Must have migration test for preprod and prod
	if strings.Count(s, "Test migrations") < 2 {
		t.Error("expected migration test steps for preprod and prod")
	}

	// Must have concurrency groups
	if !strings.Contains(s, "group: deploy-staging") {
		t.Error("missing concurrency group for staging")
	}

	// Must have environment protection
	if !strings.Contains(s, "name: prod") {
		t.Error("missing environment protection for prod")
	}

	// Sequential promotion: preprod needs staging
	if !strings.Contains(s, "needs: [deploy-staging]") {
		t.Error("missing sequential dependency: preprod -> staging")
	}

	// Frontend retagging
	if !strings.Contains(s, "frontends/*/") {
		t.Error("missing frontend retagging in retag-release")
	}

	// Header
	if !strings.HasPrefix(s, "# Code generated by forge. DO NOT EDIT.") {
		t.Error("missing generated header")
	}
}

func TestDeployTemplate_EmptyEnvironments(t *testing.T) {
	data := DeployWorkflowData{
		ProjectName:  "myapp",
		Environments: nil,
		Registry:     "ghcr",
	}

	out, err := CITemplates("github").Render("deploy.yml.tmpl", data)
	if err != nil {
		t.Fatalf("render error: %v", err)
	}

	s := string(out)
	// With no environments, should just have the header and name
	if !strings.Contains(s, "# Code generated by forge. DO NOT EDIT.") {
		t.Error("missing header for empty envs")
	}
	// Should NOT have deploy jobs
	if strings.Contains(s, "deploy-staging") {
		t.Error("should not have deploy jobs with empty environments")
	}
}

func TestDeployTemplate_GARRegistry(t *testing.T) {
	data := DeployWorkflowData{
		ProjectName: "myapp",
		Environments: []DeployEnv{
			{Name: "staging", Auto: true},
		},
		Registry: "gar",
	}

	out, err := CITemplates("github").Render("deploy.yml.tmpl", data)
	if err != nil {
		t.Fatalf("render error: %v", err)
	}

	s := string(out)
	if !strings.Contains(s, "vars.GAR_REGISTRY") {
		t.Error("should use GAR_REGISTRY variable for gar registry")
	}
}

func TestBuildImagesTemplate_Full(t *testing.T) {
	data := BuildImagesWorkflowData{
		ProjectName:  "myapp",
		Registry:     "ghcr",
		HasFrontends: true,
		VulnDocker:   true,
	}

	out, err := CITemplates("github").Render("build-images.yml.tmpl", data)
	if err != nil {
		t.Fatalf("render error: %v", err)
	}

	s := string(out)

	// Header
	if !strings.HasPrefix(s, "# Code generated by forge. DO NOT EDIT.") {
		t.Error("missing generated header")
	}

	// Concurrency group
	if !strings.Contains(s, "group: build-images-") {
		t.Error("missing concurrency group")
	}

	// Trivy scan
	if !strings.Contains(s, "trivy-scan:") {
		t.Error("missing trivy-scan job")
	}
	if !strings.Contains(s, "exit-code: \"1\"") {
		t.Error("trivy should fail on vulnerabilities")
	}

	// Frontend builds
	if !strings.Contains(s, "build-push-frontends:") {
		t.Error("missing build-push-frontends job")
	}

	// workflow_dispatch
	if !strings.Contains(s, "workflow_dispatch:") {
		t.Error("missing workflow_dispatch trigger")
	}

	// Proper tagging
	if !strings.Contains(s, "type=sha,prefix=sha-") {
		t.Error("missing sha tag")
	}
	if !strings.Contains(s, "type=semver") {
		t.Error("missing semver tag")
	}

	// Summary includes all jobs
	if !strings.Contains(s, "trivy scan") {
		t.Error("summary should include trivy scan")
	}
}

func TestBuildImagesTemplate_Minimal(t *testing.T) {
	data := BuildImagesWorkflowData{
		ProjectName:  "myapp",
		Registry:     "gar",
		HasFrontends: false,
		VulnDocker:   false,
	}

	out, err := CITemplates("github").Render("build-images.yml.tmpl", data)
	if err != nil {
		t.Fatalf("render error: %v", err)
	}

	s := string(out)

	// Should NOT have trivy or frontends
	if strings.Contains(s, "trivy-scan:") {
		t.Error("should not have trivy-scan when VulnDocker=false")
	}
	if strings.Contains(s, "build-push-frontends:") {
		t.Error("should not have build-push-frontends when HasFrontends=false")
	}

	// Should use GAR registry
	if !strings.Contains(s, "vars.GAR_REGISTRY") {
		t.Error("should use GAR_REGISTRY for gar registry")
	}
}
