package templates

import (
	"strings"
	"testing"
)

// TenantTemplateData mirrors codegen.TenantTemplateData for template rendering tests.
type TenantTemplateData struct {
	ClaimField string
	ColumnName string
}

func TestRenderTenantGenTemplate_DefaultOrgID(t *testing.T) {
	data := TenantTemplateData{
		ClaimField: "org_id",
		ColumnName: "org_id",
	}

	content, err := RenderMiddlewareTemplate("middleware/tenant_gen.go.tmpl", data)
	if err != nil {
		t.Fatalf("RenderMiddlewareTemplate() error = %v", err)
	}

	s := string(content)

	checks := []struct {
		name     string
		contains string
		want     bool
	}{
		{"DO NOT EDIT header", "Code generated by forge generate. DO NOT EDIT.", true},
		{"package middleware", "package middleware", true},
		{"context import", "\"context\"", true},
		{"connect import", "connectrpc.com/connect", true},
		{"TenantInterceptor function", "func TenantInterceptor()", true},
		{"ContextWithTenantID function", "func ContextWithTenantID(", true},
		{"TenantIDFromContext function", "func TenantIDFromContext(", true},
		{"RequireTenantID function", "func RequireTenantID(", true},
		{"extractTenantClaim function", "func extractTenantClaim(", true},
		{"claim field in interceptor", `"org_id"`, true},
		{"setup instructions", "Add TenantInterceptor()", true},
		{"claims dependency", "ClaimsFromContext", true},
		{"tenantIDKey type", "tenantIDKey struct{}", true},
	}

	for _, tc := range checks {
		found := strings.Contains(s, tc.contains)
		if found != tc.want {
			if tc.want {
				t.Errorf("%s: expected %q to be present in output", tc.name, tc.contains)
			} else {
				t.Errorf("%s: expected %q to NOT be present in output", tc.name, tc.contains)
			}
		}
	}
}

func TestRenderTenantGenTemplate_CustomClaimField(t *testing.T) {
	data := TenantTemplateData{
		ClaimField: "tenant_id",
		ColumnName: "tenant_id",
	}

	content, err := RenderMiddlewareTemplate("middleware/tenant_gen.go.tmpl", data)
	if err != nil {
		t.Fatalf("RenderMiddlewareTemplate() error = %v", err)
	}

	s := string(content)

	checks := []struct {
		name     string
		contains string
		want     bool
	}{
		{"custom claim field in interceptor", `"tenant_id"`, true},
		{"custom column in comment", `DB column: "tenant_id"`, true},
		{"TenantInterceptor present", "func TenantInterceptor()", true},
	}

	for _, tc := range checks {
		found := strings.Contains(s, tc.contains)
		if found != tc.want {
			if tc.want {
				t.Errorf("%s: expected %q to be present in output", tc.name, tc.contains)
			} else {
				t.Errorf("%s: expected %q to NOT be present in output", tc.name, tc.contains)
			}
		}
	}
}
