package forgeconv

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/reliant-labs/forge/internal/linter/finding"
)

// writeFE is a small helper: writes body to <feDir>/<rel>, creating
// parents. Paths are slash-separated regardless of platform.
func writeFE(t *testing.T, feDir, rel, body string) {
	t.Helper()
	full := filepath.Join(feDir, filepath.FromSlash(rel))
	if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(full, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
}

// configGenFixture is a trimmed copy of the real generated module's
// shape — the banner, the zod schema whose keys are the DECLARED fields,
// and the SSR branch that reads process.env by design.
const configGenFixture = `// Code generated by forge. DO NOT EDIT.
// forge-owned: regenerated every run — do not edit (forge project disown to take ownership)

import { z } from "zod";

export const configSchema = z.object({
  NEXT_PUBLIC_API_URL: z.string().default("http://localhost:8090"),
  NEXT_PUBLIC_MOCK_API: z.string().default(""),
});

function rawConfig(): Record<string, unknown> {
  if (typeof window !== "undefined" && window.__FORGE_CONFIG__) {
    return window.__FORGE_CONFIG__;
  }
  if (typeof process !== "undefined" && process.env) {
    const fromEnv: Record<string, unknown> = {};
    if (process.env["NEXT_PUBLIC_API_URL"] !== undefined) fromEnv["NEXT_PUBLIC_API_URL"] = process.env["NEXT_PUBLIC_API_URL"];
    return fromEnv;
  }
  return {};
}
`

// newFrontendWithConfig lays out a frontend that HAS the generated typed
// config module — the precondition for the rule to run at all.
func newFrontendWithConfig(t *testing.T) (root, feDir string) {
	t.Helper()
	root = t.TempDir()
	feDir = filepath.Join(root, "frontends", "web")
	writeFE(t, feDir, "src/lib/config_gen.ts", configGenFixture)
	return root, feDir
}

// TestLintFrontendProcessEnv_FlagsRawRead is the core case: a
// hand-written source file that reads process.env is reported, and the
// finding names the file, the variable, and the typed replacement.
func TestLintFrontendProcessEnv_FlagsRawRead(t *testing.T) {
	t.Parallel()
	root, feDir := newFrontendWithConfig(t)
	writeFE(t, feDir, "src/lib/basepath.ts", `
function readBasePath(): string {
  const raw = process.env.NEXT_PUBLIC_BASE_PATH || "";
  return raw;
}
`)

	res := LintFrontendProcessEnv(root, []string{feDir}, finding.SeverityWarning)
	if len(res.Findings) != 1 {
		t.Fatalf("expected 1 finding, got %d: %+v", len(res.Findings), res.Findings)
	}
	f := res.Findings[0]
	if f.Rule != RuleFrontendProcessEnv {
		t.Errorf("rule = %q, want %q", f.Rule, RuleFrontendProcessEnv)
	}
	if f.Severity != finding.SeverityWarning {
		t.Errorf("severity = %v, want warning", f.Severity)
	}
	if f.Line != 3 {
		t.Errorf("line = %d, want 3", f.Line)
	}
	if filepath.IsAbs(f.File) {
		t.Errorf("File should be root-relative, got %q", f.File)
	}
	// The finding must be a runbook: it names the variable and the
	// literal fix.
	if !strings.Contains(f.Message, "NEXT_PUBLIC_BASE_PATH") {
		t.Errorf("message must name the env var; got %q", f.Message)
	}
	if !strings.Contains(f.Remediation, "config_gen") {
		t.Errorf("remediation must point at the generated module; got %q", f.Remediation)
	}
	// NEXT_PUBLIC_BASE_PATH is NOT in the fixture's schema, so the
	// remediation must include the "declare it in the config proto" arm.
	if !strings.Contains(f.Remediation, "config.proto") {
		t.Errorf("undeclared var must be told to declare it in the proto; got %q", f.Remediation)
	}
}

// TestLintFrontendProcessEnv_DeclaredVarGetsDirectFix — when the variable
// IS already declared in the generated schema, the fix is a one-liner
// (read it from the module) with no proto edit required, and the message
// must say so rather than sending the author to the proto for a field
// that already exists.
func TestLintFrontendProcessEnv_DeclaredVarGetsDirectFix(t *testing.T) {
	t.Parallel()
	root, feDir := newFrontendWithConfig(t)
	writeFE(t, feDir, "src/lib/api.ts", `const u = process.env.NEXT_PUBLIC_API_URL;`)

	res := LintFrontendProcessEnv(root, []string{feDir}, finding.SeverityWarning)
	if len(res.Findings) != 1 {
		t.Fatalf("expected 1 finding, got %d: %+v", len(res.Findings), res.Findings)
	}
	rem := res.Findings[0].Remediation
	if !strings.Contains(rem, "loadConfig()") {
		t.Errorf("remediation must show the literal typed read; got %q", rem)
	}
	if strings.Contains(rem, "config.proto") {
		t.Errorf("an ALREADY-DECLARED var must not be sent to the proto; got %q", rem)
	}
}

// TestLintFrontendProcessEnv_NoConfigModuleIsSilent is the false-positive
// guard that matters most. A frontend that has not adopted proto-declared
// config has NO typed door to point at, so the rule must say nothing —
// otherwise every project scaffolded before the config system starts red
// with advice it cannot follow.
func TestLintFrontendProcessEnv_NoConfigModuleIsSilent(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	feDir := filepath.Join(root, "frontends", "web")
	writeFE(t, feDir, "src/lib/connect.ts", `const b = process.env.NEXT_PUBLIC_API_URL;`)
	writeFE(t, feDir, "src/lib/auth.ts", `const i = process.env.NEXT_PUBLIC_OIDC_ISSUER;`)

	res := LintFrontendProcessEnv(root, []string{feDir}, finding.SeverityWarning)
	if len(res.Findings) != 0 {
		t.Fatalf("a frontend with no config_gen.ts must produce NO findings, got %d: %+v",
			len(res.Findings), res.Findings)
	}
}

// TestLintFrontendProcessEnv_Allowlist pins every exemption, each of which
// was derived from a real file in a forge scaffold or in the control-plane
// corpus. A regression here is the check becoming noise.
func TestLintFrontendProcessEnv_Allowlist(t *testing.T) {
	t.Parallel()
	root, feDir := newFrontendWithConfig(t)

	// 1. Build-time config scripts genuinely run in Node.
	writeFE(t, feDir, "next.config.ts", `const bp = process.env.NEXT_PUBLIC_BASE_PATH ?? "";`)
	writeFE(t, feDir, "vite.config.ts", `const o = process.env.IDP_UPSTREAM_ORIGIN;`)
	writeFE(t, feDir, "vitest.config.ts", `const x = process.env.CI;`)
	// 2. Forge-generated files — flagging them tells the author to edit a
	//    file that is overwritten on the next generate.
	writeFE(t, feDir, "src/lib/basepath_gen.ts",
		"// Code generated by forge. DO NOT EDIT.\n"+
			`export const B = process.env.NEXT_PUBLIC_BASE_PATH ?? "";`)
	writeFE(t, feDir, "src/lib/otel_gen.ts",
		"// Code generated by forge. DO NOT EDIT.\n"+
			`const e = process.env.NEXT_PUBLIC_OTEL_ENDPOINT || '';`)
	// 3. Tests and mock/dev harnesses.
	writeFE(t, feDir, "src/lib/thing.test.ts", `process.env.NEXT_PUBLIC_API_URL = "x";`)
	writeFE(t, feDir, "src/lib/thing.spec.tsx", `process.env.NEXT_PUBLIC_API_URL = "x";`)
	writeFE(t, feDir, "src/__tests__/helper.ts", `process.env.NEXT_PUBLIC_API_URL = "x";`)
	writeFE(t, feDir, "src/mocks/handlers.ts", `const m = process.env.NEXT_PUBLIC_MOCK_API;`)
	// 4. Bundler build-mode discriminators. NODE_ENV can never come from
	//    KCL — both bundlers define it statically — so it is not a config
	//    value and there is nowhere else to read it from.
	writeFE(t, feDir, "src/app/providers.tsx", `const isDev = process.env.NODE_ENV === "development";`)
	writeFE(t, feDir, "src/lib/telemetry.ts", `const d = process.env?.NODE_ENV === "development";`)
	writeFE(t, feDir, "src/main.tsx", `const dev = import.meta.env.DEV;`)
	// 5. Vendored / generated protobuf output and build artefacts.
	writeFE(t, feDir, "src/gen/thing_pb.ts", `const z = process.env.NEXT_PUBLIC_API_URL;`)
	writeFE(t, feDir, "node_modules/pkg/index.js", `const z = process.env.NEXT_PUBLIC_API_URL;`)
	writeFE(t, feDir, ".next/static/chunk.js", `const z = process.env.NEXT_PUBLIC_API_URL;`)
	writeFE(t, feDir, "dist/bundle.js", `const z = process.env.NEXT_PUBLIC_API_URL;`)
	// 6. Type declarations, and prose that merely MENTIONS the door.
	writeFE(t, feDir, "src/env.d.ts", `declare const x: typeof process.env.NEXT_PUBLIC_API_URL;`)
	writeFE(t, feDir, "src/lib/notes.ts",
		"// These no longer read `process.env`. Values arrive from config.js.\n"+
			"/* a library reading process.env at runtime finds nothing */\n"+
			"export const ok = 1;\n")

	res := LintFrontendProcessEnv(root, []string{feDir}, finding.SeverityWarning)
	if len(res.Findings) != 0 {
		t.Fatalf("allowlisted files must produce NO findings, got %d:\n%s",
			len(res.Findings), res.FormatText())
	}
}

// TestLintFrontendProcessEnv_ViteSpelling — import.meta.env is the Vite
// spelling of the same wrong door and must be caught by the same rule.
func TestLintFrontendProcessEnv_ViteSpelling(t *testing.T) {
	t.Parallel()
	root, feDir := newFrontendWithConfig(t)
	writeFE(t, feDir, "src/lib/connect.ts", `const u = import.meta.env.VITE_API_URL;`)

	res := LintFrontendProcessEnv(root, []string{feDir}, finding.SeverityWarning)
	if len(res.Findings) != 1 {
		t.Fatalf("expected 1 finding, got %d: %+v", len(res.Findings), res.Findings)
	}
	if !strings.Contains(res.Findings[0].Message, "VITE_API_URL") {
		t.Errorf("message must name the var; got %q", res.Findings[0].Message)
	}
}

// TestLintFrontendProcessEnv_PerLineOptOut — the escape hatch. Both the
// forge-native spelling and the borrowed //nolint one must silence the
// rule on the line they annotate, and only that line.
func TestLintFrontendProcessEnv_PerLineOptOut(t *testing.T) {
	t.Parallel()
	root, feDir := newFrontendWithConfig(t)
	writeFE(t, feDir, "src/lib/a.ts",
		"// forge:lint-disable-next-line "+RuleFrontendProcessEnv+": SSR-only bootstrap\n"+
			"const a = process.env.NEXT_PUBLIC_ONE;\n")
	writeFE(t, feDir, "src/lib/b.ts",
		"const b = process.env.NEXT_PUBLIC_TWO; //nolint:"+RuleFrontendProcessEnv+"\n")
	writeFE(t, feDir, "src/lib/c.ts",
		"const c = process.env.NEXT_PUBLIC_THREE;\n")

	res := LintFrontendProcessEnv(root, []string{feDir}, finding.SeverityWarning)
	if len(res.Findings) != 1 {
		t.Fatalf("expected only the un-annotated read to survive, got %d: %+v",
			len(res.Findings), res.Findings)
	}
	if !strings.Contains(res.Findings[0].Message, "NEXT_PUBLIC_THREE") {
		t.Errorf("wrong finding survived: %q", res.Findings[0].Message)
	}
}

// TestLintFrontendProcessEnv_SeverityIsCallerControlled mirrors the
// forge-owned-dotenv rule: ONE analyzer, caller-chosen severity, so the
// advisory and gating verdicts can never diverge.
func TestLintFrontendProcessEnv_SeverityIsCallerControlled(t *testing.T) {
	t.Parallel()
	root, feDir := newFrontendWithConfig(t)
	writeFE(t, feDir, "src/lib/a.ts", `const a = process.env.NEXT_PUBLIC_ONE;`)

	for _, sev := range []finding.Severity{finding.SeverityWarning, finding.SeverityError} {
		res := LintFrontendProcessEnv(root, []string{feDir}, sev)
		if len(res.Findings) != 1 {
			t.Fatalf("expected 1 finding at %v, got %d", sev, len(res.Findings))
		}
		if res.Findings[0].Severity != sev {
			t.Errorf("severity = %v, want %v", res.Findings[0].Severity, sev)
		}
	}
}

// TestStripComments pins the comment/string scanner directly. It is the
// piece standing between this rule and its most embarrassing possible
// false positive — flagging the scaffold's own prose, several files of
// which explain in comments why their process.env reads cannot move.
func TestStripComments(t *testing.T) {
	t.Parallel()
	cases := []struct {
		name           string
		in             string
		inBlock        bool
		want           string
		wantStillBlock bool
	}{
		{"plain code", `const a = process.env.X;`, false, `const a = process.env.X;`, false},
		{"line comment", `// process.env.X in prose`, false, ``, false},
		{"trailing line comment", `const a = 1; // process.env.X`, false, `const a = 1; `, false},
		{"inline block", `/* process.env.X */ const b = 1;`, false, ` const b = 1;`, false},
		{"double-quoted string", `const s = "process.env.X";`, false, `const s = ;`, false},
		{"escaped quote", `const s = 'a\'b'; const c = process.env.Y;`, false, `const s = ; const c = process.env.Y;`, false},
		{"continuing block", `still inside process.env.X`, true, ``, true},
		{"block ends mid-line", `end */ const d = process.env.Z;`, true, ` const d = process.env.Z;`, false},
		{"template literal", "const t = `tpl ${process.env.Q}`;", false, `const t = ;`, false},
		{"block opens mid-line", `const a = 1; /* trailing`, false, `const a = 1; `, true},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			got, stillBlock := stripComments(c.in, c.inBlock)
			if got != c.want || stillBlock != c.wantStillBlock {
				t.Errorf("stripComments(%q, %v) = (%q, %v), want (%q, %v)",
					c.in, c.inBlock, got, stillBlock, c.want, c.wantStillBlock)
			}
		})
	}
}

// TestLintFrontendProcessEnv_MissingDirIsSilent — the rule flags files
// that exist; an absent or unreadable frontend dir is not a finding.
func TestLintFrontendProcessEnv_MissingDirIsSilent(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	res := LintFrontendProcessEnv(root, []string{filepath.Join(root, "nope")}, finding.SeverityWarning)
	if len(res.Findings) != 0 {
		t.Fatalf("missing dir must be silent, got %+v", res.Findings)
	}
}
