#!/usr/bin/env bash
# Regenerate internal/cli/testdata/ui_rpc_surface.txt: the DeployService and
# DomainService RPCs the Reliant web UI calls.
#
#   scripts/sync-ui-rpc-surface.sh <reliant-checkout>
#
# Scans the UI's data layer (web/src/services/forge, web/src/hooks/forge-*,
# the Settings/cloud usage hooks) for generated-client method calls and keeps
# those that name a real RPC of the two services. Real RPC names are read from
# the control-plane protos at origin/main of CONTROL_PLANE_DIR (required):
# a bare method name is only evidence of an RPC call once it matches one.
set -euo pipefail

reliant="${1:?usage: CONTROL_PLANE_DIR=<control-plane-checkout> $0 <reliant-checkout>}"
cp="${CONTROL_PLANE_DIR:?set CONTROL_PLANE_DIR to a control-plane checkout}"
git -C "$cp" fetch -q origin 2>/dev/null || true
out="$(cd "$(dirname "$0")/.." && pwd)/internal/cli/testdata/ui_rpc_surface.txt"
ui_files=$(cd "$reliant" && ls web/src/services/forge/*.ts web/src/hooks/forge-*.ts web/src/components/Settings/cloud/usage/*.ts 2>/dev/null | grep -v __tests__)
[ -n "$ui_files" ] || { echo "no UI files found under $reliant/web/src" >&2; exit 1; }

calls() { # <service> <proto-file-in-control-plane>
  local svc="$1" proto="$2" names
  names=$(git -C "$cp" show "origin/main:$proto" | grep -oE '^[[:space:]]*rpc \w+' | awk '{print $2}')
  (cd "$reliant" && cat $ui_files) | grep -oE '\bclient(\(\))?[[:space:]]*\.[[:space:]]*\w+\(|getControlPlaneClient\(\w+\)[[:space:]]*\.[[:space:]]*\w+\(' |
    sed -E 's/.*\.[[:space:]]*//; s/\($//' | sort -u | while read -r m; do
      rpc="$(tr '[:lower:]' '[:upper:]' <<<"${m:0:1}")${m:1}"
      if grep -qx "$rpc" <<<"$names"; then echo "$svc/$rpc"; fi
    done
}

{
  echo "# DeployService / DomainService RPCs the Reliant web UI calls."
  echo "# GENERATED by scripts/sync-ui-rpc-surface.sh from a reliant checkout; do not"
  echo "# hand-edit. One <Service>/<Rpc> per line. Pinned by TestUIRPCSurfaceHasCLIParity."
  {
    calls DeployService proto/services/deploy/v1/deploy.proto
    calls DomainService proto/services/domain/v1/domain.proto
  } | sort -u
} >"$out.tmp"
mv "$out.tmp" "$out"
echo "wrote $out"
