// Code generated by forge. DO NOT EDIT.
// Source: contract.go in this package.
//
// To customize: edit contract.go (the interface IS the public surface) and
// re-run "forge generate". This file is regenerated unconditionally.
package config

import (
	"github.com/reliant-labs/forge/pkg/contractkit"
)

// MockService is a test mock for the Service interface.
//
// The embedded contractkit.Recorder records every call so tests can
// assert call counts and captured arguments. Set XxxFunc fields to
// override per-method behaviour; unset methods return the canonical
// "MockService.<Method>Func not set" error.
type MockService struct {
	contractkit.Recorder
	EffectiveKindFunc func(string) string
}

func (m *MockService) EffectiveKind(kind string) string {
	m.Record("EffectiveKind", kind)
	if m.EffectiveKindFunc != nil {
		return m.EffectiveKindFunc(kind)
	}
	return ""
}

// Compile-time check.
var _ Service = (*MockService)(nil)
