// File: internal/generator/frontend_webruntime_floor_test.go
//
// webRuntimePublishedRange is a FLOOR, not an exact pin.
//
// THE DEFECT. Every `forge generate` rewrote the @reliantlabs/forge-web-runtime
// specifier to forge's own constant, unconditionally. A project that had
// deliberately moved AHEAD of forge — the motivating case being a security bump
// published between two forge releases — was silently DOWNGRADED back to a
// range that resolves the vulnerable version. Nothing reported it: the rewrite
// is intentionally silent idempotent bookkeeping, so the only evidence was a
// package.json diff nobody was watching and a lockfile that quietly moved back.
//
// That is forge overriding a decision that is not forge's to make. The constant
// states the OLDEST runtime this generator's output is known to work against;
// it says nothing about newer ones. A project pinning higher knows about a
// release forge predates.
//
// TestEnsureWebRuntimeDependency_KeepsAHigherProjectFloor is the regression:
// it fails against the old unconditional rewrite and passes after.
//
// The rule is one-directional, and both directions are pinned here:
//   - at or above the floor  → the project's specifier survives untouched
//   - below the floor        → forge raises it (the reason this code exists)
//   - not comparable         → forge's answer wins (keeps stale-bridge repair)
package generator

import (
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
)

// higherThanFloor returns a specifier one patch above forge's constant, so the
// tests track the constant instead of hardcoding a version that rots when
// web-runtime is released. "^0.3.2" -> "^0.3.3".
func higherThanFloor(t *testing.T) string {
	t.Helper()
	min, ok := minimumVersion(webRuntimePublishedRange)
	if !ok {
		t.Fatalf("webRuntimePublishedRange %q is not a comparable range", webRuntimePublishedRange)
	}
	parts := strings.Split(strings.TrimPrefix(min, "v"), ".")
	if len(parts) != 3 {
		t.Fatalf("unexpected version shape %q", min)
	}
	patch, err := strconv.Atoi(parts[2])
	if err != nil {
		t.Fatalf("parse patch of %q: %v", min, err)
	}
	return "^" + parts[0] + "." + parts[1] + "." + strconv.Itoa(patch+1)
}

// TestEnsureWebRuntimeDependency_KeepsAHigherProjectFloor REPRODUCES THE BUG.
//
// The project declares a specifier ABOVE forge's constant — what a team does
// after a security advisory lands in a web-runtime patch that forge has not
// released against yet. forge must leave it alone. Before the fix this
// assertion failed: the specifier came back as forge's own constant, silently
// undoing the bump.
func TestEnsureWebRuntimeDependency_KeepsAHigherProjectFloor(t *testing.T) {
	base := t.TempDir()
	forgeRoot := fakeForgeCheckout(t, filepath.Join(base, "forge"))
	pinDevBuild(t, false, forgeRoot)

	higher := higherThanFloor(t)
	projectDir := filepath.Join(base, "app")
	manifest := writeFrontendManifest(t, projectDir, "web",
		"\n    \""+WebRuntimePackage+"\": \""+higher+"\"")

	EnsureWebRuntimeDependency(projectDir, filepath.Join("frontends", "web"), "web")

	got := readDeps(t, manifest)[WebRuntimePackage]
	if got == webRuntimePublishedRange {
		t.Fatalf("forge DOWNGRADED the project from %q to its own constant %q — "+
			"a project that has moved ahead of forge (e.g. a security bump published "+
			"between forge releases) must keep its floor", higher, webRuntimePublishedRange)
	}
	if got != higher {
		t.Errorf("specifier = %q, want the project's own %q", got, higher)
	}
}

// TestEnsureWebRuntimeDependency_HigherFloorSurvivesRepeatedGenerates is the
// same property under the real usage pattern. A downgrade that only appears on
// the third generate is still a downgrade, and idempotence is what the
// reconcile path claims.
func TestEnsureWebRuntimeDependency_HigherFloorSurvivesRepeatedGenerates(t *testing.T) {
	base := t.TempDir()
	forgeRoot := fakeForgeCheckout(t, filepath.Join(base, "forge"))
	pinDevBuild(t, false, forgeRoot)

	higher := higherThanFloor(t)
	projectDir := filepath.Join(base, "app")
	feRel := filepath.Join("frontends", "web")
	manifest := writeFrontendManifest(t, projectDir, "web",
		"\n    \""+WebRuntimePackage+"\": \""+higher+"\"")

	before, err := os.ReadFile(manifest)
	if err != nil {
		t.Fatalf("read manifest: %v", err)
	}
	for i := 0; i < 5; i++ {
		EnsureWebRuntimeDependency(projectDir, feRel, "web")
	}
	after, err := os.ReadFile(manifest)
	if err != nil {
		t.Fatalf("read manifest: %v", err)
	}
	if string(after) != string(before) {
		t.Errorf("repeated generates rewrote a manifest already above the floor:\n--- before ---\n%s\n--- after ---\n%s",
			before, after)
	}
}

// TestEnsureWebRuntimeDependency_RaisesASpecifierBelowTheFloor is the other
// direction, and the reason this reconciliation exists at all: a project
// regenerated by a newer forge whose output needs a newer runtime must be
// brought UP. Keeping the floor must not turn into never touching anything.
func TestEnsureWebRuntimeDependency_RaisesASpecifierBelowTheFloor(t *testing.T) {
	base := t.TempDir()
	forgeRoot := fakeForgeCheckout(t, filepath.Join(base, "forge"))
	pinDevBuild(t, false, forgeRoot)

	projectDir := filepath.Join(base, "app")
	// A version from before the floor. 0.0.1 is unambiguously below any
	// floor this constant will ever hold.
	manifest := writeFrontendManifest(t, projectDir, "web",
		"\n    \""+WebRuntimePackage+"\": \"^0.0.1\"")

	EnsureWebRuntimeDependency(projectDir, filepath.Join("frontends", "web"), "web")

	if got := readDeps(t, manifest)[WebRuntimePackage]; got != webRuntimePublishedRange {
		t.Errorf("specifier = %q, want %q — a specifier below the floor must be raised",
			got, webRuntimePublishedRange)
	}
}

// TestEnsureWebRuntimeDependency_ExactFloorIsLeftAlone pins the boundary: equal
// satisfies the floor. (It already short-circuits on string equality, but the
// comparison must agree, so a future refactor cannot make "equal" mean "below".)
func TestEnsureWebRuntimeDependency_ExactFloorIsLeftAlone(t *testing.T) {
	base := t.TempDir()
	forgeRoot := fakeForgeCheckout(t, filepath.Join(base, "forge"))
	pinDevBuild(t, false, forgeRoot)

	projectDir := filepath.Join(base, "app")
	manifest := writeFrontendManifest(t, projectDir, "web",
		"\n    \""+WebRuntimePackage+"\": \""+webRuntimePublishedRange+"\"")

	EnsureWebRuntimeDependency(projectDir, filepath.Join("frontends", "web"), "web")

	if got := readDeps(t, manifest)[WebRuntimePackage]; got != webRuntimePublishedRange {
		t.Errorf("specifier = %q, want %q", got, webRuntimePublishedRange)
	}
}

// TestSpecSatisfiesFloor is the unit table behind the behaviour above. It is
// where the range-operator and incompatible-major rules are pinned, because
// driving each of these through a manifest would be slower and no clearer.
func TestSpecSatisfiesFloor(t *testing.T) {
	const floor = "^0.3.2"
	cases := []struct {
		name    string
		current string
		want    bool
		why     string
	}{
		{"equal caret", "^0.3.2", true, "equal satisfies the floor"},
		{"higher patch", "^0.3.3", true, "a security bump ahead of forge"},
		{"much higher patch", "^0.3.19", true, "numeric compare, not lexical — 19 > 2"},
		{"lower patch", "^0.3.1", false, "below the floor, forge raises it"},
		{"lower minor", "^0.2.9", false, "below the floor"},

		// Operators that express a minimum are comparable.
		{"tilde at floor", "~0.3.2", true, "~ admits 0.3.2 as its lowest"},
		{"gte at floor", ">=0.3.2", true, ">= admits 0.3.2 as its lowest"},
		{"bare version at floor", "0.3.2", true, "an exact pin at the floor satisfies it"},
		{"bare version above", "0.3.5", true, "an exact pin above the floor satisfies it"},
		{"bare version below", "0.3.0", false, "an exact pin below the floor does not"},

		// A 0.x MINOR is the breaking axis under npm caret semantics, so a
		// different minor is a different incompatible line, not "higher".
		{"higher 0.x minor", "^0.4.0", false, "^0.4 is incompatible with ^0.3, not a superset"},
		{"different major", "^1.0.0", false, "npm majors are not compatible"},

		// Not comparable → forge decides. This is what preserves the
		// stale-bridge normalisation, and it must not be read as "higher".
		{"file bridge", "file:../../forge/web-runtime", false, "a local path makes no version claim"},
		{"git url", "git+https://github.com/x/y.git#abc", false, "no version claim"},
		{"npm alias", "npm:@scope/other@1.0.0", false, "no version claim"},
		{"star", "*", false, "admits anything, including below the floor"},
		{"latest", "latest", false, "a dist-tag is not a version"},
		{"compound range", ">=0.3.2 <0.4.0", false, "ambiguous to parse; forge decides"},
		{"empty", "", false, "no claim"},

		// A ceiling can never clear a floor.
		{"less than", "<0.9.0", false, "a ceiling admits versions below the floor"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := specSatisfiesFloor(tc.current, floor); got != tc.want {
				t.Errorf("specSatisfiesFloor(%q, %q) = %v, want %v — %s",
					tc.current, floor, got, tc.want, tc.why)
			}
		})
	}
}

// TestReconcileSpec_NonAuthoritativeNeverRewrites keeps the existing
// authoritative=false contract intact: a build with no better answer than
// what is already declared must not touch it, floor or no floor.
func TestReconcileSpec_NonAuthoritativeNeverRewrites(t *testing.T) {
	d := webRuntimeDecision{spec: webRuntimePublishedRange, authoritative: false}
	for _, current := range []string{"^0.0.1", "file:../x", "^9.9.9"} {
		if got := reconcileSpec(current, d); got != current {
			t.Errorf("reconcileSpec(%q, non-authoritative) = %q, want it untouched", current, got)
		}
	}
}

// TestReconcileSpec_StaleBridgeStillNormalised guards the behaviour the floor
// logic must not regress: a `file:` path an older forge wrote is not a version
// claim, so forge's answer wins and the machine-local path is removed.
func TestReconcileSpec_StaleBridgeStillNormalised(t *testing.T) {
	d := webRuntimeDecision{spec: webRuntimePublishedRange, authoritative: true}
	got := reconcileSpec("file:../../../../somewhere/else/web-runtime", d)
	if got != webRuntimePublishedRange {
		t.Errorf("reconcileSpec(file: bridge) = %q, want %q — a local path must still be normalised",
			got, webRuntimePublishedRange)
	}
}
