package generator

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Frontend-workspaces emitters.
//
// When `frontend.workspaces: true` in forge.yaml, forge reshapes the
// frontend layout into a pnpm-workspace:
//
//   <root>/
//     pnpm-workspace.yaml
//     packages/
//       api/        — buf-generated Connect TS clients + proto types
//       hooks/      — React Query wrappers + per-service generated hooks
//     frontends/
//       <name>/     — Next.js / Expo / Vite SPA app, imports @<scope>/api etc.
//
// This file owns the workspace-layout files that don't fit cleanly under
// frontend_gen.go (which emits one frontend's files) — pnpm-workspace.yaml
// at the project root, packages/api/, and packages/hooks/. The per-frontend
// emitters in frontend_gen.go consult the workspaces flag to know whether
// to skip emitting per-frontend gen/hooks files (the workspace versions
// supersede them).

// FrontendWorkspaceLayout describes the workspace package names + paths
// derived from a project. It is the single source of truth that hooks
// generation, buf TS generation, and frontend templates consult.
type FrontendWorkspaceLayout struct {
	// Scope is the npm scope without the leading `@`. Derived from
	// the project name; sanitized to a valid npm scope segment.
	Scope string
	// ApiPackage is the fully-qualified npm package name for the API
	// workspace (e.g. "@myapp/api").
	ApiPackage string
	// HooksPackage is the fully-qualified npm package name for the
	// hooks workspace (e.g. "@myapp/hooks").
	HooksPackage string
}

// NewFrontendWorkspaceLayout builds the canonical layout from a raw
// project name. Falls back to "@app/api" / "@app/hooks" when the
// project name doesn't produce a valid npm scope segment.
func NewFrontendWorkspaceLayout(projectName string) FrontendWorkspaceLayout {
	scope := sanitizeNpmScopeSegment(projectName)
	if scope == "" {
		scope = "app"
	}
	return FrontendWorkspaceLayout{
		Scope:        scope,
		ApiPackage:   "@" + scope + "/api",
		HooksPackage: "@" + scope + "/hooks",
	}
}

// sanitizeNpmScopeSegment produces a string valid as an npm scope
// component (no @, lowercase, hyphens/underscores allowed, no leading
// digit/dot). npm requires:
//   - all lowercase
//   - URL-safe (no spaces, no uppercase, no @)
//   - cannot start with . or _
// Returns "" when no valid characters remain.
func sanitizeNpmScopeSegment(name string) string {
	var b strings.Builder
	for _, r := range strings.ToLower(strings.TrimSpace(name)) {
		switch {
		case r >= 'a' && r <= 'z':
			b.WriteRune(r)
		case r >= '0' && r <= '9':
			b.WriteRune(r)
		case r == '-' || r == '_':
			b.WriteRune(r)
		default:
			// Drop other chars (spaces, dots, @, /).
		}
	}
	s := b.String()
	s = strings.TrimLeft(s, "._-0123456789")
	return s
}

// WriteFrontendWorkspaceFiles emits the workspace-layout scaffolding:
//
//   - pnpm-workspace.yaml at the project root
//   - packages/api/package.json + tsconfig.json + .gitignore
//   - packages/hooks/package.json + tsconfig.json + use-api-{query,mutation}.ts
//
// Idempotent: writes files only if they do not already exist, so re-
// running `forge generate` after the user customizes (e.g.) the
// packages/api/package.json does not clobber their edits.
//
// Returns nil immediately when workspaces is disabled — callers can
// invoke unconditionally and let this function decide whether work is
// needed.
func WriteFrontendWorkspaceFiles(projectDir, projectName string, workspaces bool) error {
	if !workspaces {
		return nil
	}
	layout := NewFrontendWorkspaceLayout(projectName)

	if err := writePnpmWorkspaceYaml(projectDir); err != nil {
		return err
	}
	if err := writeApiPackage(projectDir, layout); err != nil {
		return err
	}
	if err := writeHooksPackage(projectDir, layout); err != nil {
		return err
	}
	return nil
}

// writePnpmWorkspaceYaml writes the root pnpm-workspace.yaml so pnpm
// recognizes frontends/* and packages/* as workspace members.
//
// We write `packages/*` first so a future `pnpm add` resolves intra-
// workspace deps before reaching for the frontends/* members (pnpm
// honors order for ambiguous installs).
func writePnpmWorkspaceYaml(projectDir string) error {
	path := filepath.Join(projectDir, "pnpm-workspace.yaml")
	if _, err := os.Stat(path); err == nil {
		return nil
	}
	body := `# pnpm workspace manifest — generated by ` + "`forge generate`" + `.
#
# Forge emits two workspace tiers:
#   - packages/* — shared TypeScript packages (api, hooks).
#     Adding a new shared package: ` + "`mkdir packages/<name> && pnpm init`" + `.
#   - frontends/* — per-app workspaces (Next.js, Expo, Vite SPA).
#     Created by ` + "`forge add frontend <name>`" + `.
#
# Workspace members reference each other via "workspace:*" in their
# package.json, e.g. "@<scope>/api": "workspace:*".
packages:
  - "packages/*"
  - "frontends/*"
`
	return os.WriteFile(path, []byte(body), 0o644)
}

// writeApiPackage emits packages/api/{package.json, tsconfig.json,
// .gitignore, README.md}. The api package surfaces the buf-generated
// Connect TS clients to the rest of the workspace — its `main` and
// `types` point at src/gen/index.ts (re-export barrel) so consumers
// say `import { UserService } from "@<scope>/api"`.
func writeApiPackage(projectDir string, layout FrontendWorkspaceLayout) error {
	apiDir := filepath.Join(projectDir, "packages", "api")
	if err := os.MkdirAll(filepath.Join(apiDir, "src"), 0o755); err != nil {
		return fmt.Errorf("create packages/api: %w", err)
	}

	pkg := fmt.Sprintf(`{
  "name": "%s",
  "version": "0.0.0",
  "private": true,
  "main": "./src/index.ts",
  "types": "./src/index.ts",
  "exports": {
    ".": "./src/index.ts",
    "./*": "./src/gen/*.ts"
  },
  "scripts": {
    "typecheck": "tsc --noEmit"
  },
  "dependencies": {
    "@bufbuild/protobuf": "^2.5.0",
    "@connectrpc/connect": "^2.0.0"
  },
  "devDependencies": {
    "@bufbuild/protoc-gen-es": "^2.5.0",
    "typescript": "^5.8.0"
  }
}
`, layout.ApiPackage)
	if err := writeIfMissing(filepath.Join(apiDir, "package.json"), pkg); err != nil {
		return err
	}

	tsconfig := `{
  "compilerOptions": {
    "target": "ES2022",
    "module": "ESNext",
    "moduleResolution": "bundler",
    "lib": ["ES2022", "DOM"],
    "declaration": true,
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "isolatedModules": true,
    "verbatimModuleSyntax": false,
    "allowSyntheticDefaultImports": true
  },
  "include": ["src/**/*.ts"]
}
`
	if err := writeIfMissing(filepath.Join(apiDir, "tsconfig.json"), tsconfig); err != nil {
		return err
	}

	// src/index.ts is a stub barrel that gets supplemented as buf
	// generates _pb files into src/gen/. We seed it so the package
	// compiles on a fresh scaffold (before any proto exists).
	indexTS := `// Re-export buf-generated Connect TS clients + proto types.
//
// The contents of src/gen/ are produced by ` + "`buf generate`" + ` (driven by
// the project's root ` + "`buf.gen.yaml`" + `). Add a re-export line below for
// each generated file you want to surface from the package, or import
// directly from "` + layout.ApiPackage + `/<path>" using the subpath export.
//
// e.g. once you have proto/services/users/v1/users.proto:
//   export * from "./gen/services/users/v1/users_pb";

export {};
`
	if err := writeIfMissing(filepath.Join(apiDir, "src", "index.ts"), indexTS); err != nil {
		return err
	}

	gitignore := `# buf-generated stubs are committed in some teams and ignored in
# others — leave the choice to the project. Default to ignoring so
# repositories stay clean; remove this line if you want to commit them.
src/gen/
`
	if err := writeIfMissing(filepath.Join(apiDir, ".gitignore"), gitignore); err != nil {
		return err
	}

	readme := fmt.Sprintf("# %s\n\n"+
		"Shared Connect TS clients + proto types for the project's frontends.\n\n"+
		"Generated by `forge generate` (via `buf generate`). Consumed by\n"+
		"`frontends/*` workspaces via `\"%s\": \"workspace:*\"`.\n\n"+
		"## Layout\n\n"+
		"- `src/gen/` — buf-emitted `*_pb.ts` files (one per proto file).\n"+
		"- `src/index.ts` — re-export barrel; add `export * from \"./gen/...\"`\n"+
		"  for each generated file you want to expose by the top-level package name.\n\n"+
		"Subpath imports also work: `import { UserService } from \"%s/services/users/v1/users_pb\"`.\n",
		layout.ApiPackage, layout.ApiPackage, layout.ApiPackage)
	if err := writeIfMissing(filepath.Join(apiDir, "README.md"), readme); err != nil {
		return err
	}
	return nil
}

// writeHooksPackage emits packages/hooks/{package.json, tsconfig.json,
// src/use-api-query.ts, src/use-api-mutation.ts, src/index.ts}.
//
// The package is DOM-free: it depends on @tanstack/react-query and the
// project's @<scope>/api workspace, and uses no document/window APIs.
// That keeps it consumable from both Next.js (DOM-aware) and React
// Native (DOM-free Hermes/Node runtime).
func writeHooksPackage(projectDir string, layout FrontendWorkspaceLayout) error {
	hooksDir := filepath.Join(projectDir, "packages", "hooks")
	if err := os.MkdirAll(filepath.Join(hooksDir, "src", "generated"), 0o755); err != nil {
		return fmt.Errorf("create packages/hooks: %w", err)
	}

	pkg := fmt.Sprintf(`{
  "name": "%s",
  "version": "0.0.0",
  "private": true,
  "main": "./src/index.ts",
  "types": "./src/index.ts",
  "exports": {
    ".": "./src/index.ts",
    "./generated": "./src/generated/index.ts",
    "./*": "./src/*.ts"
  },
  "scripts": {
    "typecheck": "tsc --noEmit"
  },
  "dependencies": {
    "%s": "workspace:*",
    "@bufbuild/protobuf": "^2.5.0",
    "@connectrpc/connect": "^2.0.0",
    "@tanstack/react-query": "^5.59.0"
  },
  "peerDependencies": {
    "react": "*"
  },
  "devDependencies": {
    "typescript": "^5.8.0"
  }
}
`, layout.HooksPackage, layout.ApiPackage)
	if err := writeIfMissing(filepath.Join(hooksDir, "package.json"), pkg); err != nil {
		return err
	}

	// Important: this tsconfig deliberately omits "DOM" from `lib`. The
	// hooks package is DOM-free — it must be consumable from React
	// Native (no document/window). If a contributor adds a DOM-only API,
	// tsc will fail here, which is the intended guardrail.
	tsconfig := `{
  "compilerOptions": {
    "target": "ES2022",
    "module": "ESNext",
    "moduleResolution": "bundler",
    "lib": ["ES2022"],
    "jsx": "preserve",
    "declaration": true,
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "isolatedModules": true
  },
  "include": ["src/**/*.ts", "src/**/*.tsx"]
}
`
	if err := writeIfMissing(filepath.Join(hooksDir, "tsconfig.json"), tsconfig); err != nil {
		return err
	}

	// transport.ts holds the module-level Connect Transport that
	// frontends bootstrap once at startup. The hooks package itself is
	// DOM-free; the actual Transport (fetch-backed on web, custom-fetch
	// on React Native) is constructed in the frontend's own connect.ts
	// and handed to setApiTransport(transport) before any hook runs.
	transportTS := `import { createClient, type Transport } from "@connectrpc/connect";
import type { DescService } from "@bufbuild/protobuf";

/**
 * Module-level transport. Each frontend constructs its own Transport
 * (browser fetch in Next.js, custom fetch in React Native) and registers
 * it once at startup via setApiTransport(). Hooks generated under
 * src/generated/ resolve their connect clients lazily against whichever
 * transport is registered when the hook fires.
 *
 * Keeping the transport in a module-level singleton (rather than a
 * React Context) lets the hooks package stay framework-agnostic — no
 * <Provider> wiring required from React Native, Next.js, Expo, etc.
 */
let _transport: Transport | null = null;

export function setApiTransport(t: Transport) {
  _transport = t;
}

export function getApiTransport(): Transport {
  if (!_transport) {
    throw new Error(
      "ApiTransport not initialized — call setApiTransport(transport) " +
        "from your frontend's connect.ts before rendering hooks.",
    );
  }
  return _transport;
}

/**
 * connectClient creates a typed Connect client against the currently-
 * registered Transport. Mirrors the per-frontend connectClient() helper
 * so generated hooks can call ` + "`connectClient(UserService)`" + ` exactly
 * like they do in the non-workspace layout.
 */
export function connectClient<S extends DescService>(service: S) {
  return createClient(service, getApiTransport());
}
`
	if err := writeIfMissing(filepath.Join(hooksDir, "src", "transport.ts"), transportTS); err != nil {
		return err
	}

	useApiQuery := `import { useQuery, type UseQueryOptions } from "@tanstack/react-query";

/**
 * useApiQuery wraps a Connect client promise-returning call in a
 * @tanstack/react-query useQuery. The hooks package is DOM-free so this
 * helper works in both Next.js and React Native.
 *
 * Generated per-service hooks live alongside this file under
 * src/generated/ — see ./generated/index.ts. Use this base wrapper for
 * one-off or composite operations that don't map to a generated hook.
 */
export function useApiQuery<TData, TError = Error>(
  key: readonly unknown[],
  fetcher: () => Promise<TData>,
  options?: Omit<
    UseQueryOptions<TData, TError, TData, readonly unknown[]>,
    "queryKey" | "queryFn"
  >,
) {
  return useQuery<TData, TError, TData, readonly unknown[]>({
    queryKey: key,
    queryFn: fetcher,
    ...options,
  });
}
`
	if err := writeIfMissing(filepath.Join(hooksDir, "src", "use-api-query.ts"), useApiQuery); err != nil {
		return err
	}

	useApiMutation := `import { useMutation, type UseMutationOptions } from "@tanstack/react-query";

/**
 * useApiMutation wraps a Connect client promise-returning call in a
 * @tanstack/react-query useMutation. The hooks package is DOM-free so
 * this helper works in both Next.js and React Native.
 */
export function useApiMutation<TData, TVariables, TError = Error>(
  mutationFn: (variables: TVariables) => Promise<TData>,
  options?: Omit<
    UseMutationOptions<TData, TError, TVariables>,
    "mutationFn"
  >,
) {
  return useMutation<TData, TError, TVariables>({
    mutationFn,
    ...options,
  });
}
`
	if err := writeIfMissing(filepath.Join(hooksDir, "src", "use-api-mutation.ts"), useApiMutation); err != nil {
		return err
	}

	// src/index.ts is the top-level barrel for the package. Generated
	// per-service files re-exported via src/generated/index.ts (written
	// at frontend-hooks-generation time, alongside the *.ts files).
	indexTS := `// @<scope>/hooks barrel — exports the base wrappers, the
// transport bootstrap helpers, and the generated per-service hooks.
// The generated/ subpath is also exposed directly so consumers can do
// ` + "`import { useGetUser } from \"@<scope>/hooks/generated\"`" + ` when they
// want to skip the barrel.

export * from "./transport";
export * from "./use-api-query";
export * from "./use-api-mutation";
export * from "./generated";
`
	if err := writeIfMissing(filepath.Join(hooksDir, "src", "index.ts"), indexTS); err != nil {
		return err
	}

	// Seed an empty generated barrel so the package compiles on a fresh
	// scaffold before any service hooks have been emitted. The frontend-
	// hooks step rewrites this file every run.
	generatedIndex := `// AUTO-GENERATED — DO NOT EDIT
// Re-exports per-service hooks. Re-rendered every ` + "`forge generate`" + `.
export {};
`
	if err := writeIfMissing(filepath.Join(hooksDir, "src", "generated", "index.ts"), generatedIndex); err != nil {
		return err
	}

	readme := fmt.Sprintf("# %s\n\n"+
		"Shared React Query hooks for the project's frontends. DOM-free —\n"+
		"consumable from both Next.js and React Native (Expo).\n\n"+
		"## Layout\n\n"+
		"- `src/use-api-query.ts` / `src/use-api-mutation.ts` — base wrappers\n"+
		"  for one-off Connect calls.\n"+
		"- `src/generated/<service>-hooks.ts` — per-service hooks generated\n"+
		"  by `forge generate` from the project's proto/services/ files.\n\n"+
		"Frontends consume the package via `\"%s\": \"workspace:*\"` and\n"+
		"`import { useGetUser } from \"%s\"`.\n",
		layout.HooksPackage, layout.HooksPackage, layout.HooksPackage)
	if err := writeIfMissing(filepath.Join(hooksDir, "README.md"), readme); err != nil {
		return err
	}
	return nil
}

// writeIfMissing writes content to path only if the file does not exist.
// Treats the file as user-owned once it's on disk — `forge generate` is
// not supposed to clobber edits to package.json, tsconfig.json, etc.
func writeIfMissing(path, content string) error {
	if _, err := os.Stat(path); err == nil {
		return nil
	}
	return os.WriteFile(path, []byte(content), 0o644)
}
