package generator

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
)

// GenerateOperatorBinaryOnly scaffolds an operator package WITHOUT a
// placeholder CRD. CRDs are added via `forge add crd <name>` instead,
// which produces per-CRD shims that delegate to forge/pkg/controller.
//
// The generator emits two files:
//
//   - operators/<package>/doc.go — package documentation that explains
//     the operator's role and points users at `forge add crd`.
//
//   - operators/<package>/operator.go — the wiring symbols
//     (Controller, Deps, New, AddToScheme) that the bootstrap
//     template expects every operator package to export. The
//     Controller type is a thin holder for the manager-level deps
//     and is not itself a reconciler — per-CRD reconcilers live in
//     <crd>_controller.go and are wired in cmd/<op>/main.go.
//
// The operator's main.go (the cmd binary entrypoint) is generated by
// the standard project bootstrap step.
func GenerateOperatorBinaryOnly(root, modulePath, name, group, version string) error {
	operatorPackage := ServicePackageName(name)
	operatorDir := filepath.Join(root, "operators", operatorPackage)
	if err := os.MkdirAll(operatorDir, 0755); err != nil {
		return fmt.Errorf("create directory %s: %w", operatorDir, err)
	}

	// Collision detection: if a sibling .go file in operatorDir already
	// declares the operator's wiring surface (Controller / New /
	// SetupWithManager / AddToScheme), the user has ported a v0-shape
	// controller-IS-the-reconciler scaffold. Re-emitting operator.go on
	// top of that shape duplicates the same symbols and breaks the build
	// (or worse: silently shadows the user's wiring with the default
	// Reconcilers slice). Skip operator.go (and the companion doc.go,
	// which is purely cosmetic) so the ported code stays authoritative.
	//
	// This is intentionally narrow: we only skip when the *operator* shape
	// is already present. A sibling <crd>_controller.go added via
	// `forge add crd` is fine — those don't declare a top-level Controller
	// type or AddToScheme, only a per-CRD reconciler type. The scan is
	// AST-based rather than grep-based so a comment that mentions
	// "Controller" doesn't trigger the skip.
	if shape, file, err := detectExistingOperatorShape(operatorDir); err != nil {
		return fmt.Errorf("scan operator dir for existing shape: %w", err)
	} else if shape {
		fmt.Printf("  ⏭️  Skipping operator.go + doc.go: %s already declares the operator wiring (Controller/New/SetupWithManager/AddToScheme).\n", filepath.Base(file))
		fmt.Printf("       The ported file is treated as authoritative. Edit it directly to wire reconcilers.\n")
		return nil
	}

	doc := fmt.Sprintf(`// Package %s implements the %s Kubernetes operator.
//
// This is a controller-runtime manager package that hosts the
// reconcilers for one or more CRDs in the API group %q
// (version %q).
//
// To add a CRD scaffold to this operator, run:
//
//   forge add crd <Name> --operator %s
//
// That command emits:
//
//   - api/%s/<lower>_types.go             CRD spec/status types
//   - operators/%s/<lower>_controller.go  thin reconciler shim
//   - operators/%s/<lower>_controller_test.go fake-client unit test
//
// The reconciler shim embeds forge/pkg/controller.Reconciler[T] which
// owns the fetch / NotFound / finalizer / dispatch lifecycle; you
// implement ReconcileSpec and FinalizeSpec on the embedding type.
//
// Module: %s
package %s
`, operatorPackage, name, group, version, name, version, operatorPackage, operatorPackage, modulePath, operatorPackage)

	docPath := filepath.Join(operatorDir, "doc.go")
	if err := os.WriteFile(docPath, []byte(doc), 0644); err != nil {
		return fmt.Errorf("write doc.go: %w", err)
	}

	// operator.go — wiring symbols expected by pkg/app/bootstrap.go.
	// Controller is a holder for manager-level deps (logger, etc.).
	// Per-CRD reconcilers (e.g. WorkspaceController) live in their
	// own files and are wired to the manager in cmd/<op>/main.go.
	op := fmt.Sprintf(`// Code generated by forge add operator. EDIT this file to wire your
// operator's manager-level dependencies. Per-CRD reconcilers live in
// <crd>_controller.go (added via 'forge add crd').
package %s

import (
	"log/slog"

	"k8s.io/apimachinery/pkg/runtime"
	utilruntime "k8s.io/apimachinery/pkg/util/runtime"
	clientgoscheme "k8s.io/client-go/kubernetes/scheme"
	ctrl "sigs.k8s.io/controller-runtime"
)

// Deps contains manager-level dependencies for the %s operator.
// Per-CRD reconcilers carry their own deps as fields on the embedding
// controller type.
type Deps struct {
	Logger *slog.Logger
}

// Controller is the operator's manager-level handle. It is
// constructed by pkg/app/bootstrap.go and consumed by
// cmd/%s/main.go which wires per-CRD reconcilers to the
// controller-runtime manager.
//
// You can extend Controller with additional fields (DB handle, NATS
// publisher, etc.) and propagate them to per-CRD reconcilers in
// cmd/%s/main.go's manager setup.
type Controller struct {
	Deps Deps

	// Reconcilers is the list of per-CRD reconcilers wired to the
	// manager when SetupWithManager is invoked. Populate this slice
	// in cmd/%s/main.go (or in pkg/app/setup.go) before the
	// manager is started — typically by appending each CRD's
	// New<Type>Controller() result.
	Reconcilers []ManagerSetup
}

// ManagerSetup is the contract every per-CRD reconciler implements.
// 'forge add crd' generates a SetupWithManager method on each
// reconciler that satisfies this interface; the operator's Controller
// holds them in a slice and forwards SetupWithManager to all of them.
type ManagerSetup interface {
	SetupWithManager(mgr ctrl.Manager) error
}

// Name returns the operator's identifier.
func (c *Controller) Name() string { return %q }

// SetupWithManager registers every Reconciler in c.Reconcilers with
// the manager. Per-CRD reconcilers (added via 'forge add crd') append
// themselves to c.Reconcilers in cmd/%s/main.go.
func (c *Controller) SetupWithManager(mgr ctrl.Manager) error {
	for _, r := range c.Reconcilers {
		if err := r.SetupWithManager(mgr); err != nil {
			return err
		}
	}
	return nil
}

// New constructs a Controller. Returns no error in the default
// scaffold; if your operator needs to validate config or open
// connections at construction time, switch to a fallible signature
// (the bootstrap template already supports both shapes).
func New(deps Deps) *Controller {
	if deps.Logger == nil {
		deps.Logger = slog.Default()
	}
	return &Controller{Deps: deps}
}

// AddToScheme registers all CRD types reconciled by this operator
// onto the supplied scheme. The default scaffold registers
// client-go's stock types; per-CRD 'forge add crd' runs append
// their AddToScheme calls below this line. The marker
// "+forge:operator-scheme" is recognised by 'forge generate' for
// idempotent re-registration.
//
// +forge:operator-scheme
func AddToScheme(scheme *runtime.Scheme) error {
	utilruntime.Must(clientgoscheme.AddToScheme(scheme))
	return nil
}
`, operatorPackage, name, operatorPackage, operatorPackage, operatorPackage, name, operatorPackage)

	opPath := filepath.Join(operatorDir, "operator.go")
	if err := os.WriteFile(opPath, []byte(op), 0644); err != nil {
		return fmt.Errorf("write operator.go: %w", err)
	}
	return nil
}

// detectExistingOperatorShape scans operatorDir for any .go file (other than
// the to-be-emitted operator.go itself) that already declares the operator's
// wiring surface. Returns (true, path, nil) on the first match.
//
// "Wiring surface" means at least one of:
//   - a top-level type named "Controller"
//   - a top-level func named "New" (any signature)
//   - a top-level func named "AddToScheme" (any signature)
//   - any method named "SetupWithManager" on a value/pointer receiver
//
// This matches the v0 controller-IS-the-reconciler shape (where
// `controller.go` carries `type Controller struct { ... }` plus
// `SetupWithManager`) without false-positives on per-CRD reconciler files
// scaffolded by `forge add crd` (those declare a per-CRD type like
// `WorkspaceController`, not bare `Controller`, and don't declare
// `AddToScheme`).
//
// The scan is best-effort: parse errors on individual files are skipped (a
// half-written .go file shouldn't block scaffolding). Returns ("", false, nil)
// when the directory is empty or no file matches.
func detectExistingOperatorShape(operatorDir string) (bool, string, error) {
	entries, err := os.ReadDir(operatorDir)
	if err != nil {
		if os.IsNotExist(err) {
			return false, "", nil
		}
		return false, "", err
	}
	fset := token.NewFileSet()
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		name := e.Name()
		if !strings.HasSuffix(name, ".go") {
			continue
		}
		// Skip test files (they wouldn't carry the wiring shape) and the
		// scaffolds we're about to write — those are inert until written.
		if strings.HasSuffix(name, "_test.go") || name == "operator.go" || name == "doc.go" {
			continue
		}
		path := filepath.Join(operatorDir, name)
		file, err := parser.ParseFile(fset, path, nil, parser.SkipObjectResolution)
		if err != nil {
			// Skip un-parseable files rather than blocking scaffolding.
			continue
		}
		for _, decl := range file.Decls {
			switch d := decl.(type) {
			case *ast.GenDecl:
				if d.Tok != token.TYPE {
					continue
				}
				for _, spec := range d.Specs {
					ts, ok := spec.(*ast.TypeSpec)
					if !ok {
						continue
					}
					if ts.Name.Name == "Controller" {
						return true, path, nil
					}
				}
			case *ast.FuncDecl:
				// Method on receiver (Recv != nil) — the SetupWithManager
				// method is the controller-runtime hook.
				if d.Recv != nil {
					if d.Name.Name == "SetupWithManager" {
						return true, path, nil
					}
					continue
				}
				// Top-level function.
				switch d.Name.Name {
				case "New", "AddToScheme":
					return true, path, nil
				}
			}
		}
	}
	return false, "", nil
}
