package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"

	"github.com/reliant-labs/forge/internal/checksums"
	"github.com/reliant-labs/forge/internal/config"
	"github.com/reliant-labs/forge/internal/naming"
)

// GeneratePlanORM writes internal/db/<snake_name>_orm.go for each entity
// defined in the plan. The generated files provide a Bun-tagged entity
// struct (a projection of the applied schema) and standalone CRUD
// functions built on Bun's query builder (reached via orm.Context.Bun()).
// CRUD is emitted as package-level functions that take an orm.Context, so
// the same functions run inside or outside a transaction.
//
// cs is the project's checksum tracker: every output is recorded as a
// Tier-1 manifest entry so `forge disown` can transfer ownership of an
// ORM file (kalshi fr-4dfef712e9: disown refused on internal/db/*_orm.go
// because nothing registered them) and `forge audit` doesn't see the
// files as orphans. A nil cs is tolerated (files written, not tracked).
func GeneratePlanORM(root, modulePath, serviceName string, entities []config.PlanEntity, cs *FileChecksums) error {
	if len(entities) == 0 {
		return nil
	}

	dbDir := filepath.Join(root, "internal", "db")
	if err := os.MkdirAll(dbDir, 0o755); err != nil {
		return fmt.Errorf("create db directory: %w", err)
	}

	// Clean up stale ORM files for entities that no longer exist —
	// but never a file the user owns (Tier-2 / disowned / legacy-forked
	// entries): a disowned ORM file is the user's content now, and the
	// entity disappearing from the projection doesn't change that.
	// Removed forge-owned files are pruned from the manifest too.
	expectedFiles := make(map[string]bool)
	expectedFiles["orm_shared.go"] = true
	expectedFiles["types.go"] = true
	for _, ent := range entities {
		expectedFiles[naming.ToSnakeCase(ent.Name)+"_orm.go"] = true
	}
	existing, _ := os.ReadDir(dbDir)
	for _, e := range existing {
		if e.IsDir() || !strings.HasSuffix(e.Name(), "_orm.go") || expectedFiles[e.Name()] {
			continue
		}
		rel := filepath.Join("internal", "db", e.Name())
		if cs.IsDisowned(rel) {
			continue // user-owned by recorded intent — not forge's to delete
		}
		full := filepath.Join(dbDir, e.Name())
		body, rerr := os.ReadFile(full)
		if rerr != nil {
			continue
		}
		// Ownership is read from the file itself: a verifying marker (or,
		// for pre-marker output, the forge banner) certifies forge bytes;
		// a hand-edited (Modified) file is the user's now.
		switch checksums.Verify(body) {
		case checksums.Pristine:
			os.Remove(full)
		case checksums.Modified:
			continue
		case checksums.NoMarker:
			if bytes.Contains(body, []byte("Code generated by forge")) {
				os.Remove(full)
			}
		}
	}

	// Write ormTracer var in a shared file (one per project).
	if err := writeORMFile(root, "orm_shared.go", renderORMShared(), cs); err != nil {
		return fmt.Errorf("write orm shared: %w", err)
	}

	for _, ent := range entities {
		name := naming.ToSnakeCase(ent.Name) + "_orm.go"
		if err := writeORMFile(root, name, renderORMEntity(ent), cs); err != nil {
			return fmt.Errorf("generate ORM for entity %s: %w", ent.Name, err)
		}
		// The custom-query seam: a scaffold-once, user-owned sibling file
		// documenting where hand-written / raw-SQL queries for this entity
		// go. It reuses the generated <entity>Repo, the package-level
		// delegates, and db handle. Routed through the Tier-2 writer so
		// it's NEVER overwritten after first scaffold (sibling files in
		// package db survive the *_orm.go regen sweep above).
		if err := writeRepoExtSeam(root, ent, cs); err != nil {
			return fmt.Errorf("scaffold repo-ext seam for entity %s: %w", ent.Name, err)
		}
	}
	return nil
}

// writeRepoExtSeam scaffolds internal/db/<entity>_repo_ext.go ONCE: a
// discoverable, empty-but-documented home for hand-written queries that
// reuse the generated CRUD machinery. Tier-2 (scaffold-once) — once on
// disk forge never touches it, so the user's custom methods are safe
// across every future `forge generate`.
func writeRepoExtSeam(root string, ent config.PlanEntity, cs *FileChecksums) error {
	name := naming.ToSnakeCase(ent.Name) + "_repo_ext.go"
	rel := filepath.Join("internal", "db", name)
	_, err := WriteGeneratedFileTier2(root, rel, renderRepoExtSeam(ent), cs, false)
	return err
}

// renderRepoExtSeam renders the per-entity custom-query seam. It compiles
// as-is (no unused imports, no undefined references) and shows — in a
// commented example — how to add a method that reuses the generated
// repo/delegates and drops to raw SQL via the Bun handle.
func renderRepoExtSeam(ent config.PlanEntity) []byte {
	msgName := ent.Name
	pkGoType := "string"
	for _, f := range resolveORMFields(ent) {
		if f.isPK {
			pkGoType = f.structGoType()
			break
		}
	}
	repoVar := lowerFirst(msgName) + "Repo"

	var b strings.Builder
	fmt.Fprintf(&b, "// yours: scaffolded once, never touched again — forge will not overwrite this file.\n")
	fmt.Fprintf(&b, "//\n")
	fmt.Fprintf(&b, "// This is the custom-query seam for %s. The generated %s_orm.go is\n", msgName, naming.ToSnakeCase(msgName))
	b.WriteString("// Tier-1 (a live projection of the migrations, regenerated every run);\n")
	b.WriteString("// hand-written queries that outgrow the generated CRUD belong HERE, in a\n")
	b.WriteString("// sibling file forge never rewrites. You have three building blocks:\n")
	b.WriteString("//\n")
	fmt.Fprintf(&b, "//   1. The generated repo + delegates: %s (a *crud.Repo[%s]) and the\n", repoVar, msgName)
	fmt.Fprintf(&b, "//      package-level Get%sByID / List%s / Create%s / Update%s / Delete%s\n", msgName, msgName, msgName, msgName, msgName)
	b.WriteString("//      functions — compose orm.QueryOption filters (orm.WhereEq,\n")
	b.WriteString("//      orm.WhereILikeAny, orm.WithOrderBy, orm.WithLimit) onto List/Count.\n")
	b.WriteString("//   2. Raw SQL via the Bun handle: db.Bun() (bun.IDB) gives you\n")
	b.WriteString("//      NewSelect()/NewRaw()/bun.Raw — for joins, aggregates, CTEs, or\n")
	b.WriteString("//      anything the builder can't express. Scan into the generated\n")
	fmt.Fprintf(&b, "//      %s struct (or your own row type).\n", msgName)
	b.WriteString("//   3. orm.Context: every query takes one, so the same method runs\n")
	b.WriteString("//      inside or outside a transaction (pass the tx handle to run in one).\n")
	b.WriteString("//\n")
	b.WriteString("// Example (uncomment and adapt):\n")
	b.WriteString("//\n")
	fmt.Fprintf(&b, "//\tfunc Find%sBy(ctx context.Context, db orm.Context, /* args */) ([]*%s, error) {\n", msgName, msgName)
	fmt.Fprintf(&b, "//\t\tvar rows []*%s\n", msgName)
	fmt.Fprintf(&b, "//\t\terr := db.Bun().NewSelect().Model(&rows).\n")
	fmt.Fprintf(&b, "//\t\t\tWhere(\"%s = ?\", /* value */).\n", firstNonPKColumn(ent, pkGoType))
	b.WriteString("//\t\t\tScan(ctx)\n")
	b.WriteString("//\t\treturn rows, err\n")
	b.WriteString("//\t}\n")
	b.WriteString("//\n")
	fmt.Fprintf(&b, "// Or reuse the generated repo for a filtered list:\n")
	fmt.Fprintf(&b, "//\n")
	fmt.Fprintf(&b, "//\tfunc Active%s(ctx context.Context, db orm.Context%s) ([]*%s, error) {\n", naming.Pluralize(msgName), tenantParam(ent), msgName)
	fmt.Fprintf(&b, "//\t\treturn List%s(ctx, db%s, orm.WhereEq(\"%s\", true))\n", msgName, tenantArg(ent), firstNonPKColumn(ent, pkGoType))
	b.WriteString("//\t}\n")
	b.WriteString("package db\n")

	if formatted, err := format.Source([]byte(b.String())); err == nil {
		return formatted
	}
	return []byte(b.String())
}

// firstNonPKColumn returns a representative non-PK column name for the
// doc example's WHERE clause, falling back to the PK column when the
// entity has only a primary key.
func firstNonPKColumn(ent config.PlanEntity, _ string) string {
	pk := ""
	for _, f := range resolveORMFields(ent) {
		if f.isPK {
			pk = f.columnName
			continue
		}
		return f.columnName
	}
	if pk != "" {
		return pk
	}
	return "id"
}

// tenantParam/tenantArg render the optional tenant scoping argument the
// generated List<Entity> delegate takes for a tenant-scoped entity (so
// the doc example matches the real signature).
func tenantParam(ent config.PlanEntity) string {
	if entityHasTenant(ent) {
		return ", tenantID string"
	}
	return ""
}

func tenantArg(ent config.PlanEntity) string {
	if entityHasTenant(ent) {
		return ", tenantID"
	}
	return ""
}

func entityHasTenant(ent config.PlanEntity) bool {
	for _, f := range resolveORMFields(ent) {
		if f.isTenantKey {
			return true
		}
	}
	return false
}

// writeORMFile writes one internal/db output through the Tier-1
// checksum chokepoint: the render is recorded in the manifest, a
// disowned entry is never overwritten (delete-and-regenerate is the
// documented re-adoption path), and force=true keeps the Tier-1
// regenerated-every-run semantics (hand-edit protection is the
// pre-pipeline drift guard's job, same as every other Tier-1 emitter).
func writeORMFile(root, name string, content []byte, cs *FileChecksums) error {
	rel := filepath.Join("internal", "db", name)
	// First-adoption warning: ORM files written by pre-marker forge are
	// on disk without a certification marker, so the drift guard can't
	// yet protect a hand-patch in them (kalshi carried exactly such a
	// patch). The overwrite itself matches the old regenerate-every-run
	// behavior — but now it's LOUD, and the marker stamped by the write
	// below makes every future edit guard-visible (and `forge disown`
	// possible).
	if prior, rerr := os.ReadFile(filepath.Join(root, rel)); rerr == nil {
		if checksums.Verify(prior) == checksums.NoMarker && checksums.BodyHash(prior) != checksums.BodyHash(content) {
			fmt.Printf("  ⚠️  %s existed without a forge:hash marker and differed from the fresh render — overwriting and stamping it (recover prior content from git; use `forge disown %s --reason ...` if you need to own it)\n", rel, rel)
		}
	}
	_, err := WriteGeneratedFileTier1(root, rel, content, cs, true)
	return err
}

// renderORMShared renders the shared orm_shared.go with the ormTracer var.
func renderORMShared() []byte {
	var b strings.Builder
	b.WriteString("// Code generated by forge. DO NOT EDIT.\n")
	b.WriteString("// forge-owned: regenerated every run — do not edit (forge disown to take ownership)\n")
	b.WriteString("package db\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"go.opentelemetry.io/otel\"\n")
	b.WriteString(")\n\n")
	b.WriteString("var ormTracer = otel.Tracer(\"orm\")\n")
	return []byte(b.String())
}

// ormField holds the resolved metadata for a single entity field used during
// code generation. This mirrors the information in the protoc-based codegen's
// fieldInfo but is derived directly from PlanEntityField.
type ormField struct {
	planField   config.PlanEntityField
	goName      string // PascalCase Go field name (proto-style)
	columnName  string // snake_case column name
	goType      string // base Go type (notnull variant), e.g. "time.Time"
	ormType     string // orm.TypeXxx constant name
	isTimestamp bool
	isArray     bool
	isPK        bool
	isTenantKey bool
	notNull     bool
	unique      bool
	references  string
	nullable    bool   // nullable column → pointer struct field
	hasDefault  bool   // column has a DB DEFAULT (server-supplied value)
	columnDef   string // the DEFAULT expression verbatim, when hasDefault
	// softDeleteNative is true on the deleted_at field when soft delete is
	// active AND the column projects to a proper time type (TIMESTAMPTZ →
	// time.Time). Bun's built-in ,soft_delete owns it; the generated CRUD
	// relies on Bun. False for a legacy TEXT deleted_at, which stays
	// hand-rolled (Bun's ,soft_delete stamps a time.Time that a TEXT column
	// can't round-trip — kalshi fr-3fba9166ba style).
	softDeleteNative bool
	// isGenerated marks a GENERATED ALWAYS AS (...) STORED column → ,scanonly
	// so Bun reads it but never writes it (postgres rejects writes to
	// generated columns).
	isGenerated bool
}

// isBunSoftDeleteTimeType reports whether a deleted_at field's projected
// Go type is one Bun's ,soft_delete can stamp/scan: a time. Legacy TEXT
// deleted_at columns project to "string" and fail this — they keep the
// hand-rolled stamp/filter path.
func isBunSoftDeleteTimeType(f ormField) bool {
	return f.goType == "time.Time"
}

// structGoType is the Go type of the field on the generated entity
// struct: the base type, pointered when the column is nullable
// (arrays/bytes are reference types already and stay bare).
func (f ormField) structGoType() string {
	if f.nullable && !f.isArray && f.goType != "[]byte" {
		return "*" + f.goType
	}
	return f.goType
}

func renderORMEntity(ent config.PlanEntity) []byte {
	msgName := ent.Name
	tableName := ent.TableName
	if tableName == "" {
		tableName = naming.Pluralize(naming.ToSnakeCase(ent.Name))
	}

	// Build fields list including auto-generated timestamp/soft-delete fields.
	fields := resolveORMFields(ent)

	// Identify special fields.
	var pkField *ormField
	var tenantField *ormField
	for i := range fields {
		if fields[i].isPK {
			pkField = &fields[i]
		}
		if fields[i].isTenantKey {
			tenantField = &fields[i]
		}
	}

	// pkGoType is the Go type of the primary key, used in the delegate
	// signatures (Get/Delete take an id of this type). The column name and
	// other PK details the repo derives from Bun's schema at runtime.
	pkGoType := "string"
	if pkField != nil {
		pkGoType = pkField.goType
	}

	hasTenant := tenantField != nil

	// The time import is needed only for a time.Time / *time.Time struct
	// field (the projected type of a TIMESTAMPTZ column). The managed-
	// timestamp stamping (the time.Now() instant or its RFC3339Nano string
	// for legacy TEXT columns) now lives in forge/pkg/crud, so the
	// generated file no longer references time for stamping — a TEXT
	// timestamp column projects to string and needs no time import (an
	// otherwise-unused "time" import would not compile).
	needsTime := false
	for _, f := range fields {
		if f.goType == "time.Time" {
			needsTime = true
			break
		}
	}

	var b strings.Builder

	// Header
	b.WriteString("// Code generated by forge. DO NOT EDIT.\n")
	b.WriteString("// forge-owned: regenerated every run — do not edit (forge disown to take ownership)\n")
	b.WriteString("package db\n\n")

	// Imports
	writeORMImports(&b, needsTime)

	// The entity struct: a projection of the APPLIED schema, with Bun tags.
	writeEntityStruct(&b, msgName, tableName, fields)

	// Field name constants
	fmt.Fprintf(&b, "// Field name constants for %s.\n", msgName)
	fmt.Fprintf(&b, "const %sTableName = %q\n\n", msgName, tableName)
	b.WriteString("const (\n")
	for _, f := range fields {
		fmt.Fprintf(&b, "\t%sField%s = %q\n", msgName, f.goName, f.columnName)
	}
	b.WriteString(")\n\n")

	// Column list helper. EXPORTED: this is the per-entity column
	// allowlist — handler shims hand it to pkg/crud so user-supplied
	// order_by/filter columns are validated against declared columns
	// (identifier-shape validation alone let `order_by=password_hash`
	// through as a silent no-op).
	colsVar := msgName + "Columns"
	fmt.Fprintf(&b, "// %s is the ordered list of declared columns for %s.\n", colsVar, msgName)
	fmt.Fprintf(&b, "// It doubles as the column allowlist for user-supplied order_by/filter\n")
	fmt.Fprintf(&b, "// input (see forge/pkg/crud).\n")
	fmt.Fprintf(&b, "var %s = []string{\n", colsVar)
	for _, f := range fields {
		fmt.Fprintf(&b, "\t%q,\n", f.columnName)
	}
	b.WriteString("}\n\n")

	// Soft-delete mode. With a proper time deleted_at, Bun's built-in
	// ,soft_delete owns it (detected from the schema by the generic repo). A
	// legacy TEXT deleted_at can't round-trip Bun's time.Time stamp, so the
	// repo's Spec.LegacyTextDeletedAt flag opts it into the hand-rolled
	// filter/stamp path. That flag is the only soft-delete signal the repo
	// can't infer from the Bun tags.
	nativeSoftDelete := ent.SoftDelete && entityUsesNativeSoftDelete(fields)
	legacyTextSoftDelete := ent.SoftDelete && !nativeSoftDelete

	// CRUD: a single generic crud.Repo[<Entity>] owns the lifecycle
	// (built on Bun, metadata derived from the schema/tags at first use),
	// and thin package-level delegates preserve the standalone-function API
	// the handler ops and any user code call. The repo's Spec carries ONLY
	// the forge conventions Bun can't read off the struct tags: the tenant
	// column, managed timestamps, and the legacy-TEXT deleted_at fallback.
	tenantCol := ""
	if hasTenant && tenantField != nil {
		tenantCol = tenantField.columnName
	}
	writeORMRepoAndDelegates(&b, msgName, pkGoType, hasTenant, ent.SoftDelete,
		tenantCol, ent.Timestamps, legacyTextSoftDelete)

	// gofmt the render so struct-tag/const alignment matches what the
	// project's gofmt/CI check (and the drift guard) expect. The writers
	// emit unaligned tabs; format.Source canonicalizes them. On the
	// off chance the render is not valid Go, fall back to the raw bytes so
	// the compile error surfaces at `go build` rather than here.
	src := []byte(b.String())
	if formatted, err := format.Source(src); err == nil {
		return formatted
	}
	return src
}

// writeORMImports emits the import block for a generated ORM file. The
// per-entity CRUD bodies now live in the generic forge/pkg/crud.Repo, so
// the generated file imports only what the thin delegates and the struct
// reference: context (delegate signatures), forge/pkg/crud (the Repo),
// forge/pkg/orm (the Context + QueryOption types), and bun (the embedded
// BaseModel). time is added when any column projects to time.Time. The old
// per-file fmt/strings/ulid/otel imports are gone — the library owns the
// tracing, ULID generation, and error wrapping.
func writeORMImports(b *strings.Builder, needsTime bool) {
	b.WriteString("import (\n")
	b.WriteString("\t\"context\"\n")
	if needsTime {
		b.WriteString("\t\"time\"\n")
	}
	b.WriteString("\n")
	b.WriteString("\t\"github.com/reliant-labs/forge/pkg/crud\"\n")
	b.WriteString("\t\"github.com/reliant-labs/forge/pkg/orm\"\n")
	b.WriteString("\t\"github.com/uptrace/bun\"\n")
	b.WriteString(")\n\n")
}

// writeORMRepoAndDelegates emits the per-entity repo var plus the thin
// standalone delegates that preserve the pre-generic function API. The
// generic crud.Repo[<Entity>] owns every lifecycle concern; these delegates
// are pure forwarding so the handler ops shim (and any hand-written caller)
// keeps compiling unchanged. Spec carries only the conventions Bun's schema
// can't infer: tenant column, managed timestamps, legacy-TEXT deleted_at.
func writeORMRepoAndDelegates(b *strings.Builder, msgName, pkGoType string, hasTenant, softDelete bool, tenantCol string, timestamps, legacyText bool) {
	repoVar := lowerFirst(msgName) + "Repo"

	// The per-entity repo, constructed once at package init. Metadata is
	// derived from Bun's schema lazily on the first call, so this is a
	// cheap struct literal here.
	fmt.Fprintf(b, "// %s is the generic CRUD repository for %s. It owns the\n", repoVar, msgName)
	b.WriteString("// lifecycle (tenant scope, soft delete, masked updates, managed\n")
	b.WriteString("// timestamps, pagination via QueryOption) over Bun; the standalone\n")
	b.WriteString("// functions below are thin delegates onto it.\n")
	fmt.Fprintf(b, "var %s = crud.NewRepo[%s](crud.Spec{\n", repoVar, msgName)
	if tenantCol != "" {
		fmt.Fprintf(b, "\tTenantColumn: %q,\n", tenantCol)
	}
	if timestamps {
		b.WriteString("\tTimestamps: true,\n")
	}
	if legacyText {
		b.WriteString("\tLegacyTextDeletedAt: true,\n")
	}
	b.WriteString("})\n\n")

	// tenantArg renders the trailing tenantID argument (the repo always
	// takes one; a non-tenant entity forwards "").
	tArg := `""`
	if hasTenant {
		tArg = "tenantID"
	}
	tParam := ""
	if hasTenant {
		tParam = ", tenantID string"
	}

	// Create
	fmt.Fprintf(b, "// Create%s inserts a new %s row (plain INSERT, never an upsert).\n", msgName, msgName)
	fmt.Fprintf(b, "func Create%s(ctx context.Context, db orm.Context, msg *%s%s) error {\n", msgName, msgName, tParam)
	fmt.Fprintf(b, "\treturn %s.Create(ctx, db, msg, %s)\n", repoVar, tArg)
	b.WriteString("}\n\n")

	// Get
	fmt.Fprintf(b, "// Get%sByID retrieves a %s by primary key; a missing row\n", msgName, msgName)
	b.WriteString("// satisfies errors.Is(err, orm.ErrNoRows).\n")
	fmt.Fprintf(b, "func Get%sByID(ctx context.Context, db orm.Context, id %s%s) (*%s, error) {\n", msgName, pkGoType, tParam, msgName)
	fmt.Fprintf(b, "\treturn %s.Get(ctx, db, id, %s)\n", repoVar, tArg)
	b.WriteString("}\n\n")

	// List
	fmt.Fprintf(b, "// List%s retrieves %s rows with optional QueryOption filtering.\n", msgName, msgName)
	fmt.Fprintf(b, "func List%s(ctx context.Context, db orm.Context%s, opts ...orm.QueryOption) ([]*%s, error) {\n", msgName, tParam, msgName)
	fmt.Fprintf(b, "\treturn %s.List(ctx, db, %s, opts...)\n", repoVar, tArg)
	b.WriteString("}\n\n")

	// Count
	fmt.Fprintf(b, "// Count%s returns the number of matching %s rows.\n", msgName, msgName)
	fmt.Fprintf(b, "func Count%s(ctx context.Context, db orm.Context%s, opts ...orm.QueryOption) (int64, error) {\n", msgName, tParam)
	fmt.Fprintf(b, "\treturn %s.Count(ctx, db, %s, opts...)\n", repoVar, tArg)
	b.WriteString("}\n\n")

	// ListAll (only for soft-delete entities, matching the legacy surface)
	if softDelete {
		fmt.Fprintf(b, "// ListAll%s retrieves all %s rows including soft-deleted ones.\n", msgName, msgName)
		fmt.Fprintf(b, "func ListAll%s(ctx context.Context, db orm.Context%s, opts ...orm.QueryOption) ([]*%s, error) {\n", msgName, tParam, msgName)
		fmt.Fprintf(b, "\treturn %s.ListAll(ctx, db, %s, opts...)\n", repoVar, tArg)
		b.WriteString("}\n\n")
	}

	// Update
	fmt.Fprintf(b, "// Update%s writes the updatable columns of an existing %s by PK\n", msgName, msgName)
	b.WriteString("// (created_at/PK/tenant/deleted_at excluded; updated_at re-stamped).\n")
	fmt.Fprintf(b, "func Update%s(ctx context.Context, db orm.Context, msg *%s%s) error {\n", msgName, msgName, tParam)
	fmt.Fprintf(b, "\treturn %s.Update(ctx, db, msg, %s)\n", repoVar, tArg)
	b.WriteString("}\n\n")

	// UpdateMasked
	fmt.Fprintf(b, "// Update%sMasked writes ONLY the named columns (AIP-134 update_mask;\n", msgName)
	b.WriteString("// unknown/immutable paths return *orm.UnknownFieldError).\n")
	fmt.Fprintf(b, "func Update%sMasked(ctx context.Context, db orm.Context, msg *%s, fields []string%s) error {\n", msgName, msgName, tParam)
	fmt.Fprintf(b, "\treturn %s.UpdateMasked(ctx, db, msg, fields, %s)\n", repoVar, tArg)
	b.WriteString("}\n\n")

	// Delete
	fmt.Fprintf(b, "// Delete%s removes a %s by PK (soft delete stamps deleted_at when the\n", msgName, msgName)
	b.WriteString("// entity opts in; otherwise a hard DELETE).\n")
	fmt.Fprintf(b, "func Delete%s(ctx context.Context, db orm.Context, id %s%s) error {\n", msgName, pkGoType, tParam)
	fmt.Fprintf(b, "\treturn %s.Delete(ctx, db, id, %s)\n", repoVar, tArg)
	b.WriteString("}\n")
}

// lowerFirst returns s with its first rune lower-cased (msgName ->
// repo-var prefix).
func lowerFirst(s string) string {
	if s == "" {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}

// bunTag returns the `bun:"..."` struct tag for a field, projecting the
// introspected schema into Bun's native tag vocabulary so Bun owns the
// behaviour forge used to hand-roll. The column name is always present.
//
//   - PRIMARY KEY                → ,pk; a server-allocated integer PK
//     (SERIAL/IDENTITY/BIGSERIAL) also gets ,autoincrement so Bun reads
//     the DB-assigned value back via RETURNING.
//   - deleted_at soft-delete     → ,soft_delete,nullzero — Bun's BUILT-IN
//     soft delete. NewSelect auto-excludes deleted rows, a plain
//     NewDelete stamps deleted_at, WhereAllWithDeleted/ForceDelete opt
//     out. nullzero maps a zero/NULL deleted_at to "live". (Only emitted
//     for a proper time deleted_at; a legacy TEXT column is NOT marked
//     softDeleteNative and falls through to the plain notnull/default
//     projection below, keeping the hand-rolled path.)
//   - array column               → ,array (native postgres array bind/scan).
//   - NOT NULL column            → ,notnull (skipped for the PK, which
//     ,pk already implies, and for soft_delete, which is nullable).
//   - column DEFAULT             → ,default:<expr> so Bun knows the DB
//     supplies the value (skipped for the PK/autoincrement and
//     soft_delete, whose lifecycle Bun manages).
func bunTag(f ormField) string {
	parts := []string{f.columnName}

	switch {
	case f.softDeleteNative:
		// Bun's built-in soft delete owns the column entirely.
		parts = append(parts, "soft_delete", "nullzero")
	case f.isPK:
		parts = append(parts, "pk")
		if isIntegerGoType(f.goType) {
			// SERIAL/IDENTITY: server-allocated, read back via RETURNING.
			parts = append(parts, "autoincrement")
		}
	default:
		if f.isArray {
			parts = append(parts, "array")
		}
		if f.notNull {
			parts = append(parts, "notnull")
		}
		if f.hasDefault {
			parts = append(parts, "default:"+f.columnDef)
		}
	}

	// GENERATED ALWAYS AS (...) STORED: the DB computes it. ,scanonly tells
	// Bun to read the column but never write it on INSERT/UPDATE (postgres
	// rejects writes to a generated column). Applied after the switch so it
	// stacks on whatever else the column needs (array/notnull for scanning).
	if f.isGenerated {
		parts = append(parts, "scanonly")
	}

	return fmt.Sprintf("`bun:%q`", strings.Join(parts, ","))
}

// writeEntityStruct emits the entity row type with Bun struct tags. Field
// types come from the APPLIED schema's columns: time.Time for timestamps
// (never timestamppb — the wire seam converts), pointers for nullable
// columns, native slices for array columns. Bun scans rows straight into
// this struct via the tags.
func writeEntityStruct(b *strings.Builder, msgName, tableName string, fields []ormField) {
	fmt.Fprintf(b, "// %s is the %s row type — a projection of the APPLIED schema\n", msgName, tableName)
	b.WriteString("// (db/migrations). Evolve it by writing migrations; `forge generate`\n")
	b.WriteString("// regenerates this struct from the introspected schema. The bun tags\n")
	b.WriteString("// map fields to columns for the Bun query engine; the embedded\n")
	b.WriteString("// bun.BaseModel pins the table name and its alias (alias == table so\n")
	b.WriteString("// Bun's column qualification matches the FROM clause).\n")
	fmt.Fprintf(b, "type %s struct {\n", msgName)
	fmt.Fprintf(b, "\tbun.BaseModel `bun:%q`\n", fmt.Sprintf("table:%s,alias:%s", tableName, tableName))
	for _, f := range fields {
		fmt.Fprintf(b, "\t%s %s %s\n", f.goName, f.structGoType(), bunTag(f))
	}
	b.WriteString("}\n\n")
}

// isIntegerGoType reports whether the projected Go type is an integer —
// the PK kinds that are server-allocated (BIGSERIAL / SERIAL / rowid).
func isIntegerGoType(goType string) bool {
	switch goType {
	case "int32", "int64", "uint32", "uint64":
		return true
	}
	return false
}

// ── managed-timestamp stamping (type-aware) ────────────────────────────
//
// The managed created_at/updated_at stamping (TIMESTAMPTZ → time.Now(),
// legacy TEXT → RFC3339Nano string, plus the nullable pointer variants)
// now lives in forge/pkg/crud, driven by the per-entity repo Spec's
// Timestamps flag. The generator only projects the struct field types and
// records the Spec flag; it no longer emits stamping code, so the former
// isManagedTimestampColumn/stampableTimestamp helpers are gone.

// resolveORMFields resolves an entity's declared fields plus the
// auto-added id/timestamp/soft-delete columns into the ormField list used
// by the code generator.
func resolveORMFields(ent config.PlanEntity) []ormField {
	type entry struct {
		config.PlanEntityField
		autoGenerated bool
	}

	// Check if any field already serves as the primary key.
	hasPK := false
	for _, f := range ent.Fields {
		if f.PrimaryKey || f.Name == "id" {
			hasPK = true
			break
		}
	}

	entries := make([]entry, 0, len(ent.Fields)+4)

	// Auto-add an id primary key field if none exists.
	if !hasPK {
		entries = append(entries, entry{PlanEntityField: config.PlanEntityField{
			Name: "id", Type: "string", PrimaryKey: true, NotNull: true,
		}})
	}

	declared := make(map[string]bool, len(ent.Fields))
	for _, f := range ent.Fields {
		declared[f.Name] = true
		entries = append(entries, entry{PlanEntityField: f})
	}

	// Auto-add timestamp/soft-delete columns ONLY when the entity didn't
	// declare them — proto entities routinely declare created_at /
	// updated_at / deleted_at explicitly alongside timestamps:true /
	// soft_delete:true, and a duplicate field is a compile error in the
	// generated code (duplicate consts) and a duplicate column in SQL.
	if ent.Timestamps {
		if !declared["created_at"] {
			entries = append(entries,
				entry{PlanEntityField: config.PlanEntityField{Name: "created_at", Type: "google.protobuf.Timestamp"}, autoGenerated: true})
		}
		if !declared["updated_at"] {
			entries = append(entries,
				entry{PlanEntityField: config.PlanEntityField{Name: "updated_at", Type: "google.protobuf.Timestamp"}, autoGenerated: true})
		}
	}
	if ent.SoftDelete && !declared["deleted_at"] {
		entries = append(entries,
			entry{PlanEntityField: config.PlanEntityField{Name: "deleted_at", Type: "google.protobuf.Timestamp"}, autoGenerated: true},
		)
	}

	fields := make([]ormField, 0, len(entries))
	for _, e := range entries {
		f := ormField{
			planField:   e.PlanEntityField,
			goName:      naming.ToProtoPascalCase(e.Name),
			columnName:  e.Name,
			goType:      planFieldGoType(e.Type),
			ormType:     planFieldOrmType(e.Type),
			isTimestamp: isTimePlanType(e.Type),
			isArray:     strings.HasPrefix(e.Type, "[]"),
			isPK:        e.PrimaryKey,
			isTenantKey: e.TenantKey,
			notNull:     e.NotNull,
			unique:      e.Unique,
			references:  e.References,
			hasDefault:  strings.TrimSpace(e.Default) != "",
			columnDef:   strings.TrimSpace(e.Default),
			isGenerated: e.Generated,
		}
		// Nullable column → pointer struct field. Arrays and bytes are
		// reference types already (NULL scans to nil).
		f.nullable = !f.isPK && !f.notNull && isNullablePlanType(e.Type)
		fields = append(fields, f)
	}

	// Mark the soft-delete column when soft delete is active and the
	// deleted_at column projects to a proper time type — Bun's built-in
	// ,soft_delete then owns it. A legacy TEXT deleted_at (Go type string)
	// is left unmarked and keeps the hand-rolled stamp/filter path.
	if ent.SoftDelete {
		for i := range fields {
			if fields[i].columnName == "deleted_at" && isBunSoftDeleteTimeType(fields[i]) {
				fields[i].softDeleteNative = true
			}
		}
	}
	return fields
}

// entityUsesNativeSoftDelete reports whether the entity's soft delete is
// handled by Bun's built-in ,soft_delete (proper time deleted_at) rather
// than the hand-rolled TEXT fallback. Drives the read/delete codegen: when
// true, Bun auto-excludes deleted rows from NewSelect, a plain NewDelete
// soft-deletes, and WhereAllWithDeleted includes them — the generator emits
// no deleted_at IS NULL filters and no CURRENT_TIMESTAMP stamp.
func entityUsesNativeSoftDelete(fields []ormField) bool {
	for _, f := range fields {
		if f.softDeleteNative {
			return true
		}
	}
	return false
}

// isTimePlanType reports whether the plan type is a timestamp column.
func isTimePlanType(t string) bool {
	switch t {
	case "time", "google.protobuf.Timestamp", "timestamp":
		return true
	}
	return false
}

// planFieldGoType maps a PlanEntityField.Type to the base Go type used
// on the entity struct (and in Values/Scan).
//
// The vocabulary is the canonical schema vocabulary (see
// internal/schemadef.MapDeclaredType): string, int64, float64, bool,
// time, json, bytes, []string, []int64. Legacy proto-type aliases stay
// mapped during the transition.
func planFieldGoType(t string) string {
	switch t {
	case "[]string":
		return "[]string"
	case "[]int64", "[]int", "[]int32":
		return "[]int64"
	case "string", "json":
		return "string"
	case "int32":
		return "int32"
	case "int64", "int":
		return "int64"
	case "uint32":
		return "uint32"
	case "uint64":
		return "uint64"
	case "bool":
		return "bool"
	case "float", "float32":
		return "float32"
	case "double", "float64":
		return "float64"
	case "bytes":
		return "[]byte"
	case "time", "google.protobuf.Timestamp", "timestamp":
		return "time.Time"
	default:
		return "string"
	}
}

// planFieldOrmType maps a PlanEntityField.Type to the orm.TypeXxx constant string
// used in generated Schema() code.
func planFieldOrmType(t string) string {
	if strings.HasPrefix(t, "[]") {
		return "orm.TypeJSONB"
	}
	switch t {
	case "string":
		return "orm.TypeText"
	case "json":
		return "orm.TypeJSONB"
	case "bool":
		return "orm.TypeBoolean"
	case "int32", "uint32":
		return "orm.TypeInteger"
	case "int64", "int", "uint64":
		return "orm.TypeBigInt"
	case "float", "float32":
		return "orm.TypeReal"
	case "double", "float64":
		return "orm.TypeDoublePrecision"
	case "bytes":
		return "orm.TypeBytea"
	case "time", "google.protobuf.Timestamp", "timestamp":
		return "orm.TypeTimestampTZ"
	default:
		return "orm.TypeText"
	}
}

// isNullablePlanType returns true when a nullable column of this type
// becomes a pointer field on the entity struct.
func isNullablePlanType(t string) bool {
	if strings.HasPrefix(t, "[]") || t == "bytes" {
		// Reference types: NULL scans to nil without a pointer.
		return false
	}
	switch t {
	case "string", "json", "int32", "int64", "int", "uint32", "uint64", "bool",
		"float", "float32", "double", "float64",
		"time", "google.protobuf.Timestamp", "timestamp":
		return true
	default:
		return false
	}
}
