package generator

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/reliant-labs/forge/internal/config"
)

// ── M3: ORM outputs are tracked in .forge/checksums.json ───────────────
//
// Kalshi fr-4dfef712e9, reproduced verbatim: `forge disown
// internal/db/trade_orm.go` refused because the ORM emitter never
// recorded its outputs in the manifest — the escape hatch the file's
// own header advertises ("forge disown to take ownership") was
// unusable, and `forge audit` saw every *_orm.go as an orphan.

func ormRel(name string) string {
	return filepath.Join("internal", "db", name)
}

func TestGeneratePlanORM_RegistersOutputsInManifest(t *testing.T) {
	root := t.TempDir()
	cs := &FileChecksums{Files: map[string]FileChecksumEntry{}}

	entities := []config.PlanEntity{
		{Name: "Item", Fields: []config.PlanEntityField{
			{Name: "id", Type: "string", PrimaryKey: true, NotNull: true},
			{Name: "name", Type: "string", NotNull: true},
		}},
		{Name: "Order", Fields: []config.PlanEntityField{
			{Name: "id", Type: "string", PrimaryKey: true, NotNull: true},
		}},
	}

	if err := GeneratePlanORM(root, "example.com/app", "api", entities, cs); err != nil {
		t.Fatalf("GeneratePlanORM: %v", err)
	}

	for _, rel := range []string{ormRel("orm_shared.go"), ormRel("item_orm.go"), ormRel("order_orm.go")} {
		entry, ok := cs.Files[rel]
		if !ok {
			t.Errorf("%s not recorded in the checksums manifest — forge disown/audit can't see it", rel)
			continue
		}
		if entry.Tier != 1 {
			t.Errorf("%s recorded with tier=%d, want 1 (forge-owned, regenerated every run)", rel, entry.Tier)
		}
		content, err := os.ReadFile(filepath.Join(root, rel))
		if err != nil {
			t.Fatalf("read %s: %v", rel, err)
		}
		if entry.Hash != HashContent(content) {
			t.Errorf("%s manifest hash does not match the on-disk render", rel)
		}
	}
}

// TestGeneratePlanORM_DisownedFileLeftAlone pins the disown contract on
// ORM files: once an entry is disowned, regeneration must never touch
// the user's content — not even with the emitter's force semantics.
func TestGeneratePlanORM_DisownedFileLeftAlone(t *testing.T) {
	root := t.TempDir()
	cs := &FileChecksums{Files: map[string]FileChecksumEntry{}}

	entities := []config.PlanEntity{
		{Name: "Item", Fields: []config.PlanEntityField{
			{Name: "id", Type: "string", PrimaryKey: true, NotNull: true},
		}},
	}
	if err := GeneratePlanORM(root, "example.com/app", "api", entities, cs); err != nil {
		t.Fatalf("GeneratePlanORM: %v", err)
	}

	rel := ormRel("item_orm.go")
	full := filepath.Join(root, rel)

	// User disowns and hand-patches the file.
	userContent := "package db\n\n// hand-patched after disown\n"
	if err := os.WriteFile(full, []byte(userContent), 0o644); err != nil {
		t.Fatal(err)
	}
	entry := cs.Files[rel]
	entry.Disowned = true
	entry.Tier = 2
	cs.Files[rel] = entry

	if err := GeneratePlanORM(root, "example.com/app", "api", entities, cs); err != nil {
		t.Fatalf("GeneratePlanORM after disown: %v", err)
	}
	got, err := os.ReadFile(full)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != userContent {
		t.Error("regenerate overwrote a disowned ORM file — disown not honored")
	}

	// Re-adoption: delete the file, regenerate — pristine render returns,
	// entry back to Tier-1.
	if err := os.Remove(full); err != nil {
		t.Fatal(err)
	}
	if err := GeneratePlanORM(root, "example.com/app", "api", entities, cs); err != nil {
		t.Fatalf("GeneratePlanORM re-adoption: %v", err)
	}
	got, err = os.ReadFile(full)
	if err != nil {
		t.Fatalf("re-adoption did not re-emit %s: %v", rel, err)
	}
	if !strings.Contains(string(got), "Code generated by forge") {
		t.Error("re-adoption should restore the pristine render")
	}
	entry = cs.Files[rel]
	if entry.Disowned || entry.Tier != 1 {
		t.Errorf("re-adopted entry = %+v, want tier=1 disowned=false", entry)
	}
}

// TestGeneratePlanORM_StaleSweepRespectsOwnership pins the stale-file
// sweep: an ORM file for a removed entity is deleted AND pruned from
// the manifest — unless the user disowned it, in which case it's theirs
// and the sweep must not touch it.
func TestGeneratePlanORM_StaleSweepRespectsOwnership(t *testing.T) {
	root := t.TempDir()
	cs := &FileChecksums{Files: map[string]FileChecksumEntry{}}

	idOnly := func(name string) config.PlanEntity {
		return config.PlanEntity{Name: name, Fields: []config.PlanEntityField{
			{Name: "id", Type: "string", PrimaryKey: true, NotNull: true},
		}}
	}
	if err := GeneratePlanORM(root, "example.com/app", "api",
		[]config.PlanEntity{idOnly("Item"), idOnly("Gone"), idOnly("Kept")}, cs); err != nil {
		t.Fatalf("GeneratePlanORM: %v", err)
	}

	// Disown kept_orm.go — the user owns it now.
	keptRel := ormRel("kept_orm.go")
	entry := cs.Files[keptRel]
	entry.Disowned = true
	entry.Tier = 2
	cs.Files[keptRel] = entry

	// Regenerate with Gone and Kept both removed from the entity set.
	if err := GeneratePlanORM(root, "example.com/app", "api",
		[]config.PlanEntity{idOnly("Item")}, cs); err != nil {
		t.Fatalf("GeneratePlanORM after removal: %v", err)
	}

	goneRel := ormRel("gone_orm.go")
	if _, err := os.Stat(filepath.Join(root, goneRel)); !os.IsNotExist(err) {
		t.Errorf("stale %s not removed (stat err=%v)", goneRel, err)
	}
	if _, ok := cs.Files[goneRel]; ok {
		t.Errorf("stale %s still tracked in the manifest after removal", goneRel)
	}

	if _, err := os.Stat(filepath.Join(root, keptRel)); err != nil {
		t.Errorf("disowned %s deleted by the stale sweep — user content destroyed (stat err=%v)", keptRel, err)
	}
	if _, ok := cs.Files[keptRel]; !ok {
		t.Errorf("disowned %s pruned from the manifest — ownership record lost", keptRel)
	}
}

// TestGeneratePlanORM_NilChecksumsTolerated keeps the emitter callable
// without a manifest (tests, legacy call sites): files land on disk,
// nothing is tracked.
func TestGeneratePlanORM_NilChecksumsTolerated(t *testing.T) {
	root := t.TempDir()
	entities := []config.PlanEntity{
		{Name: "Item", Fields: []config.PlanEntityField{
			{Name: "id", Type: "string", PrimaryKey: true, NotNull: true},
		}},
	}
	if err := GeneratePlanORM(root, "example.com/app", "api", entities, nil); err != nil {
		t.Fatalf("GeneratePlanORM with nil cs: %v", err)
	}
	if _, err := os.Stat(filepath.Join(root, ormRel("item_orm.go"))); err != nil {
		t.Errorf("nil-cs generate should still write files: %v", err)
	}
}

// TestGeneratePlanORM_AdoptsUntrackedExistingFiles pins the first-regen
// upgrade path: an ORM file written by pre-manifest forge exists on
// disk but has no checksum entry. The emitter overwrites it with the
// fresh render (the same regenerate-every-run behavior the file always
// had) and adopts it into the manifest as Tier-1, so every FUTURE edit
// is drift-guard-visible and `forge disown` becomes possible.
func TestGeneratePlanORM_AdoptsUntrackedExistingFiles(t *testing.T) {
	root := t.TempDir()
	rel := ormRel("item_orm.go")
	full := filepath.Join(root, rel)
	if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
		t.Fatal(err)
	}
	// Pre-manifest render with a hand-patch in it.
	if err := os.WriteFile(full, []byte("package db\n\n// hand-patch from the pre-manifest era\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	cs := &FileChecksums{Files: map[string]FileChecksumEntry{}}
	entities := []config.PlanEntity{
		{Name: "Item", Fields: []config.PlanEntityField{
			{Name: "id", Type: "string", PrimaryKey: true, NotNull: true},
		}},
	}
	if err := GeneratePlanORM(root, "example.com/app", "api", entities, cs); err != nil {
		t.Fatalf("GeneratePlanORM: %v", err)
	}

	got, err := os.ReadFile(full)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(got), "Code generated by forge") {
		t.Error("untracked stale render should be replaced by the fresh render")
	}
	entry, ok := cs.Files[rel]
	if !ok || entry.Tier != 1 {
		t.Errorf("adopted entry = %+v ok=%v, want tracked tier=1", entry, ok)
	}
}
