package generator

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/reliant-labs/forge/internal/config"
	"github.com/reliant-labs/forge/internal/naming"
)

// GeneratePlanORM writes internal/db/<snake_name>_orm.go for each entity
// defined in the plan. The generated files provide standalone CRUD functions
// and a private scan helper. Because entity types are type aliases (defined
// in internal/db/types.go), we cannot attach methods to them — everything
// is a package-level function.
//
// cs is the project's checksum tracker: every output is recorded as a
// Tier-1 manifest entry so `forge disown` can transfer ownership of an
// ORM file (kalshi fr-4dfef712e9: disown refused on internal/db/*_orm.go
// because nothing registered them) and `forge audit` doesn't see the
// files as orphans. A nil cs is tolerated (files written, not tracked).
func GeneratePlanORM(root, modulePath, serviceName string, entities []config.PlanEntity, cs *FileChecksums) error {
	if len(entities) == 0 {
		return nil
	}

	dbDir := filepath.Join(root, "internal", "db")
	if err := os.MkdirAll(dbDir, 0o755); err != nil {
		return fmt.Errorf("create db directory: %w", err)
	}

	// Clean up stale ORM files for entities that no longer exist —
	// but never a file the user owns (Tier-2 / disowned / legacy-forked
	// entries): a disowned ORM file is the user's content now, and the
	// entity disappearing from the projection doesn't change that.
	// Removed forge-owned files are pruned from the manifest too.
	expectedFiles := make(map[string]bool)
	expectedFiles["orm_shared.go"] = true
	expectedFiles["types.go"] = true
	for _, ent := range entities {
		expectedFiles[naming.ToSnakeCase(ent.Name)+"_orm.go"] = true
	}
	existing, _ := os.ReadDir(dbDir)
	for _, e := range existing {
		if e.IsDir() || !strings.HasSuffix(e.Name(), "_orm.go") || expectedFiles[e.Name()] {
			continue
		}
		rel := filepath.Join("internal", "db", e.Name())
		if cs != nil {
			if entry, ok := cs.Files[rel]; ok && (entry.Tier == 2 || entry.Disowned || entry.Forked) {
				continue // user-owned now — not forge's to delete
			}
		}
		os.Remove(filepath.Join(dbDir, e.Name()))
		if cs != nil {
			delete(cs.Files, rel)
		}
	}

	// Write ormTracer var in a shared file (one per project).
	if err := writeORMFile(root, "orm_shared.go", renderORMShared(), cs); err != nil {
		return fmt.Errorf("write orm shared: %w", err)
	}

	for _, ent := range entities {
		name := naming.ToSnakeCase(ent.Name) + "_orm.go"
		if err := writeORMFile(root, name, renderORMEntity(ent), cs); err != nil {
			return fmt.Errorf("generate ORM for entity %s: %w", ent.Name, err)
		}
	}
	return nil
}

// writeORMFile writes one internal/db output through the Tier-1
// checksum chokepoint: the render is recorded in the manifest, a
// disowned entry is never overwritten (delete-and-regenerate is the
// documented re-adoption path), and force=true keeps the Tier-1
// regenerated-every-run semantics (hand-edit protection is the
// pre-pipeline drift guard's job, same as every other Tier-1 emitter).
func writeORMFile(root, name string, content []byte, cs *FileChecksums) error {
	rel := filepath.Join("internal", "db", name)
	// First-adoption warning: ORM files written by pre-manifest forge
	// are on disk but untracked, so the drift guard can't yet protect a
	// hand-patch in them (kalshi carried exactly such a patch). The
	// overwrite itself matches the old regenerate-every-run behavior —
	// but now it's LOUD, and the manifest entry recorded below makes
	// every future edit guard-visible (and `forge disown` possible).
	if cs != nil {
		if _, tracked := cs.Files[rel]; !tracked {
			if prior, rerr := os.ReadFile(filepath.Join(root, rel)); rerr == nil && !bytes.Equal(prior, content) {
				fmt.Printf("  ⚠️  %s existed untracked and differed from the fresh render — overwriting and adopting it into .forge/checksums.json (recover prior content from git; use `forge disown %s --reason ...` if you need to own it)\n", rel, rel)
			}
		}
	}
	_, err := WriteGeneratedFileTier1(root, rel, content, cs, true)
	return err
}

// renderORMShared renders the shared orm_shared.go with the ormTracer var.
func renderORMShared() []byte {
	var b strings.Builder
	b.WriteString("// Code generated by forge. DO NOT EDIT.\n")
	b.WriteString("// forge-owned: regenerated every run — do not edit (forge disown to take ownership)\n")
	b.WriteString("package db\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"go.opentelemetry.io/otel\"\n")
	b.WriteString(")\n\n")
	b.WriteString("var ormTracer = otel.Tracer(\"orm\")\n")
	return []byte(b.String())
}

// ormField holds the resolved metadata for a single entity field used during
// code generation. This mirrors the information in the protoc-based codegen's
// fieldInfo but is derived directly from PlanEntityField.
type ormField struct {
	planField   config.PlanEntityField
	goName      string // PascalCase Go field name (proto-style)
	columnName  string // snake_case column name
	goType      string // base Go type (notnull variant), e.g. "time.Time"
	ormType     string // orm.TypeXxx constant name
	isTimestamp bool
	isArray     bool
	isPK        bool
	isTenantKey bool
	notNull     bool
	unique      bool
	references  string
	nullable    bool // nullable column → pointer struct field
}

// structGoType is the Go type of the field on the generated entity
// struct: the base type, pointered when the column is nullable
// (arrays/bytes are reference types already and stay bare).
func (f ormField) structGoType() string {
	if f.nullable && !f.isArray && f.goType != "[]byte" {
		return "*" + f.goType
	}
	return f.goType
}

func renderORMEntity(ent config.PlanEntity) []byte {
	msgName := ent.Name
	tableName := ent.TableName
	if tableName == "" {
		tableName = naming.Pluralize(naming.ToSnakeCase(ent.Name))
	}

	// Build fields list including auto-generated timestamp/soft-delete fields.
	fields := resolveORMFields(ent)

	// Identify special fields.
	var pkField *ormField
	var tenantField *ormField
	for i := range fields {
		if fields[i].isPK {
			pkField = &fields[i]
		}
		if fields[i].isTenantKey {
			tenantField = &fields[i]
		}
	}

	pkCol := "id"
	pkGoType := "string"
	if pkField != nil {
		pkCol = pkField.columnName
		pkGoType = pkField.goType
	}

	hasTenant := tenantField != nil
	// The time import is needed for time.Time struct fields AND for
	// stamping managed timestamps — including legacy TEXT columns, whose
	// stamps are time.Now()-derived RFC3339Nano strings (kalshi
	// fr-3fba9166ba: the old emitter stamped without importing time,
	// `undefined: time`).
	needsTime := false
	for _, f := range fields {
		if f.isTimestamp {
			needsTime = true
			break
		}
	}
	if ent.Timestamps {
		for _, f := range fields {
			if isManagedTimestampColumn(f.columnName) && stampableTimestamp(f) {
				needsTime = true
				break
			}
		}
	}

	// strings.Join appears in Create's INSERT (unless the only column is
	// a server-allocated integer PK) and in the UPDATE SET builders
	// (unless there are no updatable columns).
	needsStrings := false
	for _, f := range fields {
		if !f.isPK || !isIntegerGoType(f.goType) {
			needsStrings = true // participates in the INSERT column list
			break
		}
	}
	if !needsStrings {
		for _, f := range fields {
			if !excludedFromSet(f, ent.Timestamps) {
				needsStrings = true
				break
			}
		}
	}

	var b strings.Builder

	// Header
	b.WriteString("// Code generated by forge. DO NOT EDIT.\n")
	b.WriteString("// forge-owned: regenerated every run — do not edit (forge disown to take ownership)\n")
	b.WriteString("package db\n\n")

	// Imports
	writeORMImports(&b, needsTime, needsStrings, pkField != nil && pkField.goType == "string")

	// The entity struct: a projection of the APPLIED schema.
	writeEntityStruct(&b, msgName, tableName, fields)

	// Field name constants
	fmt.Fprintf(&b, "// Field name constants for %s.\n", msgName)
	fmt.Fprintf(&b, "const %sTableName = %q\n\n", msgName, tableName)
	b.WriteString("const (\n")
	for _, f := range fields {
		fmt.Fprintf(&b, "\t%sField%s = %q\n", msgName, f.goName, f.columnName)
	}
	b.WriteString(")\n\n")

	// Column list helper. EXPORTED: this is the per-entity column
	// allowlist — handler shims hand it to pkg/crud so user-supplied
	// order_by/filter columns are validated against declared columns
	// (identifier-shape validation alone let `order_by=password_hash`
	// through as a silent no-op).
	colsVar := msgName + "Columns"
	fmt.Fprintf(&b, "// %s is the ordered list of declared columns for %s.\n", colsVar, msgName)
	fmt.Fprintf(&b, "// It doubles as the column allowlist for user-supplied order_by/filter\n")
	fmt.Fprintf(&b, "// input (see forge/pkg/crud).\n")
	fmt.Fprintf(&b, "var %s = []string{\n", colsVar)
	for _, f := range fields {
		fmt.Fprintf(&b, "\t%q,\n", f.columnName)
	}
	b.WriteString("}\n\n")

	// scan function
	writeORMScanFunc(&b, msgName, colsVar, fields)

	// CRUD functions
	writeORMCreate(&b, msgName, tableName, fields, hasTenant, tenantField, pkField, ent.Timestamps)
	writeORMGetByID(&b, msgName, tableName, colsVar, pkCol, pkGoType, hasTenant, ent.SoftDelete)
	writeORMList(&b, msgName, tableName, colsVar, hasTenant, ent.SoftDelete, tenantField)
	writeORMCount(&b, msgName, tableName, hasTenant, ent.SoftDelete, tenantField)
	if ent.SoftDelete {
		writeORMListAll(&b, msgName, tableName, colsVar, hasTenant, tenantField)
	}
	writeORMUpdate(&b, msgName, tableName, colsVar, pkCol, fields, hasTenant, ent.SoftDelete, tenantField, pkField, ent.Timestamps)
	writeORMUpdateMasked(&b, msgName, tableName, pkCol, fields, hasTenant, ent.SoftDelete, tenantField, pkField, ent.Timestamps)
	writeORMDelete(&b, msgName, tableName, pkCol, pkGoType, fields, hasTenant, ent.SoftDelete, tenantField)

	return []byte(b.String())
}

func writeORMImports(b *strings.Builder, needsTime, needsStrings, stringPK bool) {
	b.WriteString("import (\n")
	b.WriteString("\t\"context\"\n")
	b.WriteString("\t\"fmt\"\n")
	if needsStrings {
		b.WriteString("\t\"strings\"\n")
	}
	if needsTime {
		b.WriteString("\t\"time\"\n")
	}
	b.WriteString("\n")
	if stringPK {
		// String PKs are generated at the Create chokepoint.
		b.WriteString("\t\"github.com/oklog/ulid/v2\"\n")
	}
	b.WriteString("\t\"github.com/reliant-labs/forge/pkg/orm\"\n")
	b.WriteString("\t\"go.opentelemetry.io/otel/attribute\"\n")
	b.WriteString("\t\"go.opentelemetry.io/otel/codes\"\n")
	b.WriteString("\t\"go.opentelemetry.io/otel/trace\"\n")
	b.WriteString(")\n\n")
}

// writeEntityStruct emits the entity row type. Field types come from
// the APPLIED schema's columns: time.Time for timestamps (never
// timestamppb — the wire seam converts), pointers for nullable
// columns, native slices for array columns.
func writeEntityStruct(b *strings.Builder, msgName, tableName string, fields []ormField) {
	fmt.Fprintf(b, "// %s is the %s row type — a projection of the APPLIED schema\n", msgName, tableName)
	b.WriteString("// (db/migrations). Evolve it by writing migrations; `forge generate`\n")
	b.WriteString("// regenerates this struct from the introspected schema.\n")
	fmt.Fprintf(b, "type %s struct {\n", msgName)
	for _, f := range fields {
		fmt.Fprintf(b, "\t%s %s\n", f.goName, f.structGoType())
	}
	b.WriteString("}\n\n")
}

// writeORMScanFunc writes a standalone scan<Entity> function.
//
// Time columns scan through orm.NullTime (drivers without parsetime
// return TEXT timestamps); array columns scan through the dual-format
// orm.StringArray/Int64Array scanners. Everything else — including
// nullable pointer fields — scans directly into the struct field.
func writeORMScanFunc(b *strings.Builder, msgName, _ string, fields []ormField) {
	fmt.Fprintf(b, "// scan%s scans a database row into a %s.\n", msgName, msgName)
	fmt.Fprintf(b, "func scan%s(scanner interface{ Scan(...interface{}) error }) (*%s, error) {\n", msgName, msgName)
	fmt.Fprintf(b, "\tentity := &%s{}\n", msgName)

	needsTemp := func(f ormField) bool { return f.isTimestamp || f.isArray }

	hasTemps := false
	for _, f := range fields {
		if needsTemp(f) {
			hasTemps = true
			break
		}
	}
	if hasTemps {
		b.WriteString("\tvar (\n")
		for _, f := range fields {
			switch {
			case f.isTimestamp:
				fmt.Fprintf(b, "\t\tdb%s orm.NullTime\n", f.goName)
			case f.isArray:
				fmt.Fprintf(b, "\t\tdb%s %s\n", f.goName, arrayScannerType(f))
			}
		}
		b.WriteString("\t)\n\n")
	}

	// Scan call
	b.WriteString("\terr := scanner.Scan(\n")
	for _, f := range fields {
		if needsTemp(f) {
			fmt.Fprintf(b, "\t\t&db%s,\n", f.goName)
		} else {
			fmt.Fprintf(b, "\t\t&entity.%s,\n", f.goName)
		}
	}
	b.WriteString("\t)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn nil, err\n")
	b.WriteString("\t}\n\n")

	// Assignments from temps.
	for _, f := range fields {
		switch {
		case f.isTimestamp && f.nullable:
			fmt.Fprintf(b, "\tif db%s.Valid {\n", f.goName)
			fmt.Fprintf(b, "\t\tt%s := db%s.Time\n", f.goName, f.goName)
			fmt.Fprintf(b, "\t\tentity.%s = &t%s\n", f.goName, f.goName)
			b.WriteString("\t}\n")
		case f.isTimestamp:
			fmt.Fprintf(b, "\tentity.%s = db%s.Time\n", f.goName, f.goName)
		case f.isArray:
			fmt.Fprintf(b, "\tentity.%s = %s(db%s)\n", f.goName, f.goType, f.goName)
		}
	}

	b.WriteString("\n\treturn entity, nil\n")
	b.WriteString("}\n\n")
}

// arrayScannerType returns the orm scanner type for an array field.
func arrayScannerType(f ormField) string {
	if f.goType == "[]int64" {
		return "orm.Int64Array"
	}
	return "orm.StringArray"
}

// valueExpr returns the expression used for a field in INSERT/UPDATE
// parameter lists. Arrays go through the dialect-aware encoder.
func valueExpr(f ormField) string {
	if f.isArray {
		return fmt.Sprintf("orm.ArrayValue(dialect, msg.%s)", f.goName)
	}
	return "msg." + f.goName
}

// isIntegerGoType reports whether the projected Go type is an integer —
// the PK kinds that are server-allocated (BIGSERIAL / SERIAL / rowid).
func isIntegerGoType(goType string) bool {
	switch goType {
	case "int32", "int64", "uint32", "uint64":
		return true
	}
	return false
}

// excludedFromSet reports whether a column is never part of an UPDATE's
// SET clause: the PK, the tenant key, deleted_at (soft-delete
// machinery), and — when timestamps are managed — created_at (immutable
// after create; round-tripping it through the request would let an
// update NULL or rewrite history).
func excludedFromSet(f ormField, timestamps bool) bool {
	if f.isPK || f.columnName == "deleted_at" || f.isTenantKey {
		return true
	}
	return timestamps && f.columnName == "created_at"
}

func writeORMCreate(b *strings.Builder, msgName, tableName string, fields []ormField, hasTenant bool, tenantField *ormField, pkField *ormField, timestamps bool) {
	stringPK := pkField != nil && pkField.goType == "string"
	intPK := pkField != nil && isIntegerGoType(pkField.goType)

	// Integer PKs are server-allocated (BIGSERIAL / SERIAL / sqlite
	// rowid): the PK column is omitted from the INSERT and the
	// database-assigned value is scanned back into msg (kalshi
	// fr-fd061aed2b: inserting msg.<PK>=0 verbatim made every BIGSERIAL
	// Create collide on id 0, so every writer routed around the ORM).
	insertFields := fields
	if intPK {
		insertFields = make([]ormField, 0, len(fields)-1)
		for _, f := range fields {
			if f.isPK {
				continue
			}
			insertFields = append(insertFields, f)
		}
	}

	fmt.Fprintf(b, "// Create%s inserts a new %s row into the database.\n", msgName, msgName)
	b.WriteString("//\n")
	b.WriteString("// Create is a plain INSERT — never an upsert. Chokepoint invariants:\n")
	if stringPK {
		fmt.Fprintf(b, "//   - msg.%s is generated (ULID) when the caller left it empty;\n", pkField.goName)
	}
	if intPK {
		fmt.Fprintf(b, "//   - msg.%s is SERVER-ALLOCATED: the column is omitted from the\n", pkField.goName)
		b.WriteString("//     INSERT and the database-assigned value is scanned back into\n")
		fmt.Fprintf(b, "//     msg.%s (RETURNING where the dialect supports it, LastInsertId\n", pkField.goName)
		b.WriteString("//     otherwise). Any caller-provided value is ignored;\n")
	}
	if timestamps {
		b.WriteString("//   - created_at/updated_at are stamped here (timestamps: true);\n")
	}
	b.WriteString("// a duplicate primary key is therefore a real error, not a silent overwrite.\n")
	if hasTenant {
		fmt.Fprintf(b, "func Create%s(ctx context.Context, db orm.Context, msg *%s, tenantID string) error {\n", msgName, msgName)
	} else {
		fmt.Fprintf(b, "func Create%s(ctx context.Context, db orm.Context, msg *%s) error {\n", msgName, msgName)
	}
	fmt.Fprintf(b, "\tctx, span := ormTracer.Start(ctx, \"orm.Create%s\",\n", msgName)
	fmt.Fprintf(b, "\t\ttrace.WithAttributes(attribute.String(\"table\", %q)))\n", tableName)
	b.WriteString("\tdefer span.End()\n\n")

	if hasTenant && tenantField != nil {
		b.WriteString("\t// Enforce tenant isolation: set tenant field from caller.\n")
		fmt.Fprintf(b, "\tmsg.%s = tenantID\n\n", tenantField.goName)
	}

	if stringPK {
		fmt.Fprintf(b, "\tif msg.%s == \"\" {\n", pkField.goName)
		fmt.Fprintf(b, "\t\tmsg.%s = ulid.Make().String()\n", pkField.goName)
		b.WriteString("\t}\n")
	}
	if timestamps {
		writeManagedCreateTimestamps(b, fields)
	}
	if stringPK || timestamps {
		b.WriteString("\n")
	}

	// Build column list and placeholders for INSERT
	b.WriteString("\tdialect := db.Dialect()\n")

	if len(insertFields) == 0 {
		// Server-allocated PK and nothing else: every column comes from
		// the database.
		b.WriteString("\tquery := fmt.Sprintf(\"INSERT INTO %s DEFAULT VALUES\", dialect.QuoteIdentifier(")
		fmt.Fprintf(b, "%q))\n", tableName)
		b.WriteString("\tvar values []any\n\n")
	} else {
		// Build columns and values
		b.WriteString("\tcolumns := []string{\n")
		for _, f := range insertFields {
			fmt.Fprintf(b, "\t\tdialect.QuoteIdentifier(%q),\n", f.columnName)
		}
		b.WriteString("\t}\n")

		b.WriteString("\tplaceholders := make([]string, len(columns))\n")
		b.WriteString("\tfor i := range columns {\n")
		b.WriteString("\t\tplaceholders[i] = dialect.Placeholder(i)\n")
		b.WriteString("\t}\n\n")

		// Build values slice
		b.WriteString("\tvalues := []any{\n")
		for _, f := range insertFields {
			fmt.Fprintf(b, "\t\t%s,\n", valueExpr(f))
		}
		b.WriteString("\t}\n\n")

		b.WriteString("\tquery := fmt.Sprintf(\"INSERT INTO %s (%s) VALUES (%s)\",\n")
		fmt.Fprintf(b, "\t\tdialect.QuoteIdentifier(%q),\n", tableName)
		b.WriteString("\t\tstrings.Join(columns, \", \"),\n")
		b.WriteString("\t\tstrings.Join(placeholders, \", \"),\n")
		b.WriteString("\t)\n\n")
	}

	if intPK {
		writeORMCreateIntPKExec(b, tableName, pkField)
	} else {
		b.WriteString("\t_, err := db.Exec(ctx, query, values...)\n")
		b.WriteString("\tif err != nil {\n")
		b.WriteString("\t\tspan.RecordError(err)\n")
		b.WriteString("\t\tspan.SetStatus(codes.Error, err.Error())\n")
		fmt.Fprintf(b, "\t\treturn fmt.Errorf(\"create %s: %%w\", err)\n", tableName)
		b.WriteString("\t}\n")
		b.WriteString("\treturn nil\n")
	}
	b.WriteString("}\n\n")
}

// writeORMCreateIntPKExec emits the execute-and-scan-back tail of
// Create<Entity> for server-allocated integer PKs: RETURNING on
// dialects that support it (postgres), Exec + LastInsertId otherwise
// (sqlite).
func writeORMCreateIntPKExec(b *strings.Builder, tableName string, pkField *ormField) {
	b.WriteString("\t// Scan the server-allocated id back into msg.\n")
	b.WriteString("\tif dialect.SupportsReturning() {\n")
	fmt.Fprintf(b, "\t\trow := db.QueryRow(ctx, query+\" RETURNING \"+dialect.QuoteIdentifier(%q), values...)\n", pkField.columnName)
	fmt.Fprintf(b, "\t\tif err := row.Scan(&msg.%s); err != nil {\n", pkField.goName)
	b.WriteString("\t\t\tspan.RecordError(err)\n")
	b.WriteString("\t\t\tspan.SetStatus(codes.Error, err.Error())\n")
	fmt.Fprintf(b, "\t\t\treturn fmt.Errorf(\"create %s: %%w\", err)\n", tableName)
	b.WriteString("\t\t}\n")
	b.WriteString("\t\treturn nil\n")
	b.WriteString("\t}\n\n")

	b.WriteString("\tres, err := db.Exec(ctx, query, values...)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\tspan.RecordError(err)\n")
	b.WriteString("\t\tspan.SetStatus(codes.Error, err.Error())\n")
	fmt.Fprintf(b, "\t\treturn fmt.Errorf(\"create %s: %%w\", err)\n", tableName)
	b.WriteString("\t}\n")
	b.WriteString("\tlastID, err := res.LastInsertId()\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\tspan.RecordError(err)\n")
	b.WriteString("\t\tspan.SetStatus(codes.Error, err.Error())\n")
	fmt.Fprintf(b, "\t\treturn fmt.Errorf(\"create %s: read server-allocated id: %%w\", err)\n", tableName)
	b.WriteString("\t}\n")
	if pkField.goType == "int64" {
		fmt.Fprintf(b, "\tmsg.%s = lastID\n", pkField.goName)
	} else {
		fmt.Fprintf(b, "\tmsg.%s = %s(lastID)\n", pkField.goName, pkField.goType)
	}
	b.WriteString("\treturn nil\n")
}

// ── managed-timestamp stamping (type-aware) ────────────────────────────
//
// The entity struct is a projection of the APPLIED schema, so managed
// created_at/updated_at columns are whatever type the migration
// declared: TIMESTAMPTZ → time.Time, legacy TEXT → string, plus the
// nullable pointer variants. Stamping must branch on the projected Go
// type — the pre-M3 emitter assumed time.Time unconditionally and
// produced non-compiling output for TEXT columns (kalshi
// fr-3fba9166ba: `undefined: time`, `msg.CreatedAt.IsZero undefined
// (type string)`) and for nullable pointer columns.

// isManagedTimestampColumn reports whether the column is one of the
// timestamps:true managed pair.
func isManagedTimestampColumn(col string) bool {
	return col == "created_at" || col == "updated_at"
}

// stampableTimestamp reports whether the emitter knows how to stamp the
// column's projected Go type. time.Time gets the instant itself; string
// gets the RFC3339Nano rendering. Anything else (e.g. an epoch INTEGER)
// is left alone — emitting a wrong-typed stamp would be a compile
// error, and guessing an encoding would corrupt data.
func stampableTimestamp(f ormField) bool {
	return f.goType == "time.Time" || f.goType == "string"
}

// stampValueExpr renders the stamp value for f given nowExpr, a Go
// expression of type time.Time. Callers must have checked
// stampableTimestamp first.
func stampValueExpr(f ormField, nowExpr string) string {
	if f.goType == "string" {
		return nowExpr + ".Format(time.RFC3339Nano)"
	}
	return nowExpr
}

// isPointerStructField reports whether the field projects to a pointer
// on the entity struct (nullable column).
func isPointerStructField(f ormField) bool {
	return strings.HasPrefix(f.structGoType(), "*")
}

// stampEmptyCond renders the "caller left it unset" condition used to
// guard the created_at stamp so caller-provided values win.
func stampEmptyCond(f ormField) string {
	if isPointerStructField(f) {
		return fmt.Sprintf("msg.%s == nil", f.goName)
	}
	if f.goType == "string" {
		return fmt.Sprintf("msg.%s == %q", f.goName, "")
	}
	return fmt.Sprintf("msg.%s.IsZero()", f.goName)
}

// writeStampAssign emits `msg.<field> = <stamp>` in the field's
// projected type, routing pointer fields through an addressable local.
func writeStampAssign(b *strings.Builder, f ormField, nowExpr, indent string) {
	expr := stampValueExpr(f, nowExpr)
	if isPointerStructField(f) {
		fmt.Fprintf(b, "%sstamp%s := %s\n", indent, f.goName, expr)
		fmt.Fprintf(b, "%smsg.%s = &stamp%s\n", indent, f.goName, f.goName)
		return
	}
	fmt.Fprintf(b, "%smsg.%s = %s\n", indent, f.goName, expr)
}

// writeManagedCreateTimestamps emits the created_at/updated_at stamping
// for entities with timestamps:true. Only fields that actually exist on
// the entity AND have a stampable projected type are touched
// (resolveORMFields guarantees the fields exist for timestamps:true,
// whether declared or auto-added).
func writeManagedCreateTimestamps(b *strings.Builder, fields []ormField) {
	var createdAt, updatedAt *ormField
	for i := range fields {
		f := &fields[i]
		if !stampableTimestamp(*f) {
			continue
		}
		switch f.columnName {
		case "created_at":
			createdAt = f
		case "updated_at":
			updatedAt = f
		}
	}
	if createdAt == nil && updatedAt == nil {
		return
	}
	b.WriteString("\tnow := time.Now().UTC()\n")
	if createdAt != nil {
		fmt.Fprintf(b, "\tif %s {\n", stampEmptyCond(*createdAt))
		writeStampAssign(b, *createdAt, "now", "\t\t")
		b.WriteString("\t}\n")
	}
	if updatedAt != nil {
		writeStampAssign(b, *updatedAt, "now", "\t")
	}
}

// writeUpdatedAtStamp emits the standalone updated_at re-stamp used by
// Update/UpdateMasked. Returns false when the column is missing or not
// stampable (caller then skips the stamp entirely).
func writeUpdatedAtStamp(b *strings.Builder, fields []ormField, indent string) bool {
	for _, f := range fields {
		if f.columnName != "updated_at" {
			continue
		}
		if !stampableTimestamp(f) {
			return false
		}
		writeStampAssign(b, f, "time.Now().UTC()", indent)
		return true
	}
	return false
}

func writeORMGetByID(b *strings.Builder, msgName, tableName, colsVar, pkCol, pkGoType string, hasTenant, softDelete bool) {
	fmt.Fprintf(b, "// Get%sByID retrieves a %s by its primary key.\n", msgName, msgName)
	b.WriteString("//\n")
	b.WriteString("// A missing row satisfies errors.Is(err, orm.ErrNoRows) so callers (and\n")
	b.WriteString("// forge/pkg/crud) can map it to NotFound without string matching.\n")
	if hasTenant {
		fmt.Fprintf(b, "func Get%sByID(ctx context.Context, db orm.Context, id %s, tenantID string) (*%s, error) {\n", msgName, pkGoType, msgName)
	} else {
		fmt.Fprintf(b, "func Get%sByID(ctx context.Context, db orm.Context, id %s) (*%s, error) {\n", msgName, pkGoType, msgName)
	}
	fmt.Fprintf(b, "\tctx, span := ormTracer.Start(ctx, \"orm.Get%sByID\",\n", msgName)
	b.WriteString("\t\ttrace.WithAttributes(\n")
	fmt.Fprintf(b, "\t\t\tattribute.String(\"table\", %q),\n", tableName)
	b.WriteString("\t\t\tattribute.String(\"id\", fmt.Sprint(id)),\n")
	b.WriteString("\t\t))\n")
	b.WriteString("\tdefer span.End()\n\n")

	if softDelete || hasTenant {
		// Use List with filters for soft-delete and/or tenant scoping.
		if hasTenant {
			fmt.Fprintf(b, "\tresults, err := List%s(ctx, db, tenantID, orm.WhereEq(%q, id), orm.WithLimit(1))\n", msgName, pkCol)
		} else {
			fmt.Fprintf(b, "\tresults, err := List%s(ctx, db, orm.WhereEq(%q, id), orm.WithLimit(1))\n", msgName, pkCol)
		}
		b.WriteString("\tif err != nil {\n")
		b.WriteString("\t\tspan.RecordError(err)\n")
		b.WriteString("\t\tspan.SetStatus(codes.Error, err.Error())\n")
		b.WriteString("\t\treturn nil, err\n")
		b.WriteString("\t}\n")
		b.WriteString("\tif len(results) == 0 {\n")
		fmt.Fprintf(b, "\t\treturn nil, fmt.Errorf(\"get %s by id: %%w\", orm.ErrNoRows)\n", tableName)
		b.WriteString("\t}\n")
		b.WriteString("\treturn results[0], nil\n")
	} else {
		// Simple case: direct query by PK.
		fmt.Fprintf(b, "\tqb := orm.NewQueryBuilder(db, %q, %s)\n", tableName, colsVar)
		fmt.Fprintf(b, "\tqb.Where(%q, orm.Eq, id)\n", pkCol)
		b.WriteString("\tqb.Limit(1)\n")
		b.WriteString("\tquery, args := qb.Build()\n")
		b.WriteString("\trow := db.QueryRow(ctx, query, args...)\n")
		fmt.Fprintf(b, "\tentity, err := scan%s(row)\n", msgName)
		b.WriteString("\tif err != nil {\n")
		b.WriteString("\t\tspan.RecordError(err)\n")
		b.WriteString("\t\tspan.SetStatus(codes.Error, err.Error())\n")
		fmt.Fprintf(b, "\t\treturn nil, fmt.Errorf(\"get %s by id: %%w\", err)\n", tableName)
		b.WriteString("\t}\n")
		b.WriteString("\treturn entity, nil\n")
	}
	b.WriteString("}\n\n")
}

func writeORMList(b *strings.Builder, msgName, tableName, colsVar string, hasTenant, softDelete bool, tenantField *ormField) {
	fmt.Fprintf(b, "// List%s retrieves %s rows with optional filtering.\n", msgName, msgName)
	if hasTenant {
		fmt.Fprintf(b, "func List%s(ctx context.Context, db orm.Context, tenantID string, opts ...orm.QueryOption) ([]*%s, error) {\n", msgName, msgName)
	} else {
		fmt.Fprintf(b, "func List%s(ctx context.Context, db orm.Context, opts ...orm.QueryOption) ([]*%s, error) {\n", msgName, msgName)
	}
	fmt.Fprintf(b, "\tctx, span := ormTracer.Start(ctx, \"orm.List%s\",\n", msgName)
	fmt.Fprintf(b, "\t\ttrace.WithAttributes(attribute.String(\"table\", %q)))\n", tableName)
	b.WriteString("\tdefer span.End()\n\n")

	if hasTenant && tenantField != nil {
		b.WriteString("\t// Prepend tenant isolation filter.\n")
		fmt.Fprintf(b, "\topts = append([]orm.QueryOption{orm.WhereEq(%q, tenantID)}, opts...)\n\n", tenantField.columnName)
	}

	if softDelete {
		b.WriteString("\t// Prepend soft-delete filter.\n")
		b.WriteString("\topts = append([]orm.QueryOption{orm.WhereIsNull(\"deleted_at\")}, opts...)\n\n")
	}

	fmt.Fprintf(b, "\tqb := orm.NewQueryBuilder(db, %q, %s)\n", tableName, colsVar)
	b.WriteString("\tfor _, opt := range opts {\n")
	b.WriteString("\t\topt(qb)\n")
	b.WriteString("\t}\n\n")

	b.WriteString("\trows, err := qb.Execute(ctx)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\tspan.RecordError(err)\n")
	b.WriteString("\t\tspan.SetStatus(codes.Error, err.Error())\n")
	fmt.Fprintf(b, "\t\treturn nil, fmt.Errorf(\"list %s: %%w\", err)\n", tableName)
	b.WriteString("\t}\n")
	b.WriteString("\tdefer rows.Close()\n\n")

	b.WriteString("\tvar results []*" + msgName + "\n")
	b.WriteString("\tfor rows.Next() {\n")
	fmt.Fprintf(b, "\t\tentity, err := scan%s(rows)\n", msgName)
	b.WriteString("\t\tif err != nil {\n")
	b.WriteString("\t\t\tspan.RecordError(err)\n")
	b.WriteString("\t\t\tspan.SetStatus(codes.Error, err.Error())\n")
	b.WriteString("\t\t\treturn nil, err\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\tresults = append(results, entity)\n")
	b.WriteString("\t}\n")
	b.WriteString("\tif err := rows.Err(); err != nil {\n")
	b.WriteString("\t\tspan.RecordError(err)\n")
	b.WriteString("\t\tspan.SetStatus(codes.Error, err.Error())\n")
	fmt.Fprintf(b, "\t\treturn nil, fmt.Errorf(\"list %s: %%w\", err)\n", tableName)
	b.WriteString("\t}\n")
	b.WriteString("\treturn results, nil\n")
	b.WriteString("}\n\n")
}

func writeORMCount(b *strings.Builder, msgName, tableName string, hasTenant, softDelete bool, tenantField *ormField) {
	fmt.Fprintf(b, "// Count%s returns the number of matching %s rows.\n", msgName, msgName)
	if hasTenant {
		fmt.Fprintf(b, "func Count%s(ctx context.Context, db orm.Context, tenantID string, opts ...orm.QueryOption) (int64, error) {\n", msgName)
	} else {
		fmt.Fprintf(b, "func Count%s(ctx context.Context, db orm.Context, opts ...orm.QueryOption) (int64, error) {\n", msgName)
	}
	fmt.Fprintf(b, "\tctx, span := ormTracer.Start(ctx, \"orm.Count%s\",\n", msgName)
	fmt.Fprintf(b, "\t\ttrace.WithAttributes(attribute.String(\"table\", %q)))\n", tableName)
	b.WriteString("\tdefer span.End()\n\n")

	if hasTenant && tenantField != nil {
		fmt.Fprintf(b, "\topts = append([]orm.QueryOption{orm.WhereEq(%q, tenantID)}, opts...)\n\n", tenantField.columnName)
	}

	if softDelete {
		b.WriteString("\topts = append([]orm.QueryOption{orm.WhereIsNull(\"deleted_at\")}, opts...)\n\n")
	}

	fmt.Fprintf(b, "\tqb := orm.NewQueryBuilder(db, %q, []string{\"COUNT(*)\"})\n", tableName)
	b.WriteString("\tfor _, opt := range opts {\n")
	b.WriteString("\t\topt(qb)\n")
	b.WriteString("\t}\n\n")

	b.WriteString("\tquery, args := qb.Build()\n")
	b.WriteString("\trow := db.QueryRow(ctx, query, args...)\n\n")
	b.WriteString("\tvar count int64\n")
	b.WriteString("\tif err := row.Scan(&count); err != nil {\n")
	b.WriteString("\t\tspan.RecordError(err)\n")
	b.WriteString("\t\tspan.SetStatus(codes.Error, err.Error())\n")
	fmt.Fprintf(b, "\t\treturn 0, fmt.Errorf(\"count %s: %%w\", err)\n", tableName)
	b.WriteString("\t}\n")
	b.WriteString("\treturn count, nil\n")
	b.WriteString("}\n\n")
}

func writeORMListAll(b *strings.Builder, msgName, tableName, colsVar string, hasTenant bool, tenantField *ormField) {
	fmt.Fprintf(b, "// ListAll%s retrieves all %s rows including soft-deleted ones.\n", msgName, msgName)
	if hasTenant {
		fmt.Fprintf(b, "func ListAll%s(ctx context.Context, db orm.Context, tenantID string, opts ...orm.QueryOption) ([]*%s, error) {\n", msgName, msgName)
	} else {
		fmt.Fprintf(b, "func ListAll%s(ctx context.Context, db orm.Context, opts ...orm.QueryOption) ([]*%s, error) {\n", msgName, msgName)
	}
	fmt.Fprintf(b, "\tctx, span := ormTracer.Start(ctx, \"orm.ListAll%s\",\n", msgName)
	fmt.Fprintf(b, "\t\ttrace.WithAttributes(attribute.String(\"table\", %q)))\n", tableName)
	b.WriteString("\tdefer span.End()\n\n")

	if hasTenant && tenantField != nil {
		b.WriteString("\t// Tenant isolation still applies even for ListAll (bypasses soft-delete only).\n")
		fmt.Fprintf(b, "\topts = append([]orm.QueryOption{orm.WhereEq(%q, tenantID)}, opts...)\n\n", tenantField.columnName)
	}

	fmt.Fprintf(b, "\tqb := orm.NewQueryBuilder(db, %q, %s)\n", tableName, colsVar)
	b.WriteString("\tfor _, opt := range opts {\n")
	b.WriteString("\t\topt(qb)\n")
	b.WriteString("\t}\n\n")

	b.WriteString("\trows, err := qb.Execute(ctx)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\tspan.RecordError(err)\n")
	b.WriteString("\t\tspan.SetStatus(codes.Error, err.Error())\n")
	fmt.Fprintf(b, "\t\treturn nil, fmt.Errorf(\"list all %s: %%w\", err)\n", tableName)
	b.WriteString("\t}\n")
	b.WriteString("\tdefer rows.Close()\n\n")

	b.WriteString("\tvar results []*" + msgName + "\n")
	b.WriteString("\tfor rows.Next() {\n")
	fmt.Fprintf(b, "\t\tentity, err := scan%s(rows)\n", msgName)
	b.WriteString("\t\tif err != nil {\n")
	b.WriteString("\t\t\treturn nil, err\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\tresults = append(results, entity)\n")
	b.WriteString("\t}\n")
	b.WriteString("\tif err := rows.Err(); err != nil {\n")
	fmt.Fprintf(b, "\t\treturn nil, fmt.Errorf(\"list all %s: %%w\", err)\n", tableName)
	b.WriteString("\t}\n")
	b.WriteString("\treturn results, nil\n")
	b.WriteString("}\n\n")
}

func writeORMUpdate(b *strings.Builder, msgName, tableName, _, pkCol string, fields []ormField, hasTenant, softDelete bool, tenantField *ormField, pkField *ormField, timestamps bool) {
	// See excludedFromSet for what never reaches the SET clause.
	excludeFromSet := func(f ormField) bool { return excludedFromSet(f, timestamps) }

	// Count updatable fields.
	updatableCount := 0
	for _, f := range fields {
		if excludeFromSet(f) {
			continue
		}
		updatableCount++
	}

	// If there are no updatable fields, generate a no-op function.
	if updatableCount == 0 {
		fmt.Fprintf(b, "// Update%s is a no-op because %s has no updatable fields.\n", msgName, msgName)
		if hasTenant {
			fmt.Fprintf(b, "func Update%s(_ context.Context, _ orm.Context, _ *%s, _ string) error {\n", msgName, msgName)
		} else {
			fmt.Fprintf(b, "func Update%s(_ context.Context, _ orm.Context, _ *%s) error {\n", msgName, msgName)
		}
		b.WriteString("\treturn nil // no updatable fields\n")
		b.WriteString("}\n\n")
		return
	}

	fmt.Fprintf(b, "// Update%s updates an existing %s by its primary key.\n", msgName, msgName)
	if timestamps {
		b.WriteString("//\n")
		b.WriteString("// updated_at is stamped here (timestamps: true); created_at is immutable\n")
		b.WriteString("// and excluded from the SET clause.\n")
	}
	if hasTenant {
		fmt.Fprintf(b, "func Update%s(ctx context.Context, db orm.Context, msg *%s, tenantID string) error {\n", msgName, msgName)
	} else {
		fmt.Fprintf(b, "func Update%s(ctx context.Context, db orm.Context, msg *%s) error {\n", msgName, msgName)
	}
	fmt.Fprintf(b, "\tctx, span := ormTracer.Start(ctx, \"orm.Update%s\",\n", msgName)
	fmt.Fprintf(b, "\t\ttrace.WithAttributes(attribute.String(\"table\", %q)))\n", tableName)
	b.WriteString("\tdefer span.End()\n\n")

	if timestamps {
		if writeUpdatedAtStamp(b, fields, "\t") {
			b.WriteString("\n")
		}
	}

	b.WriteString("\tdialect := db.Dialect()\n\n")

	// Build SET clause (see excludeFromSet for what stays out).
	type setCol struct {
		field ormField
		idx   int
	}
	var setCols []setCol
	for i, f := range fields {
		if excludeFromSet(f) {
			continue
		}
		setCols = append(setCols, setCol{field: f, idx: i})
	}

	b.WriteString("\tsetParts := []string{\n")
	for phIdx, sc := range setCols {
		fmt.Fprintf(b, "\t\tfmt.Sprintf(\"%%s = %%s\", dialect.QuoteIdentifier(%q), dialect.Placeholder(%d)),\n", sc.field.columnName, phIdx)
	}
	b.WriteString("\t}\n\n")

	// Build values for SET clause
	b.WriteString("\targs := []any{\n")
	for _, sc := range setCols {
		fmt.Fprintf(b, "\t\t%s,\n", valueExpr(sc.field))
	}
	b.WriteString("\t}\n\n")

	pkPlaceholderIdx := len(setCols)

	if softDelete && hasTenant {
		tenantPlaceholderIdx := pkPlaceholderIdx + 1
		b.WriteString("\tquery := fmt.Sprintf(\"UPDATE %s SET %s WHERE %s = %s AND %s IS NULL AND %s = %s\",\n")
		fmt.Fprintf(b, "\t\tdialect.QuoteIdentifier(%q),\n", tableName)
		b.WriteString("\t\tstrings.Join(setParts, \", \"),\n")
		fmt.Fprintf(b, "\t\tdialect.QuoteIdentifier(%q),\n", pkCol)
		fmt.Fprintf(b, "\t\tdialect.Placeholder(%d),\n", pkPlaceholderIdx)
		b.WriteString("\t\tdialect.QuoteIdentifier(\"deleted_at\"),\n")
		fmt.Fprintf(b, "\t\tdialect.QuoteIdentifier(%q),\n", tenantField.columnName)
		fmt.Fprintf(b, "\t\tdialect.Placeholder(%d),\n", tenantPlaceholderIdx)
		b.WriteString("\t)\n\n")
		// Append PK and tenant values
		if pkField != nil {
			fmt.Fprintf(b, "\targs = append(args, msg.%s, tenantID)\n", pkField.goName)
		} else {
			b.WriteString("\targs = append(args, msg.Id, tenantID)\n")
		}
	} else if softDelete {
		b.WriteString("\tquery := fmt.Sprintf(\"UPDATE %s SET %s WHERE %s = %s AND %s IS NULL\",\n")
		fmt.Fprintf(b, "\t\tdialect.QuoteIdentifier(%q),\n", tableName)
		b.WriteString("\t\tstrings.Join(setParts, \", \"),\n")
		fmt.Fprintf(b, "\t\tdialect.QuoteIdentifier(%q),\n", pkCol)
		fmt.Fprintf(b, "\t\tdialect.Placeholder(%d),\n", pkPlaceholderIdx)
		b.WriteString("\t\tdialect.QuoteIdentifier(\"deleted_at\"),\n")
		b.WriteString("\t)\n\n")
		if pkField != nil {
			fmt.Fprintf(b, "\targs = append(args, msg.%s)\n", pkField.goName)
		} else {
			b.WriteString("\targs = append(args, msg.Id)\n")
		}
	} else if hasTenant {
		tenantPlaceholderIdx := pkPlaceholderIdx + 1
		b.WriteString("\tquery := fmt.Sprintf(\"UPDATE %s SET %s WHERE %s = %s AND %s = %s\",\n")
		fmt.Fprintf(b, "\t\tdialect.QuoteIdentifier(%q),\n", tableName)
		b.WriteString("\t\tstrings.Join(setParts, \", \"),\n")
		fmt.Fprintf(b, "\t\tdialect.QuoteIdentifier(%q),\n", pkCol)
		fmt.Fprintf(b, "\t\tdialect.Placeholder(%d),\n", pkPlaceholderIdx)
		fmt.Fprintf(b, "\t\tdialect.QuoteIdentifier(%q),\n", tenantField.columnName)
		fmt.Fprintf(b, "\t\tdialect.Placeholder(%d),\n", tenantPlaceholderIdx)
		b.WriteString("\t)\n\n")
		if pkField != nil {
			fmt.Fprintf(b, "\targs = append(args, msg.%s, tenantID)\n", pkField.goName)
		} else {
			b.WriteString("\targs = append(args, msg.Id, tenantID)\n")
		}
	} else {
		// Simple case: no soft-delete, no tenant.
		b.WriteString("\tquery := fmt.Sprintf(\"UPDATE %s SET %s WHERE %s = %s\",\n")
		fmt.Fprintf(b, "\t\tdialect.QuoteIdentifier(%q),\n", tableName)
		b.WriteString("\t\tstrings.Join(setParts, \", \"),\n")
		fmt.Fprintf(b, "\t\tdialect.QuoteIdentifier(%q),\n", pkCol)
		fmt.Fprintf(b, "\t\tdialect.Placeholder(%d),\n", pkPlaceholderIdx)
		b.WriteString("\t)\n\n")
		if pkField != nil {
			fmt.Fprintf(b, "\targs = append(args, msg.%s)\n", pkField.goName)
		} else {
			b.WriteString("\targs = append(args, msg.Id)\n")
		}
	}

	b.WriteString("\n\t_, err := db.Exec(ctx, query, args...)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\tspan.RecordError(err)\n")
	b.WriteString("\t\tspan.SetStatus(codes.Error, err.Error())\n")
	fmt.Fprintf(b, "\t\treturn fmt.Errorf(\"update %s: %%w\", err)\n", tableName)
	b.WriteString("\t}\n")
	b.WriteString("\treturn nil\n")
	b.WriteString("}\n\n")
}

// writeORMUpdateMasked emits Update<Entity>Masked — the AIP-134 partial
// update sibling of Update<Entity>. It writes ONLY the columns named in
// fields (proto field names == column names, snake_case), validates each
// path against the updatable set (same excludeFromSet rules as the full
// update: never the PK, tenant key, deleted_at, or — with managed
// timestamps — created_at), and returns *orm.UnknownFieldError for any
// path outside that set so pkg/crud can map it to InvalidArgument
// without leaking SQL. updated_at is stamped on masked updates too.
func writeORMUpdateMasked(b *strings.Builder, msgName, tableName, pkCol string, fields []ormField, hasTenant, softDelete bool, tenantField *ormField, pkField *ormField, timestamps bool) {
	excludeFromSet := func(f ormField) bool { return excludedFromSet(f, timestamps) }

	var updatable []ormField
	for _, f := range fields {
		if excludeFromSet(f) {
			continue
		}
		updatable = append(updatable, f)
	}

	sigSuffix := ") error {\n"
	if hasTenant {
		sigSuffix = ", tenantID string) error {\n"
	}

	// No updatable columns: a concrete mask path can only ever be
	// unknown; an empty mask is a no-op (mirrors Update<Entity>).
	if len(updatable) == 0 {
		fmt.Fprintf(b, "// Update%sMasked is a no-op shell because %s has no updatable fields;\n", msgName, msgName)
		b.WriteString("// any concrete update_mask path is therefore unknown.\n")
		if hasTenant {
			fmt.Fprintf(b, "func Update%sMasked(_ context.Context, _ orm.Context, _ *%s, fields []string, _ string) error {\n", msgName, msgName)
		} else {
			fmt.Fprintf(b, "func Update%sMasked(_ context.Context, _ orm.Context, _ *%s, fields []string) error {\n", msgName, msgName)
		}
		b.WriteString("\tif len(fields) > 0 {\n")
		b.WriteString("\t\treturn &orm.UnknownFieldError{Field: fields[0]}\n")
		b.WriteString("\t}\n")
		b.WriteString("\treturn nil\n")
		b.WriteString("}\n\n")
		return
	}

	fmt.Fprintf(b, "// Update%sMasked updates ONLY the named fields of an existing %s\n", msgName, msgName)
	b.WriteString("// (AIP-134 update_mask paths; proto field names == column names).\n")
	b.WriteString("// Paths outside the updatable set return *orm.UnknownFieldError —\n")
	b.WriteString("// forge/pkg/crud maps it to a clean InvalidArgument.\n")
	if timestamps {
		b.WriteString("//\n")
		b.WriteString("// updated_at is stamped here too (timestamps: true); created_at is\n")
		b.WriteString("// immutable and never settable through a mask.\n")
	}
	fmt.Fprintf(b, "func Update%sMasked(ctx context.Context, db orm.Context, msg *%s, fields []string%s", msgName, msgName, sigSuffix)
	b.WriteString("\tif len(fields) == 0 {\n")
	b.WriteString("\t\treturn nil\n")
	b.WriteString("\t}\n\n")
	fmt.Fprintf(b, "\tctx, span := ormTracer.Start(ctx, \"orm.Update%sMasked\",\n", msgName)
	fmt.Fprintf(b, "\t\ttrace.WithAttributes(attribute.String(\"table\", %q)))\n", tableName)
	b.WriteString("\tdefer span.End()\n\n")

	stampUpdatedAt := false
	if timestamps {
		stampUpdatedAt = writeUpdatedAtStamp(b, fields, "\t")
		if stampUpdatedAt {
			b.WriteString("\n")
		}
	}

	b.WriteString("\tdialect := db.Dialect()\n\n")

	b.WriteString("\t// The updatable-column set. Anything else (unknown columns, the PK,\n")
	b.WriteString("\t// the tenant key, immutable bookkeeping columns) is rejected.\n")
	b.WriteString("\tcolValue := map[string]any{\n")
	for _, f := range updatable {
		fmt.Fprintf(b, "\t\t%q: %s,\n", f.columnName, valueExpr(f))
	}
	b.WriteString("\t}\n\n")

	b.WriteString("\tsetParts := make([]string, 0, len(fields)+1)\n")
	b.WriteString("\targs := make([]any, 0, len(fields)+3)\n")
	b.WriteString("\tseen := make(map[string]bool, len(fields))\n")
	b.WriteString("\tfor _, f := range fields {\n")
	b.WriteString("\t\tv, ok := colValue[f]\n")
	b.WriteString("\t\tif !ok {\n")
	b.WriteString("\t\t\treturn &orm.UnknownFieldError{Field: f}\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\tif seen[f] {\n")
	b.WriteString("\t\t\tcontinue\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\tseen[f] = true\n")
	b.WriteString("\t\tsetParts = append(setParts, fmt.Sprintf(\"%s = %s\", dialect.QuoteIdentifier(f), dialect.Placeholder(len(args))))\n")
	b.WriteString("\t\targs = append(args, v)\n")
	b.WriteString("\t}\n")
	if stampUpdatedAt {
		b.WriteString("\tif !seen[\"updated_at\"] {\n")
		b.WriteString("\t\tsetParts = append(setParts, fmt.Sprintf(\"%s = %s\", dialect.QuoteIdentifier(\"updated_at\"), dialect.Placeholder(len(args))))\n")
		b.WriteString("\t\targs = append(args, msg.UpdatedAt)\n")
		b.WriteString("\t}\n")
	}
	b.WriteString("\n")

	pkValue := "msg.Id"
	if pkField != nil {
		pkValue = "msg." + pkField.goName
	}

	if softDelete && hasTenant {
		b.WriteString("\tquery := fmt.Sprintf(\"UPDATE %s SET %s WHERE %s = %s AND %s IS NULL AND %s = %s\",\n")
		fmt.Fprintf(b, "\t\tdialect.QuoteIdentifier(%q),\n", tableName)
		b.WriteString("\t\tstrings.Join(setParts, \", \"),\n")
		fmt.Fprintf(b, "\t\tdialect.QuoteIdentifier(%q),\n", pkCol)
		b.WriteString("\t\tdialect.Placeholder(len(args)),\n")
		b.WriteString("\t\tdialect.QuoteIdentifier(\"deleted_at\"),\n")
		fmt.Fprintf(b, "\t\tdialect.QuoteIdentifier(%q),\n", tenantField.columnName)
		b.WriteString("\t\tdialect.Placeholder(len(args)+1),\n")
		b.WriteString("\t)\n")
		fmt.Fprintf(b, "\targs = append(args, %s, tenantID)\n", pkValue)
	} else if softDelete {
		b.WriteString("\tquery := fmt.Sprintf(\"UPDATE %s SET %s WHERE %s = %s AND %s IS NULL\",\n")
		fmt.Fprintf(b, "\t\tdialect.QuoteIdentifier(%q),\n", tableName)
		b.WriteString("\t\tstrings.Join(setParts, \", \"),\n")
		fmt.Fprintf(b, "\t\tdialect.QuoteIdentifier(%q),\n", pkCol)
		b.WriteString("\t\tdialect.Placeholder(len(args)),\n")
		b.WriteString("\t\tdialect.QuoteIdentifier(\"deleted_at\"),\n")
		b.WriteString("\t)\n")
		fmt.Fprintf(b, "\targs = append(args, %s)\n", pkValue)
	} else if hasTenant {
		b.WriteString("\tquery := fmt.Sprintf(\"UPDATE %s SET %s WHERE %s = %s AND %s = %s\",\n")
		fmt.Fprintf(b, "\t\tdialect.QuoteIdentifier(%q),\n", tableName)
		b.WriteString("\t\tstrings.Join(setParts, \", \"),\n")
		fmt.Fprintf(b, "\t\tdialect.QuoteIdentifier(%q),\n", pkCol)
		b.WriteString("\t\tdialect.Placeholder(len(args)),\n")
		fmt.Fprintf(b, "\t\tdialect.QuoteIdentifier(%q),\n", tenantField.columnName)
		b.WriteString("\t\tdialect.Placeholder(len(args)+1),\n")
		b.WriteString("\t)\n")
		fmt.Fprintf(b, "\targs = append(args, %s, tenantID)\n", pkValue)
	} else {
		b.WriteString("\tquery := fmt.Sprintf(\"UPDATE %s SET %s WHERE %s = %s\",\n")
		fmt.Fprintf(b, "\t\tdialect.QuoteIdentifier(%q),\n", tableName)
		b.WriteString("\t\tstrings.Join(setParts, \", \"),\n")
		fmt.Fprintf(b, "\t\tdialect.QuoteIdentifier(%q),\n", pkCol)
		b.WriteString("\t\tdialect.Placeholder(len(args)),\n")
		b.WriteString("\t)\n")
		fmt.Fprintf(b, "\targs = append(args, %s)\n", pkValue)
	}

	b.WriteString("\n\t_, err := db.Exec(ctx, query, args...)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\tspan.RecordError(err)\n")
	b.WriteString("\t\tspan.SetStatus(codes.Error, err.Error())\n")
	fmt.Fprintf(b, "\t\treturn fmt.Errorf(\"update %s: %%w\", err)\n", tableName)
	b.WriteString("\t}\n")
	b.WriteString("\treturn nil\n")
	b.WriteString("}\n\n")
}

func writeORMDelete(b *strings.Builder, msgName, tableName, pkCol, pkGoType string, fields []ormField, hasTenant, softDelete bool, tenantField *ormField) {
	if softDelete {
		fmt.Fprintf(b, "// Delete%s soft-deletes a %s by setting deleted_at.\n", msgName, msgName)
	} else {
		fmt.Fprintf(b, "// Delete%s permanently deletes a %s by its primary key.\n", msgName, msgName)
	}
	if hasTenant {
		fmt.Fprintf(b, "func Delete%s(ctx context.Context, db orm.Context, id %s, tenantID string) error {\n", msgName, pkGoType)
	} else {
		fmt.Fprintf(b, "func Delete%s(ctx context.Context, db orm.Context, id %s) error {\n", msgName, pkGoType)
	}
	fmt.Fprintf(b, "\tctx, span := ormTracer.Start(ctx, \"orm.Delete%s\",\n", msgName)
	b.WriteString("\t\ttrace.WithAttributes(\n")
	fmt.Fprintf(b, "\t\t\tattribute.String(\"table\", %q),\n", tableName)
	b.WriteString("\t\t\tattribute.String(\"id\", fmt.Sprint(id)),\n")
	b.WriteString("\t\t))\n")
	b.WriteString("\tdefer span.End()\n\n")

	if softDelete && hasTenant {
		b.WriteString("\t// Soft delete with tenant isolation.\n")
		b.WriteString("\tdialect := db.Dialect()\n")
		b.WriteString("\tquery := fmt.Sprintf(\"UPDATE %s SET %s = CURRENT_TIMESTAMP WHERE %s = %s AND %s IS NULL AND %s = %s\",\n")
		fmt.Fprintf(b, "\t\tdialect.QuoteIdentifier(%q),\n", tableName)
		b.WriteString("\t\tdialect.QuoteIdentifier(\"deleted_at\"),\n")
		fmt.Fprintf(b, "\t\tdialect.QuoteIdentifier(%q),\n", pkCol)
		b.WriteString("\t\tdialect.Placeholder(0),\n")
		b.WriteString("\t\tdialect.QuoteIdentifier(\"deleted_at\"),\n")
		fmt.Fprintf(b, "\t\tdialect.QuoteIdentifier(%q),\n", tenantField.columnName)
		b.WriteString("\t\tdialect.Placeholder(1),\n")
		b.WriteString("\t)\n")
		b.WriteString("\t_, err := db.Exec(ctx, query, id, tenantID)\n")
	} else if softDelete {
		b.WriteString("\t// Soft delete: set deleted_at instead of removing the row.\n")
		b.WriteString("\tdialect := db.Dialect()\n")
		b.WriteString("\tquery := fmt.Sprintf(\"UPDATE %s SET %s = CURRENT_TIMESTAMP WHERE %s = %s AND %s IS NULL\",\n")
		fmt.Fprintf(b, "\t\tdialect.QuoteIdentifier(%q),\n", tableName)
		b.WriteString("\t\tdialect.QuoteIdentifier(\"deleted_at\"),\n")
		fmt.Fprintf(b, "\t\tdialect.QuoteIdentifier(%q),\n", pkCol)
		b.WriteString("\t\tdialect.Placeholder(0),\n")
		b.WriteString("\t\tdialect.QuoteIdentifier(\"deleted_at\"),\n")
		b.WriteString("\t)\n")
		b.WriteString("\t_, err := db.Exec(ctx, query, id)\n")
	} else if hasTenant {
		b.WriteString("\t// Hard delete with tenant isolation.\n")
		b.WriteString("\tdialect := db.Dialect()\n")
		b.WriteString("\tquery := fmt.Sprintf(\"DELETE FROM %s WHERE %s = %s AND %s = %s\",\n")
		fmt.Fprintf(b, "\t\tdialect.QuoteIdentifier(%q),\n", tableName)
		fmt.Fprintf(b, "\t\tdialect.QuoteIdentifier(%q),\n", pkCol)
		b.WriteString("\t\tdialect.Placeholder(0),\n")
		fmt.Fprintf(b, "\t\tdialect.QuoteIdentifier(%q),\n", tenantField.columnName)
		b.WriteString("\t\tdialect.Placeholder(1),\n")
		b.WriteString("\t)\n")
		b.WriteString("\t_, err := db.Exec(ctx, query, id, tenantID)\n")
	} else {
		b.WriteString("\tdialect := db.Dialect()\n")
		b.WriteString("\tquery := fmt.Sprintf(\"DELETE FROM %s WHERE %s = %s\",\n")
		fmt.Fprintf(b, "\t\tdialect.QuoteIdentifier(%q),\n", tableName)
		fmt.Fprintf(b, "\t\tdialect.QuoteIdentifier(%q),\n", pkCol)
		b.WriteString("\t\tdialect.Placeholder(0),\n")
		b.WriteString("\t)\n")
		b.WriteString("\t_, err := db.Exec(ctx, query, id)\n")
	}

	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\tspan.RecordError(err)\n")
	b.WriteString("\t\tspan.SetStatus(codes.Error, err.Error())\n")
	fmt.Fprintf(b, "\t\treturn fmt.Errorf(\"delete %s: %%w\", err)\n", tableName)
	b.WriteString("\t}\n")
	b.WriteString("\treturn nil\n")
	b.WriteString("}\n")
}

// resolveORMFields converts PlanEntity fields (including auto-generated
// timestamp/soft-delete fields) into the ormField representation used
// by the code generator.
func resolveORMFields(ent config.PlanEntity) []ormField {
	type entry struct {
		config.PlanEntityField
		autoGenerated bool
	}

	// Check if any field already serves as the primary key.
	hasPK := false
	for _, f := range ent.Fields {
		if f.PrimaryKey || f.Name == "id" {
			hasPK = true
			break
		}
	}

	entries := make([]entry, 0, len(ent.Fields)+4)

	// Auto-add an id primary key field if none exists.
	if !hasPK {
		entries = append(entries, entry{PlanEntityField: config.PlanEntityField{
			Name: "id", Type: "string", PrimaryKey: true, NotNull: true,
		}})
	}

	declared := make(map[string]bool, len(ent.Fields))
	for _, f := range ent.Fields {
		declared[f.Name] = true
		entries = append(entries, entry{PlanEntityField: f})
	}

	// Auto-add timestamp/soft-delete columns ONLY when the entity didn't
	// declare them — proto entities routinely declare created_at /
	// updated_at / deleted_at explicitly alongside timestamps:true /
	// soft_delete:true, and a duplicate field is a compile error in the
	// generated code (duplicate consts) and a duplicate column in SQL.
	if ent.Timestamps {
		if !declared["created_at"] {
			entries = append(entries,
				entry{PlanEntityField: config.PlanEntityField{Name: "created_at", Type: "google.protobuf.Timestamp"}, autoGenerated: true})
		}
		if !declared["updated_at"] {
			entries = append(entries,
				entry{PlanEntityField: config.PlanEntityField{Name: "updated_at", Type: "google.protobuf.Timestamp"}, autoGenerated: true})
		}
	}
	if ent.SoftDelete && !declared["deleted_at"] {
		entries = append(entries,
			entry{PlanEntityField: config.PlanEntityField{Name: "deleted_at", Type: "google.protobuf.Timestamp"}, autoGenerated: true},
		)
	}

	fields := make([]ormField, 0, len(entries))
	for _, e := range entries {
		f := ormField{
			planField:   e.PlanEntityField,
			goName:      naming.ToProtoPascalCase(e.Name),
			columnName:  e.Name,
			goType:      planFieldGoType(e.Type),
			ormType:     planFieldOrmType(e.Type),
			isTimestamp: isTimePlanType(e.Type),
			isArray:     strings.HasPrefix(e.Type, "[]"),
			isPK:        e.PrimaryKey,
			isTenantKey: e.TenantKey,
			notNull:     e.NotNull,
			unique:      e.Unique,
			references:  e.References,
		}
		// Nullable column → pointer struct field. Arrays and bytes are
		// reference types already (NULL scans to nil).
		f.nullable = !f.isPK && !f.notNull && isNullablePlanType(e.Type)
		fields = append(fields, f)
	}
	return fields
}

// isTimePlanType reports whether the plan type is a timestamp column.
func isTimePlanType(t string) bool {
	switch t {
	case "time", "google.protobuf.Timestamp", "timestamp":
		return true
	}
	return false
}

// planFieldGoType maps a PlanEntityField.Type to the base Go type used
// on the entity struct (and in Values/Scan).
//
// The vocabulary is the canonical schema vocabulary (see
// internal/schemadef.MapDeclaredType): string, int64, float64, bool,
// time, json, bytes, []string, []int64. Legacy proto-type aliases stay
// mapped during the transition.
func planFieldGoType(t string) string {
	switch t {
	case "[]string":
		return "[]string"
	case "[]int64", "[]int", "[]int32":
		return "[]int64"
	case "string", "json":
		return "string"
	case "int32":
		return "int32"
	case "int64", "int":
		return "int64"
	case "uint32":
		return "uint32"
	case "uint64":
		return "uint64"
	case "bool":
		return "bool"
	case "float", "float32":
		return "float32"
	case "double", "float64":
		return "float64"
	case "bytes":
		return "[]byte"
	case "time", "google.protobuf.Timestamp", "timestamp":
		return "time.Time"
	default:
		return "string"
	}
}

// planFieldOrmType maps a PlanEntityField.Type to the orm.TypeXxx constant string
// used in generated Schema() code.
func planFieldOrmType(t string) string {
	if strings.HasPrefix(t, "[]") {
		return "orm.TypeJSONB"
	}
	switch t {
	case "string":
		return "orm.TypeText"
	case "json":
		return "orm.TypeJSONB"
	case "bool":
		return "orm.TypeBoolean"
	case "int32", "uint32":
		return "orm.TypeInteger"
	case "int64", "int", "uint64":
		return "orm.TypeBigInt"
	case "float", "float32":
		return "orm.TypeReal"
	case "double", "float64":
		return "orm.TypeDoublePrecision"
	case "bytes":
		return "orm.TypeBytea"
	case "time", "google.protobuf.Timestamp", "timestamp":
		return "orm.TypeTimestampTZ"
	default:
		return "orm.TypeText"
	}
}

// isNullablePlanType returns true when a nullable column of this type
// becomes a pointer field on the entity struct.
func isNullablePlanType(t string) bool {
	if strings.HasPrefix(t, "[]") || t == "bytes" {
		// Reference types: NULL scans to nil without a pointer.
		return false
	}
	switch t {
	case "string", "json", "int32", "int64", "int", "uint32", "uint64", "bool",
		"float", "float32", "double", "float64",
		"time", "google.protobuf.Timestamp", "timestamp":
		return true
	default:
		return false
	}
}
