package generator

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/reliant-labs/forge/internal/codegen"
	"github.com/reliant-labs/forge/internal/naming"
	"github.com/reliant-labs/forge/internal/templates"
)

// generateBootstrap writes pkg/app/bootstrap.go with explicit service construction.
func (g *ProjectGenerator) generateBootstrap() error {
	// Each bootstrap-component type carries an Alias mirroring the
	// codegen.BootstrapComponentData.Alias field — initial-scaffold
	// emission has no cross-role collisions, so Alias defaults to
	// Package and the rendered import lines look identical to the
	// pre-Alias template (Go accepts redundant `<alias> "<path>"` aliases).
	// VarName is the lowerCamel form of FieldName for any local-var
	// references the template expands.
	type bootstrapService struct {
		Name      string
		Package   string
		FieldName string
		Fallible  bool
		Alias     string
		VarName   string
		// HasWebhooks mirrors codegen.BootstrapServiceData.HasWebhooks. The
		// initial-scaffold pass never declares webhooks (forge.yaml hasn't
		// grown a webhooks: block yet), so this stays false here; the
		// codegen-pass regenerator overwrites bootstrap.go later with the
		// real value after descriptor walk + forge.yaml read.
		HasWebhooks bool
	}

	type bootstrapPackage struct {
		Name       string
		Package    string
		ImportPath string
		FieldName  string
		Fallible   bool
		Alias      string
		VarName    string
	}

	type bootstrapWorker struct {
		Name      string
		Package   string
		FieldName string
		Fallible  bool
		Alias     string
		VarName   string
	}

	type bootstrapOperator struct {
		Name      string
		Package   string
		FieldName string
		Fallible  bool
		Alias     string
		VarName   string
	}

	var services []bootstrapService
	if g.ServiceName != "" {
		// Display name keeps the user's spelling (which may include hyphens),
		// while Package needs to be a valid Go package identifier so it can
		// be used both as the import directory tail and the package-decl
		// name. FieldName uses ToPascalCase so "admin-server" becomes
		// "AdminServer" — matching what the unit/integration test templates
		// emit via `{{.ServiceName | pascalCase}}` (e.g. NewTestAdminServer).
		pkg := ServicePackageName(g.ServiceName)
		fieldName := naming.ToPascalCase(g.ServiceName)
		services = []bootstrapService{
			{
				Name:      g.ServiceName,
				Package:   pkg,
				FieldName: fieldName,
				Alias:     pkg,
				VarName:   lowerFirstRune(fieldName),
			},
		}
	}

	// In binary=shared mode, scaffold ALL services (ServiceName +
	// AdditionalServices) into the bootstrap up-front so the per-service
	// cobra subcommands compile against a complete dependency graph. In
	// binary=per-service mode this is preserved as-is (only ServiceName);
	// AppendServiceToConfig/GenerateServiceFiles handles the rest later.
	if g.isBinaryShared() && len(g.AdditionalServices) > 0 {
		for _, svcName := range g.AdditionalServices {
			pkg := ServicePackageName(svcName)
			fieldName := naming.ToPascalCase(svcName)
			services = append(services, bootstrapService{
				Name:      svcName,
				Package:   pkg,
				FieldName: fieldName,
				Alias:     pkg,
				VarName:   lowerFirstRune(fieldName),
			})
		}
	}

	data := struct {
		Module       string
		Services     []bootstrapService
		Packages     []bootstrapPackage
		Workers      []bootstrapWorker
		Operators    []bootstrapOperator
		HasDatabase  bool
		OrmEnabled   bool
		HasFallible  bool
		BinaryShared bool
		ConfigFields map[string]bool
	}{
		Module:    g.ModulePath,
		Services:  services,
		Packages:  nil, // No packages at initial project creation
		Workers:   nil, // No workers at initial project creation
		Operators: nil, // No operators at initial project creation
		// Initial scaffold has no proto/db entities; the post-scaffold
		// generate pipeline re-renders with the correct flags if the user
		// adds entities.
		HasDatabase:  false,
		OrmEnabled:   false,
		BinaryShared: g.isBinaryShared(),
		ConfigFields: codegen.DefaultConfigFieldNames(),
	}

	content, err := templates.ProjectTemplates().Render("bootstrap.go.tmpl", data)
	if err != nil {
		return fmt.Errorf("render bootstrap.go.tmpl: %w", err)
	}

	// Emit pkg/app/app_gen.go + pkg/app/app_extras.go alongside
	// bootstrap.go. bootstrap.go references the App type (defined in
	// app_gen.go) and AppExtras (defined in app_extras.go); without
	// these companions the initial `go build` after `forge new` fails.
	// app_extras.go is Tier-2 (user-owned, never overwritten); app_gen.go
	// is Tier-1 and will be regenerated by the codegen pipeline as
	// services/workers/operators/packages are added.
	if err := g.generateAppGen(len(services) > 0, false, false, false); err != nil {
		return fmt.Errorf("generate app_gen.go: %w", err)
	}
	if err := g.generateAppExtras(); err != nil {
		return fmt.Errorf("generate app_extras.go: %w", err)
	}

	destPath := filepath.Join(g.Path, "pkg", "app", "bootstrap.go")
	if err := os.WriteFile(destPath, content, 0644); err != nil {
		return err
	}

	// Emit wire_gen.go alongside bootstrap.go at scaffold time so the
	// project compiles immediately. The bootstrap.go references
	// wireXxxDeps for each service; without this companion file, the
	// initial `go build` after `forge new` would fail. The post-scaffold
	// `forge generate` regenerates wire_gen.go with handler-Deps-derived
	// fields once the user fills in the service.
	wireInfos := make([]scaffoldServiceInfo, 0, len(services))
	for _, s := range services {
		wireInfos = append(wireInfos, scaffoldServiceInfo{
			FieldName: s.FieldName,
			Package:   s.Package,
			Alias:     s.Alias,
			Name:      s.Name,
		})
	}
	if err := g.generateWireGen(wireInfos); err != nil {
		return fmt.Errorf("generate wire_gen.go: %w", err)
	}
	return nil
}

// scaffoldWireAssignment / scaffoldWireService are the slim cousins of
// codegen.WireAssignment / codegen.WireGenServiceData used at
// initial-scaffold time. The full WireGenServiceData walks the
// handler's Deps AST to derive fields, but at scaffold time the
// handler directory doesn't exist yet — we emit just the bare-Deps
// trio so the generated wire_gen.go compiles. The post-scaffold
// `forge generate` regenerates the file with AST-derived assignments.
type scaffoldWireAssignment struct {
	Field   string
	Expr    string
	Comment string
}

type scaffoldWireService struct {
	FieldName        string
	Package          string
	Alias            string
	Name             string
	// ImportPath / LoggerAttrKey mirror the production
	// codegen.WireGenServiceData fields. The shared template uses
	// {{.ImportPath}} in the import line so workers/operators can reuse
	// the same template; scaffold-time projects only emit services so
	// ImportPath is always "handlers/<pkg>".
	ImportPath       string
	LoggerAttrKey    string
	NeedsAuthzVar    bool
	NeedsDevMode     bool
	Assignments      []scaffoldWireAssignment
	UnresolvedFields []struct{ Name, Type, Hint string }
}

// scaffoldServiceInfo is the minimal cross-cut between the
// generateBootstrap-local bootstrapService type and what
// generateWireGen needs (FieldName + Package + Alias + Name).
// generateBootstrap maps its local services to this before invoking
// the wire-gen scaffold so we don't have to promote the local type.
type scaffoldServiceInfo struct {
	FieldName string
	Package   string
	Alias     string
	Name      string
}

// generateWireGen writes pkg/app/wire_gen.go for the initial-scaffold
// pass. See scaffoldWireService for the rationale on why this differs
// from codegen.GenerateWireGen.
func (g *ProjectGenerator) generateWireGen(services []scaffoldServiceInfo) error {
	if len(services) == 0 {
		return nil
	}
	var wireSvcs []scaffoldWireService
	for _, s := range services {
		wireSvcs = append(wireSvcs, scaffoldWireService{
			FieldName:     s.FieldName,
			Package:       s.Package,
			Alias:         s.Alias,
			Name:          s.Name,
			ImportPath:    "handlers/" + s.Package,
			LoggerAttrKey: "service",
			NeedsAuthzVar: true,
			NeedsDevMode:  true,
			Assignments: []scaffoldWireAssignment{
				{Field: "Logger", Expr: fmt.Sprintf("logger.With(%q, %q)", "service", s.Name)},
				{Field: "Config", Expr: "cfg"},
				{Field: "Authorizer", Expr: "authz", Comment: "devMode swap to middleware.DevAuthorizer in development"},
			},
		})
	}

	data := struct {
		Module                string
		Services              []scaffoldWireService
		Workers               []scaffoldWireService
		Operators             []scaffoldWireService
		NeedsAuthorizerImport bool
	}{
		Module:                g.ModulePath,
		Services:              wireSvcs,
		NeedsAuthorizerImport: true,
	}

	content, err := templates.ProjectTemplates().Render("wire_gen.go.tmpl", data)
	if err != nil {
		return fmt.Errorf("render wire_gen.go.tmpl: %w", err)
	}
	destPath := filepath.Join(g.Path, "pkg", "app", "wire_gen.go")
	return os.WriteFile(destPath, content, 0644)
}

// generateBootstrapTesting writes pkg/app/testing.go with test helper functions.
func (g *ProjectGenerator) generateBootstrapTesting() error {
	type bootstrapTestService struct {
		Name                   string
		Package                string
		FieldName              string
		ProtoServiceName       string
		ProtoConnectImportPath string
		ProtoConnectPkg        string
		Fallible               bool
		HasDB                  bool
		Alias                  string
		VarName                string
	}

	type bootstrapPackage struct {
		Name       string
		Package    string
		ImportPath string
		FieldName  string
		Fallible   bool
		Alias      string
		VarName    string
	}

	var services []bootstrapTestService
	var connectImports []string
	if g.ServiceName != "" {
		pkg := ServicePackageName(g.ServiceName)
		fieldName := naming.ToPascalCase(g.ServiceName)
		// ProtoServiceName matches what the proto template emits:
		// `service {{.ServiceName | pascalCase}}Service` (PascalCase handles hyphens).
		protoServiceName := naming.ToPascalCase(g.ServiceName) + "Service"
		// Project bootstrap is the first scaffold pass before any descriptor
		// exists; use the convention path. The codegen-pass regenerator will
		// later replace this file with descriptor-derived imports.
		connectPkg := pkg + "v1connect"
		connectImport := g.ModulePath + "/gen/services/" + pkg + "/v1/" + connectPkg
		services = []bootstrapTestService{
			{
				Name:                   g.ServiceName,
				Package:                pkg,
				FieldName:              fieldName,
				ProtoServiceName:       protoServiceName,
				ProtoConnectImportPath: connectImport,
				ProtoConnectPkg:        connectPkg,
				Alias:                  pkg,
				VarName:                lowerFirstRune(fieldName),
			},
		}
		connectImports = []string{connectImport}
	}

	data := struct {
		Module             string
		Services           []bootstrapTestService
		ConnectImports     []string
		Packages           []bootstrapPackage
		MultiTenantEnabled bool
		AnyServiceHasDB    bool
	}{
		Module:             g.ModulePath,
		Services:           services,
		ConnectImports:     connectImports,
		Packages:           nil,   // No packages at initial project creation
		MultiTenantEnabled: false, // Multi-tenancy configured post-creation via forge generate
		AnyServiceHasDB:    false, // DB deps are added later by forge generate
	}

	content, err := templates.ProjectTemplates().Render("bootstrap_testing.go.tmpl", data)
	if err != nil {
		return fmt.Errorf("render bootstrap_testing.go.tmpl: %w", err)
	}

	destPath := filepath.Join(g.Path, "pkg", "app", "testing.go")
	return os.WriteFile(destPath, content, 0644)
}

// generateAppGen writes pkg/app/app_gen.go at scaffold time. The App
// struct definition lives here (forge-owned, regenerated as components
// are added/removed) instead of bootstrap.go so the user-extension
// scaffold (app_extras.go) can embed AppExtras into it cleanly.
//
// At initial scaffold time we always pass false for HasDatabase /
// OrmEnabled — the project hasn't grown a db driver yet. The codegen
// pipeline re-emits app_gen.go with the right values once forge.yaml
// and proto/db/ have entities.
func (g *ProjectGenerator) generateAppGen(hasServices, hasWorkers, hasOperators, hasPackages bool) error {
	data := struct {
		HasDatabase bool
		OrmEnabled  bool
		Services    bool
		Workers     bool
		Operators   bool
		Packages    bool
	}{
		HasDatabase: false,
		OrmEnabled:  false,
		Services:    hasServices,
		Workers:     hasWorkers,
		Operators:   hasOperators,
		Packages:    hasPackages,
	}
	content, err := templates.ProjectTemplates().Render("app_gen.go.tmpl", data)
	if err != nil {
		return fmt.Errorf("render app_gen.go.tmpl: %w", err)
	}
	destPath := filepath.Join(g.Path, "pkg", "app", "app_gen.go")
	return os.WriteFile(destPath, content, 0644)
}

// generateAppExtras writes pkg/app/app_extras.go ONCE at scaffold time
// — the Tier-2 user-extension scaffold with an empty AppExtras struct.
// Subsequent `forge generate` runs leave it alone (matches setup.go's
// never-overwrite rule).
func (g *ProjectGenerator) generateAppExtras() error {
	destPath := filepath.Join(g.Path, "pkg", "app", "app_extras.go")
	if _, err := os.Stat(destPath); err == nil {
		// User-owned file already exists — leave it alone.
		return nil
	}
	content, err := templates.ProjectTemplates().Render("app_extras.go.tmpl", struct{}{})
	if err != nil {
		return fmt.Errorf("render app_extras.go.tmpl: %w", err)
	}
	return os.WriteFile(destPath, content, 0644)
}

// lowerFirstRune returns s with the first rune lowercased — used to
// derive a lowerCamel local-var prefix from a PascalCase FieldName.
// Mirrors codegen.lowerFirst (kept private here to avoid an import
// cycle from generator → codegen).
func lowerFirstRune(s string) string {
	if s == "" {
		return s
	}
	r := []rune(s)
	if r[0] >= 'A' && r[0] <= 'Z' {
		r[0] = r[0] + ('a' - 'A')
	}
	return string(r)
}