// Code generated by forge. DO NOT EDIT.
// forge:hash=801b9aeb073954dd81bc90fbd0fc42c6f100fd43dd55e183c5fae249d4b3e8bf
// forge-owned: regenerated every run — do not edit (forge disown to take ownership)
// Source: contract.go in this package.
//
// To customize: edit contract.go (the interface IS the public surface) and
// re-run "forge generate". This file is regenerated unconditionally.
package doctor

import (
	"context"
	"io"

	"github.com/reliant-labs/forge/pkg/contractkit"
)

// MockService is a test mock for the Service interface.
//
// The embedded contractkit.Recorder records every call so tests can
// assert call counts and captured arguments. Set XxxFunc fields to
// override per-method behaviour; unset methods return the canonical
// "MockService.<Method>Func not set" error.
type MockService struct {
	contractkit.Recorder
	RunStandardFunc func(context.Context, string, string) Report
	RunFilteredFunc func(context.Context, string, string, string) (Report, error)
	PrintReportFunc func(io.Writer, Report, bool)
	PrintJSONFunc   func(io.Writer, Report) error
}

func (m *MockService) RunStandard(ctx context.Context, projectName string, projectDir string) Report {
	m.Recorder.Record("RunStandard", ctx, projectName, projectDir)
	if m.RunStandardFunc != nil {
		return m.RunStandardFunc(ctx, projectName, projectDir)
	}
	return Report{}
}

func (m *MockService) RunFiltered(ctx context.Context, projectName string, projectDir string, signal string) (Report, error) {
	m.Recorder.Record("RunFiltered", ctx, projectName, projectDir, signal)
	if m.RunFilteredFunc != nil {
		return m.RunFilteredFunc(ctx, projectName, projectDir, signal)
	}
	return Report{}, contractkit.MockNotSet("MockService", "RunFiltered")
}

func (m *MockService) PrintReport(w io.Writer, report Report, verbose bool) {
	m.Recorder.Record("PrintReport", w, report, verbose)
	if m.PrintReportFunc != nil {
		m.PrintReportFunc(w, report, verbose)
		return
	}
}

func (m *MockService) PrintJSON(w io.Writer, report Report) error {
	m.Recorder.Record("PrintJSON", w, report)
	if m.PrintJSONFunc != nil {
		return m.PrintJSONFunc(w, report)
	}
	return contractkit.MockNotSet("MockService", "PrintJSON")
}

// Compile-time check.
var _ Service = (*MockService)(nil)
