// Code generated by forge. DO NOT EDIT.
// forge-owned: regenerated every run — do not edit.
package requiregenerated

// generatedAuthorizer mirrors the shape of a real forge-generated
// authorizer_gen.go: its exported methods (Can/CanAccess) are codegen output,
// not a hand-authored behavioral surface, so they must NOT force a contract.go.
type generatedAuthorizer struct{}

func NewGeneratedAuthorizer() *generatedAuthorizer { return &generatedAuthorizer{} }

func (a *generatedAuthorizer) Can(method string) bool { return true }

func (a *generatedAuthorizer) CanAccess(resource string) bool { return true }
